const artificialInteligence = {
    videoId: 'H6mhZAmk4Y0',
    transcript: {
        pinyin: "Yuè lái yuè juǎn de réngōng zhìnéng wèilái huì rúhé fāzhǎn? Cóng xīnpiàn liáo kējì cóng kējì kàn rénshēng Hello dàjiā hǎo zhèlǐ shì lǎo shí tán xīn wǒ shì xīnpiàn gōngchéngshī lǎo shí wǒ yīzhí xiǎng zuò tánhuà lèi de jiémù a yīn wéiyīgè rén de zhīshì shízài shì tài yǒuxiànle suǒyǐ wǒ qǐng dà lǎo hé wǒmen yīqǐ tán chúle xīnpiàn hé kējì wǒmen hái huì liáo hěnduō yǒuyìsi de shìqíng jì yào yǎngwàng xīngkōng yòu yào dītóu kàn lù shuō de jiùshì zhège yìsi jīntiān wǒmen yào liáo de shì hěnduō rén dōu fēicháng guānxīn de réngōng zhìnéng dehuàtí xiànzài réngōng zhìnéng yǐjīng wú chù bùzàile shènzhì zhè qī shìpín dōu yǒu kěnéng shì réngōng zhìnéng tuīsòng gěi nǐ de dànshì tā de fǎ zhǎn sìhū xiànrùle píngjǐng yě yǐnfāle hěnduō rén de kùnhuò hé zhíyí jīntiān wǒmen jiù hǎohǎo lái liáo yī liáo yuè lái yuè juǎn de réngōng zhìnéng zài xiànzài hé wèilái jiùjìng hái yǒu nǎxiē jīhuì jīntiān fēicháng kāixīn qǐng dàole féng jì bóshì tā shì chuàngxīn gōngchǎng nánjīng AI yán jiù yuàn de zhí háng yuàn zhǎng yěshì bèi yàng liànghuà de chuàngshǐ rén tā zài réngōng zhìnéng lǐngyù yǒuzhe shēnhòu de yánjiū jīngyàn Hello féng bóshì nǐ hǎo néng bùnéng gěi dàjiā dǎ gè zhāohū xièxiè lǎo shí de yāoqǐng dàjiā hǎo wǒ shì féng jì AI chuàngxīn yù dào tiānhuābǎn? Féng bóshì fēicháng kāixīn jīntiān jiēshòu wǒmen de yāoqǐng wǒmen jīntiān qíshí shì xiǎng tán nín fēicháng shúxī de réngōng zhìnéng lǐngyù tèbié shì zuìjìn wǒmen fāxiàn réngōng zhìnéng yuè lái yuè juǎnle yīn wéi zhīqián wǒ kàn dào yīgè xiāoxī jiùshì gǔgē de Jeff Dean tā zuòle yīgè xīn de gōngzuò jùtǐ gōngzuò běnshēn wǒmen jiù bù zài duō shuōle dànshì tā de jiéguǒ hǎoxiàng shì bǐ xiànzài zuìxīn de jiéguǒ tíshēngle 0.03% Dànshì tā zhège jiéguǒ yǐnfāle xuānrándàbō de zuì zhǔyào de yuányīn shì tā huāle dàgài 57,000 duō měiyuán qù qǔdéle 0.03%De zhème yīdiǎndiǎn tíshēng suǒyǐ dàjiā dōu shuō AI zhège lǐngyù shízài shì tài juǎnle rúguǒ shì pǔtōng rén pǔtōng gāoxiào huòzhě shì pǔtōng de gōngsī shènzhì dōu bù kěnéng qù fù xiàn zhèyàng de gōngzuò duìyú zhège gōngzuò nín zěnme kàn zhège wèntí qíshí zuìjìn shòudàole tǐng duō de guānzhù wǒ shì zhèyàng kàn de shǒuxiān dì yī quèshí yǐ shēndù shénjīng wǎngluò jìshù wéi zhǔdǎo de réngōng zhìnéng mùqián quèshí dà chǎng kāishǐ zhújiàn de zǒuxiàngle suǒwèi de bàolì měixué jiùshì yòng chāodà guīmó de shùjù jiā chāodà guīmó de suàn lì lái qù tànsuǒ shēndù shénjīng wǎngluò tā de tiānhuābǎn dàgài dàodǐ zài nǎ dì èr jiùshì cóng xuéshù kēyán lái shuō yěxǔ zhè bìng bùshì wéi yī de yītiáo lù mùqián yǒu dàliàng de yīxiē yánjiū zài qù tànsuǒ yīxiē qítā de jìshù lùxiàn lái zěnme yàng de qù zuò dào cóng gǎnzhī zhìnéng wǎng rèn zhī zhìnéng qù zuò zhèyàng de yīgè zhuǎnbiàn hái yǒu bǐrú shuō yīxiē xiǎo yàngběn de rènwù zěnme yàng lìyòng yīxiē fēicháng xiǎo de zhèyàng de yīxiē shùjù liàng lái qù zuò yīxiē xiāngguān de réngōng zhìnéng de shìqíng dì sān jiùshì shuō cóng gōngyè jiè lái kàn suǒyǒu de shìqíng wèibì xūyào zhème dà de suàn lì qíshí gōngyè jiè yěyǒu dàliàng de fēi yǔyīn túxiàng huòzhě wénběn zhèyàng de zhèxiē rènwù qíshí yě zài dào bī zhèxiē xuéshù jiè lái qù tuīchū yīxiē bǐjiào gāoxiào de yīxiē zhèyàng de suànfǎ AI suànfǎ bìng bù zhǐyǒu shēndù shénjīng wǎngluò? Suǒyǐ wǒmen xiān cóng suànfǎ de jiǎodù lái qù kàn réngōng zhìnéng nín juédé yǒu méiyǒu gèngjiā guǎngkuò huòzhě shì gèngjiā wánquán de yīgè shìjiǎo qù héngliáng huòzhě shì qù kàndài réngōng zhìnéng zhè jiàn shìqíng ne kěnéng zài 90 niándài zhīqián réngōng zhìnéng de gàiniàn tā suǒ dàibiǎo de bèihòu de jìshù kěnéng zhǔyào háishì yǐ fúhào zhǔyì jiùshì jīyú zhèxiē luójí tuīlǐ Planning Searching zhèyàng de jìshù zhège shìjì de cóng 10 nián wǎng hòu kěnéng gèng zhòngyào de yīcì zhuǎnbiàn jiùshì yòng shénjīng wǎngluò de jìshù lái gèng hǎo de qù biǎoshì zhèxiē gǎnzhī lèi de rènwù dànshì mùqián qíshí hái yǒu dàliàng de réngōng zhìnéng de suǒwèi de bǐrú bìng méiyǒu jiějué bǐrú shuō xiàng zěnme yàng de qù zuò luójí tuīlǐ zěnme yàng de qù zuò chángshì zěnme yàng gèng hǎo de qù duì jìyì lái qù zuò jiàn mó zhèxiē shìqíng shì bùshì shénjīng wǎngluò jiù gòu zhè yīkuài kěnéng shì mùqián xuéshù jiè shènzhì gōngyè jiè dàjiā gèng guānxīn de xià yīgè gèng zhòngyào de shì er gāngcái nín tí dào yīgè fēicháng zhòngyào de yīdiǎn wǒmen xiànzài de réngōng zhìnéng de yánjiū kěnéng gèng duō de jízhōng zài zhè zhǒng gǎnzhī lǐngyù dànshì zài rèn zhī lǐngyù kěnéng bìng méiyǒu túpò xìng de jìnzhǎn nín juédé zhè huì shì xīn de réngōng zhìnéng de wèilái de fǎ zhǎn fāngxiàng ma zhège wèntí fēicháng zhòngyào jiùshì wǒmen suǒ shuō de gǎnzhī réngōng zhìnéng qíshí jiùshì zuìjìn jǐ niánlái réngōng zhìnéng chénggōng luòdì de bǐrú shuō túxiàng shìbié bǐrú shuō yǔyīn zhuǎi wénzì zhèyàng de yìngyòng huòzhě bǐrú shuō yīxiē wénběn de shēngchéng zhèyàng de yīxiē rènwù gèng zhòngyào de kěnéng shì zěnme yàng de cóng zhè zhǒng gǎnzhī lèi de rènwù zhuǎnxiàng yīxiē jùyǒu yīxiē rèn zhī nénglì de shìqíng yóuqí shì bǐrú shuō zěnme yàng de yòng réngōng zhìnéng de fāngshì lái qù shíxiàn luójí tuīlǐ lái qù shíxiàn chángshì děng děng mùqián dàgài jù wǒ suǒ zhī dàgài xuéshù jiè zhǔyào háishì yǒusāntiáo jìshù lùxiàn dì yī háishì yánzhe shénjīng wǎngluò zhè tiáo lù qù zǒu jiùshì shuō tōngguò bu duàn de duī shùjù ránhòu qù duī suàn lì lái qù kàn yī kàn zhè jiàn shìqíng shìfǒu yǒu kěnéng dì èr tiáo jìshù lùjìng shì chángshì qù tóng zhīqián de zhèxiē fúhào zhǔyì de zhèxiē jìshù lái qù zuò jiéhé suǒwèi de shénjīng zhǔyì jiā zhège fúhào zhǔyì de jiéhé ránhòu dì sān gè jiùshì shuō zěnme yàng jiāng chuántǒng de zhèxiē luójí tuīlǐ de zhèxiē jìshù zài zuò yīxiē xīn de tíshēng zhè yīkuài kěnéng huì bǐjiào nán yīn wéi dàjiā yǐjīng zuòle hěnduō niánle gāngcái wǒmen yě tǎolùnle xiànzài de AI suànfǎ bāokuò yìngyòng de fùzá dù bāokuò duōyàng xìng dōu fēicháng fēicháng dà dànshì cóng lìngwài yīgè jiǎodù lái shuō chúle AI de suànfǎ shùjù shì bùshì yěshì tóngyàng de zhòngyào yīnwèi yǒu hěnduō de gōngsī bāokuò yánjiū zhě dōu shuō shùjù shì xiàndài shèhuì de shíyóu nàme shènzhì kěnéng shùjù de zhòngyào xìng bǐ shíyóu de zhòngyào xìng gēng jiā de zhòngyào yīn wéi bùguǎn wǒmen gànshénme shìqíng bǐ wǒmen xiànzài zài liáotiān dūhuì chǎnshēng mángmáng duō de shùjù nàme cóng xiànzài xuéshù huòzhě shì gōngyè jiè de jiǎodù lái kàn shùjù duìyú réngōng zhìnéng huòzhě duìyú AI lái shuō tā de zhòngyào xìng jiùjìng zài shénme dìfāng qíshí shùjù duìyú réngōng zhìnéng gōngchéng lái shuō zhòngyào xìng yǐjīng yuè lái yuè gāole shènzhì xiànzài gōngyè jiè wǒmen tíchūle yīgè gàiniàn jiàozuò yǐ “shùjù wéi zhōngxīn de kāifā móshì” zhīqián jiàozuò “yǐ móxíng wéi zhōngxīn” shénme yìsi ne jiùshì zhīqián dàgài gōngchéngshī gèng duō de shíjiān zàiyú zěnme yàng dājiàn yīgè móxíng zěnme yàng qù diào cān lái ràng zhège xìtǒng dì xìngnéng gèng hǎo dàgài dàole xiànzài dehuà kěnéng dàjiā de 80%zuǒyòu de zhùyì lì dōu zài zěnme yàng de ràng nǐ de shùjù jí biàn dé gèng hǎo wǒ zěnme yàng ràng wǒ de xùnliàn jí biàn dé gèng hǎo zěnme yàng ràng wǒ de xùnliàn jí gèng pínghéng lái qù ràng wǒ de zhège móxíng zài hǎo de shùjù jí shàng xùnliàn zhīhòu nénggòu dédào yīgè bǐjiào hǎo de zhèyàng de yīgè jiéguǒ dì èr gè jiùshì shuō wǒmen qíshí suízhe bāokuò xiàng duì shùjù yǐnsī xūqiú zhújiàn de zēngzhǎng bāokuò shùjù suǒ dài lái de yīxiē fùzuòyòng huòzhě shuō shùjù suǒ dài lái de yīxiē fēi jìshù de yāoqiú yuè lái yuè duōle bǐrú shuō dāng jǐ jiā jīgòu rúguǒ yào zuò liánhé jiàn mó de shíhòu shùjù bù nénggòu zài jīgòu zhī jiān fēnxiǎng bāokuò xiàng liánbāng xuéxí zhèyàng de jìshù jiùshì wèile zuò zài mǎnzú shùjù yǐnsī bǎohù de qíngkuàng xià lái qù zuò liánhé jiàn mó yě jiùshì shuō xiànzài dàjiā yǐjīng zhújiàn de yìshí dào zài jùtǐ de gōngyè kāifā zhōng kěnéng měi jiā jīgòu bù yīyàng dì dìfāng jiùshì tāmen de shùjùle xiànzài wǒmen yǒule fēicháng biànlì de ruǎnjiàn de kāiyuán de kuàngjià yǒule fēicháng gāoxiào de yìngjiàn de zhèxiē shíxiàn kěnéng mùqián gōngchéngshī dàliàng de shíjiān dōu zhuǎn ér qù guānzhù tā zìjǐ de shùjùle zhè dàgài shì yīgè Paradigm Shift jiùshì shuō yīgè bǐjiào fànshì jíbié de yīgè zhuǎnbiàn nín juédé zài zhège shùjù de jiǎodù duìyú réngōng zhìnéng de fǎ zhǎn lái shuō hái yǒu nǎxiē xiànzài de yù dào de wèntí yǒu yīgè wèntí kěnéng jiùshì shuō chǔlǐ shùjù de nénglì hé wǒmen cúnchú shùjù de nénglì bāokuò cúnchú shùjù de dàikuān zhōngjiān kěnéng cúnzàizhe yīdìng de hónggōu yě jiào wǒmen shuō de “shùjù qiáng” huòzhě shì zhèyàng de wèntí shì bùshì yěshì guānyú shùjù de xiànzài cúnzài de yīgè bǐjiào dà de wèntí nǐ shuō dé fēicháng duì wǒ zìjǐ fūhuà de bèi yàng liànghuà shì yījiā yǐ AI jìshù wèi héxīn de zhèyàng de yīgè duìchōng jījīn wǒmen qíshí jiù zāoyù dàole bǐjiào zhòngyào de yīgè wèntí jiùshì zěnme yàng dǎpò nèicún qiáng xiàng zài wǒmen gōngsī nèibù měitiān xūyào cúnchú de shùjù liàng dàgài shì 25~30TB/tiān suǒyǐ shuō zài zhèyàng dàliàng de zhè zhǒng rènwù xià wǒmen huì bǎ shùjù fēnchéng “lěng shùjù” “wēn shùjù” gēn “rè shùjù” “lěng shùjù” dàgài zhǐ de shì wǒmen fǎngwèn de pínlǜ bùshì hěn gāo luò kù jiù hǎo rè shùjù dàgài zhǐ de shì wǒmen yào zuò dàliàng de yīxiē dú xiě de zhèxiē rènwù ér shùjù yībān lái shuō dōu bǐjiào de sàn ér měi yīcì dú xiě de liàng yòu fēicháng de dà zěnme yàng de bǎ “rè shùjù” zuò yīgè bǐjiào hǎo de fēnbù shì de cúnchú zài zhīqián dehuà kěnéng zhǐyǒu bǐrú shuō chún SSD lái qù zuò zhèyàng de cúnchú xiànzài bǐrú shuō kěnéng huì yǒu yīxiē gèng hǎo de jiějué fāng'àn bǐrú shuō xiàng ào téng (chíjiǔ) nèicún zhèyàng de tā jiè yú nèicún gēn SSD zhī jiān lái qù jiāng “rè shùjù” lái zuò zhèyàng de yīgè fēnbù shì cúnchú kěnéng huì yǒu yīdìng chéngdù de lái jiǎnhuǎn “nèicún qiáng” de wèntí qíshí wǒmen dōu zhīdào ren gōng zhìnéng yìngyòng yǒu sān gè huòzhě wǒmen shuō sān jià mǎchē jiùshì suàn lì shùjù hái yǒu wǒmen zhège suànfǎ wǒmen qiánmiàn liáoguòle zhège suànfǎ hé shùjù xiànzài wǒmen kěyǐ liáo liáo suàn lì xiànzài yǒu gè hěn huǒ de gàiniàn jiào “yún yuánshēng” “yún yuánshēng” tā cùjìnle zhěnggè de yún jīchǔ shèshī de yīgè zhòng gòu cóng zhège jiǎodù lái kàn réngōng zhìnéng shìfǒu huì tuīdòng IT jīchǔ shèshī jiàgòu de yīgè xīn de zhòng gòu yě jiùshì shuō suǒwèi de zhè zhǒng AI yuánshēng de jīchǔ shèshī jiàgòu huì chūxiàn ma wǒ juédé zhège shìqíng yǐjīng zài zhēnshí de fǎ shēng le yóuqí shì wǒ juédé cóng guòqù de shí nián wǒmen duìyú yúnduāndì kě xìn jìsuàn de zhè zhǒng de xūqiú yuè lái yuè duō ér jiùshì shuō wǒmen de bǐrú shuō móxíng de jìsuàn guòchéng shì yīgè gōngsī de héxīn de zhīshì chǎnquán rúguǒ bǎ tā fàng dào yúnduāndì huà huòzhě fàng dào yīgè gòngyǒu de píngtái shàng dehuà tā yǒu kěnéng huì dānxīn jìsuàn guòchéng huì yǒu bèi qièqǔ de fēngxiǎn zài zhè zhǒng qíngkuàng xià yǒu méiyǒu yīxiē yìngjiàn de jiějué fāng'àn kěnéng zhège jiùshì yīgè fēicháng diǎnxíng de cóng xūqiú chūfā ránhòu ràng xīnpiàn chǎngshāng huòzhě yìngjiàn chǎngshāng lái qù tígōng xiāngyìng de jiějué fāng'àn de zhèyàng de yīgè lìzi bǐrú shuō xiànzài qíshí wǒmen nèibù yě zài yòng de yīxiē jìshù qù cèshì zài yīngtè'ěr xīnpiàn shàng de SGX jiùshì shuō zhèyàng de yīgè yǐnsī shā hé jiù nénggòu bǎozhàng wǒmen de suǒyǒu de jìsuàn yǐ yìngjiàn de fāngshì lái dédào yīdìng chéngdù de bǎohù qíshí shì kuà jī gòu zhī jiān hézuò de yīgè fēicháng zhòngyào de jīchǔ wǒmen shuō dào zhège yìngjiàn qíshí yìngjiàn néng zuò de shìqíng yě fēicháng de duōle gāngcái nín tí dào SGX qíshí shì yīgè fēicháng diǎnxíng de yīgè yuánběn zài ruǎnjiàn shàng dànshì xiànzài kěyǐ fàng dào yìngjiàn shàngqù zuò de yīgè shìqíng dànshì zài hěnduō rén de yǎnzhōng hǎoxiàng réngōng zhìnéng hǎoxiàng jiù děngtóng yú GPU huòzhě shì shuō réngōng zhìnéng de suàn lì hǎoxiàng jiù děngtóng yú shǐyòng GPU qù zuò xùnliàn nǐ juédé zhèyàng de xiǎngfǎ shì bù shì duì de zhège quèshí huì shāowéi piànmiàn yīxiē bǐrú shuō yǐ wǒ de bèi yàng liànghuà wǒmen rìcháng měitiān zuò de gōngzuò lái shuō dāng nǐ zài zuò liànghuà jiāoyì de shíhòu rúguǒ bǎ shùjù cóng CPU kǎobèi dào GPU shàng zài kǎobèi huílái duìyú hěnduō de liànghuà jiāoyì de rènwù yǐjīng láibujíle yě jiùshì shuō qíshí wǒmen xūyào yǒu yīgè fēicháng gāo xìngnéng shíxiàn de yīgè CPU bǎnběn de réngōng zhìnéng móxíng de shíxiàn zài bǐrú shuō wǒmen yǒu hěnduō de yīxiē rènwù xūyào zài wǎngkǎ shàng zhíjiē de duì yīxiē shùjù lái zuò fēnxī gēn chǔlǐ nà wǎngkǎ shàng yībān huì dài de yībān shì yīgè FPGA de zhèyàng de xīnpiàn zhège dōngxī qíshí tā yěshì rúguǒ yào chuán dào GPU shàng jiù gèng láibujíle duìyú zhè zhǒng dī yán shí yòu xūyào réngōng zhìnéng jìshù de bāngzhù de zhèxiē chǎngjǐng kěnéng wǒmen shì xūyào yīgè yì gòu de zhèyàng de yīgè jiàgòu yě jiùshì shuō bu guǎn shì PGA,ASIC háishì CPU háishì GPU kěnéng shì zài bùtóng de chǎngjǐng xià tā yǒu bùtóng de yòng wǔzhī dì qíshí xiànzài zhěnggè de xīnpiàn hángyè de fǎ zhǎn yěshì cóng yīgè tōngyòng zhuǎnxiàng yì gòu de zhème yīgè dà de huánjìng dànshì zhè lǐmiàn qíshí yěyǒu hěnduō zhèyàng de wèntí bǐrú shuō zhème duō zhǒng bùtóng de lèixíng de xīnpiàn rúhé bǎ tāmen zuò chéng yīgè wánzhěng de xìtǒng rúhé qù duì tā jìnxíng tǒngyī de biānchéng huòzhě shì tǒngyī de diàodù hé kòngzhì mùqián wǒ yě kàn dàole zài gōngyè jiè yǒu yīxiē chángshì bǐrú shuō xiàng yīngtè'ěr zhèngzài zuò de oneAPI wǒ juédé shì yīgè mán zhòngyào de gōngjù jiùshì shuō wǒ yòng zhège jiějué fāng'àn tóngyàng yī tào dàimǎ nǐ kěyǐ bǎ tā lǐjiě chéngwéi yī zhǒng tèshū de biānyì qì nǐ kěyǐ bǎ tā lǐjiě chéngwéi yī zhǒng tèshū de biānyì qì tā nénggòu zìdòng de zhuǎnhuàn chéngwéi fēnbié zài CPU shàng pǎo huòzhě zài FPGA huòzhě zài qítā lèixíng xīnpiàn shàng pǎo de chéngxù zhège jiāng huì dàdà de jiǎnshǎo gōngchéngshī zhè biān de kùnnán huòzhě shuō nénggòu dàdà de ràng gōngchéngshī zhuānzhù zài zuò suànfǎ zhè jiàn shìqíng shàng wǒ juédé shì yīgè tuīdòng yì gòu yìngyòng de yīgè fēicháng zhòngyào de shìqíng wǒ fēicháng néng lǐjiě nǐ shuō de zhè yī diǎn yīnwèi cóng FPGA de jiǎodù bǐrú shuō FPGA běnshēn suīrán yǒu gāngcái nín shuō de kěyǐ tígōng gāo bìngxíng huòzhě shì dī yán shí dànshì tā de biānchéng móxíng fēicháng de fùzá nàme GPU zhī suǒyǐ nénggòu zài réngōng zhìnéng shídài biàn dé rúcǐ de huǒbào huòzhě shì tā yǐndǎole yīdìng chéngdù de réngōng zhìnéng de tuīdòng qíshí bèihòu tā de biānchéng huòzhě shì tā de zhè zhǒng yì yòng xìng hé tā de biānchéng de nénglì yěshì hé tā fēn bù kāi de suǒyǐ rúguǒ yǒu yīgè tǒngyī de zhè zhǒng biānchéng de píngtái huòzhě shì zhè zhǒng fāngfǎ nénggòu shǐyòng yī tào ruǎnjiàn qù duì duō zhǒng de yìngjiàn qù jìnxíng biānchéng nàme kěndìng huì nénggòu zài zhěnggè xìtǒng de céngmiàn duì zhěnggè de shèjì lái shuō huì shì jí dà de tuīdòng nín juédé cóng xìtǒng de jiǎodù ruǎn yìngjiàn de jiǎodù wèilái de réngōng zhìnéng de fǎ zhǎn de fāng xiàng dōu hái yǒu nǎxiē wǒ juédé kěnéng wǒmen xūyào yīgè gèng hǎo de duān dào duān dì jiějué fāng'àn jiùshì shuō wǒmen xiànzài qíshí yǐjīng cóng suǒwèi de ruǎnjiàn 1.0 Shēngjí dàole ruǎnjiàn 2.0 Shídài jiùshì shuō cóng chuántǒng de guīzé qūdòng de fùzá de ruǎnjiàn gōngchéng de gòujiàn biàn chéngle shùjù qūdòng de zhèyàng de yīgè ruǎnjiàn gōngchéng de zhèyàng de yīgè gòujiàn fāngfǎ jiùshì shuō zài zhīqián wǒmen yào yòng fēicháng hǎo de cōngmíng cáizhì qù xiě yī xìliè jīngmiào de xìtǒng lái qù ràng zhěnggè de chéngxù nénggòu pǎo qǐlái jiù lèisì yú jīxiè shǒubiǎo zuì hǎo de chéngxù yuán de jīnglì dōu shì zài qù gòujiàn zhèxiē chǐlún de yùnzhuǎn nénggòu ràng shǒubiǎo jīngmì de nénggòu pǎo qǐlái xiànzài dehuà dàgài wǒmen zǒuxiàng de ruǎnjiàn gōngchéng shídài shì zhè yī tào de guīzé wǒ bù zhīdào gāi zěnme dìng wǒ zhíjiē bǎ tā liào gěi dàliàng de shùjù huòzhě shuō liào gěi yī tào jīqì xuéxí suànfǎ ránhòu zhège suànfǎ huì shēngchéng yīgè xīn de suànfǎ ér zhège xīn de suànfǎ shì wǒmen xiǎng qù dédào de zhège dōngxī yǒudiǎn lèisì yú xiàng wǒmen qù zào yīxiē zào jīqìrén de jīqìrén wǒmen bǎ tā jiào shùjù qūdòng zài ruǎnjiàn 2.0 Shídài zhěnggè de ruǎnjiàn gōngchéng de kāifā fànshì jiāng huì dédào yīgè bǐjiào dà de yīgè zhuǎnbiàn wǒmen hěn xīwàng dédào de yīgè yī zhǒng duān dào duān dì zhèyàng de yī tào jiějué fāng'àn héxīn jiùshì shuō zěnme yàng de gèng fāngbiàn de lái qù zuò zhè zhǒng yǐ shùjù wéi zhōngxīn de ruǎnjiàn gōngchéng de kāifā huí dào zhīqián wǒmen duì tán yī kāishǐ tí chūlái de wèntí hěn duō rén qíshí shuō xiànzài de",
        chinese: `越來越卷的人工智能未來會如何發展？
        從芯片聊科技
        從科技看人生
        Hello大家好 這裡是老石談芯
        我是芯片工程師老石
        我一直想做談話類的節目啊
        因為一個人的知識實在是太有限了
        所以我請大佬和我們一起談
        除了芯片和科技
        我們還會聊很多有意思的事情
        既要仰望星空
        又要低頭看路
        說的就是這個意思
        今天我們要聊的是很多人都非常關心的
        人工智能的話題
        現在人工智能已經無處不在了
        甚至這期視頻
        都有可能是人工智能推送給你的
        但是它的發展似乎陷入了瓶頸
        也引發了很多人的困惑和質疑
        今天我們就好好來聊一聊
        越來越卷的人工智能
        在現在和未來
        究竟還有哪些機會
        今天非常開心請到了馮霽博士
        他是創新工廠南京AI研究院的執行院長
        也是倍漾量化的創始人
        他在人工智能領域有著深厚的研究經驗
        Hello馮博士你好
        能不能給大家打個招呼
        謝謝老石的邀請 大家好
        我是馮霽
        AI創新遇到天花板？
        馮博士非常開心今天接受我們的邀請
        我們今天其實是想談
        您非常熟悉的人工智能領域
        特別是最近我們發現人工智能越來越捲了
        因為之前我看到一個消息
        就是谷歌的Jeff Dean
        他做了一個新的工作
        具體工作本身我們就不再多說了
        但是它的結果
        好像是比現在最新的結果
        提升了0.03%
        但是它這個結果
        引發了軒然大波的
        最主要的原因是
        他花了大概57,000多美元
        去取得了0.03%的這麼一點點提升
        所以大家都說
        AI這個領域
        實在是太捲了
        如果是普通人 普通高校
        或者是普通的公司
        甚至都不可能去複現這樣的工作
        對於這個工作您怎麼看
        這個問題其實最近受到了挺多的關注
        我是這樣看的
        首先第一
        確實以深度神經網絡技術
        為主導的人工智能
        目前確實 大廠開始逐漸的
        走向了所謂的暴力美學
        就是用超大規模的數據
        加超大規模的算力
        來去探索深度神經網絡
        它的天花板大概到底在哪
        第二就是從學術科研來說
        也許這並不是唯一的一條路
        目前有大量的一些研究
        在去探索一些其他的技術路線
        來怎麼樣的去做到從感知智能
        往認知智能
        去做這樣的一個轉變
        還有比如說一些小樣本的任務
        怎麼樣利用一些非常小的
        這樣的一些數據量
        來去做一些相關的人工智能的事情
        第三就是說從工業界來看
        所有的事情未必需要這麼大的算力
        其實工業界也有大量的
        非語音圖像
        或者文本這樣的這些任務
        其實也在倒逼這些學術界
        來去推出一些比較高效的
        一些這樣的算法
        AI算法並不只有深度神經網絡？
        所以我們先從算法的角度來去看
        人工智能
        您覺得有沒有更加廣闊
        或者是更加完全的一個視角去衡量
        或者是去看待人工智能這件事情呢
        可能在90年代之前
        人工智能的概念
        它所代表的背後的技術
        可能主要還是以符號主義
        就是基於這些邏輯推理
        Planning
        Searching這樣的技術
        這個世紀的從10年往後
        可能更重要的一次轉變
        就是用神經網絡的技術
        來更好的去表示
        這些感知類的任務
        但是目前其實還有大量的
        人工智能的所謂的
        比如說"聖杯"問題並沒有解決
        比如說像怎麼樣的去做邏輯推理
        怎麼樣的去做常識
        怎麼樣更好的去對記憶來去做建模
        這些事情是不是神經網絡就夠
        這一塊可能是目前學術界
        甚至工業界
        大家更關心的
        下一個更重要的事兒
        剛才您提到一個非常重要的一點
        我們現在的人工智能的研究
        可能更多的集中在這種感知領域
        但是在認知領域
        可能並沒有突破性的進展
        您覺得這會是新的人工智能的
        未來的發展方向嗎
        這個問題非常重要
        就是我們所說的感知人工智能
        其實就是最近幾年來
        人工智能成功落地的
        比如說圖像識別
        比如說語音轉文字這樣的應用
        或者比如說一些文本的生成
        這樣的一些任務
        更重要的可能是怎麼樣的
        從這種感知類的任務
        轉向一些
        具有一些認知能力的事情
        尤其是比如說
        怎麼樣的用人工智能的方式
        來去實現邏輯推理
        來去實現常識等等
        目前大概據我所知
        大概學術界主要還是有三條技術路線
        第一
        還是沿著神經網絡這條路去走
        就是說通過不斷的堆數據
        然後去堆算力來去看一看
        這件事情是否有可能
        第二條技術路徑是
        嘗試去同之前的這些符號主義的
        這些技術來去做結合
        所謂的神經主義加這個符號主義的結合
        然後第三個就是說怎麼樣
        將傳統的這些
        邏輯推理的這些技術
        再做一些新的提升
        這一塊可能會比較難
        因為大家已經做了很多年了
        剛才我們也討論了現在的AI算法
        包括應用的複雜度
        包括多樣性都非常非常大
        但是從另外一個角度來說
        除了AI的算法
        數據是不是也是同樣的重要
        因為有很多的公司
        包括研究者都說
        數據是現代社會的石油
        那麼甚至可能數據的重要性
        比石油的重要性更加的重要
        因為不管我們幹什麼事情
        比我們現在在聊天都會產生茫茫多的數據
        那麼從現在學術或者是工業界的角度來看
        數據對於人工智能或者對於AI來說
        它的重要性究竟在什麼地方
        其實數據對於人工智能工程來說
        重要性已經越來越高了
        甚至現在工業界我們提出了一個概念
        叫做以“數據為中心的開發模式”
        之前叫做“以模型為中心”
        什麼意思呢
        就是之前大概工程師更多的時間
        在於怎麼樣搭建一個模型
        怎麼樣去調參
        來讓這個系統的性能更好
        大概到了現在的話
        可能大家的80%左右的注意力都在
        怎麼樣的讓你的數據集變得更好
        我怎麼樣讓我的訓練集變得更好
        怎麼樣讓我的訓練集更平衡
        來去讓我的
        這個模型在好的數據集上訓練之後
        能夠得到一個比較好的這樣的一個結果
        第二個就是說我們其實隨著包括像對
        數據隱私需求逐漸的增長
        包括數據所帶來的一些副作用
        或者說數據所帶來的一些
        非技術的要求越來越多了
        比如說當幾家機構
        如果要做聯合建模的時候
        數據不能夠在機構之間分享
        包括像聯邦學習這樣的技術
        就是為了做
        在滿足數據隱私保護的情況下
        來去做聯合建模
        也就是說現在大家已經逐漸的意識到
        在具體的工業開發中
        可能每家機構不一樣的地方
        就是他們的數據了
        現在我們有了非常便利的
        軟件的開源的框架
        有了非常高效的硬件的這些實現
        可能目前工程師大量的時間
        都轉而去關注他自己的數據了
        這大概是一個
        Paradigm Shift
        就是說一個比較範式級別的一個轉變
        您覺得在這個數據的角度
        對於人工智能的發展來說
        還有哪些現在的遇到的問題
        有一個問題可能就是說
        處理數據的能力
        和我們存儲數據的能力
        包括存儲數據的帶寬
        中間可能存在著一定的鴻溝
        也叫我們說的“數據牆”
        或者是這樣的問題
        是不是也是關於數據的
        現在存在的一個比較大的問題
        你說得非常對
        我自己孵化的倍漾量化
        是一家以 AI技術為核心的
        這樣的一個對沖基金
        我們其實就遭遇到了比較重要的一個問題
        就是怎麼樣打破內存牆
        像在我們公司內部每天需要存儲的數據量
        大概是25~30TB/天
        所以說在這樣大量的這種任務下
        我們會把數據分成“冷數據”
        “溫數據”跟“熱數據”
        “冷數據”大概指的是
        我們訪問的頻率不是很高
        落庫就好
        熱數據大概指的是
        我們要做大量的一些
        讀寫的這些任務
        而數據一般來說都比較的散
        而每一次讀寫的量又非常的大
        怎麼樣的把“熱數據”
        做一個比較好的分佈式的存儲
        在之前的話可能只有比如說
        純SSD
        來去做這樣的存儲
        現在比如說可能會有一些更好的解決方案
        比如說像傲騰（持久）內存這樣的
        它介於內存跟SSD之間
        來去將“熱數據”
        來做這樣的一個分佈式存儲
        可能會有一定程度的來減緩“內存牆”的問題
        其實我們都知道人工智能應用有三個
        或者我們說三駕馬車
        就是算力 數據 還有我們這個算法
        我們前面聊過了這個算法和數據
        現在我們可以聊聊算力
        現在有個很火的概念叫“雲原生”
        “雲原生”它促進了整個的
        雲基礎設施的一個重構
        從這個角度來看
        人工智能是否會推動
        IT基礎設施架構的一個新的重構
        也就是說
        所謂的這種AI原生的
        基礎設施架構會出現嗎
        我覺得這個事情已經在真實的發生了
        尤其是我覺得從過去的十年
        我們對於雲端的
        可信計算的
        這種的需求越來越多
        而就是說我們的
        比如說模型的計算過程
        是一個公司的核心的知識產權
        如果把它放到雲端的話
        或者放到一個共有的平台上的話
        他有可能會擔心計算過程
        會有被竊取的風險
        在這種情況下有沒有一些硬件的解決方案
        可能這個就是一個非常典型的從需求出發
        然後讓芯片廠商
        或者硬件廠商
        來去提供相應的解決方案的
        這樣的一個例子
        比如說現在其實我們內部
        也在用的一些技術
        去測試在英特爾芯片上的SGX
        就是說這樣的一個隱私沙盒
        就能夠保障我們的所有的計算
        以硬件的方式來得到一定程度的保護
        其實是跨機構之間合作的
        一個非常重要的基礎
        我們說到這個硬件
        其實硬件能做的事情也非常的多了
        剛才您提到SGX
        其實是一個非常典型的一個
        原本在軟件上
        但是現在可以放到硬件上去做的一個事情
        但是在很多人的眼中
        好像人工智能好像就等同於GPU
        或者是說人工智能的算力
        好像就等同於使用GPU去做訓練
        你覺得這樣的想法是不是對的
        這個確實會稍微片面一些
        比如說以我的倍漾量化
        我們日常每天做的工作來說
        當你在做量化交易的時候
        如果把數據從CPU拷貝到GPU上
        再拷貝回來
        對於很多的量化交易的任務已經來不及了
        也就是說其實我們需要有一個
        非常高性能實現的
        一個CPU版本的人工智能模型的實現
        再比如說我們有很多的一些任務
        需要在網卡上
        直接的對一些數據來做分析跟處理
        那網卡上一般會帶的
        一般是一個FPGA的這樣的芯片
        這個東西其實它也是
        如果要傳到GPU上
        就更來不及了
        對於這種低延時
        又需要人工智能技術的
        幫助的這些場景
        可能我們是需要一個
        異構的這樣的一個架構
        也就是說不管是PGA、ASIC還是CPU
        還是GPU
        可能是在不同的場景下
        它有不同的用武之地
        其實現在整個的芯片行業的發展
        也是從一個通用轉向異構的
        這麼一個大的環境
        但是這裡面其實也有很多這樣的問題
        比如說這麼多種不同的類型的芯片
        如何把它們做成一個完整的系統
        如何去對它進行統一的編程
        或者是統一的調度和控制
        目前我也看到了在工業界有一些嘗試
        比如說像英特爾正在
        做的oneAPI
        我覺得是一個蠻重要的工具
        就是說我用這個解決方案
        同樣一套代碼
        你可以把它理解成為一種特殊的編譯器
        你可以把它理解成為一種特殊的編譯器
        它能夠自動的轉換成為分別在CPU上跑
        或者在FPGA
        或者在其它類型
        芯片上跑的程序
        這個將會大大的減少
        工程師這邊的困難
        或者說能夠大大的讓工程師
        專注在做算法這件事情上
        我覺得是一個推動異構應用的
        一個非常重要的事情
        我非常能理解你說的這一點
        因為從 FPGA 的角度
        比如說 FPGA 本身
        雖然有剛才您說的
        可以提供高並行
        或者是低延時
        但是它的編程模型非常的複雜
        那麼GPU之所以能夠在人工智能時代
        變得如此的火爆
        或者是它引導了
        一定程度的人工智能的推動
        其實背後它的編程
        或者是它的這種易用性
        和它的編程的能力
        也是和它分不開的
        所以如果有一個統一的這種編程的平台
        或者是這種方法
        能夠使用一套軟件
        去對多種的硬件去進行編程
        那麼肯定會能夠在整個系統的層面
        對整個的設計來說會是極大的推動
        您覺得從系統的角度
        軟硬件的角度
        未來的人工智能的發展的方向都還有哪些
        我覺得可能我們需要一個更好的
        端到端的解決方案
        就是說我們現在
        其實已經從所謂的軟件1.0升級到了
        軟件2.0時代
        就是說從傳統的規則驅動的
        複雜的軟件工程的構建
        變成了數據驅動的
        這樣的一個軟件工程的
        這樣的一個構建方法
        就是說在之前
        我們要用非常好的聰明才智
        去寫一系列精妙的系統
        來去讓整個的程序能夠跑起來
        就類似於機械手錶
        最好的程序員的精力
        都是在去構建這些齒輪的運轉
        能夠讓手錶精密的能夠跑起來
        現在的話大概我們走向的軟件工程時代
        是這一套的規則 我不知道該怎麼定
        我直接把它撂給大量的數據
        或者說撂給一套機器學習算法
        然後這個算法會生成一個新的算法
        而這個新的算法
        是我們想去得到的這個東西
        有點類似於像我們去造一些
        造機器人的機器人
        我們把它叫數據驅動
        在軟件2.0時代
        整個的軟件工程的開發範式
        將會得到一個比較大的一個轉變
        我們很希望得到的一個
        一種端到端的
        這樣的一套解決方案
        核心就是說怎麼樣的
        更方便的來去做這種
        以數據為中心的
        軟件工程的開發
        回到之前
        我們對談一開始提出來的問題
        很多人其實說現在的技`
    }
};

export default artificialInteligence;