const becomingRich = {
    videoId: 'dO43YU9XVqo',
    transcript: {
        pinyin: "hi, dàjiā hǎo, wǒ shì hǎo yè. Péi nǐ yīqǐ xuéxí xuéxiào méi jiào de zhīshì! Jīngguò yìqíng de xǐlǐ, ràng wǒmen zài sīkǎo hé xíngwéi shàng dū chūxiànle hěnduō biànhuà, zhè bāo kuò liǎo shìyè, gōngzuò, jiànkāng hé guānxì. Yě ràng wǒmen jìnrùle fǎnsī de jiēduàn, fǎnsī zìjǐ de gèzhǒng xīnzhì móshì hé xíguàn. Ér jīntiān zhè yī jí ne, wǒ jiāng huì hé dàjiā fēnxiǎng, yǒu guānyú cáifù shàng de fǎnsī. Ràng dàjiā liàojiě dào, pǔtōng rén shì rúhé kěyǐ biàn yǒu qián de 4 gè jiēduàn. Zài měi gè jiēduàn wǒ dūhuì jǐyǔ xiāngguān tiējìn xiànshí de gèrén kànfǎ. Shì wǒ zhè yīgè pǔtōng rén guòqù de jīngyàn hé guāndiǎn, xīwàng kěyǐ duì nǐ yǒu suǒ qǐfā. Shǒuxiān dì yīgè jiēduàn, fù jiēduàn qíshí, wǒmen yī chūshēng xiàlái jiùshì líng zīchǎn líng fùzhài de, dàn suízhe wǒmen de fùmǔ fǔyǎng wǒmen zhǎngdà, cháimǐyóuyán yīshízhùxíng zhèxiē jiùshì wǒmen qiàn fùmǔ de qián. Dāngrán nǐ yě kěyǐ shuō zhè shì nǐ fùmǔ qiánshì qiàn nǐ de, xiànzài lái fǔyǎng nǐ jiùshì zài huánzhài. Dàn wǒ xiāngxìn hěnduō pǔtōng rén dōu gēn wǒ yīyàng, zài dàxué bìyè de shíhòu, hěn kěnéng hái huì yǒu yīxiē xuéxiào dàikuǎn xūyào chánghuán de. Tóngshí ne, shēn wèi xiǎokāng zhī jiā de nǐ cúnkuǎn yě bù huì duō dào nǎlǐ qù, suǒyǐ zài zhè yīgè jiēduàn, zài cáifù shàng, wǒmen suànshì yīgè fù jiēduàn ba, jiùshì fùzhài de fù. Wǒ jìdé zài wǒ 20 suì de shíhòu ne, cúnkuǎn jiù zhǐyǒu 8000 kuài éryǐ. Jiā shàng dú dàxué de dàikuǎn hé fùmǔ de yǎnglǎo jīn, rúguǒ kòuchú diào zhè yīxiē zhīhòu, xiāngxìn nǐ hé wǒ yīyàng, dōu shì fùzhài lěi lèi de. Zài xiàn jiēduàn, qiān wàn bùyào xiǎng shénme cáifù zìyóu, tóuzī lǐcái, gǔpiào, shénme jījīn huíbào lǜ děng děng de. Nǐ mùqián zuìdà de mùbiāo jiùshì cún qián, xiān ràng zìjǐ yǒu cúnkuǎn, bù huì yīnwèi fùzhài ér fánnǎo huò shì gǎndào yālì. Yīnwèi rúguǒ nǐ dàizhe zhàiwù, qù zuò tóuzī, yòuhuòzhě shì kāiqǐ rènhé de shēngyì dehuà, wǎngwǎng wǒmen dūhuì gǎndào fēicháng de yālì, fēicháng de qíngxù huà. Hěn róngyì de jiù huì kuī qiánle, érqiě hái huì yǒu duǎn shì de qíngkuàng chūxiàn, yīnwèi nǐ yīdìng huì jígōngjìnlì, xīnjí xiǎng yào zhuàn kuài qián. Suǒyǐ zài zhè yīgè shíhòu 99%huì bèi piàn, yòuhuòzhě shì luàn luàn chǎogǔ. Suǒyǐ fǎn fǎnfù fù de qù zhuànqián ránhòu kuī qián, jiùshì yīgè bìrán de shìqíng. Dàotóulái nǐ jiù huì fāxiàn, yuánlái háishì yuán dì tàbù, què làngfèile xǔduō shíjiān chéngběn. Hěn xiàng wǒ yǐqián zài 18 suì de shíhòu, jiù jīngcháng chǎogǔ ránhòu chǎo qíhuò, hái yǒu gèzhǒng gè yàng de xiǎo xiǎo de tóuzī, dàn měi yīcì ne dōu shì huì huíguī dào yuán diǎn, zuìhòu wǒ jiù huì fāxiàn, tā gēnběn jiùshì yīnwèi wǒ qióng suǒyǐ xiǎng yào yīyè bào fù, ér zhè zhǒng bù hǎo de xīnlǐ zhuàngtài, jígōngjìnlì de qíngkuàng zhī xià ne, ràng wǒ hěn róngyì de jiù huì kuīběn. Suǒyǐ zài nà yīgè shíhòu, wǒ jiù juédìng, xiān zhuānzhù qù dǎgōng lái cún qián, qù zuò zhuāngxiū gōng a, qù zuò zhè yīgè qīngjié gōng, fúwùyuán děng děng de. Dūhuì yīgè yīgè de lái qián yīqián, ràng zìjǐ yǒu yīxiē cúnkuǎn, děng zìjǐ yǒule yīxiē cúnkuǎn xīnlǐ tàshí de shíhòu cái láiqù zuò tóuzī. Hòulái ne, dāng wǒ yǒu yīxiē cúnkuǎn de shíhòu ne, wǒ de tóunǎo jiù biàn qīngxīle, yīnwèi wǒ zhīdào wèilái yào zěnyàng qù guīhuàle, zhīdào yīnggāi yào zěnyàng tóuzī yīnggāi yào tóuzī shénme. Nà yǒule chàbùduō 10000 mǎ bì de cúnkuǎn de shíhòu ne, zài zhè yīgè shíhòu jiù yǐjīng zúgòu wǒ 1 nián de shēnghuófèi. Yě jiùshì shuō wǒ zài bù gōngzuò de qíngkuàng xià ne, háishì kěyǐ shēnghuó yī nián zhèyàng jiǔ de. Zài nà shíhòu ne, wǒ cái kāishǐ xiǎo'é qù tóuzī gǔpiào, jiéguǒ yòng xiánqián tóuzī shì wánquán méiyǒu yālì de. Nà zìrán'érrán de qíngkuàng zhī xià ne, zhè yīgè tóuzī de shōuyì jiùshì bùduàn de zài zēngzhǎng. Suǒyǐ shuō, zài yī kāishǐ wǒmen de fù jiēduàn, zuì shǒuyào de mùbiāo, shǒuyào de rènwù, jiùshì yào ràng wǒmen yǒu yīxiē cúnkuǎn, ràng zìjǐ kěyǐ ānxīn xiàlái, zhèyàng wǒmen cái kěyǐ zuò chū lěngjìng de pànduàn, zuò chū zhèngquè de juédìng. Yàoshi nǐ de fùzhài yǒu hěn gāo de lìxí yào chánghuán dehuà, nà yě jiànyì xiān hái diào. Dàn rúguǒ nǐ de fùzhài shì méiyǒu shé me lìxí, xiàng shì xuéshēng dàikuǎn zhèyàng dehuà, nà jiù kěyǐ zìjǐ ānpái yīxià, zuì zhǔ shì yào ràng zìjǐ ānxīn zhèyàng jiù kěyǐle. Wǒ zìjǐ běnshēn jiùshì kǎoqǔ hǎochéngjī, huòmiǎn diào xuéshēng dàikuǎn de. Dāng shíhòu wǒ shì wèile bǎ xuéshēng dàikuǎn zhuǎnhuàn chéng zhège jiǎngxuéjīn cái yòngxīn qù dúshū de, bìng bùshì yīnwèi wǒ tiānshēng jiù hěn lìhài dúshū, yǐqián wǒ zài zhōngxué de shí hóu ne chéngjī shì fēicháng de làn de, guówén, yīngwén hái yǒu lìshǐ quánbù dōu shì jīngcháng ná Elephant de. Dànshì wèile huòmiǎn diào dài xué jīn, suǒyǐ jiù jī qǐle xuéxí yùwàng. Cóng'ér jīfā chūle tǐnèi de yīxiē xiǎoyǔzhòu. Dì èr bù, líng jiēduàn zài zhè yīgè jiēduàn, wǒmen méiyǒu shé me fùzhài, cúnkuǎn yě bù duō. Suànshì cóng 0 kāishǐ ba, zhèshíhòu wǒmen xūyào zuò de shìqíng, jiùshì dǐng zhù yòu huò. Shēnghuó zài zhège hùliánwǎng shídài, shèjiāo méitǐ zǒng shì huì gěi wǒmen yīzhǒng xìnxī. Yào qù huán yóu shìjiè shìjiè, tǐyàn shēnghuó, pǐncháng gèzhǒng gè yàng dì měishí, huó chū zìwǒ. Ránhòu ne nǐ jīngcháng jiù huì kàn dào nǐ shēnbiān de péngyǒu, jīngcháng qù mǒu mǒu guójiā lǚxíng, ránhòu zuò shénme jiāohuàn shēng děng děng de. Zhè shíhòu ne, nǐ hěn róngyì jiù huì gǎndào dòngyáo, jiù huì gàosù zìjǐ wǒ yě yào qù nà biān wán, wǒ yě yào hé tā yīyàng tǐyàn shēnghuó, huán yóu shìjiè ránhòu pāi měiměi de zhàopiàn. Bùrán dehuà nǐ de shēnghuó jiù huì fēicháng de wúqù, hěn diūliǎn, yīnwèi nǐ bù rùliú. Dàn rúguǒ zhè shíhòu nǐ zhèyàng zuò dehuà, jiù huì gěi nǐ cáifù jīlěi de guòchéng mái xià yīgè fúbǐ, yīnwèi nǐ cún bù dào qián, méiyǒu cúnkuǎn. Tóngyàng shì 10%de huíbào lǜ, tóuzī 1000 kuài hé tóuzī 100000, suǒ shōuhuò de huíbào shì chà hěnduō hěnduō de. Suǒyǐ yīdìng yào xiān jīlěi dào dì yī tǒng jīn zhīhòu, cái lái xiǎng lǚyóu zhèxiē dōngxī. Yīnwèi ne nǐ suǒ kàn dào de zhèxiē péngyǒu dōu shì jiājìng bù fěi, yòu huòzhě shì jīnqián guān shì yǒu suǒ bùtóng de. Nà yīxīn xiǎng yào chéngwéi yǒu qián rén de nǐ, yīdìng yào zhuānzhù zài zìjǐ xiǎng yào de, kàn dé yuǎn yīdiǎn. Ér bùshì yīnwèi biérén yǒu ránhòu zìjǐ jiù xiǎng yào, ránhòu jiù mǎshàng jiù chōngdòngle. Jìdé, wǒ zài shàng dàxué de shíhòu, yǒu yīgè nǚxìng péngyǒu yāoyuē wǒ yīqǐ qù chūguó zuò jiāohuàn shēng, ránhòu qù lǚxíng. Nà shíhòu ne wǒ jiù mǎshàng wèn tā, è, zhège jiāohuàn shēng shì xuéxiào zhīfù de ma? Háishì wǒ yào zìjǐ tāoyāobāo ne? Nà rúguǒ shì zìjǐ tāoyāobāo dehuà, fèiyòng dàgài shì xūyào zhǔnbèi duōshǎo? Tā dàgài jiù gēn wǒ shuōle yīxià, yīnggāi shì 10000 mǎ bì ba, nà rúguǒ jiā shàng lǚyóu dehuà yīnggāi shì 15000 zhèyàng zi de. Nà shíhòu wǒ mǎshàng jiù gē'ài jùjuéle. Dàn tā quèshuō, wèishéme nǐ yào fánnǎo zhèxiē dōngxī ne, dàxuéshēnghuó, nǐ jiù yīnggāi jìnqíng xiǎngshòu ma, qù tǐyàn gèzhǒng gè yàng bù yīyàng de dōngxī. Nà shì wǒ hái lèngle yīxià, yǒudiǎn zìbēi de jiù shuōdao: Duìbùqǐ a, wǒ xūyào kǎolǜ zhèxiē xiànshí céngmiàn shàng de dōngxī. Rúguǒ nǐ yǒu yù dào lèisì qíngkuàng dehuà, qíshí wǒmen yě bù xūyào gǎndào fēicháng de zìbēi de, yīnwèi wǒmen měi gèrén de chéngzhǎng jīnglì de bùtóng, suǒyǐ yě huì yǎnshēng chū bù yīyàng de jīnqián guān. Suǒyǐ ne dàjiā zhǐshì jīnqián guān shàng de bùtóng éryǐ, wǒmen dōu shì píngděng de. Nà huàshuō huílái a, jiù xiàng shì gāng chū shèhuì gōngzuò de xué shēng yěshì yīyàng, zhèxiē lǚyóu a, kàn shìjiè, tǐyàn shēnghuó de, wǒmen zhèxiē pǔtōng rén jiù xiān rěn yī rěn ba, yánchí xiǎnglè yīxià. Yào biàn yǒu qián dehuà, xiàn jiēduàn wǒmen yào zuò de jiùshì jīlěi zìjǐ de dì yī tǒng jīn, zhèyàng cáinénggòu gèngjiākuài de xiǎngshòu dào fùlì xiàoyìng suǒ dài lái de xiàoguǒ. Guānyú `dì yī tǒng jīn'de gàiniàn dàjiā yě kěyǐ guānkàn wǒ nà zhǐ dì yī tǒng jīn de yǐngpiàn ó. Tóngyàng de, zài gāng chū shèhuì gōngzuò, jiéhūn bǎi jiǔxí, shēng háizi de, wǒmen dōu yào hǎohǎo de qù kǎoliáng hé guīhuà yīxià, yīnwèi háizi yīshēng xiàqù, tóngyàng yě huì dà fúdù yǐngxiǎng wǒmen biàn yǒu qián de sùdù de. Suǒyǐ zài zhège yīgè jiēduàn, wǒmen de shǒuyào rènwù jiùshì yánchí xiǎnglè, xuéhuì zuìxiǎo huà ràng cáifù biǎnzhí de xiǎngshòu. Hěnduō xiǎngshòu xíng de huódòng dōu shì yī qù bù fǎn de. Bǐrú,Netflix, lǚxíng, zuò spa, gèzhǒng gè yàng de tǐyàn. Tóng shíjiān wǒmen zài zhè yīgè jiēduàn yě yào bùduàn de qù xúnzhǎo zhuànqián de jīhuì, bǐrú dǎgōng jiānzhí, fùyè, pǎotuǐ, shénme dōu zuò yī zuò cái kěyǐ ràng zìjǐ zhǎodào yīgè ràng nǐ cáifù kuàisù zēngzhǎng de jīhuì, lěijì dào zìjǐ yībǐ kěguān de cúnkuǎn. Nà shíhòu, wǒ jiù zuòle gèzhǒng jiānzhí de gōngzuò, bǐrú bǎoxiǎn, xīnjiāpō zuò qīngjié gōng, gèzhǒng wǎngluò diǎn guǎnggào, yǐngpiàn jiǎnjí, zài xuéxiào màidiǎn dōngxī, zūchē děng děng de. Zài yīcì de jīyuán qiǎohé zhī xià ne, wǒ zhǎodàole yīgè yǒu guānyú xīnchē de shìchǎng tiáo chá gōngzuò. Zhè yī fèn gōngzuò de gōngzī duìyú dāng shíhòu zàidú dàxué de wǒ lái shuō ne, shì fēicháng de gāo de. Qù xúnzhǎo yīgè xīnchē de chēzhǔ, ránhòu hòu liǎnpí shàngmén qù wènjuàn diàochá, diàochá dào yī liàng chē jiù kěyǐ mǎshàng huòdé RM100 de shōurùle. Zhè yīgè gōngzuò suīrán duǎn duǎn de 3-4 yuè, dàn měi gè yuè ne wǒ dū kěyǐ cóng zhè fèn gōngzuò zhuàn qǔ 5000 kuài mǎ bì zuǒyòu de gōngzī, jiù zhèyàng dǐ zhù yòu huò de wǒ, kāishǐ cún dàole yīxiē qián. Nà dāng wǒmen yǒule yīdiǎn xiǎoqián hé cúnkuǎn, yě bù suànshì fùzú de qíngkuàng xià ne, zhè shíhòu, wǒmen jiù lái dào zú jiēduàn. Nà xiàn jiēduàn, wǒmen jiù kěyǐ bǎ wǒmen de zījīn fēnchéng jǐ gè bùfèn lái yòng de. Wǒ de fāngshì fēnbié jiùshì tóuzī zìjǐ, tóuzī shìyè, tóuzījīnqián, yǐjí jǐnjí chúbèi jīn. Yǒule zhè yīxiē cúnkuǎn jiù yào bǎ zhèxiē qián huóyòng qǐlái. Shǒuxiān tóuzī zìjǐ, bǐrú jiàoyù: Tóuzī zài zìjǐ de rènzhī shàngmiàn. Bǐrú yuèdú, sīkǎo fāngshì, chǔlǐ wèntí; zài bǐrú hái yǒu wǒmen de jìnéng: Tóuzī zài zìjǐ duìyú mǒu zhǒng lǐngyù de cāozuò nénglì xiàng shì wén'àn, biānchéng, xiāoshòu, xíngxiāo, jīngyíng shèjiāo méitǐ děng děng de. Yǐshàng duìyú wǒmen zìjǐ de tóuzī ne, dōu shì tíshēng wǒmen wèilái zhuànqián qiánlì de tóuzī xiàngmù. Zhèxiē huíbào lǜ ne kěndìng shì chāoguò 100%de. Dì èr, tóuzī shìyè bǎ yībùfèn de qián, ná lái tóuzī zìjǐ xiǎng yào kāiqǐ de shìyè shàngmiàn. Zài nàgè shíhòu ne, wǒ jiù tèbié xǐhuān wǎngluò zhuànqián zhège gàiniàn. Suǒyǐjīngcháng jiù huì mǎi yīxiē shū hé kèchéng lái xuéxí, tóuzī zài zìjǐ de jìnéng shàngmiàn, ránhòu yě huì dàochù gòumǎi gèzhǒng gè yàng de ruǎnjiàn láiqù chángshì, yě jǐ zìjǐ mǎile yī bù bǐjiào hǎo de diànnǎo lái tíshēng zìjǐ de gōngzuò xiàolǜ. Jiéguǒ hěn xìngyùn de, yīnwèi xǐhuān zuò, suǒyǐ jiù huì fēicháng yòngxīn de zuò, yī bù xiǎoxīn jiù zuò chūle hǎo yè píndào, yě kāishǐ chénglìle yīgè yǒu guānyú gèrén chéngzhǎng de xiànshàng jiàoyù pǐnpái, chéngzhǎng ba. Yòng zhīshì diǎnrán shēnghuó, bāngzhù gèng duō rén péiyǎng rénshēng bìbèi ruǎn shílì. Suǒyǐ qiān wàn bùyào ràng zìjǐ hòuhuǐ, yǒu xiǎngfǎ yǒu rèchén dehuà, jiù yào gǎn gǎn qù zuò, yīnwèi zìjǐ xǐhuān de dōngxī, wǎngwǎng huì bǐ biérén zuò dé gèng jiā de hǎo, suǒyǐ yě huì gěi nǐ dài lái gèng gāo shōurù de jīhuì. Gēnjù fǎn cuìruò de lǐlùn, zhǐyào yuànyì zài zìjǐ juédé yǒu wèilái fāzhǎn qiánjǐng de lǐngyù duō chángshì dehuà, nà chéngwéi bā'èr fǎzé lǐmiàn de 20%de kěnéng xìng shì fēicháng de gāo de. Suǒyǐ qiān wàn bùyào hàipà chángshì. Dì sān, tóuzījīnqián dāngrán, tóuzī shìyè yěshì yǒu fēngxiǎn de, érqiě hěnduō qíngkuàng xià ne, chuàngyè yě bù xūyào nǐ nàme duō de qián. Yīnwèi qián bìng bùshì bǎozhèng chuàngyè chénggōng de guānjiàn. Suǒyǐ ne hái yǒu duō chūlái de qián ne, wǒmen jiù kěyǐ ná qù tóuzī ba, gěi nǐ de qián yī fèn gōngzuò, tì nǐ chuàngzào gèng duō de shōurù. Yīnwèi rúguǒ nǐ cúnzài yínháng, huòzhě shì fàng dìng cún dehuà, lìxí jiù zhǐyǒu 1-2%éryǐ. Tōnghuò péngzhàng shì 5%, měinián ne nǐ dūhuì kuī gè 3%. Zài nà yīgè shíhòu wǒ jiù xuǎnzéle gǔpiào, yīnwèi wǒ fēicháng xǐhuān kējì hé zīxùn. Suǒyǐ jīngcháng jiù huì yuèdú gèzhǒng gè yàng guānyú kējì de fāzhǎn hái yǒu shāngyè de zīxùn. Yīnwèi tóuzī gǔpiào jiùshì tóuzī gōngsī ma, suǒyǐ hěn zìrán de, kànle gèzhǒng gè yàng de zīxùn, xuéxí jìnxíng pànduàn. Ránhòu jiù shùnbiàn jiù tóuzī yīxià. Suǒyǐ chéngjī hái suàn shì bùcuò de, měinián píngjūn xiàlái dōu yǒu yīgè 20%yǐshàng de huíbào lǜ de. Nà yàoshi nǐ xiǎng yào tóuzī, dànshì yòu méiyǒu jīngyàn dehuà, nàme tóuzī ETF jījīn jiùshì yīgè bùcuò de xuǎnzé. Guānyú zhè yīdiǎn wǒ huì zài zhìfù de jiēduàn de shíhòu ne, gēn dàjiā xiángxì de jiěshì de. Dì sì gè bùfèn, jǐnjí chóubèi jīn cúnkuǎn yǒule, wǒmen yě yào xuéhuì wèiyǔchóumóu a, wèi zuì huài de dǎsuàn zuò zuò zhǔnbèi, suǒyǐ shēnghuó zhǐ huì yuè lái yuè hǎo. Nǐ wèi zuì huài de dǎsuàn zuò zhǔnbèi, děngdào huài de qíngkuàng chūxiàn de shí hóu ne nǐ jiù huìguò dé fēicháng de hǎo. Jiù xiàng shì 07,08 nián de jīnróng hǎixiào yīyàng, hěnduō rén dōu hènbudé shǒu tóushàng yǒu hěnduō de zī jīn, zài shìchǎng rúcǐ huài de qíngkuàng zhī xià ne jìn chǎng gòurù zīchǎn, dànshì xiāngxìn dà bù fèn de rén dōu méiyǒu zhème zuò, érqiě hái kěnéng yīzhí bùduàn de mài diào shǒu tóushàng de zīchǎn, bǐrú fángdìchǎn huò shì gǔpiào, huàn lái xiànjīn jiějué yǎnqián de jīnróng wéijī. Zhè yīcì 2020 de yìqíng yěshì yīyàng, rúguǒ nǐ yǒngyǒu liánghǎo de tóuzī nénglì, yǐjí bèiyòng jījīn dehuà, nà zhè shí fǎn'ér shì kěyǐ ràng nǐ de cáifù kuòzhāng bèizēng de jīhuì. Xiàng zhècì wǒ jiù chènjī dàikuǎn mǎile liǎng tàofáng, měi yīcì de dàxiǎo jīnróng shìjiàn dūhuì zàochéng cáifù chóngxīn de fēnpèi, rúguǒ wǒmen méiyǒu wéi zuì huài de qíngkuàng zuò zhǔnbèi, zǒng huì jiāng zìjǐ de cáifù fēnpèi jǐ le biérén. Nà dāng wǒmen kāishǐ yǒule wěndìng de cáifù zēngzhǎng jīchǔ, yǒule gè shì de shōurù, yǒu jǐnjí chúbèi jīn, yě kāishǐ yǒule yīxiē tóuzī de bèidòng shōurù de zhè shíhòu ne, xiànzài wǒmen jiù lái dàole zhǔnbèi zhìfù de jiēduàn. Zài zhè yīgè jiēduàn ne, shǒuxiān wǒmen xūyào shèzhì yīgè cáifù zìyóu de mùbiāo. Jiǎndān lái shuō, dāng nǐ měi gè yuè de bèidòng shōurù, dà guòyú wǒmen jiātíng zhīchū de shíhòu ne, jīběn shàng wǒmen jiù yǐ jīng dádàole cáifù zìyóu de jiēduànle. Suǒyǐ nǐ xiànzài yào jìsuàn de jiùshì, nǐ de jiātíng kāizhī shì duōshǎo? Nà bùguǎn nǐ yǒu méiyǒu mǎifáng huòzhě shì jiéhūn shēng háizi dōu hǎo, dōu kěyǐ dàgài de yùjì yīxià, nǐ xiǎng yào zhù zěnme yàng de fángzi, kāi zěnme yàng de chēzi, ránhòuguò zěnme yàng de shēnghuó? Zhè yīqiè dōu xūyào duōshǎo de qián? Nà bǐfāng shuō, nǐ yī nián de jiātíng kāizhī shì 10000 měiyuán dehuà, suǒyǐ nǐ mùqián de cáiwù zìyóu mùbiāo, jiù yào quèbǎo zìjǐ měinián dōu zhìshǎo yǒu chāoguò 10000 měijīn de bèidòng shōurù. Zhīdàole zhège shùzì zhīhòu ne, jiē xiàlái wǒmen jiù kěyǐ lái jìsuàn yīxià, zěnyàng kěyǐ tòuguò tóuzī de fāngshì lái dádào zhè yīgè mùbiāo. Rúguǒ shì tòuguò tóuzī gǔpiào huò shì ETF, měinián píngjūn huíbào shì 10%dehuà, nà wǒmen yào tóurù duōshǎo de qián, cái néng měinián huòdé 10000 měijīn de bèidòng shōurù ne? Hěn jiǎndān, jiùshì bǎ 10000 chú yǐ 10%, zhèyàng jiù huì huòdé 100000 měijīn de zhè yīgè shùmùliǎo, nà zhè yīgè 100000 měijīn jiùshì nǐ de mùbiāole, zhǐyào nǐ nénggòu léi jī dào zhège shùmù, bǎ tā chéngwéi nǐ de shēng qián gōngjù, měinián gěi nǐ dài lái 10%de huíbào, jiù huì ràng nǐ měinián shōuhuò 10000 měiyuán de bèidòng shōurùle. Yào jīlěi dào 100000 měijīn de tóuzī jīn'é qíshí yīdiǎn yě bù nán. Kào de jiùshì fùlì +zhǔdòng tóurù de fāngshì. Jiǎshè nǐ xiànzài yǒu 10000 měijīn de qǐdòng zī jīn dehuà, rúguǒ shì 10%fùlì, dān kào běn jīn yào gǔn dào 100000 měijīn dehuà, zhǐ shǎo yào yī gè 25 nián. Suǒyǐ wǒmen zài qiánqí de shíhòu, kěndìng shì yào bùduàn de tiānjiā tóuzī jīn'é de. Rúguǒ měinián dōu tóurù shōurù de 30%, bǐrú 5000 kuài dehuà, nàmó xuě qiú jiù huì yuè",
        chinese: `Hi，大家好，我是好葉。
        陪你一起學習學校沒教的知識！
        經過疫情的洗禮，
        讓我們在思考和行為上都出現了很多變化，
        這包括了事業，工作，健康和關係。
        也讓我們進入了反思的階段，
        反思自己的各種心智模式和習慣。
        而今天這一集呢，我將會和大家分享，
        有關於財富上的反思。
        讓大家瞭解到，普通人是如何可以變有錢的4個階段。
        在每個階段我都會給予相關貼近現實的個人看法。
        是我這一個普通人過去的經驗和觀點，
        希望可以對你有所啓發。
        首先第一個階段，負階段
        其實，我們一出生下來就是零資產零負債的，
        但隨著我們的父母撫養我們長大，
        柴米油鹽衣食住行這些就是我們欠父母的錢。
        當然你也可以說這是你父母前世欠你的，
        現在來撫養你就是在還債。
        但我相信很多普通人都跟我一樣，在大學畢業的時候，
        很可能還會有一些學校貸款需要償還的。
        同時呢，身為小康之家的你存款也不會多到哪裡去，
        所以在這一個階段，在財富上，
        我們算是一個負階段吧，就是負債的負。
        我記得在我20歲的時候呢，存款就只有8000塊而已。
        加上讀大學的貸款和父母的養老金，
        如果扣除掉這一些之後，
        相信你和我一樣，都是負債累累的。
        在現階段，千萬不要想什麼財富自由，
        投資理財，股票，什麼基金回報率等等的。
        你目前最大的目標就是存錢，
        先讓自己有存款，
        不會因為負債而煩惱或是感到壓力。
        因為如果你帶著債務，去做投資，
        又或者是開啓任何的生意的話，
        往往我們都會感到非常的壓力，非常的情緒化。
        很容易的就會虧錢了，
        而且還會有短視的情況出現，
        因為你一定會急功近利，心急想要賺快錢。
        所以在這一個時候99%會被騙，又或者是亂亂炒股。
        所以反反復復的去賺錢然後虧錢，
        就是一個必然的事情。
        到頭來你就會發現，原來還是原地踏步，
        卻浪費了許多時間成本。
        很像我以前在18歲的時候，就經常炒股然後炒期貨，
        還有各種各樣的小小的投資，
        但每一次呢都是會回歸到原點，
        最後我就會發現，
        它根本就是因為我窮所以想要一夜暴富，
        而這種不好的心裡狀態，急功近利的情況之下呢，
        讓我很容易的就會虧本。
        所以在那一個時候，我就決定，
        先專注去打工來存錢，
        去做裝修工啊，去做這一個清潔工，服務員等等的。
        都會一個一個的來乾一乾，讓自己有一些存款，
        等自己有了一些存款心裡踏實的時候才來去做投資。
        後來呢，當我有一些存款的時候呢，
        我的頭腦就變清晰了，
        因為我知道未來要怎樣去規劃了，
        知道應該要怎樣投資應該要投資什麼。
        那有了差不多10000馬幣的存款的時候呢，
        在這一個時候就已經足夠我1年的生活費。
        也就是説我在不工作的情況下呢，
        還是可以生活一年這樣久的。
        在那時候呢，我才開始小額去投資股票，
        結果用閒錢投資是完全沒有壓力的。
        那自然而然的情況之下呢，
        這一個投資的收益就是不斷的在增長。
        所以說，在一開始我們的負階段，
        最首要的目標，首要的任務，
        就是要讓我們有一些存款，讓自己可以安心下來，
        這樣我們才可以做出冷靜的判斷，做出正確的決定。
        要是你的負債有很高的利息要償還的話，
        那也建議先還掉。
        但如果你的負債是沒有什麼利息，像是學生貸款這樣的話，
        那就可以自己安排一下，
        最主是要讓自己安心這樣就可以了。
        我自己本身就是考取好成績，豁免掉學生貸款的。
        當時候我是為了把學生貸款轉換成這個獎學金
        才用心去讀書的，
        並不是因為我天生就很厲害讀書，
        以前我在中學的時侯呢成績是非常的爛的，
        國文，英文還有歷史全部都是經常拿Elephant的。
        但是為了豁免掉貸學金，所以就激起了學習慾望。
        從而激發出了體內的一些小宇宙。
        第二步，零階段
        在這一個階段，我們沒有什麼負債，存款也不多。
        算是從0開始吧，
        這時候我們需要做的事情，就是頂住誘惑。
        生活在這個互聯網時代，
        社交媒體總是會給我們一種信息。
        要去環遊世界世界，體驗生活，
        品嚐各種各樣的美食，活出自我。
        然後呢你經常就會看到你身邊的朋友，
        經常去某某國家旅行，然後做什麼交換生等等的。
        這時候呢，你很容易就會感到動搖，
        就會告訴自己我也要去那邊玩，
        我也要和她一樣體驗生活，
        環遊世界然後拍美美的照片。
        不然的話你的生活就會非常的無趣，
        很丟臉，因為你不入流。
        但如果這時候你這樣做的話，
        就會給你財富積累的過程埋下一個伏筆，
        因為你存不到錢，沒有存款。
        同樣是10%的回報率，
        投資1000塊和投資100000，
        所收穫的回報是差很多很多的。
        所以一定要先積累到第一桶金之後，
        才來想旅遊這些東西。
        因為呢你所看到的這些朋友都是家境不菲，
        又或者是金錢觀是有所不同的。
        那一心想要成為有錢人的你，
        一定要專注在自己想要的，看得遠一點。
        而不是因為別人有然後自己就想要，
        然後就馬上就衝動了。
        記得，我在上大學的時候，
        有一個女性朋友邀約我一起去出國做交換生，
        然後去旅行。
        那時候呢我就馬上問她，
        呃，這個交換生是學校支付的嗎？
        還是我要自己掏腰包呢？
        那如果是自己掏腰包的話，費用大概是需要準備多少？
        她大概就跟我說了一下，應該是10000馬幣吧，
        那如果加上旅遊的話應該是15000這樣子的。
        那時候我馬上就割愛拒絕了。
        但她卻說，為什麼你要煩惱這些東西呢，
        大學生活，你就應該盡情享受嘛，
        去體驗各種各樣不一樣的東西。
        那是我還愣了一下，有點自卑的就說道：
        對不起啊，我需要考慮這些現實層面上的東西。
        如果你有遇到類似情況的話，
        其實我們也不需要感到非常的自卑的，
        因為我們每個人的成長經歷的不同，
        所以也會衍生出不一樣的金錢觀。
        所以呢大家只是金錢觀上的不同而已，
        我們都是平等的。
        那話說回來啊，就像是剛出社會工作的學生也是一樣，
        這些旅遊啊，看世界，體驗生活的，
        我們這些普通人就先忍一忍吧，延遲享樂一下。
        要變有錢的話，現階段我們要做的
        就是積累自己的第一桶金，
        這樣才能夠更加快的享受到復利效應所帶來的效果。
        關於「第一桶金」的概念大家也可以觀看我那只
        第一桶金的影片哦。
        同樣的，在剛出社會工作，
        結婚擺酒席，生孩子的，
        我們都要好好的去考量和規劃一下，
        因為孩子一生下去，
        同樣也會大幅度影響我們變有錢的速度的。
        所以在這個一個階段，我們的首要任務就是延遲享樂，
        學會最小化讓財富貶值的享受。
        很多享受型的活動都是一去不返的。
        比如，Netflix，
        旅行，做spa，各種各樣的體驗。
        同時間我們在這一個階段也要不斷的去尋找
        賺錢的機會，
        比如打工兼職，副業，跑腿，
        什麼都做一做才可以讓自己找到一個
        讓你財富快速增長的機會，
        累計到自己一筆可觀的存款。
        那時候，我就做了各種兼職的工作，
        比如保險，新加坡做清潔工，
        各種網絡點廣告，影片剪輯，
        在學校賣點東西，租車等等的。
        在一次的機緣巧合之下呢，
        我找到了一個有關於新車的市場調查工作。
        這一份工作的工資對於當時候在讀大學的我來說呢，
        是非常的高的。
        去尋找一個新車的車主，
        然後厚臉皮上門去問卷調查，
        調查到一輛車就可以馬上獲得RM100的收入了。
        這一個工作雖然短短的3-4月，
        但每個月呢我都可以從這份工作
        賺取5000塊馬幣左右的工資，
        就這樣抵住誘惑的我，開始存到了一些錢。
        那當我們有了一點小錢和存款，也不算是富足的情況下呢，
        這時候，我們就來到足階段。
        那現階段，我們就可以把我們的資金
        分成幾個部分來用的。
        我的方式分別就是投資自己，投資事業，
        投資金錢，以及緊急儲備金。
        有了這一些存款就要把這些錢活用起來。
        首先投資自己，
        比如教育：
        投資在自己的認知上面。
        比如閱讀、思考方式、處理問題；
        再比如還有我們的技能：
        投資在自己對於某種領域的操作能力
        像是文案、編程、銷售、行銷、
        經營社交媒體等等的。
        以上對於我們自己的投資呢，
        都是提升我們未來賺錢潛力的投資項目。
        這些回報率呢肯定是超過100%的。
        第二，投資事業
        把一部分的錢，拿來投資自己想要開啓的事業上面。
        在那個時候呢，我就特別喜歡網絡賺錢這個概念。
        所以經常就會買一些書和課程來學習，
        投資在自己的技能上面，
        然後也會到處購買各種各樣的軟件來去嘗試，
        也給自己買了一部比較好的電腦來提升自己的工作效率。
        結果很幸運的，因為喜歡做，所以就會非常用心的做，
        一不小心就做出了好葉頻道，
        也開始成立了一個有關於個人成長的線上教育品牌，
        成長吧。
        用知識點燃生活，幫助更多人培養人生必備軟實力。
        所以千萬不要讓自己後悔，
        有想法有熱忱的話，就要敢敢去做，
        因為自己喜歡的東西，往往會比別人做得更加的好，
        所以也會給你帶來更高收入的機會。
        根據反脆弱的理論，
        只要願意在自己覺得有未來發展前景的領域多嘗試的話，
        那成為八二法則裡面的20%的可能性是非常的高的。
        所以千萬不要害怕嘗試。
        第三，投資金錢
        當然，投資事業也是有風險的，
        而且很多情況下呢，創業也不需要你那麼多的錢。
        因為錢並不是保證創業成功的關鍵。
        所以呢還有多出來的錢呢，我們就可以拿去投資吧，
        給你的錢一份工作，替你創造更多的收入。
        因為如果你存在銀行，或者是放定存的話，
        利息就只有1-2%而已。
        通貨膨脹是5%，
        每年呢你都會虧個3%。
        在那一個時候我就選擇了股票，
        因為我非常喜歡科技和資訊。
        所以經常就會閱讀各種各樣關於
        科技的發展還有商業的資訊。
        因為投資股票就是投資公司嘛，
        所以很自然的，看了各種各樣的資訊，學習進行判斷。
        然後就順便就投資一下。
        所以成績還算適不錯的，
        每年平均下來都有一個20%以上的回報率的。
        那要是你想要投資，但是又沒有經驗的話，
        那麼投資ETF基金就是一個不錯的選擇。
        關於這一點我會在致富的階段的時候呢，
        跟大家詳細的解釋的。
        第四個部分，緊急籌備金
        存款有了，我們也要學會未雨綢繆啊，
        為最壞的打算作做準備，所以生活只會越來越好。
        你為最壞的打算做準備，
        等到壞的情況出現的時侯呢你就會過得非常的好。
        就像是07、08年的金融海嘯一樣，
        很多人都恨不得手頭上有很多的資金，
        在市場如此壞的情況之下呢進場購入資產，
        但是相信大部份的人都沒有這麼做，
        而且還可能一直不斷的賣掉手頭上的資產，
        比如房地產或是股票，
        換來現金解決眼前的金融危機。
        這一次2020的疫情也是一樣，
        如果你擁有良好的投資能力，以及備用基金的話，
        那這時反而是可以讓你的財富擴張倍增的機會。
        像這次我就趁機貸款買了兩套房，
        每一次的大小金融事件都會造成財富重新的分配，
        如果我們沒有為最壞的情況做準備，
        總會將自己的財富分配給了別人。
        那當我們開始有了穩定的財富增長基礎，
        有了各式的收入，有緊急儲備金，
        也開始有了一些投資的被動收入的這時候呢，
        現在我們就來到了準備致富的階段。
        在這一個階段呢，首先我們需要設置一個
        財富自由的目標。
        簡單來說，當你每個月的被動收入，
        大過於我們家庭支出的時候呢，
        基本上我們就已經達到了財富自由的階段了。
        所以你現在要計算的就是，
        你的家庭開支是多少？
        那不管你有沒有買房或者是結婚生孩子都好，
        都可以大概的預計一下，
        你想要住怎麼樣的房子，
        開怎麼樣的車子，然後過怎麼樣的生活？
        這一切都需要多少的錢？
        那比方說，你一年的家庭開支是10000美元的話，
        所以你目前的財務自由目標，
        就要確保自己每年都至少有
        超過10000美金的被動收入。
        知道了這個數字之後呢，
        接下來我們就可以來計算一下，
        怎樣可以透過投資的方式來達到這一個目標。
        如果是透過投資股票或是ETF，
        每年平均回報是10%的話，
        那我們要投入多少的錢，
        才能每年獲得10000美金的被動收入呢？
        很簡單，
        就是把10000除以10%，
        這樣就會獲得100000美金的這一個數目了，
        那這一個100000美金就是你的目標了，
        只要你能夠纍積到這個數目，把它成為你的生錢工具，
        每年給你帶來10%的回報，
        就會讓你每年收穫10000美元的被動收入了。
        要積累到100000美金的投資金額其實一點也不難。
        靠的就是複利+主動投入的方式。
        假設你現在有10000美金的啟動資金的話，
        如果是10%複利，
        單靠本金要滾到100000美金的話，
        只少要一個25年。
        所以我們在前期的時候，
        肯定是要不斷的添加投資金額的。
        如果每年都投入收入的30%，
        比如5000塊的話，
        那麽雪球就會越`
    }
};

export default becomingRich;