const bookReview = {
    videoId: 'Wei1rfAyTw0',
    transcript: {
        pinyin: "dàjiā hǎo wǒ shì xiǎo wéi jīntiān dehuà huì tuījiàn 5 běn shū kěyǐ zhèyàng shuō zhè 5 běn shū gǎibiànle wǒ de rénshēng shènzhì shì gǎibiànle wǒ de yīxiē sīwéi fāngshì jīngcháng huì xiǎng rúguǒ wǒ zǎo yīdiǎn néng kàn dào zhè jǐ běn shū jiù hǎole wǒ huì àn zhè 5 běn shū de kě dú xìng pái yīgè xù jiùshì yuè wǎng hòu dehuà kěnéng yuè shāowéi huìsè yīdiǎn píngshí yǒu yuèdú xíguàn dehuà yě bù huì shuō dú bù xiàqù hǎole wǒmen xiànzài jiù lái jièshào wǒ tuījiàn de dì 1 běn dehuà zhè shì táiwān zuòjiā hóuwényǒng de “méiyǒu shén de suǒzài —— sīfáng yuèdú jīnpíngméi” zhè běn shū jiù xiàng dàjiā kàn dào de sīfáng yuèdú jīnpíngméi tā kěyǐ shuō shì hóuwényǒng duì jīnpíngméi de yīgè dúhòugǎn xiěchéngle zhèyàng yī běn shū dàjiā kěyǐ kàn qíshí tǐng hòu de dàn nǐ bié kàn tā hòu yuèdú tǐyàn fēicháng hǎo kěyǐ hěn liúchàng de bǎ tā kàn wán wǒ běnshēn méiyǒu dúguò “jīnpíngméi” Kindle li yǒu “jīnpíngméi” dànshì chū yú zhǒngzhǒng yuányīn wǒ yīzhí méiyǒu dú wán kěnéng shì wǒ běnshēn gǔwén dǐzi bù tài hǎo dú qǐlái hěn lèi zài jiā shàng yǒudiǎn fúzào xīn dìng bù xiàlái dàn wánquán bù yǐngxiǎng nǐ kàn zhè běn shū de gǎnjué jiù xiàng yǒuyīgè fēicháng bó wén guǎng shí dàn yòu fēicháng píngyìjìnrén bù yā rén de yīgè zhǎngbèi zài dàilǐng nǐ dú yī běn suǒwèi de `qiāngǔ yín shū' tā huì zhǐchū jīnpíngméi zhè běn shū dāngzhōng fēicháng duō yǒu guānyú rénxìng de yǒu guānyú bēitiānmǐnrén de yīxiē dìfāng hái yǒuyīxiē zìjǐ dú dehuà kěnéng bù huì zhùyì dào de yīxiē xiǎo xìjié zhè běn shū gěi wǒ zuìdà de gǎnjué jiùshì yǒu shíhòu nǐ dú yīxiē rìběn de huòzhě shuō xīfāng de xiǎoshuō nǐ nánmiǎn huì juédé yǒudiǎn gémó wǒ yě bù zhīdào shì fānyì de wèntí háishì wǒmen de shèhuì xíngtài běnshēn yǒu chāodà chāodà de chāyì dànshì nǐ gēnzhe hóuwényǒng dú yībiàn “jīnpíngméi” dehuà nǐ jiù huì fāxiàn suīrán jīnpíngméi miáoxiě de shì 400 nián qián de shìqíng kěshì gēn wǒmen dāngjīn shèhuì méiyǒu chābié kěyǐ shuō shì tàiyáng dǐxia wú xīn shìle ràng wǒ juédé yǒu yīdiǎndiǎn de bēi'āi nǐ shuō wǒmen zhōnghuá mínzú yǒu méiyǒu jìnbù dāngrán shì yǒu jìnbù kěyǐ shuō shì fāntiānfùdì de dàn nǐ shuō zhēn de yǒu jìnbù ba hěnduō dōngxī háishì zàiyuán dì tàbù suǒyǐ píngmùqián de gèwèi niánqīng rén wèilái jiù kào nǐmenle dì 2 běn dehuà wǒ tóngyàng shì yǒu zhǐ zhì shū The Women's Room wǒ dú de shì yīngwén bǎn de dànshì zhè běn shū de zhōngwén fānyì bǎn fēicháng hǎo zhōngwén yìběn míngzì jiào “xǐng lái de nǚxìng” zhè běn shū tóngyàng shì wǒ kěyǐ shuō shì 30 suì zhīhòu dú dào duì wǒ yǐngxiǎng fēicháng dà de yī běn shū wǒ zài yuèdúguòchéng zhōng kūle hǎoduō cì yīn wéi qízhōng lǐmiàn nǚxìng de zāoyù nǐ shízài shì tài néng gǎntóngshēnshòule tā suīrán miáoxiě de shì shàng shìjì wǔliùshí niándài dì měiguó dànshì nǐ zài yuèdúguòchéng zhōng nǐ huì fǎnfù de liánxiǎng dào nǐ de péngyǒu nǐ de tóngbèi huòzhě shuō nǐ de yīxiē nǚxìng cháng bèi nǐ hái huì liánxiǎng dào nǐ dú guò de xīnwén nǐ dú guò xīnwén de xiàmiàn de yīxiē pínglùn tā huì gàosù nǐ jiùshì nǚxìng yīshēng dāngzhōng shuō bu qīngdào bùmíng de yīxiē tòngkǔ zài fǎnfù de fǎ shēng wǒmen gēn shàng shìjì wǔliùshí niándài de měiguó nǚxìng de zāoyù zhēn de méiyǒu rènhé de chābié kěyǐ shuō nǚxìng de xìngfú kěnéng shì gè yǒu gè de xìngfú dànshì nǚxìng de bùxìng yīyàng de gǔwǎngjīnlái méiyǒu chāyì yě jiùshì shuō wǒ juédé quán shìjiè de nǚxìng shìjiè shàng rénkǒu de 1/2 dōu shì mìngyùn gòngtóngtǐ wǒ duì dāngzhōng de yīgè duànluò fēicháng de yǒu gǎnchù jiùshì zhǔréngōng mǐ lā tā zài yīgè péngyǒu fēicháng luònàn de shíhòu tā xiǎng jǐyǔ tā de yīgè hǎo péngyǒu yīgè jiējì yīnwèi tā fēicháng tóngqíng tā péngyǒu de zāoyù dàn tā qù gēn tā de zhàngfū nuò mǔ jiǎng de zhège tā de zhàngfū shì duànrán jùjué de ránhòu wǒ dú dào zhège de shíhòu wǒ gēn nǚ zhǔréngōng yīyàng wǒ méiyǒu bànfǎ píngjìng wǒ zhēn de shì qì dào fādǒu tā qízhōng jiǎngle jiùshì nǚ zhǔréngōng de yīxiē sīkǎo tā shuō wǒ miàn duì de shì wǒ de zhàngfū ma? Wǒ rúguǒ xiànzài jiùsuàn wǒ qù qiān yī zhāng zhīpiào gěi wǒ de péngyǒu tā yòu néng ná wǒ zěnme yàng ne? Wèishéme wǒ de zhàngfū huì bù tóngyì tā yīkào shì shénme tā huì fāxiàn tāmen liǎng gèrén de lìliàng de duìbǐ shì jiànlì zài yīgè shèhuì mòrèn de qìyuē shàng kěyǐ shuō shì gōngxùliángsú jiùshì nǐ dǐkàng de bìng bùshì nǐ de zhàngfū ér shì zài zhěnggè shèhuì zài nàgè shíhòu jiù zhǔréngōng mǐ lā túrán yìshí dào tā de gèrén de lìliàng tā suǒwèi dì měiguó mèng shì duōme de miǎoxiǎo duōme de kěxiào suǒyǐ ràng tóng wèi nǚxìng de wǒ tèbié nénggòu gǎntóngshēnshòu wǒ zhēn de tuījiàn suǒyǒu de nǚ háizi kěyǐ dú yīxià zhè běn shū bùguāng shì nǚ háizi rúguǒ duì nǐ de nǚ péngyǒu duì nǐ de qīzi duì nǐ de māmā huò duì nǐ de yīxiē nǚxìng cháng bèi nǐ guānxīn tāmen dehuà nán háizi yě kěyǐ dú yīxià zhè běn shū wǒ zài shàng yī qí de jiémù dāngzhōng jiùshì jiǎng dào wǒ zhàngfū de 10 gè yōudiǎn wǒ fǎnsīle yīxià wǒ lù zhè qī jiémù wǒ jiù juédé zuòwéi nǚxìng běnshēn dehuà wǒ juédé wǒ mù qián de shēnghuó zhuàngtài wǒ shì mǎnyì de wǒguò dé yěshì bǐjiào xìngfú de dàn wǒ xìngfú de zhège dōngxī yǎnglài de shì shénme wǒ yǎnglài de shì wǒ de gèrén sùzhì ma wǒ juédé bùshì yīnwèi wǒ de gèrén sùzhì wǒ zìjǐ xīnlǐ qīngchǔ wǒ shì yīgè fēicháng pǔtōng de nǚxìng wǒ yǎnglài de shì shèhuì zhège tǐxì gěi wǒ de bǎohù ma? Tóngyàng bùshì wǒ yǎnglài de shì yīgè rén wǒ zhàngfū zhège rén běnshēn wǒ yǎnglài de shì tā bǐjiào gāo de yīgè dàodé biāozhǔn bǐjiào qiáng de yīgè zérèngǎn ràng wǒguò dé bǐjiào hǎo bǐjiào xìngfú nǐguò dé hǎobù hǎo xūyào yǎnglài yīgè rén dehuà gǔwǎngjīnlái xiělínlín de lìzi fēicháng duō yīlài yīgè rén shì kàobùzhù de rúguǒ nǚxìng xiǎngguò dé hǎo dehuà nǐ xūyào yīlài de shì zhěnggè shèhuì yě jiùshì zhège tǐxì lái bāng nǐ dì 3 běn dehuà wǒ tuījiàn shì tuījiànguò hǎoduō cì de zì qū xíng chéngzhǎng The Self-driven Child ránhòu zhè běn shū dehuà wǒ zìjǐ mǎi de jiùshì zhōng yìběn ránhòu wǒ juédé fānyì de yě hěn hǎo tuījiàn gěi dàjiā zhè běn shū jiù diānfùle hěnduō wǒ de xiǎngfǎ wǒmen dàjiā tí dào zìlǜ dehuà dūhuì shuō `yuè zìlǜ, yuè zìyóu' zhè shì duì de dàn zhè běn shū gěi nǐ lìngwài yīgè jiǎodù qù kàn tā gàosù nǐ jiùshì nǐ xiǎng péiyǎng yīgè zìlǜ de háizi huòzhě shuō nǐ xiǎng péiyǎng yīgè zìlǜ de zìjǐ qíshí shì `yuè zìyóu, yuè zìlǜ' gěi dàjiā jǔ gè lìzi bù zhīdào dàjiā yǒu méiyǒu kàn dào yīgè xīnwén jiùshì shuō huáyì de bālěiwǔ de yīgè wǔ zhě tā hǎoxiàng zhǐyǒu shíwǔliù suì ránhòu tā měitiān shíjiān ānpái de fēicháng zìlǜ hěn zǎo jiù qǐchuáng zǎozǎo de wēnxí gōngkè ránhòu měitiān yào huā dàgài 8~9 gè xiǎoshí (dìngzhèng: Shì 5 gè xiǎoshí) qù liànxí tā de bālěi ránhòu xiàmiàn de pínglùn quán shì `wa tā zhēn de hǎo zìlǜ' dàn wǒ xiǎng wèn dàjiā yǒu méiyǒu xiǎngguò tā zhège gāodù zìlǜ shì wèishéme yīnwèi tā rè'ài bālěi zhè yě jiùshì zuòzhě xiǎng tíchū de rúguǒ yīgè háizi bèi fāngmiàn de yǐjīng dōu guǎnshù zhùle biérén gàosù nǐ nǐ gāi zuò shénme nǐ gāi zuò shénme zhèyàng dehuà shì méiyǒu bànfǎ zìlǜ de nǐ huì gěi háizi yī zhǒng shénme gǎnjué tā de gǎnxiǎng bùzuò shù tā méiyǒu bànfǎ kòngzhì tā zìjǐ tā shì yīgè kōngxīn rén zuòzhě shì liǎng gè yīgè shì línchuáng xīnlǐ xué jiā yīgè shì nǎo kēxuéjiā tāmen bùdàn yǒu dàliàng xiángshí de ànlì hái yǒu fēicháng fēngfù de nǎo kēxué zhīshì tāmen de shuōfǎ shì kēxué zhàn zài tāmen zhè yībiān de píngmù qián yǒu xiǎohái de huò méiyǒu xiǎohái dōu kěyǐ dú yīxià zhè běn shū nǐ jiù huì míngbái wèishéme nǎo kēxué shuō `yuè zìyóu, yuè zìlǜ' qíshí wǒ zuòguò yī qí guānyú zhè běn shū de jiémù jiù jiào `shuāng píng shíyàn' fēngmiàn shàng liǎng gè píngzi dì nà yī qí dàjiā rúguǒ yǒu jīhuì yòu bùxiǎng kàn zhè běn shū dehuà kěyǐ qù kàn yīxià wǒ zuò dì nà qī jiémù dì 4 běn wǒ yào tuījiàn de yěshì wǒ fǎnfù tí dào de The Defining Decade zhè běn shū dehuà wǒ shì tuījiàn dàjiā qù dú yīngwén bǎn yīnwèi zhè běn shū zhōngwén bǎn hěnduō rén dōu shuō fānyì de bù zě me yàng qícì dehuà zhè běn shū yīngwén bǎn bìng bù nán yīnwèi wǒ shǔyú yīngwén shuǐpíng yě jiù yībān bān de wǒ yě néng bǎ tā dú wán zhǔyàoshi gēn nǐ jièshàole wèishéme 20 suì duì yīgè rén lái shuō shì zhì guān zhòngyào de wǒmen dōu shuō sānshí érlì hǎoxiàng 30 suì zhīhòu cái huì màn man de dúlì qíshí bùshì de jiùshì 20 suì bìng bùshì xīfāng shuō dì nà zhǒng pre-adult yě bùshì wǒmen dōngfāng rén shuō de zuǐ shàng méi máo bànshì bù láo ér shì duì nǐ rénshēng zhì guān zhòngyào de nà shí nián tā yěshì cóng work gōngzuò love relationship àiqíng bāokuò gège fāngmiàn gěi nǐ pōuxīle wèishéme 20 suì duì nǐ zhème zhòngyào bìngqiě yīnwèi zuòzhě Meg Jay yěshì yīgè línchuáng xīnlǐ xué zhuānjiā PHD ránhòu tā yěyǒu dàliàng de shílì lái gàosù nǐ zàidú de shíhòu bìng bù huì gǎnjué lèi zhǐyǒu yī diǎn wǒ juédé zuòzhě yǒu shíhòu huì ràng rén dú qǐlái yǒudiǎn bú shūfú dì dìfāng jiùshì tā fǒurènle yīxiē xiǎo zhòng de shēnghuó fāngshì jiù zài tā zhè běn shū lǐmiàn tā juédé suǒyǒu de rén dōu yīnggāi zūnxún yīgè tàolù jiùshì dúshū ránhòu jìnrù shèhuì jiéhūn shēngzǐ wěndìng de shēnghuó tā shì nà zhǒng miáoshù de yīgè zhǔliú de shēnghuó fāngshì tā hǎoxiàng méiyǒu guānzhù dào yīxiē xiǎo zhòng qúntǐ rúguǒ nǐ shì yīgè cóngxiǎo líjīngpàndào nǎo hòu yǒu fǎngǔ de nǐ dú zhè běn shū de shíhòu jiù yǒu zhǒng hěn bú shūfú de gǎnjué jiùshì tā yǒudiǎn shuōjiào dànshì rúguǒ nǐ shì yīgè bǐjiào wěndìng de huòzhě shuō bǐjiào zhǔliú dì nà lèi rén dehuà nǐ dú de shíhòu jiù fǎnfù yǒu yī zhǒng gǎnjué jiǎng dé hǎo yǒu dàolǐ duì jiùshì zhèyàng xīwàng zìjǐguò dé bǐjiào zhǔliú de xīwàng bùyào cuōtuó zìjǐ niánhuá de wǒ zhēn de kěyǐ tuījiàn nǐ kěyǐ qù dú yīxià rúguǒ méiyǒu shíjiān dehuà kěyǐ qù kàn Meg Jay Ted yǎnjiǎng shàng de yīgè yǎnjiǎng yěshì guānyú zhè běn shū de kěyǐ shuō shì zhè běn shū de jīnghuá nǐ qù sōu Meg Jay yīnggāi jiù kěyǐ sōu dào dì 5 běn qíshí yěshì wǒ zuì tuījiàn de yī běn dànshì zhè běn shū yuèdú tǐyàn zhēn de hěn chà suǒyǐ wǒ bǎ tā fàng dào zuìhòu jiǎrú yǒu xìngqù de péngyǒu qù kàn yīxià jiùshì shūběn huá de “rénshēng de zhìhuì” wǒ duì zhè běn shū xǐhuān dào shénme chéngdù jiùshì shuō wǒ xǐhuān dào wǒ xǐhuān dào wǒ shěbudé duō dú tā wǒ hěn pà bǎ tā de shū dú wánliǎo jiù méiyǒu dōngxī kěyǐ dúle ér zhè běn shū dehuà tā huìsè jiù huìsè zàiyú tā lǐmiàn méiyǒu rènhé de lìzi jiùshì wǒmen shuō bǎi shìshí jiǎng dàolǐ duì ba tā lǐmiàn méiyǒu bǎi shìshí chúncuì shì jiǎng dàolǐ suǒyǐ nǐ měi kàn yīduàn dōu juédé nǐ xūyào hěnduō shíjiān qù xiāohuà tā dànshì zhè běn shū zhēn de shì zuòzhě sīwéi de jīnghuá tā háo wú bǎoliú de bǎ tā de rénshēng de yīxiē jīngyàn bǎ tā sīkǎo de yīxiē jiéjīng xiě xiàlái fēnxiǎng gěi wǒmen wǒ měi cì dú wán shū běn huá de yīxiē shū ránhòu zài qù kàn yīxiē shūdiàn lǐ línlángmǎnmù dì xiàng yīxiē chénggōng xué jītāng wén wǒ dūhuì yǒu yī zhǒng tíxiàojiēfēi de gǎnjué wǒ jiù juédé zhège shìjiè gēn shū běn huá shuō de yīyàng tā zhēn de kěyǐ shuō shì yīgè xiānzhī tā yùliào de shìjiè jiùshì zhèyàng ránhòu shìjiè yě ànzhào tā yùliào de yīyàng zài zǒu jiǎrú shì méiyǒu shíjiān huòzhě shì bù tài xǐhuān dú yīxiē wùxū fāngmiàn de zhéxué fāngmiàn de shūjí dehuà wǒ shì bù tài tuījiàn de qíshí méiyǒu guānxì hěnduō shíhòu wǒmen kànshū bìng bù yīdìng yào qù yìng kěn yǒu shíhòu jiùshì kàn yuánfèn yǐshàng 5 běn jiùshì wǒ jīntiān tuījiàn de suǒyǒu de shūle háishì yīyàng rúguǒ dàjiā yǒu shé me xiǎng gēn wǒ tǎolùn dehuà dōu huānyíng gěi wǒ duō liúyán huòzhě zhè běn shū nǐ yě kànguò yǒu shé me xīndé xiǎng gēn wǒ fēnxiǎng dehuà wǒ yě fēicháng de huānyíng xǐhuān zhèxiē jiémù dì huà bùyào wàngjì gěi wǒ diǎn yīgè zàn yào shi néng shùnshǒu guānzhù dehuà jiù gèng hǎole zuìhòu háishì xièxiè dàjiā de shíjiān xièxiè",
        chinese: `大家好
        我是小唯
        今天的話會推薦5本書
        可以這樣說
        這5本書改變了我的人生
        甚至是改變了我的一些思維方式
        經常會想
        如果我早一點能看到這幾本書就好了
        我會按這5本書的可讀性
        排一個序
        就是越往後的話
        可能越稍微晦澀一點
        平時有閱讀習慣的話
        也不會說讀不下去
        好了
        我們現在就來介紹
        我推薦的第1本的話
        這是台灣作家侯文詠的
        《沒有神的所在 —— 私房閱讀金瓶梅》
        這本書就像大家看到的
        私房閱讀金瓶梅
        它可以說是侯文詠
        對金瓶梅的一個讀後感
        寫成了這樣一本書
        大家可以看其實挺厚的
        但你別看它厚 閱讀體驗非常好
        可以很流暢的把它看完
        我本身沒有讀過《金瓶梅》
        Kindle裡有《金瓶梅》
        但是出於種種原因
        我一直沒有讀完
        可能是我本身古文底子不太好
        讀起來很累
        再加上有點浮躁
        心定不下來
        但完全不影響
        你看這本書的感覺
        就像有一個非常博聞廣實
        但又非常平易近人
        不壓人的一個長輩
        在帶領你讀一本所謂的「千古淫書」
        他會指出
        金瓶梅這本書當中
        非常多有關於人性的
        有關於悲天憫人的一些地方
        還有一些自己讀的話
        可能不會注意到的一些小細節
        這本書給我最大的感覺就是
        有時候你讀一些
        日本的
        或者說西方的小說
        你難免會覺得有點隔膜
        我也不知道是翻譯的問題
        還是我們的社會形態本身
        有超大超大的差異
        但是你跟著侯文詠讀一遍
        《金瓶梅》的話
        你就會發現
        雖然金瓶梅描寫的是400年前的事情
        可是跟我們當今社會沒有差別
        可以說是太陽底下無新事了
        讓我覺得有一點點的悲哀
        你說我們中華民族有沒有進步
        當然是有進步
        可以說是翻天覆地的
        但你說真的有進步吧
        很多東西還是在原地踏步
        所以屏幕前的各位年輕人
        未來就靠你們了
        第2本的話
        我同樣是有紙質書
        The Women's Room
        我讀的是英文版的
        但是這本書的中文翻譯版非常好
        中文譯本名字叫《醒來的女性》
        這本書同樣是
        我可以說是30歲之後
        讀到
        對我影響非常大的一本書
        我在閱讀過程中哭了好多次
        因為其中里面女性的遭遇
        你實在是太能感同身受了
        它雖然描寫的是
        上世紀五六十年代的美國
        但是你在閱讀過程中
        你會反复的聯想到
        你的朋友 你的同輩
        或者說你的一些女性長輩
        你還會聯想到
        你讀過的新聞
        你讀過新聞的下面的一些評論
        他會告訴你
        就是女性一生當中
        說不清道不明的一些痛苦
        在反复的發生
        我們跟上世紀五六十年代的
        美國女性的遭遇
        真的沒有任何的差別
        可以說女性的幸福
        可能是各有各的幸福
        但是女性的不幸 一樣的
        古往今來沒有差異
        也就是說
        我覺得全世界的女性
        世界上人口的1/2
        都是命運共同體
        我對當中的一個段落非常的有感觸
        就是主人公米拉
        她在一個朋友非常落難的時候
        她想給予她的一個好朋友
        一個接濟
        因為她非常同情她朋友的遭遇
        但她去跟她的丈夫諾姆講的這個
        她的丈夫是斷然拒絕的
        然後我讀到這個的時候
        我跟女主人公一樣
        我沒有辦法平靜
        我真的是氣到發抖
        它其中講了
        就是女主人公的一些思考
        她說我面對的是我的丈夫嗎？
        我如果現在就算
        我去簽一張支票給我的朋友
        他又能拿我怎麼樣呢？
        為什麼我的丈夫會不同意
        他依靠是什麼
        她會發現
        他們兩個人的力量的對比
        是建立在一個社會默認的契約上
        可以說是公序良俗
        就是你抵抗的
        並不是你的丈夫
        而是在整個社會
        在那個時候
        就主人公米拉
        突然意識到
        她的個人的力量
        她所謂的美國夢
        是多麼的渺小
        多麼的可笑
        所以讓同為女性的我
        特別能夠感同身受
        我真的推薦所有的女孩子
        可以讀一下
        這本書
        不光是女孩子
        如果對你的女朋友
        對你的妻子
        對你的媽媽
        或對你的一些女性長輩
        你關心他們的話
        男孩子也可以讀一下這本書
        我在上一期的節目當中
        就是講到我丈夫的10個優點
        我反思了一下
        我錄這期節目
        我就覺得
        作為女性本身的話
        我覺得我目前的生活狀態
        我是滿意的
        我過得也是比較幸福的
        但我幸福的這個東西
        仰賴的是什麼
        我仰賴的是我的個人素質嗎
        我覺得不是
        因為我的個人素質
        我自己心裡清楚
        我是一個非常普通的女性
        我仰賴的是社會這個體系
        給我的保護嗎？
        同樣不是
        我仰賴的是一個人
        我丈夫這個人本身
        我仰賴的是他比較高的一個道德標準
        比較強的一個責任感
        讓我過得比較好
        比較幸福
        你過得好不好
        需要仰賴一個人的話
        古往今來血淋淋的例子非常多
        依賴一個人是靠不住的
        如果女性想過得好的話
        你需要依賴的是整個社會
        也就是這個體係來幫你
        第3本的話
        我推薦是推薦過好多次的
        自驅型成長 The Self-driven Child
        然後這本書的話
        我自己買的就是中譯本
        然後我覺得翻譯的也很好
        推薦給大家
        這本書就顛覆了很多我的想法
        我們大家提到自律的話
        都會說「越自律，越自由」
        這是對的
        但這本書給你另外一個角度去看
        它告訴你
        就是你想培養一個自律的孩子
        或者說你想培養一個自律的自己
        其實是「越自由，越自律」
        給大家舉個例子
        不知道大家有沒有看到一個新聞
        就是說華裔的芭蕾舞的一個舞者
        她好像只有十五六歲
        然後她每天時間安排的非常自律
        很早就起床
        早早的溫習功課
        然後每天要花大概8~9個小時（訂正：是5個小時）
        去練習她的芭蕾
        然後下面的評論
        全是「哇她真的好自律」
        但我想問大家
        有沒有想過
        她這個高度自律是為什麼
        因為她熱愛芭蕾
        這也就是作者想提出的
        如果一個孩子被方面的已經都
        管束住了
        別人告訴你你該做什麼
        你該做什麼
        這樣的話
        是沒有辦法自律的
        你會給孩子一種什麼感覺
        他的感想不作數
        他沒有辦法控制他自己
        他是一個空心人
        作者是兩個 一個是臨床心理學家
        一個是腦科學家
        他們不但有大量詳實的案例
        還有非常豐富的腦科學知識
        他們的說法是
        科學站在他們這一邊的
        屏幕前
        有小孩的
        或沒有小孩
        都可以讀一下
        這本書
        你就會明白
        為什麼腦科學說「越自由，越自律」
        其實我做過一期
        關於這本書的節目
        就叫「雙瓶實驗」
        封面上兩個瓶子的那一期
        大家如果有機會
        又不想看這本書的話
        可以去看一下
        我做的那期節目
        第4本我要推薦的
        也是我反复提到的
        The Defining Decade 這本書的話
        我是推薦大家去讀英文版
        因為這本書中文版
        很多人都說翻譯的不怎麼樣
        其次的話
        這本書英文版並不難
        因為我屬於英文水平
        也就一般般的
        我也能把它讀完
        主要是跟你介紹了
        為什麼20歲
        對一個人來說是至關重要的
        我們都說三十而立
        好像30歲之後
        才會慢慢地獨立
        其實不是的
        就是20歲
        並不是西方說的那種pre-adult
        也不是我們東方人說的
        嘴上沒毛辦事不牢
        而是對你人生至關重要的
        那十年
        她也是從 work 工作
        love relationship 愛情
        包括各個方面給你剖析了
        為什麼20歲對你這麼重要
        並且因為作者 Meg Jay
        也是一個臨床心理學專家
        PHD 然後她也有大量的實例
        來告訴你
        在讀的時候
        並不會感覺累
        只有一點
        我覺得作者有時候會讓人
        讀起來
        有點不舒服的地方
        就是她否認了一些小眾的
        生活方式
        就在她這本書裡面
        她覺得所有的人
        都應該遵循一個套路
        就是讀書
        然後進入社會 結婚生子
        穩定的生活
        她是那種描述的一個主流的
        生活方式
        她好像沒有關注到一些小眾群體
        如果你是一個從小離經叛道
        腦後有反骨的
        你讀這本書的時候
        就有種很不舒服的感覺
        就是她有點說教
        但是如果你是一個比較穩定的
        或者說比較主流的那類人的話
        你讀的時候就反復有一種感覺
        講得好有道理
        對就是這樣 希望自己過得比較主流的
        希望不要蹉跎自己年華的
        我真的可以推薦
        你可以去讀一下
        如果沒有時間的話
        可以去看Meg Jay
        Ted演講上的一個
        演講
        也是關於這本書的
        可以說是這本書的精華
        你去搜Meg Jay
        應該就可以搜到
        第5本
        其實也是我最推薦的一本
        但是這本書閱讀體驗真的很差
        所以我把它放到最後
        假如有興趣的朋友
        去看一下
        就是叔本華的《人生的智慧》
        我對這本書喜歡到什麼程度
        就是說我喜歡到
        我喜歡到我捨不得多讀它
        我很怕把它的書讀完了
        就沒有東西可以讀了
        而這本書的話
        它晦澀就晦澀
        在於它裡面沒有任何的例子
        就是我們說擺事實 講道理
        對吧
        它裡面沒有擺事實
        純粹是講道理
        所以你每看一段
        都覺得
        你需要很多時間去消化它
        但是這本書
        真的是作者思維的精華
        他毫無保留的
        把他的人生的一些經驗
        把他思考的一些結晶寫下來
        分享給我們
        我每次讀完書本華的一些書
        然後再去看一些書店裡琳瑯滿目的
        像一些成功學
        雞湯文
        我都會有一種啼笑皆非的感覺
        我就覺得
        這個世界跟叔本華說的一樣
        他真的可以說是一個先知
        他預料的世界就是這樣
        然後世界也按照他預料的一樣在走
        假如是沒有時間
        或者是不太喜歡讀一些
        務虛方面的
        哲學方面的書籍的話
        我是不太推薦的
        其實沒有關係
        很多時候我們看書
        並不一定要去硬啃
        有時候就是看緣分
        以上5本
        就是我今天推薦的
        所有的書了
        還是一樣
        如果大家有什麼想跟我討論的話
        都歡迎給我多留言
        或者這本書你也看過
        有什麼心得
        想跟我分享的話
        我也非常的歡迎
        喜歡這些節目的話
        不要忘記給我點一個贊
        要是能順手關注的話
        就更好了
        最後還是謝謝大家的時間謝謝`
    }
};

export default bookReview;