const climateChange = {
    videoId: 'Nl_J8mMIIZU',
    transcript: {
        pinyin: "nǐ zhīdào ài dìqiú qíshí shì wèile àirénlèi zìjǐ yīdiǎn dōu bù guān dìqiú de shì ma hā luō dàjiā hǎo wǒ shì qìhòu māmā hé nǐ yīqǐ xuéxí huó zài wèilái xūyào de qìhòu zhīshì zhèlǐ shì yīgè jiǎng duì wǒmen shēnghuó yǐngxiǎng hěn dà dàn hěnduō shíhòu wǒmen què bù tài qīngchǔ yě bù tài míngliào gāi zěnme miàn duì de qìhòu biànqiān de gùshì de píndào lìngwài qìhòu māmā yěshìgè wùshí de qìhòu zhǔyì zhě yě jiùshì wǒ jiānxìn ài dìqiú yīdìng yào gēn zìshēn lìyì xiāng jiéhé cáinéng jī qǐ zuìdà de xíngdòng lì yě yào bāng diǎn jìn wǒmen zhèlǐ de nǐ pāi pāishǒu yīnwèi nǐ jīntiān huì diǎn jìn wǒmen zhèlǐ jiù biǎoshì nǐ yǐjīng bǐ zhège shèhuì shàng dà duō shǔ de rén dōu lái de guānxīn zìjǐ de shēnghuó huánjìng hé zìjǐ de wèiláile nǐ yǒu méiyǒu xiǎngguò dāng nǐ xuǎnzé yào dìngyuè shuí de shíhòu nǐ qíshí shì zài xuǎnzé nǐ wèilái de sīwéi fāngshì suǒyǐ huānyíng dìngyuè wǒmen ràng wǒmen yīqǐ mài xiàng wùshí ài dìqiú de hángliè ba jīntiān wǒmen yào lái shuō yīgè wǒmen xiǎo rénlèi hé dà dìqiú gǎnqíng yuè lái yuè bù hǎo de gùshì shǒuxiān xiān lái jiǎndān shuō yīxià dìqiú de gùshì dìqiú cóng dànshēng dào xiànzài yǐjīng 46 yì nián yībān rènwéi zhǐyào yǒu tàiyáng dìqiú jiù huì yīzhí cúnzài suǒyǐ dìqiú xiànzài yuē děngyú rénlèi de 46 suì zuǒyòu yě jiùshì gēn qìhòu māmā wǒ xiànzài chàbùduō dà shì gè zhōng nián dàmā láizhe rénlèi ne qíshí jiùshì shēnghuó zài dìqiú shàng de yīqún xìbāomen bùzhǐshì rénlèi suǒyǒu de shēngwù dōu suànshì bùtóng de xìbāo qún nàxiē gāoshān wǒmen kěyǐ bǐyù chéngrén shēntǐ lǐ de gǔtou héliú jiù xiàng xiěguǎn hǎiyáng jiù xiàng wǒmen shēntǐ lǐmiàn de xiěyè měi yīkuài dàlù dōu xiàng shì wǒmen shēntǐ lǐ de qìguān dànshì bù yīyàng de shì wǒmen rénlèi rúguǒ méiyǒu shēntǐ lǐ de qìguān rénlèi jiù huì sǐwáng dànshì dìqiú de yùnzhuǎn hé cúnzài shì kào tàiyáng shǎole gāngcái shuō de rènhé yīkuài suīrán zhànshí huì gǎibiàn dìqiú nèibù de zǔchéng dànshì duì dìqiú běnshēn ér yán méi chà dìqiú wánquánbù huì yīncǐ ér sǐwáng huò mièwáng yě jiùshì shuō rénlèi rúguǒ méiyǒu dìqiú jiù wándànle dànshì dìqiú méiyǒu wǒmen rénlèi wánquánbù huì zěnme yàng érqiě zhèxiē shìqíng dōu fāshēngguò guòqù dìqiú lìshǐ shàng jiù fāshēngguò wǔ cì de shēngwù dà mièjué duì, wǔ cì dāngshí dìqiú shàng yībàn yǐshàng de shēngwù dōu sǐ guāng guāngle dàn dìqiú háishì chíxù de zhuǎndòng zhìjīn zhìjīn rénlèi yěshì zài zhè wǔ cì dà mièjué zhīhòu cái dànshēng zài dìqiú shàng de zhūduō wùzhǒng zhī yī rénlèi chūxiànzài zhège shìjiè shàng zhǐyǒu 500 dào 700 wànnián yóuqí shì wǒmen xiànzài zhège pǐnzhǒng xiàndài zhì rén gèng zhǐyǒu 25-40 wànnián tīng qǐlái jǐ shí wàn jǐ bǎi wàn nián hǎoxiàng hěnjiǔ hěnjiǔ dànshì duì dìqiú ér yán ruò bǎ dìqiú de shēngmìng nóngsuō chéng yītiān de 24 xiǎoshí dehuà xiàndài zhì rén de chū xiàn dào xiànzài yě zhǐshì yītiān zhī zhōng zuìhòu de duǎn duǎn duǎn duǎn de liǎng miǎo zhōng yě zhǐ bùguò shì yī zhǎyǎn de shì gèng bùyòng shuō wǒmen dānyī rénlèi gètǐ de shēngmìng zhǐyǒu 100 nián xiāngduì dìqiú shēngmìng shì yǐ yì wèi dānwèilái shuō zhè gēnběn jiù bù suàn gè shì zhè bù zhǐshì shuō shíjiān shùliàng shàng yěshì cóng rénlèi shùliàng lái kàn rénlèi shēngmìng tǐ zhǐyǒu zhàn dìqiú zǒng shēngmìng de 0.01% Yě jiùshì yī wàn fēn zhī yī éryǐ lǐlùn shàng wǒmen rénlèi duì dìqiú ér yán yīnggāi huì gēn qítā de dòngwù yīyàng bù huì yǐngxiǎng dào dìqiú shàng de zìrán yùnzuò cái shì dàn piānpiān rénlèi zài jìnhuà de guòchéng zhōng fāzhǎn chū yīgè hěn lìhài de nǎodai bù zhǐ gǎibiànle dìqiú shàng de gèzhǒng shānhǎi héchuān de yàng mào yě gǎibiànle dàqì yě niǎn yāle gèzhǒng qítā shēngwù de shēngcún gēnjù kēxuéjiāmen jìsuàn wǒmen rénlèi yǐjīng cuīhuǐle zhège dìqiú shàng qítā 83%de wùzhǒng xiǎngxiàng yīxià, wǒmen měi yīgèrénlèi huózhe jiù cǎizhe gèzhǒng dòngwù shītǐ de múyàng gānggāng yěyǒu tí dào dìqiú wùzhǒng xiāoshī yībàn yǐshàng jiù fúhé shēngwù dà mièjué de dìngyì yě jiùshì yīnwèi zhèyàng suǒyǐ kēxuéjiā shuō wǒmen xiànzài dìqiú yīn wéi rénlèi de guānxì zhèngzài jīnglì dì liù cì de shēngwù dà mièjué jiù zhège jiǎodù ér yán rénlèi yuè duō jiù yuè shì huì páijǐ qítā de xìbāo qún yě jiùshì qítā shēngwù de shēngcún wǒmen rénlèi qíshí jiùshì zhège dìqiú shàng de ái xìbāo xiànzài wǒmen de nǔlì mùbiāo yīnggāi shì ràng rénlèi kěyǐ cóng ái xìbāo biànchéng pǔtōng xìbāo shènzhì shì biànchéng duì dìqiú hǎo de yìshēng jùn ràng dìqiú yīn wéi rénlèi ér gèng jiànkāng gèng měihǎo nǐ juédé rénlèi kěnéng biànchéng dìqiú shàng de yìshēng jùn ma? Háishì juédé shì wǒ yǒu wàngxiǎng zhèng ne? Ruò juédé kěnéng qǐng zài dǐxia bāng wǒ liúyán 1 juédé bù kěnéng qǐng bāng wǒ liúyán 2 wǒ yǒudiǎn xiǎng zhīdào wǒ dàodǐ shì yǒu duō biānyuán huíguī zhèngzhuàn kěnéng huì xiǎng wèn ér wǒmen rénlèi dàodǐ shì zuòle shénme huì ràng zhème duō de wùzhǒng xiāoshī zài zhège dìqiú shàng a zhè shíhòu jiù yào kāishǐ tí dào rénlèi duì dìqiú huánjìng de gǎizào yě jiùshì huánjìng pòhuài hé qìhòu biànqiānle qíshí rénlèi zhǐ zuòle yī jiàn shìqíng jiùshì xiǎng bànfǎ lìyòng zhège dìqiú shàng de zīyuán ràng rénlèi zìjǐ de shēnghuóguò dé gèng hǎo cóng rénlèi dànshēng zài zhège dìqiú shàng hòu yīnwèi fāzhǎn chū yīgè hǎo yòng de nǎodai suǒyǐ tòuguò lìyòng gōngjù, xùnhuà dòngwùzhíwù děng chuàngzào gèng ānquán gèng āndìng de shēnghuó huánjìng ránhòu rénlèi jiù màn man de zài dìqiú shàng kuò zhǎnkāi lái zǎoqí de rénlèi shì fēicháng yīlài zìrán de tiānshēng tiān yǎng, kào tiān chī tiān yóuqí zài gōngyè gémìng zhīqián rénlèi suīrán dōu yǒu xiǎng guò hǎo diǎn rìzi de yùwàng dàn yīnwèi gōngjù hé jìshù de xiànzhì suǒyǐ zuì hǎo de zīyuán jiù zhǐ néng jízhōng zài yīxiē shǎoshù rén de shēnshang jiù tōngcháng shì měi gè shèhuì de lǐngdǎo jiējí huòzhě shì guìzú jiējí zhèyàng de rìzi yěguòle jǐ qiān jǐ wàn nián ránhòu zài 260 nián qián, jiùshì 18 shìjì zài ōuzhōu yīngguó chūxiànle yīqún cōngmíng de kēxué fāmíng jiā yīnwèi fāmíng jīqì hé zhēngqìjī gèng yǒuxiào de shǐyòng néngyuán suǒyǐ gōngyè gémìng jiù fāshēngle tòuguò jīqì hé néngyuán de shǐyòng rénlèi chāoyuèle zìjǐ ròushēn de xiànzhì lìqì gèng dà, yídòng gèng yuǎn gōngzuò shíjiān kěyǐ gèng zhǎng jiùshì suǒwèi de láodònglì de jiěfàng cóng nà shíhòu kāishǐ rénlèi de xīnsī kāishǐ xiǎngzhe dàodǐ kěyǐ zěnme yàng bǎ dìqiú zīyuán quán bù ná lái ràng rénlèi de shēnghuó gèng měihǎo ne yúshì kāishǐ wākōngxīnsī xiǎngzhe yào bǎ mái zài dìdǐxia jǐ bǎi wàn nián jǐ qiān wàn nián de gèzhǒng huàshí hé jīnshǔ zīyuán dōu wā chūlái shǐyòng chúle jīnyín tóng tiě zhī wài méitàn shíyóu tiānránqì děng yěshì zhèxiē zīyuán dà bùfèn shǐyòng fāngshì dōu xūyào kào ránshāo néngyuánlái dáchéng yī shāo jiù bǎ běnlái zài dì dǐ de wùzhí quán bù shāo chūlái wǎng tiānshàng qùle rénlèi jìnrùle yīgè ránshāo de jìyuán yuè jìnbù jiù xūyào yuè duō de néngyuán zǎoqí gōngchǎng lǐ jīhū suǒyǒu de jīqì shǐyòng de néngyuán dōu shì shāo méi suǒyǐ gōngyè gémìng de tèsè jiùshì hēi hēisè de jīqì hēisè de gōngchǎng hēisè de jiēdào hēisè de yīfú běnlái jiù hēi bèi méitàn xūn hēi zhīhòu, jiù gèng hēi de fā liàng yīn wéi shēnghuó yuè lái yuè biànlì rénmen de wù zhí yùwàng yě yuè lái yuè péngzhàng wèile mǎnzú rénlèi shí yī zhù xíng yúlè gèzhǒng xūyào hé xiǎnglè yúshì gōngchǎng jiù zhìzào chū gèng duō gèng duō de chǎnpǐn hé shāngpǐn yě jiùshì zhège shíhòu kāishǐ rénlèi de lìliàng hé xìnxīn dū dà bàopéng jīhū měi gè rén dōu xiāngxìn réndìngshèngtiān zhǐyǒu rénlèi xiǎngbùdào, méiyǒu zuò bù dào de dōngxī wǒmen rénlèi rì fù yī rì de zuò chū yīgè jiē yīgè zhège dìqiú gēnběn bù xūyào chúncuì zhǐshì wǒmen rénlèi xiǎng yào de dōngxī dàliàng de zhìzào xūyào dàliàng de yuánliào hé zhìzào zhèxiē dōngxī xūyào de chǎngdì gōngchǎng ránhòu jiù kāishǐ bù bù de bǎ dà zìrán de gèzhǒng zīyuán dōu dàngchéng zìjǐ jiā de xiǎng ná jiù ná bùyào de zāng dōngxī rú fèishuǐ, fèi kōngqì jiù wǎng tiānkōng qù huò wǎng héchuān hǎilǐ dào ránhòu jiù biànchéng wǒmen xiànzài kàn dào dì dìqiúle zǒngzhī guòqù 200 duōnián cóng gōngyè gémìng dào xiànzài rénlèi dōu shì kào shāo gèzhǒng huàshí néngyuán cóng méitàn dào shíyóu shènzhì hénéng dōu shì lái zhīchēng rénlèi shèhuì de jìnbù hé rénlèi de yùwàng yóuqí méitàn shíyóu de ránshāo huì chǎnshēng dàliàng de wēnshì qìtǐ tōngtōng dū wǎng tiānkōng pái qù wēnshì qìtǐ shì dìqiú wàimiàn běnlái jiù yǒuyīcéng báo báo de yǔróng bèi zhèyàng kěyǐ bāng dìqiú bǎowēn ràng dìqiú wēndù bù huì tài rè yě bù huì tài lěng shìhé dìqiú shēngwù shēngcún dāng wǒmen rénlèi yīnwèi ránshāo huàshí néngyuán páifàng chū tài duō de wēnshì qìtǐ jiù xiàng dìqiú de yǔróng bèi yuè jiā yuè hòu érqiě zhège yǔróng bèi shì xiàtiān yě huì jìxù gàizhe de yǔróng bèi nǐ nénggòu xiǎngxiàng nǐ xiàtiān hái chuānzhuó yǔróng bèi de múyàng ma suǒyǐ dìqiú wēndù jiù huì shàngshēng dìqiú wēndù shàngshēng zhè jiùshì quánqiú nuǎn huà ránhòu yīnwèi quánqiú nuǎn huà kuài yǐngxiǎng dìqiú de qìhòu zhè jiùshì qìhòu biànqiān nà nǐ shuō rénlèi shì gùyì de ma yī kāishǐ kěnéng bùshì yīnwèi yǐqián de rénlèi bìng bù zhīdào yuán lái zìjǐ zuò de zhèxiē shì huì chǎnshēng zhèxiē bù hǎo de hòuguǒ dàn xiànzài míngmíng yǐjīng zhīdào wǒmen rénlèi de xíngwéi huì chǎnshēng zhèxiē bù hǎo de hòuguǒ què háishì zhǐgùzhe yào zìjǐ fā dà cái huò rénlèi zìjǐguò hǎo rìzi jiù hǎo bùyòng qù guǎn zìrán huì bèi wūrǎn yě bùguǎn qítā huò shēngwù zěnme yàng huò háishì shuō bu zhīdào, bù guān wǒ de shì dehuà nà jiùshì gùyì zhī wài yěshì wúzhīliǎo nà qìhòu biànqiān yòu huì zěnyàng ne huì hěn kěpà ma qìhòu biànqiān zuì kěpà dì dìfāng shì tā huì zàochéng yīliánchuàn de liánsuǒ fǎnyìng jiǎndān lái shuō, qìhòu biànqiān huì chǎnshēng shí dà yǐngxiǎng bù jiǎndān dehuà, wǒmen kěyǐ shuō chū yībǎi zhǒng yǐngxiǎng dàn yīnggāi méiyǒu rén xiǎng tīng jīntiān wǒmen xiān jiǎndān dàiguò yīxià jiē xiàlái wǒmen huì zài zhège xìliè zhōng zài xiángxì de jièshào měi yīgè yǐngxiǎng suǒyǐ xiǎng yào ài dìqiú yòu juédé zìjǐ zhīdào de bùgòu duō de nǐ huānyíng dìngyuè wǒmen de píndào jiù kěyǐ bāngzhù nǐ liàojiě gèng duō lóu yī, tiānqì yuè lái yuè rè jīběn kuǎn jiùshì tiānqì yuè lái yuè rè suīrán zhè jǐ cì hánliú lái dàjiā dōu yīnggāi juédé lěng sǐle nǎ yǒu shé me qìhòu biànqiān dàn nà zhǐshì zhè jǐ tiān de tiānqì bùshì qìhòu qìhòu shì zhǐ chángqí de tiānqì de lěijī suǒyǐ kěnéng yǒu jǐ tiān suīrán lěng sǐle dànshì qíshí zài táiwān měinián hánlěng de rì shù shì yuè lái yuè shǎo de yóuqí zuì míngxiǎn de jiùshì xià tiān huì yuè lái yuè rè rè sǐrén yóuqí shì zhù zài gāoxióng de wǒmen chāojí yǒu gǎn èr, yīxià yǔ jiù yān shuǐ yī bùxià yǔ jiù hànzāi xiàng táiwān jiù bǐ shìjiè shàng qítā dì dìfāng hái míngxiǎn táiwān měinián shàng bànnián dōu yīnwèi méi xià yǔ zài kànghàn chángcháng hóng dēng huáng dēng qǐng dàjiā wùbì wùbì jiéyuē yòngshuǐ ránhòu chángcháng xià bànnián yīxià yǔ jiùshì chāodà háoyǔ jiù dà yān shuǐ zhège jiù jiàozuò jíduān tiānqì qìhòu biànqiān huì ràng zhè zhǒng jíduān tiānqì yuè lái yuè duō sān, hǎi píngmiàn shàngshēng shòudào qìhòu biànqiān de yǐngxiǎng dìqiú hǎi píngmiàn zhèng yǐ měinián 1.9 Gōng lí de sùdù shàngshēng táiwān dì hǎi píngmiàn shàngshēng sùdù shì quánqiú de liǎng bèi guòqù 20 nián yǐ měinián 3.4 Gōng lí de sùdù chíxù shàngshēng zhōng érqiě suízhe tàn pái zēngjiā qíngkuàng kěnéng huì gèngjiā yánzhòng lǜsè hépíng de yánjiū gèng shuō 30 nián hòu de 2050 nián táiwān yǒu hěnduō chéngshì zhōngxīn dūhuì chéngwéi yānmò qū qízhōng bāokuò wǒmen jiā sì, hǎiyáng yuè lái yuè suān, yuè lái yuè nuǎn hǎiyáng suānhuà kuài ràng hǎiyáng shēngwù méi bànfǎ xíngchéng tànsuān gài ér tànsuān gài jiùshì tāmen de jiǎké hé gǔjià de zhǔyào chéngfèn suǒyǐ zhèxiē yúlèi bèilèi jiù huì yuè lái yuè cuìruò shènzhì sǐwáng hǎiyáng biàn nuǎn kěnéng zhíjiē jiù huì bǎ zhèxiē hǎiyáng shēngwù tàng sǐ huì ràng tāmen quē yǎng sǐ diào wǔ, yǐngxiǎng dòngzhíwù de xíxìng gǎibiàn shēngtài xìtǒng tiānqì yuè lái yuè nuǎn yǐngxiǎng zuì yánzhòng de shì zhíwù de shòufěn kāihuā hé jiéguǒ érqiě yòu yīnwèi zhíwù shì dìqiú shàng dà bùfèn de dòngwù hé wǒmen rénlèi de zhǔyào liángshí láiyuán suǒyǐ qíshí shì huì mǎshàng yǐngxiǎng dào wǒmen shēnghuó de liù, yúlèi xiāoshī shàngmiàn shuō hǎiyáng suānhuà hé nuǎn huà kuài ràng yú yuè lái yuè shǎo dāngrán rénlèi duì hǎiyáng de wūrǎn yě huì ràng yú yuè lái yuè shǎo yuè lái yuè bùjiànkāng ránhòu hǎishuǐ yuè nuǎn jiù huì bǎ hǎicǎo zhǔ shú ránhòu huì suānhuà jiā quē yǎng shènzhì huì ràng yú zhìxí ér sǐ jiā shàng rénlèi dà dàxiǎo xiǎotōu zhuā, luàn zhuā, làn bǔ, làn zhuā wǒmen xiànzài chī de yú yǐjīng yuè lái yuè xiǎo dōu yǐjīng chī dào yú jiè de xiǎohái qùle suǒyǐ zhuānjiā yùcè zàibu yǒu zǎn jié yīdiǎn 2048 nián rénlèi kěnéng jiù chī bù dào yúle qī, méiyǒu shuǐ hē suǒwèi méiyǒu shuǐ hē bù zhǐshì méiyǒu shuǐ tóngshí bāokuò méiyǒu ānquán de yǐnyòng shuǐ kěyǐ hē méi xià yǔ de shíhòu méi shuǐ hē tīng qǐlái hěn zhèngcháng dànshì zài táiwān chángcháng xià guo dàyǔ zhīhòu yě kěnéng yīn wéi shuǐ tài zāng háishì méi shuǐ hē dàn dàyǔ guòhòu de shuǐ huì chōngshuā chū hěnduō qí qíguài guài de wéishēngwù suǒyǐ rúguǒ méiyǒu chǔlǐguò juéduì bùnéng hē bā, néngyuán èxìng xúnhuán huàshí néngyuán shǐyòng huì páifàng dàliàng de èryǎnghuàtàn shì zuì zhòngyào de wēnshì qìtǐ ràng dìqiú shēnshang de yǔróng bèi yuè lái yuè dà jiàn dànshì qìhòu biànqiān ràng dìqiú huánjìng yuè lái yuè chà rénlèi wèile yào huó xiàqù jiù huì xūyào gèng duō néngyuán lái chuàngzào jūzhù kōngjiān bǐrú tài rè yào lěngqì tài lěng yào nuǎnqì xià yǔ yào chōushuǐ, fáng yān shuǐ méi yǔ yòu yào rénzào yǔ zhèxiē dōu xūyào xiāohào dàliàng de néngyuán rénlèi jiù huì shǐyòng gèng duō de néngyuán páifàng gèng duō de èryǎnghuàtàn rán ránhòu dìqiú huánjìng jiù huì gèng chà gèng bùshìhé rén zhù jiù yòu yào huā gèng duō de néngyuán lái gǎishàn zhè jiùshì néngyuán de èxìng xúnhuán jiǔ, dàjiā yì qǐ méi fàn chī qìwēn shàngshēng huì jíduān gāowēn jíduān dīwēn xià dàyǔ méi xià yǔ dōu duì zhíwù yǒu hěn dà de yǐngxiǎng dāngrán wǒmen rénlèi lài yǐwéi shí de nóngzuòwù yěshì zhíwù shòudào de yǐngxiǎng yě chāojí dà nóngzuòwù yóuqí shì gǔwù shì rénlèi shíwù yěshì dòngwù de sìliào zhǐyào yīdàn shòudào yǐngxiǎng wǒmen jiù zhǐ néng děngzhe è dùzi suǒyǐ qìhòu biànqiān yě huì ràng quánqiú de shíwù gōngyìng liàn biàn dé hěn cuìruò shí, jiànkāng wǒmen shì bùshì chángcháng huì yīn wéi tiānqì tài rè huì shuì bùzháo, hěn nán shuì tiānqì tài lěng yòu hěn róngyì yǐnqǐ gèzhǒng xīn xiěguǎn jíbìng shuì bù hǎo duì shēntǐ bù hǎo bùyòng shuō yǐnfā de xīn xiěguǎn jíbìng gèng shì qìhòu jiànjiē yǐngxiǎng wǒmen rénlèi jiànkāng de zhèngjù yě jiùshì shuō qíshí qìhòu shì huì shārén de jiǎnjié yīdiǎn dehuà jiùshì qìhòu kěyǐ ràng rén hé dòngzhíwù rè sǐ lěng sǐ, kě sǐ huò yān sǐ jiànjiē yīdiǎn de jiùshì kōngqì qíshí shì kěyǐ tòuguò hūxīdào shuǐ hé shíwù kěyǐ tòuguò rénlèi de xiāohuà dào yǐnfā gèzhǒng jíbìng huò áizhèng lái shārén hái kěyǐ yòng dài yǒu dēnggérè de wénzi dàjūn lái gōngjí wǒmen ránhòu, qìhòu biànqiān huì ràng rénlèi mièwáng ma nǐ yīdìng xiǎng zhème wèn mùqián kàn lái yěshì yǒu zhège kěnéng de zài rénlèi mièwáng zhīqián dìqiú shàng dà bùfèn de dòngzhíwù dūhuì xiān gēnzhe péizàng jiùshìle jiù xiànzài de rénlèi kējì fāzhǎn ér yán shuō bu dìng zhēn de yǒuxiē rén kěyǐ yímín huǒxīng huò shì yǒuxiē rén kěyǐ duǒ zài tèshū shēngcún zhuāngzhì lǐmiàn cúnhuó dào zuìhòu dàn nà yǒuxiē rén jiù juéduì bù huì shì wǒmen wǒmen yībānrén háishì yǒu yī xiàn xīwàng de bǐ qǐ kǒnglóng dà mièjué ràng kǒnglóng wánquán xiāoshī zài zhège shìjiè shàng wǒmen rénlèi hé kǒnglóng bù yīyàng nà nǎlǐ bù yīyàng wǒmen rénlèi yǒu xiǎng xiàng lì yěyǒu jítǐ hézuò de lìliàng wǒmen de nǎodai kěyǐ yùxiǎng dào wèi lái kěnéng de jǐngxiàng wǒmen yěyǒu zúgòu de cōngmíng cáizhì kěyǐ nǔlì bìmiǎn zhèxiē zuì zāogāo de qíngkuàng fāshēng bùshì dōu shuō wǒmen rénlèi zhǐyǒu xiǎngbùdào méiyǒu zuò bù dào ma tòuguò rénlèi de jítǐ nǔlì wǒmen háishì hěn yǒu jīhuì kěyǐ zhěngjiù wǒmen zìjǐ de zhìshǎo wǒ shì zhème xiāngxìn de ruò dàjiā zài zuò dāngxià de měi yī gè xuǎnzé bāokuò xiāofèi yǔ tóuzī dōu kěyǐ bāng dìqiú duō xiǎng yīdiǎn dehuà nà wǒmen jiù kěyǐ chéngwéi dìqiú de yìshēng jùn bùguò qìhòu māmā yě zài zhèlǐ tíxǐng dàjiā ài dìqiú qiān wàn yě bùyòng juédé yālì tài dà jiù xiàng ài rén yě bùnéng ài de tài yònglì bùrán hěn róngyì huì yālì tài dà bǎ zìjǐ bī dào sǐjiǎo zhèyàng fǎn'ér chēng bùjiǔ zhè yītiáo lù hěn màncháng yīdìng yào yǒu huǒbàn jiù xiàng zǒulù dōu yào yǒu bàn cái huì zǒu dé yuǎn zhè tiáo lù ràng wǒmen péi nǐ, wǒmen yīqǐ zǒu ba jīntiān jiù xiān dào zhèlǐ xià cì wǒmen yào gēn dàjiā shuō shuō nǐ bù zhīdào de běijíxióng hé qìhòu biànqiān de gùshì yě qǐng àn xià pángbiān de dìngyuè sānjiǎoxíng hé xiǎo língdāng zhèyàng youtube cái huì tōngzhī nǐ ó yě huānyíng hé wǒmen fēnxiǎng nǐ de xīndé wǒ shì qìhòu māmā wǒmen xià gè yǐngpiàn jiàn hēi bàibài",
        chinese: `你知道愛地球其實是為了愛人類自己
        一點都不關地球的事嗎
        哈囉大家好
        我是氣候媽媽
        和你一起學習
        活在未來需要的氣候知識
        這裡是一個講對我們生活影響很大
        但很多時候我們卻不太清楚
        也不太明瞭該怎麼面對的
        氣候變遷的故事的頻道
        另外
        氣候媽媽也是個務實的氣候主義者
        也就是我堅信
        愛地球一定要跟自身利益相結合
        才能激起最大的行動力
        也要幫點進我們這裡的你拍拍手
        因為你今天會點進我們這裡
        就表示
        你已經比這個社會上大多數的人
        都來的關心自己的生活環境和自己的未來了
        你有沒有想過
        當你選擇要訂閱誰的時候
        你其實是在選擇你未來的思維方式
        所以歡迎訂閱我們
        讓我們一起邁向務實愛地球的行列吧
        今天我們要來說一個我們小人類和大地球
        感情越來越不好的故事
        首先先來簡單說一下地球的故事
        地球從誕生到現在已經46億年
        一般認為只要有太陽
        地球就會一直存在
        所以
        地球現在約等於人類的46歲左右
        也就是跟氣候媽媽我現在差不多大
        是個中年大媽來著
        人類呢
        其實就是生活在地球上的一群細胞們
        不只是人類
        所有的生物都算是不同的細胞群
        那些高山
        我們可以比喻成人身體裡的骨頭
        河流就像血管
        海洋就像我們身體裡面的血液
        每一塊大陸都像是我們身體裡的器官
        但是不一樣的是
        我們人類如果沒有身體裡的器官
        人類就會死亡
        但是地球的運轉和存在是靠太陽
        少了剛才說的任何一塊
        雖然暫時會改變地球內部的組成
        但是對地球本身而言沒差
        地球完全不會因此而死亡或滅亡
        也就是說人類如果沒有地球就完蛋了
        但是地球沒有我們人類
        完全不會怎麼樣
        而且這些事情都發生過
        過去地球歷史上就發生過
        五次的生物大滅絕
        對，五次
        當時
        地球上一半以上的生物都死光光了
        但地球還是持續的轉動至今
        至今人類也是在這五次大滅絕之後
        才誕生在地球上的諸多物種之一
        人類出現在這個世界上
        只有500到700萬年
        尤其是我們現在這個品種
        現代智人更只有25-40萬年
        聽起來幾十萬幾百萬年好像很久很久
        但是對地球而言
        若把地球的生命濃縮成
        一天的24小時的話
        現代智人的出現到現在
        也只是一天之中
        最後的短短短短的兩秒鐘
        也只不過是一眨眼的事
        更不用說
        我們單一人類個體的生命只有100年
        相對地球生命是以億為單位來說
        這根本就不算個事
        這不只是說時間
        數量上也是
        從人類數量來看
        人類生命體只有占
        地球總生命的0.01%
        也就是一萬分之一而已
        理論上我們人類對地球而言
        應該會跟其他的動物一樣
        不會影響到地球上的自然運作才是
        但偏偏人類在進化的過程中
        發展出一個很厲害的腦袋
        不只改變了地球上的各種
        山海河川的樣貌
        也改變了大氣
        也碾壓了各種其他生物的生存
        根據科學家們計算
        我們人類已經摧毀了這個地球上
        其他83%的物種
        想像一下，我們每一個人類活著
        就踩著各種動物屍體的模樣
        剛剛也有提到地球物種消失一半以上
        就符合生物大滅絕的定義
        也就是因為這樣
        所以科學家說
        我們現在地球因為人類的關係
        正在經歷第六次的生物大滅絕
        就這個角度而言
        人類越多就越是會排擠其他的細胞群
        也就是其他生物的生存
        我們人類
        其實就是這個地球上的癌細胞
        現在我們的努力目標
        應該是讓人類可以
        從癌細胞變成普通細胞
        甚至是變成對地球好的益生菌
        讓地球因為人類而更健康更美好
        你覺得
        人類可能變成地球上的益生菌嗎？
        還是覺得是我有妄想症呢？
        若覺得可能請在底下幫我留言1
        覺得不可能請幫我留言2
        我有點想知道我到底是有多邊緣
        回歸正傳
        可能會想問
        而我們人類到底是做了什麼
        會讓這麼多的物種消失在這個地球上
        啊這時候
        就要開始提到人類對地球環境的改造
        也就是環境破壞和氣候變遷了
        其實人類只做了一件事情
        就是想辦法利用這個地球上的資源
        讓人類自己的生活過得更好
        從人類誕生在這個地球上後
        因為發展出一個好用的腦袋
        所以透過利用工具、馴化動物植物等
        創造更安全更安定的生活環境
        然後人類就慢慢的在地球上擴展開來
        早期的人類是非常依賴自然的
        天生天養，靠天吃天
        尤其在工業革命之前
        人類雖然都有想過好點日子的慾望
        但因為工具和技術的限制
        所以最好的資源就只能集中在
        一些少數人的身上
        就通常是每個社會的領導階級
        或者是貴族階級
        這樣的日子也過了幾千幾萬年
        然後在260年前，就是18世紀
        在歐洲
        英國出現了一群聰明的科學發明家
        因為發明機器和蒸汽機
        更有效的使用能源
        所以工業革命就發生了
        透過機器和
        能源的使用
        人類超越了自己肉身的限制
        力氣更大，移動更遠
        工作時間可以更長
        就是所謂的勞動力的解放
        從那時候開始
        人類的心思開始想著
        到底可以怎麼樣把地球資源全部拿來
        讓人類的生活更美好呢
        於是開始挖空心思
        想著要把埋在地底下幾百萬年
        幾千萬年的各種化石
        和金屬資源都挖出來使用
        除了金銀銅鐵之外
        煤炭石油
        天然氣等也是這些資源
        大部分使用方式都需要靠
        燃燒能源來達成
        一燒
        就把本來在地底的物質全部燒出來
        往天上去了
        人類進入了一個燃燒的紀元
        越進步就需要越多的能源
        早期工廠裡幾乎所有的機器
        使用的能源都是燒煤
        所以工業革命的特色就是黑
        黑色的機器
        黑色的工廠
        黑色的街道
        黑色的衣服本來就黑
        被煤炭熏黑之後，就更黑的發亮
        因為生活越來越便利
        人們的物質慾望也越來越膨脹
        為了滿足人類食衣住行娛樂
        各種需要和享樂
        於是工廠就製造出更多更多的產品和商品
        也就是這個時候開始
        人類的力量和信心都大爆棚
        幾乎每個人都相信人定勝天
        只有人類想不到，沒有做不到的東西
        我們人類日復一日的做出一個接一個
        這個地球根本不需要
        純粹只是我們人類想要的東西
        大量的製造需要大量的原料和
        製造這些東西需要的場地
        工廠
        然後就開始步步的把大自然的各種資源
        都當成自己家的
        想拿就拿
        不要的髒東西如廢水、廢空氣
        就往天空去或往河川海裡倒
        然後就變成我們現在看到的地球了
        總之過去200多年從工業革命到現在
        人類都是靠燒各種化石能源
        從煤炭到石油
        甚至核能
        都是
        來支撐人類社會的進步和人類的慾望
        尤其煤炭石油的燃燒
        會產生大量的溫室氣體
        通通都往天空排去
        溫室氣體是
        地球外面本來就有一層薄薄的羽絨被
        這樣可以幫地球保溫
        讓地球溫度不會太熱
        也不會太冷
        適合地球生物生存
        當我們人類因為燃燒化石能源
        排放出太多的溫室氣體
        就像地球的羽絨被越加越厚
        而且這個羽絨被
        是夏天也會繼續蓋著的
        羽絨被
        你能夠想像
        你夏天還穿著羽絨被的模樣嗎
        所以地球溫度就會上升
        地球溫度上升
        這就是全球暖化
        然後因為全球暖化會影響地球的氣候
        這就是氣候變遷
        那你說人類是故意的嗎
        一開始可能不是
        因為以前的人類
        並不知道原來自己做的這些事
        會產生這些不好的後果
        但現在
        明明已經知道我們人類的行為
        會產生這些不好的後果
        卻還是只顧著要自己發大財
        或人類自己過好日子就好
        不用去管自然會被污染
        也不管其他或生物怎麼樣
        或還是說不知道、不關我的事的話
        那就是故意之外也是無知了
        那氣候變遷又會怎樣呢
        會很可怕嗎
        氣候變遷最可怕的地方是
        它會造成一連串的連鎖反應
        簡單來說，氣候變遷會產生十大影響
        不簡單的話，我們可以說出一百種影響
        但應該沒有人想聽
        今天我們先簡單帶過一下
        接下來我們會在這個系列中
        再詳細的介紹每一個影響
        所以想要愛地球
        又覺得自己知道的不夠多的
        你歡迎訂閱我們的頻道
        就可以幫助你瞭解更多嘍
        一、天氣越來越熱
        基本款就是天氣越來越熱
        雖然這幾次寒流來
        大家都應該覺得冷死了
        哪有什麼氣候變遷
        但那只是這幾天的天氣不是氣候
        氣候是指長期的天氣的累積
        所以可能有幾天雖然冷死了
        但是其實在臺灣
        每年寒冷的日數是越來越少的
        尤其最明顯的就是夏天會越來越熱
        熱死人
        尤其是住在高雄的我們超級有感
        二、一下雨就淹水
        一不下雨就旱災
        像臺灣就比世界上其他的地方還明顯
        臺灣每年上半年都因為沒下雨在抗旱
        常常紅燈黃燈
        請大家務必務必節約用水
        然後常常下半年一下雨就是超大豪雨
        就大淹水
        這個就叫做極端天氣
        氣候變遷會讓這種極端天氣越來越多
        三、海平面上升受到氣候變遷的影響
        地球海平面正以每年
        1.9公厘的速度上升
        臺灣的海平面上升速度是全球的兩倍
        過去20年
        以每年3.4公厘的速度持續上升中
        而且隨著碳排增加
        情況可能會更加嚴重
        綠色和平的研究更說
        30年後的2050年
        臺灣有很多城市中心都會成為淹沒區
        其中包括我們家
        四、海洋越來越酸，越來越暖
        海洋酸化會
        讓海洋生物沒辦法形成碳酸鈣
        而碳酸鈣就是它們的甲殼和
        骨架的主要成分
        所以這些魚類貝類就會越來越脆弱
        甚至死亡
        海洋變暖
        可能直接就會把這些海洋生物燙死
        會讓它們缺氧死掉
        五、影響動植物的習性
        改變生態系統
        天氣越來越暖
        影響最嚴重的是植物的授粉
        開花和結果
        而且又因為
        植物是地球上大部分的動物和
        我們人類的主要糧食來源
        所以其實是會馬上影響到我們生活的
        六、魚類消失
        上面說海洋酸化和
        暖化會讓魚越來越少
        當然
        人類對海洋的污染也會讓魚越來越少
        越來越不健康
        然後海水越暖就會把海草煮熟
        然後會酸化加缺氧
        甚至會讓魚窒息而死
        加上人類大大小小偷抓、亂抓、濫捕、濫抓
        我們現在吃的魚已經越來越小
        都已經吃到魚界的小孩去了
        所以專家預測再不有攢節一點
        2048年人類可能就吃不到魚了
        七、沒有水喝
        所謂沒有水喝不只是沒有水
        同時包括沒有安全的飲用水可以喝
        沒下雨的時候沒水喝聽起來很正常
        但是在臺灣常常下過大雨之後
        也可能因為水太髒還是沒水喝
        但大雨過後的水
        會沖刷出很多奇奇怪怪的微生物
        所以如果沒有處理過絕對不能喝
        八、能源惡性循環
        化石能源使用會排放大量的二氧化碳
        是最重要的溫室氣體
        讓地球身上的羽絨被越來越大件
        但是氣候變遷讓地球環境越來越差
        人類為了要活下去
        就會需要更多能源來創造居住空間
        比如太熱要冷氣
        太冷要暖氣
        下雨要抽水、防淹水
        沒雨又要人造雨
        這些都需要消耗大量的能源
        人類就會使用更多的能源
        排放更多的二氧化碳
        然然後地球環境就會更差
        更不適合人住
        就又要花更多的能源來改善
        這就是能源的惡性循環
        九、大家一起沒飯吃
        氣溫上升會極端高溫
        極端低溫下大雨
        沒下雨都對植物有很大的影響
        當然
        我們人類賴以為食的農作物也是植物
        受到的影響也超級大
        農作物尤其是穀物
        是人類食物也是動物的飼料
        只要一旦受到影響
        我們就只能等著餓肚子
        所以氣候變遷
        也會讓全球的食物供應鏈變得很脆弱
        十、健康
        我們是不是常常會因為天氣太熱
        會睡不著、很難睡
        天氣太冷
        又很容易引起各種心血管疾病
        睡不好對身體不好不用說
        引發的心血管疾病更是氣候間接
        影響我們人類健康的證據
        也就是說其實氣候是會殺人的
        簡潔一點的話
        就是氣候可以讓人和動植物熱死
        冷死、渴死或淹死
        間接一點的就是
        空氣其實是可以透過呼吸道
        水和食物可以透過人類的消化道
        引發各種疾病或癌症來殺人
        還可以用帶有登革熱的
        蚊子大軍來攻擊我們
        然後，氣候變遷會讓人類滅亡嗎
        你一定想這麼問
        目前看來也是有這個可能的
        在人類滅亡之前
        地球上
        大部分的動植物都會先跟著陪葬就是了
        就現在的人類科技發展而言
        說不定真的有些人可以移民火星
        或是有些人可以躲在
        特殊生存裝置裡面
        存活到最後
        但那有些人就絕對不會是我們
        我們一般人還是有一線希望的
        比起恐龍大滅絕
        讓恐龍完全消失在這個世界上
        我們人類和恐龍不一樣
        那哪裡不一樣
        我們人類有想像力
        也有集體合作的力量
        我們的腦袋
        可以預想到未來可能的景象
        我們也有足夠的聰明才智
        可以努力避免這些最糟糕的情況發生
        不是都說我們人類只有想不到
        沒有做不到嗎
        透過人類的集體努力
        我們還是很有機會
        可以拯救我們自己的
        至少我是這麼相信的
        若大家在做當下的每一個選擇
        包括消費與投資
        都可以幫地球多想一點的話
        那我們就可以成為地球的益生菌
        不過氣候媽媽也在這裡提醒大家
        愛地球千萬也不用覺得壓力太大
        就像愛人也不能愛的太用力
        不然很容易會壓力太大
        把自己逼到死角
        這樣反而撐不久
        這一條路很漫長
        一定要有夥伴
        就像走路都要有伴才會走得遠
        這條路讓我們陪你，我們一起走吧
        今天就先到這裡
        下次我們要跟大家說說
        你不知道的北極熊和
        氣候變遷的故事
        也請按下旁邊的訂閱三角形和小鈴鐺
        這樣 youtube才會通知你哦
        也歡迎和我們分享你的心得
        我是氣候媽媽
        我們下個影片見嘿拜拜`
    }
};

export default climateChange;