const coronavirus = {
    videoId: 'Dwx0QkOK7lw',
    transcript: {
        pinyin: "yīngguó gōngbùle xīnguān bìngdú réntǐ tiǎozhàn shìyàn de jiéguǒ zhège shíyàn ne wǒ jiǎndān de jièshào yīxià ràng dàjiā yǒu gè lúnkuò nà jiùshì yīngguó zhèngfǔ yìmiáo tèbié gōngzuò zǔzhī děng děng de yīxiē jīgòu ne zhāomùle 36 wèi méiyǒu zhùshè yìmiáo de niánqīng rén gěi tāmen de bízi zhùrù xīnguān bìngdú ràng tāmen gǎnrǎn kěshì jiéguǒ jiù chūxiàn yǒu yìwài de fāxiàn jiùshì 36 gè tóngyàng xīrù xīnguān bìngdú dí jiànkāng niánqīng rén zhōng zhǐyǒu 50%de rén gǎnrǎn dànshì lìngwài yībàn rén què méiyǒu gǎnrǎn wǒmen gūqiě bù tǎolùn zhège shìyàn de dàodé lúnlǐ zhège wèntí dànshì zhège shíyàn de jiéguǒ ràng rén juédé fēicháng de shénqí yīnwèi lìngwài yībàn rén wéi shénme méiyǒu gǎnrǎn bìngdú jiùsuàn zhíjiē bǎ bìngdú zhùshè dào bízi lǐmiàn yě méiyǒu gǎnrǎn xiǎng qǐngjiào dǒng bóshì shì de díquè fēicháng yǒuyìsi nǐ kàn zhè yībàn rén bǎ nàgè bìngdú cóng tā de bízi lǐ zhù jìnqù pēn jìnqù tā yě bù huì gǎnrǎn zhè quèshí shì zhège shíyàn fāxiàn de yīgè kēxué de zīliào yīgè xiànxiàng wǒmen dàjiā cū yī kàn qǐlái hǎoxiàng bùkěsīyì qíshí wǒmen xiǎng yīxià zài xiànshí shìjiè zhōng yǒu de rén jiùshì zài yīyuàn gōnggòng chǎngsuǒ zhè zhǒng hěn gāo bìngdú huánjìng zhōng qù gōngzuò yǒu de rén jiùshì bùgǎnrǎn nà zhèyàng qízhōng de yuányīn dàodǐ shì wèishéme ne nà zhège yánjiū jiùshì wèile huídá rénmen de zhège wèntí de yě jiùshì shuō wèishéme yǒurén tā duì zhège bìngdú jiù yǒu zìrán de dǐkàng lì wǒmen zài huí dào zhège shíyàn de shèjì shànglái kàn shǒuxiān zài zuò de guòchéng zhōng shíyàn shèjì zhě tā jiù yào quèbǎo suǒyǒu de cānyù shòu shì zhě de ānquán xìng nà tā dāngrán xuǎn de jiùshì yīqún niánqīng rén niánqīng rén miǎnyì lì yībān lái shuō dōu shì bǐjiào hǎo de yīgè zhuàngtài ránhòu hái yǒu jiànkāng méiyǒu shé me jíbìng zhèxiē dōu shì yángé shāixuǎn de yīqún rén wǒmen kàn kàn zhěnggè de zhège liúchéng měi yīgè shòu shì zhě tā jìnlái zhīhòu dàgài yǒu 2 dào 3 gè yuè de shāixuǎn qī zài zuǒbiān de shāixuǎn de mùdì jiùshì wèile gěi tā chōu xiě huàyàn jìn háng gè fāngmiàn de yīgè jiǎnchá quèbǎo tā fúhé shíyàn de zhège rùxuǎn hé páichú biāozhǔn zhè shì yīgè ránhòu zài zhùrù bìngdú dí qián 2 tiān jiù bǎ zhèxiē rén gěi sòng dào yīyuàn de zhège tèshū de gélí de bìngfáng lǐ yīn wéi shì yǒuyīgè bìngdú dí bàolù de huánjìng ma suǒyǐ jiùshì yīgè hěn tèshū de fù yā de yīgè huánjìng ránhòu ne cóng zhùrù zhīhòu měitiān kěyǐ dōu yào qǔ zhège yānhóu hái yǒu bí bù de zhège yàngpǐn de zhège bìngdú dí zhège nóngdù hái yào chōu xiě huàyàn chá zhège xuè lǐ de xiěqīng de kàngtǐ nà wǒmen zài kàn yī kàn zhège shíyàn de jiéguǒ dì yīlèi jiùshì wánquán méiyǒu gǎnrǎn de rén wánquán méiyǒu gǎnrǎn de rén jiùshì zuì yòubiān de zhège lǜsè de zhè yīlèi tāmen jiùshì yānhóu bù de zhège yàngpǐn qǔyàng méiyǒu cè dào rènhé bìngdú dí jīxiàng ér xuè lǐtou yě méiyǒu kàngtǐ chǎnshēng suǒyǐ zhè yīlèi rén zhēn de shì bù zhàn ér qū rén zhī bīng gēnběn jiù bùyòng gēn nǐ dǎ bìngdú zuòzhàn yě méiyǒu zhège kàngtǐ de hénjī zhè zhǒng rén de miǎnyì lì kěyǐ shuō shì zuì bàng de tā de zhège shēntǐ de xìbāo jiù xiàng yīpiàn héyè yīyàng nǐ bǎ bìngdú sǎ shàngqù yě bù huì zhān shuǐ sǎ shàngqù yě bù huì zhān bìngdú sòng dào bízi lǐ yě bù huì gǎnrǎn shàng zhēn de shì chāojí bàng de yīgè miǎnyì lì wǒmen zhège jiàozuò zuì hǎo de miǎnyì lì zhuàngtài ránhòu dì èr lèi rén jiùshì zài zhōngjiān de zhè yīgè wǒ zǐxì kànle yīxià qíshí yǒuyīgèrén tā qíshí fāshēngle yīgè wú zhèngzhuàng de gǎnrǎn jiùshì shuō tā háishì guī zài méiyǒu gǎnrǎn de zhège 18 gè lǐtou dànshì yānhóu bù yě méiyǒu chá dào bìngdú dànshì tā xuè lǐtou yǒuyīgè kàngtǐ de chǎnshēng tā méiyǒu zhèngzhuàng suǒyǐ dànshì yīnwèi xuè lǐ yǒu kàngtǐ shuōmíng háishì fāshēngle yīxiē miǎnyì xìtǒng yǒuyīxiē zuòyòng zài lǐtou gēn bìngdú yǒuyīxiē jiāofēng dànshì tā méiyǒu zhèngzhuàng shuōmíng zhège jiāofēng shì hěn shùnlì de suǒyǐ zhège miǎnyì lì yěshì fēicháng bàng de yīgè zhuàngtài zhè shì dì 2 zhǒng rén fēicháng shǎo ránhòu zài jiùshì dì sān lèi rén yě jiùshì zuǒbiān de zhè yīqún 18 gèrén tāmen ne jiùshì shuō bèi gǎnrǎn shàngle yǒu zhèngzhuàng de yǒu yīxiē qīng dù huòzhě zhōng dù de zhèngzhuàng chōu xiě de bùguāng yǒu kàngtǐ hái yǒu yīgè yánzhèng biāozhìzhe yánzhèng fǎnyìng de yīgè dànbáizhí tā shēng shàngláile nà shuōmíng shénme ne shuōmíng tǐnèi yǒu zhège kàng bìngdú dí miǎnyì fǎnyìng érqiě shì yīgè tèyì xìng de miǎnyì fǎnyìng yǒu yánzhèng yīn shǔ de shìfàng yǒu zhàndòu yǒu xiāoyān zuìhòu yǒu sǔnshī dànshì zuìhòu de jiéguǒ shì hěn hǎo de dāngránle wǒ mén zài hóngguān shàng kàn dào zhèngzhuàng fēicháng de qīngwéi kěshì wǒmen xiǎng yī xiǎng miǎnyì xìtǒng zài wéiguān xià yěshì yīgè hěn pángdà de yīgè yǔzhòu tā yǒu gèzhǒng gè yàng de xìbāo yǒu gèzhǒng gè yàng de fēnzǐ yě xiàng yīgè hěn dà de shìjiè yīyàng nàme qíshí yěshì yīgè zhànchǎng zhège xìbāo shòudào bìngdú dí qīnfàn tā yě kěnéng huì sǐwáng de suǒyǐ jiù xiàng rénlèi de zhànzhēng yīyàng bǐfāng shuō zuìjìn wūkèlán jǐnguǎn zhège shì hěn qīngwéi de yīgè zhèngzhuàng dànshì tā shì yào chū rénmìng de jiùshì shuō zài miǎnyì xìbāo fàngdà yī kàn tā yě kěnéng jiùshì yīgè shēngmìng miǎnyì xìbāo de sǐwáng tā yěshì yǒu dàijià de suǒyǐ wǒmen hái láihuí dào hóngguān shìjiè ràng dàjiā kàn yī kàn zhè gāngcái shuō dào de zhè sān lèi rén wǒmen xiān bǎ zhège quányù de zhè liǎng lèi rén fàng zài yībiān wǒmen lái kàn kàn bèi gǎnrǎn de zhè yīqún rén tāmen yībān dōu shì yānhóu bù yīnwèi jǐnguǎn bìngdú shì cóng bízi lǐ pēn jìnqù de dànshì shì zài yānhóu bùwèi shǒuxiān 2 tiān jiù cè dàole zhège bìngdú ránhòu dì 5 tiān de yānhóu bùwèi de bìngdú jiù dádàole gāofēng zhè yòubiān de zhège tú ránhòu zhège zuǒbiān de zhège tú jiùshì bízi bízi de zhège qǔyàng jiùshì bǐ yānhóu bùwèi tā shǒuxiān jiǎncè dào de bìngdú dí shíjiān yào wǎn yītiān dàgài shì dì 3 tiān jiǎncè dào jiù zuì zuǒbiān zhège bìngdú néng jiǎncè dào de zhège shuǐzhǔn ránhòu tā de dá fēng shíjiān ne yěshì yào bǐ yānhóu bù yě yào wǎn yītiān yào dào wǔliù tiān de shíhòu cái dá fēng suǒyǐ zhěnggè de jiùshì zhème yīgè qíngkuàng ránhòu zhège lán sè de zhège qūxiàn shì yīgè PCR nà zhège dìfāng wǒ jiù xiǎng yǐnshēn yīdiǎn jiù dàjiā kěyǐ sīkǎo yīxià bǐjiào yǒuyìsi jiùshì wèishéme cóng bízi lǐ dǎ jìnqù de bìngdú shì zài yānhóu bùwèi xiān dádào gāofēng ránhòu hòumiàn zhìhòu yīdiǎn cái dào bízi lǐ cè dédào gāofēng ne zhège qíshí gēn bìngdú dí tèxìng yǒu guānxì yīnwèi bìngdú tā shì yīgè jìshēng zài yīlài yú wǒmen réntǐ de xìbāo cáinéng cúnhuó xiàlái de yīgè wéishēngwù tā zǒng shì zài shìtú xúnzhǎo yīxiē bǐjiào héshì de shìhé tā shēngzhǎng de shēngcún huánjìng bǐfāng shuō wǒmen réntǐnèi zhège xiěyè bǐjiào wàngshèng xīnchéndàixiè bǐjiào hǎo zhège bǐjiào wàngshèng de yīxiē zǔzhī qìguān jiùshì tā shǒuxiān yào gōngjí de wùjiàn ér yānhóu bùwèi zhènghǎo yěshì xiěyè xìtǒng bǐjiào fēngfù de yīgè bùwèi suǒyǐ kěnéng yěshì zuì róngyì bèi bìngdú qù miáozhǔn dì yīgè bùwèi ránhòu dànshì dì 2 diǎn jiùshì shuō zhège shìqíng rènhé shìqíng dōu shì yǒu liǎngmiànxìng de nǐ dào wǒ zhège yānhóu bùwèi gǎnrǎn de duō nǐ fánzhí de kuài nǐ zài wǒ zhè'er fánzhí de kuài dànshì wǒ zhè biān de fángyù xìtǒng yěyǒu hěn zúgòu de yīgè pèibèi wǒmen zhīdào wǒmen de yānhóu zài wǒmen de bíqiāng zhège hòufāng jìnrù zhège qìguǎn zhège fèi bù de yīgè yào dào yānhóu yǒu yīgè hěn qiángdà de yīgè jiù xiàng wǒmen de réntǐ de wèishì yīyàng wǒmen zhīdào nàgè liǎngbiān yǒu 2 gè biǎntáotǐ tāmen jiùshì lǐmiàn yǒu hěnduō de línbā xìbāo tā shǒuhùzhe wǒmen de ménhù zǔdǎng wàilái de bìngjùn xìjùn bìngdú dí qīnrù suǒyǐ yīdàn fāxiànle yīxiē xìjùn bìngdú dí zhēnxiàng ne zhège yānhóu bùwèishì shǒuxiān gēn tāmen zuòzhàn de wèi shì jíshǐ shì hěn jiànkāng de rén qíshí tā yānhóu bùwèi de zhège línbā xìbāo yě yīzhí bǎochí zài yīgè bèizhàn de zhuàngtài érqiě wǒmen chángcháng gǎnmào de chūqí jiùshì hóulóng tòng tán duō děng děng zhèxiē zhèngzhuàng qíshí zhè shì yīgè wǒmen de niánmó de zhège yóuqí shì yānhóu bùwèi de zhège miǎnyì lì tā zài zhèngcháng fāhuī gōngnéng de yīgè hǎo de zhēnxiàng rén de miǎnyì lì rúguǒ zài zhè'er zúgòu qiáng dehuà hěn kuài jiù néng bǎ zhège shàng hūxīdào jìnlái de zhèxiē bìngdú xìjùn gěi tā bǎipíng suǒyǐ wǒmen yīgèrén rúguǒ shuō tā yīniándàotóu yě bù gǎn jǐ cì mào tā gǎn yīcì mào zhīhòu ne yī liǎng tiān hěn kuài jiù guòqùle nà zhè zhǒng rén jiù shuōmíng tā de zhège jītǐ de zhège ménhù de zhège miǎnyì lì shì fēicháng hǎo de yīgè zhuàngtài dànshì rúguǒ yīgèrén tā yī gǎnmào jiùshì yī liǎng gè xīngqí hěn nán hǎo érqiě yīniándàotóu jīngcháng gǎnmào nà zhè jiùshì wǒmen jītǐ gěi wǒmen de yīgè xìnhào jiùshì tíxǐng wǒmen wǒmen de miǎnyì xìtǒng zhìshǎo zài yānhóu bùwèi zhè shì yīgè dàibiǎo xìng de yīgè bùwèi wǒmen yīdìng yào duōjiā liúyì wǒmen de miǎnyì lìle wèishéme qízhōng 17 gèrén jiù bù gǎnrǎn ne shì de suǒyǐ qíshí zhè dì sān zhège miǎnyì lì zuì hǎo de zhè zhǒng rén tā bù gēn bìngdú fāshēng zhège chōngtú dànshì tā yòu nénggòu bǎ bìngdú wánquán de páichú zài shēntǐ zhī wài wǒmen hěn xiǎng yào zhīdào duì duì duì suǒyǐ rúguǒ yào xiǎng zhīdào zhège dehuà wǒmen kěnéng yào kàn yī kàn réntǐ de miǎnyì xìtǒng miǎnyì xìtǒng shì zěnme yùnzuò de zhège yùnzuò de zhège jīzhì ne jiùshì chúle gāngcái shuō dào de bìngdú cóng zhè'er pífū zhè biān guòlái ránhòu jīngguò zhè yīgè zǔdǎng zhīhòu ne wǒmen réntǐ qíshí jìn lái liǎo zhīhòu jiù yǒu yīdào fēicháng qiángdà de zhège zhānmó xìbāo zhège niánmó xìbāo tā shì fēicháng jǐnmì de liánjiē zài yīqǐ de ránhòu tā zhège bìngdú cóng zhè'er rùqīn zhīhòu ránhòu bìngdú jiù jìnrùle bèi tūnshì dàole zhège xìbāo lǐmiànle tūnshì dào xìbāo lǐmiàn wǒmen zhè jiào bāo nèi tǐ zhège bāo nèi tǐ shàngmiàn yǒu yī dàlèi zhège shòu tǐ jiù xiàng zhège FBI de zhège rén liǎn de shìbié xìtǒng yīyàng tā huì suíshí de sǎomiáo shìbié zhège xìbāo nèi rùqīn de zhège wùzhí tā yīdàn sǎomiáo chū yǒu bìngdú dí zhège kēlì zhège RNA zhèxiē dōngxī zhīhòu tā mǎshàng jiù qǐdòng yīzhǒng jiàozuò toll-like receptor zhè zhǒng jīzhì yě jiùshì móshì shìbié de zhè zhǒng xìtǒng ránhòu zhège shòu tǐ yī qǐdòng liǎo zhīhòu ne tā de xiàyóu jiù huì chǎnshēng yīgè fēicháng zhòngyào de yīgè guòchéng shénme guòchéng ne réntǐ de zhège gānrǎo sù jiùshì kàng bìngdú dí yīgè fēicháng zhòngyào de yīgè wùzhí tā jiù huì bèi héchéng érqiě huì bèi dàliàng de fēnmì chūlái wǒmen zhège shì zǐsè de zhèxiē sānjiǎoxíng de zhège jiùshì xìbāo nèi chǎnshēng de gānrǎo sù érqiě zhège gānrǎo sù huì fēnmì dào xìbāo wài wèishéme yào fēnmì dào xìbāo wài ne jiùshì yīnwèi tā yào gěi línjū de zhège línjìn de xìbāo tā bùguāng shì zìjǐ yào jìnrù yīgè bèizhàn zhuàngtài tā hái yào gàosù zhōuwéi de línjū bìngdú láile nǐ gǎnkuài nǐ yào tiáozhěng guòlái xiànzài wǒ gěi nǐ yīxiē hǎo dōngxī jiùshì zhège gānrǎo sù zhèxiē xìbāo shàngmiàn jiù yǒu yīgè gānrǎo sù de shòu tǐ tā yī jiēshōu dào gānrǎo sù shòu tǐ de xìnhào zhīhòu zhège xìbāo jiù jìnrùle yīzhǒng kàng bìngdú dí zhuàngtài jiù hǎoxiàng diànnǎo shūrù yīgè jiàn tā lǐmiàn jiù qǐdòng yī tào chéngshì yīyàng de cóng zhège bìngdú shēngmìng zhōuqí de gège huánjié lái zhìzhǐ tā bùnéng zhuǎnlù zhuǎnlù zhīhòu bù nénggòu hěn kuài jiù jiàngjiě diào ránhòu hái yìzhì bìngdú dí dànbáizhí de héchéng zuìhòu hái yìzhì tā de zǔ zhuāng zǒng'éryánzhī jiùshì ràng zhège bìngdú zài zhège xìbāo nèi méi fǎ huóle bìngdú zài méi fǎ zài lǐmiàn fùzhì tā zhǐ néng zàiwài zhōuyóuzǒu yóu zǒu dào yīdìng chéngdù de shíhòu tā jiù yào sǐwáng de érqiě huì bèi tūnshì xìbāo tūnshì diào suǒyǐ zhèyàng dehuà jiù yǒuxiào de zhìzhǐle zhège bìngdú dí shēngmìng de zhège zhōuqí lìngwài wǒmen zài kàn dào zhège xiāntiān miǎnyì xìtǒng chúle hěn zhòngyào de zhège gānrǎo sù de zhège cúnzài dehuà tā hái nénggòu qǐdòng zìrán de shāshāng xìbāo nà zìrán shāshāng xìbāo tā quèqiè de zhège qǐdòng de jīzhì rénmen qíshí dào xiànzài hái bùshì tèbié de nénggòu liàojiě dànshì zhìshǎo fāxiàn zhège zìrán shāshāng xìbāo tā yīdàn qǐdòng liǎo zhīhòu tā jiù nénggòu zìrán de bǎ zhège bèi bìngdú gǎnrǎn de xìbāo gěi tā pòhuài diào gěi tā bēng jiě diào zhèyàng dehuà bìngdú yě jiù méiyǒu yīlài cúnhuó xiàqù de zhège kōngjiānle zhè shì zìrán shāshǒu xìbāo de yīgè gōngnéng ránhòu ne qíshí rúguǒ yīgèrén de tā de xiāntiān miǎnyì lì zúgòu qiángdà dehuà kào zhège shàngpí wùlǐ píngzhàng hái yǒu zhège shàngpí niánmó xìbāo píngzhàng hái yǒu tā qízhōng dài de gānrǎo sù hé zhège zìrán shāshǒu xìbāo děng děng zhèxiē xiāntiān miǎnyì xìbāo de zhège píngzhàng dehuà shì zúgòu yǒuxiào de dǎng zhù zhège bìngdú zài jìxù shēnrù de suǒyǐ zhè jiùshì gāngcái jiǎng dào de zhège 17 gèrén tā wèishéme méiyǒu rènhé kàngtǐ de chǎnshēng méiyǒu bìngdú dí zhège jīxiàng tā jiù nénggòu bǎ bìngdú hěn kuài de hěn hǎo de gěi dǎng zài shēntǐ zhī wài de yīgè zhòngyào de yīgè yuányīn suǒyǐ zhège tiānrán miǎnyì xìtǒng zúgòu qiángdà dehuà quèshí shì fēicháng zhòngyào de kàng bìngdú dí yīgè guòchéng nà rúguǒ tiānrán miǎnyì xìtǒng tā yǒu de rén dǎng bù zhù bùshì yǒu 18 gèrén bèi gǎnrǎnle ma érqiě hái yǒu kàngtǐ de chǎnshēng nà jiùshì hòumiàn yǒu yī tào hòumiàn de jīzhì yě yào gēnzhe bèi qǐdòngle shénme jīzhì ne jiùshì wǒmen tǐnèi hái yǒu yīzhǒng jiàozuò jù shì xìbāo huòzhě shì shù tū zhuàng xìbāo wǒmen bǎ tā tǒngchēng jiàozuò kàngyuán chéngdì xìbāo tā nénggòu qǐdòng hòutiān de miǎnyì bǎ bìngdú dí kēlì gěi tā sòng dào xìbāo de zhège biǎomiàn lái wǒmen zhèlǐ huàle liǎng dào gàngzi zhè yīdào bǐfāng shuō zhè yīdào gàngzi tā jiùshì bǎ zhège bìngdú dí kēlì jiù gěi tā yībùfèn fàng dào zhège xìbāo de biǎomiàn rén de T xìbāo zhè'er lái ránhòu zhège fǔzhù T xìbāo cóng yīgè jìngzhǐ de zhuàngtài jìnrù dào yīgè qǐdòng de zhuàngtài nà qǐdòng liǎo zhīhòu tā huì yǒu gè zhǒng gè yàng de xìbāo gōngnéng de yīgè fēnhuà bǐfāng shuō zhè shì dì yī zhǒng xìbāo zhè jiào wǒmen jiàozuò TH 1 zhège TH 1 xìbāo tā qǐdòng liǎo zhīhòu tā jiù nénggòu fāhuī kàng bìngdú dí zuòyòng tā zhǔyào yěshì fēnmì yīxiē gānrǎo sù jiā mǎ hái yǒu nǐmen kàn zhè biān yěshì yǒu hěnduō de gānrǎo sù chūlái zhège gānrǎo sù fēnmì chūlái jiù huì míbǔ zhège xiāntiān miǎnyì de yīxiē bùzú ránhòu jiēzhe qù shuōmíng zánmen de miǎnyì xìtǒng gèng hǎo de qù dǐkàng zhège bìngdú dí gǎnrǎn zhè shì yīgè hěn zhòngyào de yīgè hòufāng de yīgè bǔchōng ránhòu tā hái yǒu yī dàlèi qǐ dòng jiùshì hòumiàn de zhège TH2 xìbāo zhè yī lèi xìbāo ne tā gànshénme yòng ne tā zhǔyào jiùshì wèile qǐ dòng wǒmen de réntǐ de B xìbāo B xìbāo tā shì zhǔyào shi wèile chǎnshēng kàngtǐ de huà de zhège Y zìxíng de zhè zhǒng kàngtǐ zhèxiē kàngtǐ jiù nénggòu bǎ xuè lǐ de zhège bìngdú dí kēlì gěi tā tuántuán de bāowéi zhù ránhòu zuìhòu bǎ zhège bèi zhège kàngtǐ bāoguǒ de bìngdú kēlì gěi tā gèng róngyì jiù bèi tūnshì xìbāo zhège shìbié ránhòu cóng xuè lǐtou zǔzhī lǐtou gěi tā qīngchú diào suǒyǐ zhège B xìbāo de zuòyòng yěshì zuìhòu lái fǔzhù rén tǐ zěnme qīngchú bìngdú dí suǒyǐ zhège zhè 2 gè xìbāo qǐ dàole hěn zhòngyào de fǔzhù qīngchú bìngdú dí zuòyòng lìngwài hái yǒu yī dàlèi xìbāo jiùshì zhège shāshǒu T xìbāo zhège shāshǒu T xìbāo tā de gōngnéng fēicháng xiàng zhège zìrán shāshāng xìbāo dànshì tā shì yào yīgè tèyì xìng de yī gè shìbié qǐ dòng de jīzhì de suǒyǐ zhège kàngyuán chéngdì xìbāo yě yào tōngguò mǒu zhǒng fāngshì bǎ bìngdú dí kēlì chéngdì gěi tā ránhòu tōngguò zhège kēlì chéngdì gěi tā zhīhòu bǎ tā qǐdòngle tā jiù néng tèyì xìng de qù shìbié bèi bìngdú gǎnrǎn dào de xìbāo ránhòu tōngguò zhè zhǒng fāngshì tā yě shìfàng chū yī xiē kēlì méi chuānkǒng sù jiù zhè zhǒng xiàng pàodàn yì yàng de dōngxī bǎ zhège bìngdú dí wài mó gěi tā bēng jiě diào nà bìngdú dí wài mó bēng jiě diào liǎo zhīhòu ne nà zìrán'érrán de zhège bìngdú yě jiù méiyǒu shēngcún de kōngjiānle suǒyǐ wǒmen kěyǐ kàn dào cóng tiānrán miǎnyì dào tèyì miǎnyì wǒmen de xìbāo jīběn shàng jiùshì 2 gè sīlù cóng yìqíng yǐlái dà bùfèn rén de zhòngxīn dōu shì fàng zàile hòutiān de miǎnyì xìtǒng zhè yīkuài er bǐfāng shuō yánjiū yìmiáo hái yǒu yánjiū dān kèlóng kàngtǐ kěshì wǒmen yě kàn dào zhè yībùfèn ne shì bǐjiào wǎnqí qǐ dòng de děngdào zài zhè yībùfèn qǐ zuòyòng de shíhòu yǐjīng shīqùle bǎ bìngdú xiāomiè zài qiánxiàn de zhège xiān jīle nǐ kàn suǒyǐ shuō zhège bǐjiào wǎnqí de zhège dàjiā dōu bǐjiào zài zhè fāngmiàn zuò wénzhāng ér qíshí rénmen wǎngwǎng hūshìle nàxiē bùdé bìngdú dí zhèxiē rén tāmen shì zěnme bùdé bìngdú dí bù huì bèi gǎnrǎn bìngdú dí ne qíshí tāmen de zhè ge xiāntiān de miǎnyì xìtǒng bāokuò gānrǎo sù de zhè",
        chinese: `英國公佈了新冠病毒人體挑戰試驗的結果
        這個實驗呢
        我簡單的介紹一下
        讓大家有個輪廓
        那就是英國政府疫苗特別工作組織等等的一些機構呢
        招募了36位沒有注射疫苗的年輕人
        給他們的鼻子注入新冠病毒
        讓他們感染
        可是結果就出現有意外的發現
        就是36個同樣吸入新冠病毒的健康年輕人中
        只有50%的人感染
        但是另外一半人卻沒有感染
        我們姑且不討論這個試驗的道德倫理
        這個問題
        但是這個實驗的結果讓人覺得非常的神奇
        因為另外一半人為什麼沒有感染病毒
        就算直接把病毒注射到鼻子裡面
        也沒有感染
        想請教董博士
        是的
        的確非常有意思
        你看 這一半人
        把那個病毒從他的鼻子裡注進去
        噴進去他也不會感染
        這確實是這個實驗
        發現的一個科學的資料
        一個現象
        我們大家粗一看起來好像不可思議
        其實我們想一下
        在現實世界中
        有的人就是在醫院公共場所這種
        很高病毒環境中去工作
        有的人就是不感染
        那這樣其中的原因到底是為什麼呢
        那這個研究就是為了回答人們的這個問題的
        也就是說為什麼有人
        他對這個病毒就有自然的抵抗力
        我們再回到這個實驗的設計上來看
        首先在做的過程中
        實驗設計者
        他就要確保所有的參與受試者的安全性
        那他當然選的就是一群年輕人
        年輕人免疫力一般來說都是比較好的一個狀態
        然後還有健康
        沒有什麼疾病
        這些都是嚴格篩選的一群人
        我們看看整個的這個流程
        每一個受試者
        他進來之後大概有2到3個月的篩選期
        在左邊的
        篩選的目的就是為了給他抽血化驗
        進行各方面的一個檢查
        確保他符合實驗的這個入選和排除標準
        這是一個
        然後在注入病毒的前2天
        就把這些人給送到醫院的這個特殊的
        隔離的病房裡
        因為是有一個病毒的暴露的環境嘛
        所以就是一個很特殊的負壓的一個環境
        然後呢
        從注入之後每天可以都要取這個咽喉
        還有鼻部的這個樣品的這個病毒的這個濃度
        還要抽血化驗查這個血裡的血清的抗體
        那我們再看一看這個實驗的結果
        第一類就是完全沒有感染的人
        完全沒有感染的人
        就是最右邊的這個綠色的這一類
        他們就是咽喉部的這個樣品取樣
        沒有測到任何病毒的跡象
        而血裡頭也沒有抗體產生
        所以這一類人真的是不戰而屈人之兵
        根本就不用跟你打病毒作戰
        也沒有這個抗體的痕跡
        這種人的免疫力可以說是最棒的
        他的這個身體的細胞就像一片荷葉一樣
        你把病毒灑上去也不會粘
        水灑上去也不會粘
        病毒送到鼻子裡也不會感染上
        真的是超級棒的一個免疫力
        我們這個叫做最好的免疫力狀態
        然後第二類人就是在中間的這一個
        我仔細看了一下
        其實有一個人
        他其實發生了一個無症狀的感染
        就是說他還是歸在沒有感染的這個18個裡頭
        但是咽喉部也沒有查到病毒
        但是他血裡頭有一個抗體的產生
        他沒有症狀
        所以但是因為血裡有抗體
        說明還是發生了一些免疫系統
        有一些作用在裡頭
        跟病毒有一些交鋒
        但是他沒有症狀
        說明這個交鋒是很順利的
        所以這個免疫力也是非常棒的一個狀態
        這是第2種人
        非常少
        然後再就是第三類人
        也就是左邊的這一群18個人
        他們呢就是說被感染上了
        有症狀的
        有一些輕度或者中度的症狀
        抽血的不光有抗體
        還有一個炎症
        標誌著炎症反應的一個蛋白質它升上來了
        那說明什麼呢
        說明體內有這個抗病毒的免疫反應
        而且是一個特異性的免疫反應
        有炎症因數的釋放
        有戰鬥 有硝煙 最後有損失
        但是最後的結果是很好的
        當然了
        我門在宏觀上看到症狀非常的輕微
        可是我們想一想
        免疫系統在微觀下
        也是一個很龐大的一個宇宙
        它有各種各樣的細胞
        有各種各樣的分子
        也像一個很大的世界一樣
        那麼其實也是一個戰場
        這個細胞受到病毒的侵犯
        它也可能會死亡的
        所以就像人類的戰爭一樣
        比方說最近烏克蘭
        儘管這個是很輕微的一個症狀
        但是他是要出人命的
        就是說在免疫細胞放大一看
        他也可能就是一個生命
        免疫細胞的死亡他也是有代價的
        所以我們還來回到宏觀世界
        讓大家看一看
        這剛才說到的這三類人
        我們先把這個痊癒的這兩類人放在一邊
        我們來看看被感染的這一群人
        他們一般都是咽喉部
        因為儘管病毒是從鼻子裡噴進去的
        但是是在咽喉部位
        首先2天就測到了這個病毒
        然後第5天的咽喉部位的病毒就達到了高峰
        這右邊的這個圖
        然後這個左邊的這個圖
        就是鼻子
        鼻子的這個取樣就是比咽喉部位
        他首先檢測到的病毒的時間要晚一天
        大概是第3天檢測到
        就最左邊這個病毒能檢測到的這個水準
        然後他的達峰時間呢
        也是要比咽喉部也要晚一天
        要到五六天的時候才達峰
        所以 整個的就是這麼一個情況
        然後這個藍色的這個曲線
        是一個PCR
        那這個地方我就想引申一點
        就大家可以思考一下
        比較有意思
        就是為什麼從鼻子裡打進去的病毒
        是在咽喉部位先達到高峰
        然後後面滯後一點才到鼻子裡
        測得到高峰呢
        這個其實跟病毒的特性有關係
        因為病毒
        它是一個寄生在依賴於我們人體的細胞
        才能存活下來的一個微生物
        它總是在試圖尋找一些
        比較合適的
        適合它生長的生存環境
        比方說我們人體內這個血液比較旺盛
        新陳代謝比較好
        這個比較旺盛的一些組織器官
        就是它首先要攻擊的物件
        而咽喉部位正好也是血液系統比較豐富的一個部位
        所以可能也是最容易被病毒去瞄準的一個部位
        然後但是第2點就是說
        這個事情任何事情都是有兩面性的
        你到我這個咽喉部位感染的多
        你繁殖的快
        你在我這兒繁殖的快
        但是我這邊的防禦系統也有很足夠的一個配備
        我們知道我們的咽喉
        在我們的鼻腔這個後方
        進入這個氣管
        這個肺部的一個要道
        咽喉有一個很強大的
        一個就像我們的人體的衛士一樣
        我們知道那個兩邊有2個扁桃體
        它們就是裡面有很多的淋巴細胞
        它守護著我們的門戶
        阻擋外來的病菌 細菌病毒的侵入
        所以一旦發現了一些細菌病毒的真相呢
        這個咽喉部位是首先跟它們作戰的衛士
        即使是很健康的人
        其實他咽喉部位的這個淋巴細胞
        也一直保持在一個備戰的狀態
        而且我們常常感冒的初期就是喉嚨痛
        痰多等等這些症狀
        其實 這是一個我們的黏膜的這個
        尤其是咽喉部位的這個免疫力
        它在正常發揮功能的一個好的真相
        人的免疫力如果在這兒足夠強的話
        很快就能把這個上呼吸道進來的這些病毒細菌給它擺平
        所以我們一個人
        如果說他一年到頭也不感幾次冒
        他感一次冒之後呢
        一兩天很快就過去了
        那這種人就說明他的這個機體的這個門戶的這個免疫力
        是非常好的一個狀態
        但是如果一個人他
        一感冒就是一兩個星期很難好
        而且一年到頭經常感冒
        那這就是我們機體給我們的一個信號
        就是提醒我們
        我們的免疫系統至少在咽喉部位
        這是一個代表性的一個部位
        我們一定要多加留意我們的免疫力了
        為什麼其中17個人就不感染呢
        是的
        所以其實這第三這個
        免疫力最好的這種人
        他不跟病毒發生這個衝突
        但是他又能夠把病毒完全的排除在身體之外
        我們很想要知道
        對對對
        所以 如果要想知道這個的話
        我們可能要看一看人體的免疫系統
        免疫系統是怎麼運作的
        這個運作的這個機制呢
        就是除了剛才說到的病毒從這兒皮膚這邊過來
        然後經過這一個阻擋之後呢
        我們人體其實進來了之後
        就有一道非常強大的這個粘膜細胞
        這個黏膜細胞
        它是非常緊密的連接在一起的
        然後它這個病毒從這兒入侵之後
        然後病毒就進入了
        被吞噬到了這個細胞裡面了
        吞噬到細胞裡面
        我們這叫胞內體
        這個胞內體上面有一大類這個受體
        就像這個FBI的這個人臉的識別系統一樣
        它會隨時地掃描識別這個細胞內入侵的這個物質
        它一旦掃描出有病毒的這個顆粒
        這個RNA這些東西之後
        它馬上就啟動一種叫做toll-like receptor這種機制
        也就是模式識別的這種系統
        然後這個受體一啟動了之後呢
        它的下游就會產生一個非常重要的一個過程
        什麼過程呢
        人體的這個干擾素
        就是抗病毒的一個非常重要的一個物質
        它就會被合成
        而且會被大量的分泌出來
        我們這個是紫色的這些三角形的
        這個就是細胞內產生的干擾素
        而且這個干擾素會分泌到細胞外
        為什麼要分泌到細胞外呢
        就是因為它要給鄰居的這個臨近的細胞
        它不光是自己要進入一個備戰狀態
        它還要告訴周圍的鄰居
        病毒來了
        你趕快
        你要調整過來
        現在我給你一些好東西
        就是這個干擾素
        這些細胞上面就有一個干擾素的受體
        它一接收到干擾素受體的信號之後
        這個細胞就進入了一種抗病毒的狀態
        就好像電腦輸入一個鍵
        它裡面就啟動一套程式一樣的
        從這個病毒生命週期的各個環節來制止它
        不能轉錄
        轉錄之後不能夠
        很快就降解掉
        然後還抑制病毒的蛋白質的合成
        最後還抑制它的組裝
        總而言之
        就是讓這個病毒在這個細胞內沒法活了
        病毒在沒法在裡面複製
        它只能在外周遊走
        遊走到一定程度的時候
        它就要死亡的
        而且會被吞噬細胞吞噬掉
        所以這樣的話就有效的制止了這個病毒的生命的這個週期
        另外我們在看到
        這個先天免疫系統除了很重要的這個干擾素的這個存在的話
        它還能夠啟動自然的殺傷細胞
        那自然殺傷細胞
        它確切的這個啟動的機制
        人們其實到現在還不是特別的能夠瞭解
        但是至少發現這個自然殺傷細胞
        它一旦啟動了之後
        它就能夠自然的把這個被病毒感染的細胞
        給它破壞掉
        給它崩解掉
        這樣的話
        病毒也就沒有依賴存活下去的這個空間了
        這是自然殺手細胞的一個功能
        然後呢
        其實如果一個人的
        他的先天免疫力足夠強大的話
        靠這個上皮物理屏障
        還有這個上皮黏膜細胞屏障
        還有他其中帶的干擾素和這個自然殺手細胞等等
        這些先天免疫細胞的這個屏障的話
        是足夠有效的擋住這個病毒
        再繼續深入的
        所以這就是剛才講到的這個17個人
        他為什麼沒有任何抗體的產生
        沒有病毒的這個跡象
        他就能夠把病毒很快的
        很好的給擋在身體之外的一個重要的一個原因
        所以這個天然免疫系統足夠強大的話
        確實是非常重要的抗病毒的一個過程
        那如果天然免疫系統
        他有的人擋不住
        不是有18個人被感染了嘛
        而且還有抗體的產生
        那就是後面有一套後面的機制
        也要跟著被啟動了
        什麼機制呢
        就是我們體內還有一種叫做巨噬細胞
        或者是樹突狀細胞
        我們把它統稱叫做抗原呈遞細胞
        它能夠啟動後天的免疫
        把病毒的顆粒給它送到細胞的這個表面來
        我們這裡劃了兩道杠子
        這一道 比方說這一道杠子
        它就是把這個病毒的顆粒
        就給它一部分放到這個細胞的表面
        人的T細胞這兒來
        然後這個輔助T細胞
        從一個靜止的狀態進入到一個啟動的狀態
        那啟動了之後
        它會有各種各樣的細胞功能的一個分化
        比方說這是第一種細胞
        這叫我們叫做TH 1
        這個TH 1細胞它啟動了之後
        它就能夠發揮抗病毒的作用
        它主要也是分泌一些干擾素伽馬
        還有你們看這邊也是有很多的干擾素出來
        這個干擾素分泌出來
        就會彌補這個先天免疫的一些不足
        然後接著去説明咱們的免疫系統
        更好的去抵抗這個病毒的感染
        這是一個很重要的一個後方的一個補充
        然後它還有一大類啟動
        就是後面的這個TH2細胞
        這一類細胞呢
        它幹什麼用呢
        它主要就是為了啟動我們的人體的B細胞
        B細胞它是主要是為了產生抗體的
        畫的這個Y字形的這種抗體
        這些抗體就能夠把血裡的這個病毒的顆粒
        給它團團的包圍住
        然後最後把這個被這個抗體包裹的病毒顆粒
        給它更容易就被吞噬細胞這個識別
        然後從血裡頭組織裡頭給它清除掉
        所以這個B細胞的作用
        也是最後來輔助人體怎麼清除病毒的
        所以這個這2個細胞起到了很重要的輔助清除病毒的作用
        另外還有一大類細胞
        就是這個殺手T細胞
        這個殺手T細胞
        它的功能非常像這個自然殺傷細胞
        但是它是要一個特異性的一個識別 啟動的機制的
        所以這個抗原呈遞細胞也要通過某種方式
        把病毒的顆粒呈遞給它
        然後通過這個顆粒呈遞給它之後把它啟動了
        它就能特意性的去識別
        被病毒感染到的細胞
        然後通過這種方式
        它也釋放出一些顆粒酶 穿孔素就這種
        像炮彈一樣的東西
        把這個病毒的外膜給它崩解掉
        那病毒的外膜崩解掉了之後呢
        那自然而然的
        這個病毒也就沒有生存的空間了
        所以我們可以看到
        從天然免疫到特異免疫
        我們的細胞基本上就是2個思路
        從疫情以來
        大部分人的重心
        都是放在了後天的免疫系統這一塊兒
        比方說研究疫苗
        還有研究單克隆抗體
        可是我們也看到這一部分呢
        是比較晚期啟動的
        等到在這一部分起作用的時候
        已經失去了把病毒消滅在前線的這個先機了
        你看
        所以說這個比較晚期的這個
        大家都比較在這方面做文章
        而其實人們往往忽視了那些不得病毒的這些人
        他們是怎麼不得病毒的
        不會被感染病毒的呢
        其實他們的這個先天的免疫系統
        包括干擾素的這`
    }
};

export default coronavirus;