const investing = {
    videoId: '9yQZDZr-AHs',
    transcript: {
        pinyin: "hello dàjiā hǎo huānyíng huí dào běiměi jiǔcài rìjì wǒ shì 99! Bùzhī bù jué zhōng wǒ zhège píndào cóng kāibō dào xiànzài jūrán yǐjīng yǒu liǎng nián bànle wǒ dì yī qí shìpín shì zài 2020 nián de 6 yuè fābù de rúguǒ àn niántóu suàn dehuà nà jíjiāng jìnrù de 2023 nián jiùshì wǒ zài youtube shàng fēnxiǎng tóuzī nèiróng de dì sān niánle. Shíjiān shàng shuō cháng bù cháng shuō duǎn yě bùnéng suàn tài duǎn dànshì guòqù sān nián zài gǔshì bì quān lǐ jīnglì de gè zhǒng dà dàxiǎo xiǎo de qǐfú xiànzài huítóu kàn dehuà yīnggāi shì kǔ là suān tián néng jīnglì de dōu jīnglìle 2020 nián háo wú yíwèn shì zuì fēngkuáng de yī nián gè zhǒng tóuzī biāodì gǔpiào zhàiquàn fángdìchǎn jiāmì huòbì dōu xiàng shì fāqíng de gōngniú yīyàng dà yáng zhù tǐng qǐlái zhīhòu gēnběn tíng bù xiàlái zěnme yàng qù xíngróng dāngshí de pàomò chéngdù ba wǒ jìdé yǒu cì wǒ hé yīgè zhuānyè zuò máo piào jiāoyì de péngyǒu liáo hángqíng tā hé wǒ shuō dāngshí měigǔ zài 1 měiyuán yǐxià de gǔpiào jīběn shàng yǐjīng méiyǒule shèng xià de bù chāoguò 5 zhī xiànzài huítóu kàn dehuà gè zhǒng pàomò yùjǐng qíshí yǐjīng míngxiǎn de bùnéng zài míngxiǎnle dànshì dāng nǐ shēn chǔ pàomò zhī zhōng hé pàomò gòng wǔ de shíhòu zhēn de shì yùbàbùnéng zhǐ néng shuō tānlán shǐ rén biàn dé mángmù ránhòu jiù dàole 2021 nián suànshì chǔyú niú xióng jiāojiē hángqíng pūshuòmílí de yī nián wèishéme shuō shì pūshuòmílí zài 21 nián qíshí gǔshì lǐ de gè zhǒng pàomò biāodì zài niánchū 2 yuèfèn de shíhòu yǐjīng kāishǐ zǒu xiàpōlùle zhèlǐ zhǔyàoshi zhǐ zhōngxiǎo pán kējì gǔ zuì diǎnxíng de ARKK 2 yuè dào 5 yuè zhī jiān gǔjià diē qùle 40% dànshì pūshuòmílí dì dìfāng jiù zàiyú dàpán zài 2021 yī zhěng nián de shíjiān lǐ yījiùshì wéichízhe fēng niú hángqíng 12 gè yuè de shíjiān lǐ jīhū shàngzhǎngle 30% suǒyǐ zhè jiù ràng hěnduō rénwù yǐwéi shuō niúshì hángqíng hái méi jiéshù zhōngxiǎo pán kējì gǔ zài dāngshí zhǐshì liángxìng huítiáo hái yǒuyīgè gèng jiājùle míhuò xìng dì dìfāng jiùshì zhěnggè bì quān suīrán zài 21 nián shàng bànnián yě jīnglì liǎo bù xiǎo de huí chè bǐtè bì zài dāngshí cóng 6 wàn 4 zhíjiē yāozhǎn dào 3 wàn dànshì zàixià bànnián jūrán yòu yìng qǐláile zài 11 yuè de shíhòu chuàng chūle xīngāo bǐtè bì zuìgāo chōng dàole 6 wàn 8, yǐtài fāng chōng dàoguò jiējìn 4 qiān 9 wǒ yìnxiàng zuìshēn dì dìfāng jiùshì wǒ gèrén zhànghù de zuìgāo jìlù jiùshì zài nàgè shíhòu chuàngxià de dāngshí hái tǐng zhānzhānzìxǐ juédé hēihēi suīrán gǔshì huítiáole zhème duō dànshì zìjǐ zhànghù jūrán chuàng chū xīngāole yěshì wàn wàn méi xiǎngdào yuánlái hǎo xì hái zài hòumiàn 2022 nián háo bù kuāzhāng de shuō yīnggāi shì wǒ tóuzī shēngyá lǐ xué dào dōngxī zuìduō de yī nián zhǔyào láizì liǎng gè fāngmiàn yīgè shì zìjǐ zhànghù jīnglìle jùdà de huí chè yě suànshì zhēnzhèng jiànshì dàole xióngshì de wēilì lǐnglüè dàole shénme jiào shēn bù jiàn dǐ nǐ yǐwéi dǐ yǐjīng dàole, shíjì xiàmiàn hái yǒu shíbā céng dìyù zài děngdàizhuó nǐ dì èr fāngmiàn zhǔyào yěshì yīnwèi zài qùnián de 10 yuèfèn wǒ yěshì jiārù dàole yījiā fēng tóujīgòu yě suànshì zhèngshì tà rù jīgòu tóuzī quānle suǒyǐ kěyǐ zài dì yīxiàn kàn kàn jīgòumen zài niú xióng jiāojiē de shíhòu dàodǐ shì zěnme wán de yěshì xué dào liǎo bù shǎo cóngzhōng yě bāng wǒ bì diàole hěnduō kēng shǎo zǒule yīxiē wānlù suǒyǐ wǒ háishì fēicháng gǎnjī de jīntiān zhè qī shìpín yěshì shòu dàole ōu yì OKX zhōngwén YouTube píndào de yāoqǐng chènzhe niándǐ lái liáo yī liáo zài 2022 nián de yīxiē jīng lì hé gǎnshòu tóngshí yě zhǎnwàng yīxià jíjiāng dàolái de 2023 nián de shìchǎng hángqíng xīwàng zài xióngshì lǐ gěi chuándì yīxiē zhèng néngliàng gěi zhèngzài jīnglìzhe hándōng de xiǎo huǒbànmen yīdiǎn xìnxīn hé gǔlì yīqǐ zǒuguò zhège dōngtiān OKX zhè biān yěshì fēicháng tiēxīn de gěi wǒ tíqián zhǔnbèile jǐ gè wèntí zánmen kěyǐ yī qǐlái kàn yīxià zhèngpiàn kāishǐ zhīqián yěshì lóngzhòng gǎnxiè yīxià OKX duìyú zánmen píndào chángqí yǐlái de dàlì zhīchí wǒ gèrén duìyú OKX de pǐnpái yǐjí chǎnpǐn xìnrèn dù háishì bǐjiào gāo de zài wǒmen yènèi OKX de kǒubēi yě yīzhí dōu tǐng bùcuò de nénggòu zài bùduàn tuīchénchūxīn de tóngshí yòu fēicháng zhùyì zìjǐ de fēngxiǎn bǎ kòng shǔyú wěnzhāwěndǎ nénggòu chíxù shūchū de lèixíng tuījiàn dàjiā kěyǐ qù duō liǎo jiè yīxià Okay nàme huí dào zhèngpiàn. Dì yīgè wèntí: Xuǎn sān gè cí zuòwéi 2022 nián nǐ de guānjiàn cí huì xuǎn shénme? Hmm shāo gěi wǒ jǐ fēnzhōng ràng wǒ kuàisù de lái gè tóunǎo fēngbào tóngshí lǎo guānzhòngmen kěyǐ lìyòng zhège kòngxián shíjiān gěi běn qí shìpín diǎn yīgè zàn hǎo jùshuō diǎn zàn de rén zài 2023 nián dōu néng cáiyùn hēngtōng! Okay xiǎng hǎole yǔqí shuō shì gěi 2022 niánlái sān gè guānjiàn cí wǒ juédé bùrú shuō fēnxiǎng yīxià wǒ zài 2022 nián xué dào de sān gè zuì bǎoguì de guānyú tóuzī de gǎnwù gèng yǒu jiàzhí yīxiē dì yīgè gǎnwù shì jīngguò zhè lún xióngshì ràng wǒ duì jiàzhí tóuzī zhège cí yǒule gēng shēnkè de lǐjiě nàme wǒ de lǐjiě jiùshì – gēnběn jiù méiyǒu jiàzhí tóuzī bùduì gèng quèqiè de shuōfǎ yīnggāi shì wǒ rènwéi jué dà duō shǔ de sǎnhù jiù bù yìng gāi qù zhuīqiú suǒwèi de jiàzhí tóuzī zhè huàshuō chūlái kěnéng huì ràng hěnduō péngyǒumen dū dà diēyǎnjìng yě fēicháng de zhèngzhì bù zhèngquè dànshì wǒ háishì xiǎng shuō chū wǒ zìjǐ zuì zhēnshí de xiǎngfǎ Investopedia gěi jiàzhí tóuzī de dìngyì shì – jiàzhí tóuzī shì yī zhǒng tóuzī cèlüè shèjì tiāoxuǎn jiàgé dī yú qí nèizài jiàzhí huò zhàngmiàn jiàzhí de gǔpiào tīng shàngqù hěn jiǎndān dànshì zuì zuì tricky dì dìfāng jiù zàiyú zěnme yàng qù pànduàn tā de nèizài jiàzhí xiànzài zuì zhǔliú de jiàokēshū bǎn de suàn nèizài jiàzhí de fāngfǎ jiùshì yòng xiànjīn liú zhé xiàn fǎ qù yù gū yījiā gōngsī huòzhě yīgè xiàngmù tā wèilái jǐ nián de xiànjīn liú qíngkuàng ránhòu qù suànchū tā duìyìng de jiàgé yīnggāi shì duōshǎo zhè zhǒng fāngfǎ shuō shíhuà bùnéng shuō wánquán méi yòng dànshì xiǎng yòng zhè zhǒng fāngfǎ qù zuò tóuzī zhuànqián dehuà wǒ juédé jīběn shǔyú chīrénshuōmèng shǒuxiān qízhōng shèjí de biànliàng dà dàxiǎo xiǎo jiù yǒu jǐ shí zhǒng zīchǎn fùzhài biǎoxiànjīn liú lǐ měi yīxiàng nèiróng hái yǒu wèilái de shōurù yínglì qíngkuàng shènzhì hái bāokuò zhīhòu jǐ shí nián de lìlǜ zhèxiē dōu shì yào gēnjù zìjǐ duì zhège shēngyì yǐjí hóngguān jīngjì céngmiàn de lǐjiě ránhòu biān chūlái yīgè shù zuìhòu jīyú zhèxiē biān chūlái de shù zài suànchū yīgè suǒwèi de zhēnshí jiàzhí zhè xiàng gōngzuò bùjǐn zánmen sǎnhù jiàyù bùliǎo wǒ juédé jué dà duō shǔ de jījīn jīnglǐ yěshìjiàyù bùliǎo de chúle běnshēn ménkǎn bǐjiào gāo lìngwài yīgè jiàzhí tóuzī bùshìhé sǎnhù cānyù dì dìfāng jiùshì zhè yīnggāi shì yīxiàng tèbié gūdú tèbié wúliáo de huódòng zhùyì zhèlǐ shuō de gūdú wúliáo bùshì xiàng tè sī lā zhè zhǒng gǔpiào yīyàng yǒu hěnduō haters yǐjí hěnduō kàn kōng de shēngyīn zhè bù suàn gūdú yīnwèi yǒu kàn kōng de jiù yǒu kàn duō de nǐ qǐmǎ hái kěyǐ zài wǎngshàng zhǎodào hěnduō hé nǐ kànfǎ yīzhì de rén bào tuán qǔnuǎn zhèlǐ shuō de gūdú wúliáo zhǐ de shì kěnéng zhè zhī gǔpiào yàgēn jiù méiyǒu rènhé huàtí dù méitǐ bù tǎolùn néng zhǎodào de xiāngguān bàodào yě shǎo de kělián gǔpiào chéngjiāo liàng dī gǔjià hǎojǐ nián wénsībùdòng shènzhì hái bùduàn yīn diē zhè jiù yìwèizhe nǐ shènzhì dōu zhǎo bù dào yīgè dìfāng qù yànzhèng dāngchū zuò de zhège juédìng shìfǒu zhèngquè yóuqí shì chóngcāngle de shíhòu dàjiā kěyǐ pāizhe zìjǐ de xiōngpú ránhòu chéngshí de xiǎng yīxià zhèyàng de gūdú gǎn yǒu jǐ gè sǎnhù shì kěyǐ chéngshòu dele de yǐshàng jiùshì wǒ rènwéi wèishéme jiàzhí tóuzī bùshìhé sǎnhù de zhǔyào yuányīn dāngránle gǎo bùliǎo jiàzhí tóuzī yě bù dàibiǎo shuō jiù gǎo bùliǎo tóuzīle nǐ hái kěyǐ yǒu zhème liǎng tiáo lù dì yī tiáo jiùshì xiàng jiàzhí tóuzī de dàibiǎo lǎo bā gàojiè zánmen dì nàyàng sǎnhù tóuzī zhě zuì hǎo de guīsù jiùshì mǎi dàpán jiù hǎole nǐ xiǎng xiǎng bāfēitè zhème tuīchóng jiàzhí tóuzī de rén tā wèi shà gàosù nǐ shuō mǎi dàpán ér bùshì qù zhuīqiú suǒwèi de jiàzhí tóuzī wǒ gūjìzhe zhǔyào háishì yīnwèi tài nánle, bùshì yībānrén néng jiàyù dele de dì èr tiáo lù jiùshì rúguǒ xiánqì mǎi dàpán tài wúliáo zhìfù tài màn dehuà zánmen hái kěyǐ qù gǎo yīxiē qítā tóuzī biāodì zài èr jí shìchǎng lǐ wǒ shuō de qítā tóuzī biāodì hǎotīng diǎn zánmen kěyǐ chēng wèi “chéngzhǎng gǔ” nántīng diǎn zhíjiē jiào tóujī wǒ juédé yě bùguò fèn jīngguò zhè yī nián duō xióngshì de xǐlǐ wǒ juédé chéngzhǎng gǔ tóuzī hé jiàzhí tóuzī jué dà duōshù qíngkuàng xià dōu shì bèidào'érchí de yīnwèi jiàzhí tóuzī jiǎngjiù de shì quèdìng xìng bìxū yào shi nà zhǒng jīnglìle hǎojǐ lún jīngjì shuāituì yīrán yìlì bù dǎo de bǎinián lǎo qǐ ér chéngzhǎng gǔ tóuzī jiǎngjiù de shì gāo fēngxiǎn gāo shōuyì bù quèdìng xìng shì gōngsī de zhǔyào jīdiào hěnduō gōngsī zài jīngjì shàngshēng qī kěnéng shùnfēng shùnshuǐ dànshì shuāituì yī lái néng bùnéng huó xiàqù dōu shìgè wèntí hé tán jiàzhí kě yán dāngránle zhèlǐ shuō de shì dà bùfèn de suǒ wèi de chéngzhǎng gǔ bù bāokuò wéi shǔ bù duō de yīxiē huángjīn kēng suǒyǐ yǐ wǒ xiànzài duì tóuzī de lǐjiě zánmen sǎnhù piān'ài de chéngzhǎng gǔ zài wǒ zhèlǐ gèng jiējìn yú tóujī ér fēi jiàzhí tóuzī nàme shuō qǐ tóujīle zhōngyú kěyǐ liáo dào wǒ de dì èr gè gǎnwùle zhè yīgè wèntí huídá de shíjiān hǎoxiàng yǒudiǎn zhǎng wǒ de dì èr gè gǎnwù jiùshì yīdìng yào timing the market. Āi? Méi cuò hǎoxiàng yòu shì yīgè hé zánmen jīngcháng bèi guànshū de lǐlùn yǐjí tóuzī guān wánquán xiāngfǎn de guāndiǎn wǒ zàilái shūchū yīxià wǒ de zhè tào lǐlùn shǒuxiān wǒ juédé zhǔliú jiàzhíguān lǐ de don’t try to time the market bìng bùshì shuō háo wú shì chù zhǐ bùguò shì bèi hěnduō sǎnhù tóuzī zhě qūjiěle yòng zàile cuòwù de tóuzī biāodì shàng jiéguǒ jiùshì cuò shàng jiā cuò shānghài chéng jǐhé bèi shǔ de zēngzhǎng bùyào zé shí yuè diē yuè mǎi de qiántí shì shénme? Tā de dà qiántí kěndìng shì shuō nǐ yào yòng zài 100%quèdìng tā yīdìng huì zhǎng huílái de biāodì shàng yàome nǐ shì yǒu bāfēitè nàyàng de yǎnguāng, yìlì yǐjí xuǎn gǔ nénglì yàome nǐ jiùshì mǎi dàpán zhè zhǒng biāodì zánmen shì kěyǐ yuè diē yuè mǎi de zhǐyào měiguó de guóyùn hái zài nà jiù méi wèntí dànshì zánmen sǎnhùmen xǐhuān wán de xiǎnrán gēng qīngxiàng yú chéngzhǎng gǔ huòzhě jiào tóu jī gǔ yě bāokuò bì quān zài nèi zhè lèi biāodì wǒ xiànzài de tǐhuì jiùshì yīdìng yào zé shí gòumǎi érqiě niúshì lǐ péiyǎng qǐlái de yuè diē yuè mǎi de guànxìng sīwéi yòng zài xióngshì yóuqí shì yòng zàile fēngxiǎn gāo bù quèdìng xìng dà de biāodì shàng nà zuìhòu kěnéng péi de zhā dōu bù shèngle wǒ jìyì bǐjiào shēn de jiùshì zài 21 nián niánchū de shíhòu yǒuyī zhènzi chǎo máo piào zài yóuguǎn shàng tèbié fēngmí érqiě hěnduō rén shì yǐ jiàzhí tóuzī zìjū de yǐ bùyào zé shí yào yuè diē yuè mǎi de luójí qù “tóuzī” máo piào dōu shuō yào fājué xià yīgè tè sī lā shénme de jiéguǒ zěnme yàng kě xiǎng ér zhīliǎo dāngránle wǒ zìjǐ dāngshí fēicháng tuīchóng de ARK yě bìng bùbǐ zhèxiē máo piào hǎo dào nǎ qù yīxī jìdé mùtou jiě zài ARKK 160 de shíhòu hǎn huàshuō zìjǐ de fāngfǎ shì xīn yīdài de jiàzhí tóuzī zhīhòu 5 nián kěyǐ gěi tóuzī rén tígōng nián huà 15%de huíbào xiànzài kàn zhēn de shì hēhēle wǒ duì ARK yǐjīng shì chèdǐ shīwàngle dào bù shì shuō wǒ bù rènwéi tā zhīhòu zhǎng bù huílái jùtǐ yuányīn gǎitiān dāndú chū yī qí shìpín lái tǔcáo yīxià Okay nàme zhège jiùshì wǒ jīnglìle 2022 nián xióngshì zhīhòu de yīxiē gǎnwù OKX zhè biān yěshì gěi wǒ zhǔnbèile hǎojǐ gè wèntí zhè cáigāng huídá wán dì yīgè jìndù yánzhòng delay, zánmen lái kàn yīxià dì èr gè wèntí. Dì èr gè wèntí shì:2022 Bì quān nèi nǐ yìnxiàng zuìshēn de shìqíng 2022 nián bì quān nèi yìnxiàng shēnkè de shìqíng yě tài duōle dànshì yào shuō qǐ zuìshēn de yī jiàn nà háo wú yíwèn shì FTX de bào léile yěshì wǒ rènwéi duì bì quān shānghài zuìdà de shìjiàn méiyǒu zhī yī zhīqián de Luna bào léi zài dāngshí jiù yǐwéi tǐng zhènjīng dele dànshì hé FTX shìjiàn bǐ qǐlái nà jiǎnzhí shì xiǎowū jiàn dàwūle yīnwèi wán Luna de dà bùfèn péngyǒu zhǐyào nǐ shāowéi zuòguò yīxiē diàoyán de dōu zhīdào tā shì páng shì wánfǎ 20%de nián huà wěndìng bì lìxí shōuyì nà jiùshì míngpái páng shìle suǒyǐ cānyù de réndà bùfèn dōu yīnggāi yǒu yīdìng de fēngxiǎn bǎ kòng cuòshī zuìhòu bào léile méi pǎo diào nà jiùshì yuàn dǔ fúshū dànshì FTX bù yīyàng yòng FTX de bì quān péngyǒumen hěnduō dōu shì lǎo lǎoshí shí tún bì de jiéguǒ méi xiǎngdào SBF zhège rén zhā jūrán ná yònghù de qián qù gànggǎn chǎo bìle duìyú bì quān yònghù lái shuō jiù xiāngdāng yúshì wǒ bǎ qián cún yínháng jiéguǒ yínháng nále zhèxiē qián qù chǎo máo piàole chàbùduō yīgè yìsi érqiě shēn wèi zhuāngjiā jūrán bǎ zìjǐ gěi chǎo bào cāngle yěshì fěiyísuǒsī fāshēng zhè zhǒng shìqíng yě nánguài jīgòu bāokuò pǔtōng dàzhòng dōu juédé hùn bì quān de dōu shì yīqún piànzile háo bù kuāzhāng de shuō wǒ juédé FTX shìjiàn qǐmǎ ràng zhěnggè bì quān de fǎ zhǎn dàotuìle 3-5 nián zhǔyào shi quān wàirén de jiēshòu dù shàng kǎolǜ zhèlǐ yě bù duō tánle dànshì duìyú zhěnggè bì quān de cháng qī fāzhǎn wǒ shì méiyǒu sīháo dòngyáo de. Okay dì sān gè wèntí: Rúguǒ xuǎn 2022 jiāmì quān de nián duó rénwù nǐ huì xuǎn shéi? Zhège wèntí rúguǒ yào shuō dāngxuǎn 2022 jiāmì quān de fùmiàn nián duó rénwù wǒ zhèlǐ dǎoshì yǒu yī cháng chuàn Luna de Do Kwon sān jiàn de Su Zhu dào FTX de SBF Alemeda de Caroline yī gè gè de dōu yǐjīng bèi sǐshén dài zǒule zhèngmiàn nián duó rénwù yīdìng yào xuǎn dehuà wǒ yīnggāi huì xuǎn yǐtài fāng de V shén ba dàilǐng yǐtài fāng tuánduì zài 9 yuè shùnlì wánchéngle hébìng cóng gōngzuò liàng zhèngmíng jīzhì chénggōng zhuǎn dàole quányì zhèngmíng jīzhì EIP1559 ránshāo jīzhì měitiān yě dū zài gōngzuòzhe dàfú jiàngdīle yǐtài fāng zhīhòu fāxíng liàng zài xióngshì jiāoyì liàng rúcǐ dīmí de qíngkuàng xià yīrán shì bǎ tōngzhàng lǜ wěndìng kòngzhì zài 0.01%Yǐxià rúguǒ méiyǒu hébìng hé EIP1559 wǒ rènwéi yǐtài fāng de jiàgé shì yào yuǎn yuǎn dī yú xiànzài de shì jià de mùqián zài 1200 de wèizhì yěshì fēicháng jiāntǐng jiàgé biǎo xiàn shènzhì shì yào yōu yú xióngshì lǐ zuì kàng dié de bǐtè bì bǐtè bì xiànzài de wèizhì shì yǐjīng diē pò 6 yuèfèn de wèizhìle dànshì yǐtài fāng de jiàgé bǐ liù yuèfèn zuìdī diǎn háishì yào gāo chū 30%zuǒyòu suǒyǐ wǒ de 2022 jiāmì quān de nián duó rén wù shì yào bān gěi V shén. Zuìhòu yī gè wèntí:2023 Nián duì píndào de fěnsī hé OKX de yònghùmen yǒu shé me xiǎng shuō de zhège wèntí yǔqí shuō yīxiē jītāng huòzhě shì dàjiā bǐjiào xiǎng tīng ài tīng dehuà wǒ juédé háishì jiǎndān liáo yī xià wǒ duì 23 nián hángqíng de zhǎnwàng lái de shíjì yīxiē zǒng de lái shuō wǒ duì 2023 nián de jǐnshèn tàidù yīrán shì gāo yú lèguān tàidù de yóuqí shì zài shàng bànnián lǐ shìchǎng lǐ mùqián yǒu méiyǒu hǎo xiāoxī? Yǒu de nà jiùshì míngnián tōngzhàng huì kāishǐ xiàjiàng zhè shì yī gè shìchǎng de gòngshìle suí zhī ér lái de zìrán yě jiùshì měiliánchǔ kāishǐ fàng huǎn jiā xī bùfá kěnéng zuìduō yě jiùshì yī yuèfèn sān yuèfèn gè jiā 25 gè jīdiǎn jiù chàbùduō dàotóule yě jiùshì shuō zhè lún xiàxíng zhōuqí suànshì zǒu wán yībànle nàme huài xiāoxī shì shénme ne? Huài xiāoxī jiùshì zhēnzhèng de shuāituì jíjiāng dàolái lìshǐ shàng měiliánchǔ zuìzhōng néng ruǎn zhuólù de cìshù shǎo zhī yòu shǎo duōshù qíngkuàng xià dūhuì guòdù jǐnsuō ránhòu bǎ jīngjì gǎo zá jìnrù dào shuāituì wǒ yùjì míngnián gǔshì de zhǔxuánlǜ dà gàilǜ jiùshì wéirào shīyè lǜ hé gōngsī pòchǎn zhǎnkāi de ránhòu zài dì sān jìdù měiliánchǔ yǒu kěnéng huì kāishǐ kǎolǜ jiàngxī bùguò dàng tāmen kāishǐ jiàngxī de shíhòu shìchǎng yòu huì chūxiàn xīn yī lún de kǒnghuāng wèishéme měiliánchǔ yào jiàngxīle? Shì bù shì jīngjì zhēn de bù xíng liǎo zhī lèi de kàn zhè zhāng tú yě kěyǐ fāxiàn lìshǐ shàng duōshù qíngkuàng xià gǔshì zhēnzhèng kāishǐ xiàdié wǎngwǎng shì zài měiliánchǔ kāishǐ jiàngxī de shíhòu yīnwèi zhè jiù yìwèizhe something is out of their control. Dàjiā kěyǐ zàntíng yī xià ránhòu zǐxì yánjiū yī xià zhè zhāng tú wǒ juédé háishì yǒu yīdìng de cānkǎo jiàzhí de zǒngjié qǐlái ne wǒ rènwéi míngnián cái yǒu kěnéng chéngwéi zuì hēi'àn zuì kǒngbù de yī nián But hēi'àn guòhòu límíng zǒng huì dàolái 24 nián de hángqíng wǒ rènwéi huì yǒu yīdìng de qǐsè yóuqí shì zài bì quān yě jiùshì áoguò míngnián zuìhòu yī nián ránhòu děngdào 24 nián bǐtè bì de yòu yīcì jiǎn bàn bǐtè bì jiǎn bàn jīběn shàng jiù shì bì quān nèi rèdù zuìgāo suǒyǒu rén dōu zuì zuì qídài de yīcì shìjiàn méiyǒu zhī yī tóngshí qiāzhe shíjiān diǎn suàn dehuà hé hóngguān jīngjì kāishǐ huínuǎn měiliánchǔ",
        chinese: `Hello大家好
        歡迎回到北美韭菜日記我是99！
        不知不覺中我這個頻道從開播到現在居然已經有兩年半了
        我第一期視頻是在2020年的6月發布的
        如果按年頭算的話那即將進入的2023年
        就是我在youtube上分享投資內容的第三年了。
        時間上說長不長說短也不能算太短
        但是過去三年在股市幣圈裡經歷的各種大大小小的起伏
        現在回頭看的話應該是苦辣酸甜能經歷的都經歷了
        2020年毫無疑問是最瘋狂的一年
        各種投資標的股票債券房地產加密貨幣
        都像是發情的公牛一樣大陽柱挺起來之後根本停不下來
        怎麼樣去形容當時的泡沫程度吧
        我記得有次我和一個專業做毛票交易的朋友聊行情
        他和我說當時美股在1美元以下的股票基本上已經沒有了
        剩下的不超過5支
        現在回頭看的話各種泡沫預警其實已經明顯的不能在明顯了
        但是當你身處泡沫之中和泡沫共舞的時候真的是欲罷不能
        只能說貪婪使人變得盲目
        然後就到了2021年
        算是處於牛熊交接行情撲朔迷離的一年
        為什麼說是撲朔迷離
        在21年其實股市裡的各種泡沫標的在
        年初2月份的時候已經開始走下坡路了
        這裡主要是指中小盤科技股
        最典型的ARKK 2月到5月之間股價跌去了40%
        但是撲朔迷離的地方就在於
        大盤在2021一整年的時間裡依舊是維持著瘋牛行情
        12個月的時間裡幾乎上漲了30%
        所以這就讓很多人誤以為說牛市行情還沒結束
        中小盤科技股在當時只是良性回調
        還有一個更加劇了迷惑性的地方就是
        整個幣圈雖然在21年上半年也經歷了不小的回撤
        比特幣在當時從6萬4直接腰斬到3萬
        但是在下半年居然又硬起來了
        在11月的時候創出了新高
        比特幣最高衝到了6萬8，以太坊衝到過接近4千9
        我印象最深的地方就是我個人賬戶的最高記錄就是在那個時候創下的
        當時還挺沾沾自喜覺得嘿嘿雖然股市回調了這麼多
        但是自己賬戶居然創出新高了
        也是萬萬沒想到原來好戲還在後面
        2022年毫不誇張的說應該是我投資生涯裡學到東西最多的一年
        主要來自兩個方面
        一個是自己賬戶經歷了巨大的回撤也算是真正見識到了熊市的威力
        領略到了什麼叫深不見底
        你以為底已經到了，實際下面還有十八層地獄在等待著你
        第二方面主要也是因為在去年的10月份
        我也是加入到了一家風投機構也算是正式踏入機構投資圈了
        所以可以在第一線看看機構們在牛熊交接的時候到底是怎麼玩的
        也是學到了不少
        從中也幫我避掉了很多坑少走了一些彎路
        所以我還是非常感激的
        今天這期視頻也是受到了歐易OKX中文YouTube頻道的邀請
        趁著年底來聊一聊在2022年的一些經歷和感受
        同時也展望一下即將到來的2023年的市場行情
        希望在熊市裡給傳遞一些正能量
        給正在經歷著寒冬的小伙伴們一點信心和鼓勵
        一起走過這個冬天
        OKX這邊也是非常貼心的給我提前準備了幾個問題
        咱們可以一起來看一下
        正片開始之前也是隆重感謝一下OKX對於咱們頻道長期以來的大力支持
        我個人對於OKX的品牌以及產品信任度還是比較高的
        在我們業內OKX的口碑也一直都挺不錯的
        能夠在不斷推陳出新的同時又非常注意自己的風險把控
        屬於穩紮穩打能夠持續輸出的類型
        推薦大家可以去多了解一下
        Okay那麼回到正片。
        第一個問題：選三個詞
        作為2022年你的關鍵詞會選什麼？
        Hmm稍給我幾分鐘讓我快速地來個頭腦風暴
        同時老觀眾們可以利用這個空閒時間給本期視頻點一個讚好
        據說點讚的人在2023年都能財運亨通！
        Okay想好了
        與其說是給2022年來三個關鍵詞我覺得不如說
        分享一下我在2022年學到的三個最寶貴的關於投資的感悟更有價值一些
        第一個感悟是經過這輪熊市讓我對價值投資這個詞有了更深刻的理解
        那麼我的理解就是 – 根本就沒有價值投資
        不對更確切的說法應該是
        我認為絕大多數的散戶就不應該去追求所謂的價值投資
        這話說出來可能會讓很多朋友們都大跌眼鏡也非常的政治不正確
        但是我還是想說出我自己最真實的想法
        Investopedia給價值投資的定義是 – 價值投資是一種投資策略
        設計挑選價格低於其內在價值或賬面價值的股票
        聽上去很簡單但是最最tricky的地方就在於怎麼樣去判斷他的內在價值
        現在最主流的教科書版的算內在價值的方法就是用現金流折現法
        去預估一家公司或者一個項目他未來幾年的現金流情況
        然後去算出他對應的價格應該是多少
        這種方法說實話不能說完全沒用但是想用這種方法去做投資賺錢的話
        我覺得基本屬於癡人說夢
        首先其中涉及的變量大大小小就有幾十種
        資產負債表現金流裡每一項內容
        還有未來的收入盈利情況
        甚至還包括之後幾十年的利率
        這些都是要根據自己對這個生意
        以及宏觀經濟層面的理解然後編出來一個數
        最後基於這些編出來的數再算出一個所謂的真實價值
        這項工作不僅咱們散戶駕馭不了
        我覺得絕大多數的基金經理也是駕馭不了的
        除了本身門檻比較高
        另外一個價值投資不適合散戶參與的地方
        就是這應該是一項特別孤獨特別無聊的活動
        注意這裡說的孤獨無聊不是像特斯拉這種股票一樣
        有很多haters以及很多看空的聲音
        這不算孤獨因為有看空的就有看多的你起碼
        還可以在網上找到很多和你看法一致的人報團取暖
        這裡說的孤獨無聊指的是可能這支股票壓根就沒有任何話題度
        媒體不討論能找到的相關報導也少的可憐
        股票成交量低股價好幾年紋絲不動甚至還不斷陰跌
        這就意味著你甚至都找不到一個地方去驗證當初做的這個決定是否正確
        尤其是重倉了的時候
        大家可以拍著自己的胸脯然後誠實的想一下這樣的孤獨感
        有幾個散戶是可以承受的了的
        以上就是我認為為什麼價值投資不適合散戶的主要原因
        當然了搞不了價值投資也不代表說就搞不了投資了
        你還可以有這麼兩條路
        第一條就是像價值投資的代表老巴告誡咱們的那樣
        散戶投資者最好的歸宿就是買大盤就好了
        你想想巴菲特這麼推崇價值投資的人他為啥告訴你說買大盤
        而不是去追求所謂的價值投資
        我估計著主要還是因為太難了，不是一般人能駕馭的了的
        第二條路就是如果嫌棄買大盤太無聊致富太慢的話
        咱們還可以去搞一些其他投資標的
        在二級市場裡我說的其他投資標的好聽點咱們可以稱為“成長股”
        難聽點直接叫投機我覺得也不過分
        經過這一年多熊市的洗禮
        我覺得成長股投資和價值投資絕大多數情況下都是背道而馳的
        因為價值投資講究的是確定性
        必須要是那種經歷了好幾輪經濟衰退依然屹立不倒的百年老企
        而成長股投資講究的是高風險高收益不確定性是公司的主要基調
        很多公司在經濟上升期可能順風順水但是衰退一來能不能活下去都是個問題
        何談價值可言
        當然了這裡說的是大部分的所謂的成長股不包括為數不多的一些黃金坑
        所以以我現在對投資的理解
        咱們散戶偏愛的成長股在我這裡更接近於投機而非價值投資
        那麼說起投機了
        終於可以聊到我的第二個感悟了
        這一個問題回答的時間好像有點長
        我的第二個感悟就是一定要timing the market.
        哎？沒錯
        好像又是一個和咱們經常被灌輸的理論以及投資觀完全相反的觀點
        我再來輸出一下我的這套理論
        首先我覺得主流價值觀裡的don’t try to time the market並不是說毫無是處
        只不過是被很多散戶投資者曲解了用在了錯誤的投資標的上
        結果就是錯上加錯傷害成幾何倍數的增長
        不要擇時越跌越買的前提是什麼？
        他的大前提肯定是說你要用在100%確定他一定會漲回來的標的上
        要么你是有巴菲特那樣的眼光、毅力以及選股能力
        要么你就是買大盤
        這種標的咱們是可以越跌越買的
        只要美國的國運還在那就沒問題
        但是咱們散戶們喜歡玩的顯然更傾向於成長股或者叫投機股
        也包括幣圈在內
        這類標的我現在的體會就是一定要擇時購買
        而且牛市裡培養起來的越跌越買的慣性思維
        用在熊市尤其是用在了風險高不確定性大的標的上
        那最後可能賠的渣都不剩了
        我記憶比較深的就是在21年年初的時候有一陣子炒毛票在油管上特別風靡
        而且很多人是以價值投資自居的以不要擇時要越跌越買的邏輯去“投資”毛票
        都說要發掘下一個特斯拉什麼的
        結果怎麼樣可想而知了
        當然了我自己當時非常推崇的ARK也並不比這些毛票好到哪去
        依稀記得木頭姐在ARKK 160的時候喊話說自己的方法是新一代的價值投資
        之後5年可以給投資人提供年化15%的回報
        現在看真的是呵呵了
        我對ARK已經是徹底失望了
        倒不是說我不認為他之後漲不回來
        具體原因改天單獨出一期視頻來吐槽一下
        Okay那麼這個就是我經歷了2022年熊市之後的一些感悟
        OKX這邊也是給我準備了好幾個問題這才剛回答完第一個
        進度嚴重delay，咱們來看一下第二個問題。
        第二個問題是：2022幣圈內你印象最深的事情
        2022年幣圈內印象深刻的事情也太多了
        但是要說起最深的一件
        那毫無疑問是FTX的暴雷了
        也是我認為對幣圈傷害最大的事件沒有之一
        之前的Luna暴雷在當時就以為挺震驚的了
        但是和FTX事件比起來那簡直是小巫見大巫了
        因為玩Luna的大部分朋友只要你稍微做過一些調研的都知道他是龐氏玩法
        20%的年化穩定幣利息收益那就是名牌龐氏了
        所以參與的人大部分都應該有一定的風險把控措施
        最後暴雷了沒跑掉那就是愿賭服輸
        但是FTX不一樣
        用FTX的幣圈朋友們很多都是老老實實屯幣的
        結果沒想到SBF這個人渣居然拿用戶的錢去槓桿炒幣了
        對於幣圈用戶來說就相當於是我把錢存銀行結果銀行拿了這些錢去炒毛票了
        差不多一個意思
        而且身為莊家居然把自己給炒爆倉了也是匪夷所思
        發生這種事情也難怪機構包括普通大眾都覺得混幣圈的都是一群騙子了
        毫不誇張的說我覺得FTX事件起碼讓整個幣圈的發展倒退了3-5年
        主要是圈外人的接受度上考慮這裡也不多談了
        但是對於整個幣圈的長期發展我是沒有絲毫動搖的。
        Okay第三個問題：如果選2022加密圈的年度人物你會選誰？
        這個問題如果要說當選2022加密圈的負面年度人物
        我這裡倒是有一長串
        Luna的Do Kwon
        三箭的Su Zhu到FTX的SBF
        Alemeda的Caroline
        一個個的都已經被死神帶走了
        正面年度人物一定要選的話我應該會選以太坊的V神吧
        帶領以太坊團隊在9月順利完成了合併
        從工作量證明機製成功轉到了權益證明機制
        EIP1559燃燒機制每天也都在工作著
        大幅降低了以太坊之後發行量
        在熊市交易量如此低迷的情況下依然是把通脹率穩定控制在0.01%以下
        如果沒有合併和EIP1559我認為以太坊的價格是要遠遠低於現在的市價的
        目前在1200的位置也是非常堅挺
        價格表現甚至是要優於熊市裡最抗跌的比特幣
        比特幣現在的位置是已經跌破6月份的位置了
        但是以太坊的價格比六月份最低點還是要高出30%左右
        所以我的2022加密圈的年度人物是要頒給V神。
        最後一個問題：2023年對頻道的粉絲和OKX的用戶們有什麼想說的
        這個問題與其說一些雞湯或者是大家比較想听愛聽的話
        我覺得還是簡單聊一下我對23年行情的展望來的實際一些
        總的來說我對2023年的謹慎態度依然是高於樂觀態度的
        尤其是在上半年裡
        市場裡目前有沒有好消息？有的
        那就是明年通脹會開始下降這是一個市場的共識了
        隨之而來的自然也就是美聯儲開始放緩加息步伐
        可能最多也就是一月份三月份各加25個基點就差不多到頭了
        也就是說這輪下行週期算是走完一半了
        那麼壞消息是什麼呢？
        壞消息就是真正的衰退即將到來
        歷史上美聯儲最終能軟著陸的次數少之又少
        多數情況下都會過度緊縮然後把經濟搞砸進入到衰退
        我預計明年股市的主旋律大概率就是圍繞失業率和公司破產展開的
        然後在第三季度美聯儲有可能會開始考慮降息
        不過當他們開始降息的時候市場又會出現新一輪的恐慌
        為什麼美聯儲要降息了？是不是經濟真的不行了之類的
        看這張圖也可以發現歷史上多數情況下
        股市真正開始下跌往往是在美聯儲開始降息的時候
        因為這就意味著something is out of their control.
        大家可以暫停一下然後仔細研究一下這張圖
        我覺得還是有一定的參考價值的
        總結起來呢我認為明年才有可能成為最黑暗最恐怖的一年
        But黑暗過後黎明總會到來
        24年的行情我認為會有一定的起色尤其是在幣圈
        也就是熬過明年最後一年然後等到24年比特幣的又一次減半
        比特幣減半基本上就是幣圈內熱度最高所有人都最最期待的一次事件沒有之一
        同時掐著時間點算的話和宏觀經濟開始回暖
        美聯儲`
    }
};

export default investing;