const kobyBryant = {
    videoId: 'v2fNlc7ZmQQ',
    transcript: {
        pinyin: "yīnwèi Kobe bùjǐn jǐn shì dǎ lánqiú de tā háishì yīgè qǐyè jiā, yǎnjiǎng jiā, zhéxué jiā, xīnlǐ xué jiā, jiàoyù jiā děng děng shì de, shì lánqiú ràng dàjiā rènshí Kobe dàn lánqiú zhǐshì yīgè zàitǐ wǒ hěn kěndìng de shuō,Kobe de chénggōng shì mìngzhòng zhùdìng de! Yīnwèi tā de zhè zhǒng sīwéi móshìhé jīngshén jiùsuàn tàoyòng zài rènhé yīgè lǐngyù, yě huì chéngwéi nàgè lǐngyù de zhuānjiā! Suǒyǐ, wǒ jiù huì wèn zìjǐ yīgè wèntí Kobe de jīngshén nénggòu tàoyòng zài chuàngyè hé zhuànqián shàng ma? Hěnduō xiōngdì jiěmèimen sīxià wèn wǒ shuō: Wǒ bùxiǎng zài bāng biérén dǎgōngle! Wǒ yào zìjǐ dāng lǎobǎn! Tāmen wèn wǒ yǒu shé me chuàngyè de fāngfǎ wǒ gàosù tāmen, chuàngyè de fāngfǎ hěn zhòngyào dàn qíshí yīgèrén zhēnzhèng néng chuàngyè chénggōng wǎngwǎng bùshì fāngfǎ suǒ juédìng de ér shì nàxiē yōuxiù de pǐnzhí suǒ juédìng de! Dāng yīgèrén jùbèile yōuxiù de pǐnzhí hěnduō dōngxī nǐ gēnběn bùyòng wèn wǒ dōu kěyǐ wú shī zì tōng, jiùshì suǒwèi de juéxǐng ér juéxǐng zhīqián, kào de yīdìng shì mófǎng yīnwèi mófǎng shì xuéxí de jīchǔ wǒmen wúlùn xué yóuyǒng, xué kāichē, shènzhì gāng kāishǐ xué zǒulù, yěshì kào mófǎng wǒ háo bù kuāzhāng de jiǎng, zhǐyào dàjiā bǎ zhè bù yǐngpiàn kàn dào zuìhòu nòng dǒng zhèxiē yōuxiù de pǐnzhí nǐ gēnběn bùyòng pà zhuàn bù dào qián, yě bùyòng sīkǎo zhuànqián zhè jiàn shì yīnwèi zhuànqián jiāng huì biànchéng nǐ de běnnéng nǐ zhǐ xūyào xiàng Kobe yīyàng zhǎodào yīgè zàitǐ jiùxíngle dàn kāishǐ zhīqián, wǒ háishì qiángdiào yīxià zhège píndào shì zhuānmén péiyǎng qǐyè jiā, zīběnjiā, yǒu qián rén de rúguǒ nǐ xiǎng miǎnfèi de huòdé zhè fāngmiàn de zīxùn nǐ kěyǐ kǎolǜ dìngyuè wǒ de píndào, ránhòu dǎkāi xiǎo língdāng! Wǒ zhēnxīn de zhùfú wèi zhè bù yǐngpiàn diǎn zàn de xiōngdì jiěmèimen, zǎorì dádào cáifù zìyóu! Yě xīwàng dàjiā kěyǐ wúsī de bǎ yǐngpiàn fēnxiǎng chūqù, ràng gèng duō de yǒuyuán rén huòdé zhùfú! Hǎole, huà bù duō shuō, wǒmen zhíjiē shàng qiánhuò ba! Shǒuxiān, chéng dàshì zuì zhòngyào de shì yánjiū xìjié de jīngshén qù bǎ suǒyǒu ràng nǐ chénggōng de xìjié dōu yánjiū tòuchèliǎo! Yǒu jù huà jiào chéng dàshì zhě bùjū xiǎojié zhè jù huà jiù bǎ hěnduō rén hài cǎn, ràng dà bùfèn rén dōu zhǐshì pǔtōng rén dāng nǐ shìgè càiniǎo de shíhòu nǐ jiù yào qù zhǎo yīgè ǒuxiàng, ránhòu zhíjiē mófǎng tā bǐrú Kobe de ǒuxiàng jiùshì Michael Jordan tā gāng jìn NBA de shíhòu, jiù zhíjiē mófǎng Michael Jordan de měi yīgè dòngzuò Jordan de měi yīgè zǒu wèi, měi yīgè fángshǒu, tā dōu qù yánjiū yánjiū dào lián Jordan dài qiúguò rén de shíhòu huì tǔ shétou de xiǎo xíguàn tā dōu quán dān mófǎngle dàole yǐhòu jiù biànchéngle zìjǐ de, zhè jiùshì suǒwèi qīngchūyúlán ér shèng yú lán bùzhǐ zhèyàng,Kobe hái huì bǎ suǒyǒu NBA yōuxiù xuǎnshǒu de bǐsài quánbù kàn wán bìngqiě hái mǎi lùxiàng huí jiā, yībiàn biàn de qù yánjiū yánjiū tāmen jìqiǎo, zhànshù, hái yǒu xùnliàn, měi yīyàng dōu yánjiū dào jízhì yīnwèi, tā yào chéngwéi zhèxiē rén de wáng, tā yào dǎbài tāmen! Wǒmen chuàngyè huòzhě zuò zìjǐ shìyè de shíhòu jiù yào qù zhǎo yīxiē wǒmen lǐngyù de lǐngtóu rén bǐrú wǒ zìjǐ huì yánjiū qiáobùsī, lǐjiāchéng, mǎyún, mǎhuàténg děng děng wǒ huì qù kàn tāmen de zìzhuàn, fǎngtán, hái yǒu yǎnjiǎng nǐ kàn duōle jiù huì cóng zhèxiē chénggōng qǐyè jiā shēnshang zhǎodào guīlǜ jiù xiàng wǒmen xué xiě zì yīyàng, nǐ bù qù kàn nàgè zì, nǐ yǒngyuǎn yě bù huì xiě wǒmen yào zuò dào yīgè jìngjiè, jiùshì bǎ wǒmen ǒuxiàng de shēngpíng dōu yánjiū dào tòuchè shènzhì yào bǐ tāmen gèng liǎojiě zìjǐ nǐ juédé hěn kuāzhāng ma? Hái yǒu gèng kuāzhāng de dāng Kobe bǎ zìjǐ de jìshù gǎo shànglái yǐhòu jiù qù yánjiū zài nǎge jiǎodù fànguī shì cáipàn kàn bùjiàn de qù yánjiū shénme yàng de dòngzuò huì dédào cáipàn de fáqiú jiǎndān lái shuō jiùshì yánjiū cáipàn xīnlǐ xué xīnlǐ xué shì měi gè hángyè dōu yào yánjiū de yǒulì yú wǒmen qù tán shēngyì, qù zhǎo hézuò jiùsuàn nǐ shì dǎgōng de, nǐ yě yào cāicè lǎobǎn xīnlǐmiàn zài xiǎng shénme, duì ma? Nǐ gōngzuò nénglì zài hǎo, rúguǒ bǎ nǐ lǎobǎn gěi dézuìle ér nǐ de tóngshì gēn lǎobǎn de guānxì bǐ nǐ gèng hǎo shēng zhí jiā xīn de rén yě bù huì shì nǐ a! Nà yánjiū wán xīn lǐ xué,Kobe jiù qù yánjiū lánqiú xié tā fāxiàn dāngshí suǒyǒu de lánqiú xié dōu shì gāo bāng de, jiùshì wèile bǎohù jiǎohuái nà tā jiù wèn zìjǐ wèishéme bùkěyǐ zuò chéng dī bāng de ne? Yòng dī bāng dehuà kěyǐ pǎo dé gèng kuài, tántiào gèng gāo a! Yúshì tā jiù zhǎodàole Nike gōngsī, shuō yào zuò yī kuǎn dī bāng de lánqiú xié! Nike gōngsī de fùzé rén jiù shǎyǎnle shuō bu kěnéng! Lánqiú xié cónglái dōu shì gāo bāng de! Kobe jiù wèn wèishéme yīdìng yàoshi gāo bāng a? Wǒ yě bù zhīdào, fǎnzhèng jiùshì gāo bāng! Yúshì,Kobe jiù gēn nàgè fùzé rén jiǎngle yī duī yùndòng xué, réntǐ xué tā yào yòng kēxué qù lùnzhèng wèishéme dī bāng gèng hǎo wǒmen yào gǎnxiè Kobe yīnwèi tā, shìjiè chǎnshēngle dī bāng de lánqiú xié! Tīngdào zhèlǐ, dàjiā gǎo qīngchǔ wǒ bùshì yào ràng dàjiā qù yánjiū lánqiú xié! Wǒ zhèlǐ shì péiyǎng dàjiā zhuànqián hé chuàngyè de suǒyǐ wǒ shì xīwàng dàjiā qù yánjiū rúhé chuàngzào chū nǐmen hángyè lǐmiàn zuì yōuxiù de chǎnpǐn hěnduō lǎobǎn wèn wǒ, shuō tāmen de gōngsī de chǎnpǐn hǎoxiàng dàodále píngjǐng qī yǐjīng bùnéng zài yuánběn de gōngnéng shàng zài jiāqiángle! Wǒ jiù gàosù tā, qù yánjiū chǎnpǐn bù fāngbiàn dì dìfāng, ránhòu gěi tā gěi yōuhuàle huòzhě bǎ qítā chǎnpǐn yōuxiù dì dìfāng jiārù dào zìjǐ de chǎnpǐn lǐmiàn wǒ jǔ gè lìzi, yǐqián wǒmen shì yánjiū rúhé bǎ yī bù hěn dà, hěn zhòng de diànhuà suōjiǎn dào yī bù kěyǐ fàng zài kǒudài lǐ de, fāngbiàn xiédài de shǒujī, wán de shì jiǎnfǎ yǐqián wǒmen de shǒujī zhǐyǒu dǎ diànhuà de gōngnéng hòulái jiù màn man de jiā shàngle pāizhào, tīng yīnyuè hái yǒu shàngwǎng de gōngnéng, wán de shì jiāfǎ! Nǐ tīng dǒngle ma? Wǒ zhīdào yǒu de rén jiù huì shuō dàolǐ tāmen dōu dǒng, dàn jiùshì méiyǒu shíjiān qù yánjiū zhèxiē a érqiě jiùshì bù zhīdào rúhé kāishǐ a! Zhèxiē rén rènwéi Kobe huòzhě qítā wěirén tāmen zhī suǒyǐ chénggōng, shì yǔ yùnqì hái yǒu tiānfù yǒuguān dàn zhè shì nǐ gèrén de xiǎngfǎ bàle! Bié bǎ zhǐshì zìjǐ de xiǎngfǎ dàngchéng shì shìshí! Nǐmen yǒu shìguò rènzhēn de qù fēnxī yánjiūguò měi yīgè chénggōng de qǐyè jiā huò wěirén ma? Rúguǒ nǐ yǒu dehuà, nǐ jiù huì zhǎodào tāmen de yīgè guīlǜ hé gòngtōng diǎn jiùshì tāmen dūhuì juédé zìjǐ shì hěn miǎoxiǎo de! Suǒyǐ tāmen huì bùduàn de kànshū, qù xuéxí, xīwàng néng chōngshí zìjǐ de zhīshì wǒ gàosù nǐ, dúshū, shì zhège shìjiè zuì huásuàn de shìle yīnwèi nǐ zhǐ xūyào huā diǎn qián, jiù kěyǐ bǎ zhèxiē wěirén de yīshēng jīnghuá, dōu xuéxí dào! Tíshēng zìjǐ de dì yī bù jiùshì qiānxū, ránhòu jiùshì xuéxí! Lián zhèxiē nǐ rènwéi bǐ nǐ yǒu yùnqì hé tiānfù de rén dōu qù dúshū de shíhòu nǐ hái yǒu jíkǒu tōulǎn ma? Dàn jiùsuàn nǐ shì yīgè qiānxū de rén, háishì cúnzài yīgè zuì gēnběn de wèntí jiùshì shíjiān hé wùxìng de quēfá! Wǒ zhīdào zhè shì dàjiā zuì nán kuàguò de yīdào kǎn, yóuqí shì shíjiān dāng nǐ gōngzuò wán yǐjīng hěn lèile, jiù méiyǒu xīnqíng qù xuéxíle! Wǒ shì guòláirén, suǒyǐ wǒ dǒng! Wǒ yě xiǎngdàole yīgè bànfǎ qù bāng dàjiā jiějué zhège wèntí wǒ jǔbànle yīgè sǎodì sēng cáng jīng gé dúshū huì shǒuxiān wǒ huì bāng dàjiā jiějué bù huì xuǎnshū de wèntí wǒ qīnzì wéi dàjiā tiāoxuǎnle “yībǎi běn” bùtóng lǐngyù de hǎo shū zhèxiē dōu shì céngjīng bāngzhùguò wǒ chénggōng chuàngyè hé tóuzī hái yǒu gǎibiàn wǒ mìngyùn hé sīwéi de shūjí ránhòu zài zhè yī nián nèi, yòng yīnpín de fāngshì gēn dàjiā jìnxíng shēndù chāi jiě fēnxī yīduàn yīnpín 20 fēnzhōng zuǒyòu, měi zhōu liǎng gèng ràng dàjiā lìyòng hǎo suìpiàn huà de shíjiān qù tíshēng zìjǐ! Wǒ hái huì wéi dàjiā tígōngsīwéi dǎo tú, fāngbiàn dàjiā zuò guīnà lǐjiě dāngzhōng, hánjīnliàng zuìgāo de jiùshì wǒmen de Facebook qún zǔ dàjiā jiārù dúshū huì yǐhòu jiù kěyǐ miǎnfèi de jìnrù qún zǔ hùxiāng rènshí, jìnxíng xīndé jiāoliú! Rénmài jiùshì qián mài! Wǒ huì kǎolǜ dìngqí jǔbàn yīxiē chōujiǎng huódòng huòzhě gōngkāi yīxiē wǒ zuìxīn yánjiū de zhuànqián fāngfǎ, mùdì shì bàotuán! Wǒ de mùbiāo shì yào ràng qún lǐ měi yīgè xiōngdì jiěmèi dōu néng chéngwéi shèhuì de jīngyīng! Dàjiā dōu yào kāi dé qǐ pǎochē! Zhù de qǐ háozhái! Zǔjiàn xìngfú měimǎn de jiātíng! Dàjiā zhǐyào zài zhè yī nián nèi, gēnzhe wǒmen tuánduì de jiǎobù zuò hǎo wǒ zài qún zǔ wéi dàjiā bùzhì de gōngkè jiù kěyǐ tòuguò zhīshì de lìliàng, cóng yīwúsuǒyǒu dào yī wú suǒ quē! Wèile huíkuì yīzhí zhīchí wǒ de xiōngdì zǐmèi wǒ wéi dàjiā bǔtiēle yīdiǎn qián rúguǒ dàjiā xiànzài jiārù dehuà jiù kěyǐ jiéshěng bǎi fēn zhī 80 de fèiyòng zhīhòu wǒmen kěnéng hěn kuài jiù huì zhǎng huí yuánjiàle yīnwèi yǒu tuánduì de chéngběn zài wǒ yě zhòngjīn yāoqǐngle yīxiē fēicháng zhuānyè de zhǔbō péngyǒu jìnxíng lùzhì nǐ yào zhīdào, zhīshì háishì xūyào shíjiān qù duījī chūlái de dúshū cónglái dōu shì tóuzī zìjǐ zuì hǎo de fāngshì! Rúguǒ nǐ xiǎng yào kāishǐ gǎibiàn zìjǐ de rénshēng, bǎituō pínqióng dàn yòu bù zhīdào rúhé kāishǐ nàme huānyíng nǐ jiārù wǒ de `sǎodì sēng cáng jīng gé dúshū huì' kāishǐ gǎibiàn de dì yī bù! Dàjiā xiànzài kěyǐ diǎnjī yǐngpiàn yòushàng jiǎo de liánjié huòzhě yǐngpiàn miáoshù lán shàng de liánjié, jiārù wǒ de dúshū huì ba! Qícì, shì zìlǜ de jīngshén wǒmen dāng lǎobǎn de, jīngcháng shuō yuángōng nán guǎnlǐ dàn zhège shìjiè shàng zuì nán guǎnlǐ de shì zìjǐ zhēnzhèng niú de lǐngdǎo zhě, jiùshì néng bǎ zìjǐ guǎnlǐ hǎo de rén zhè zhǒng jiùshì suǒwèi de zìlǜ jīngshén, wǒ bǎ tā fēnchéng liǎng zhǒng móshì dàn rén hé rén bù yīyàng, qiān wàn bùyào mángmù dì xué biérén dì yī tào wǒ rènwéi shì rújiā de jīngshén rúguǒ ànzhào zhè zhǒng fāngfǎ qù zuò, jiùshì jǐ zìjǐ liè yīgè shíjiān biǎo bǐrú shénme shíhòu chīfàn, shénme shíhòu shuìjiào, shénme shíhòu gōngzuò ránhòu wánquán ànzhào shíjiān biǎo jiānjué zhíxíng wǒ yǐqián dúshū kǎo dàxué de shíhòu dōu shì guīdìng zìjǐ měitiān zǎoshang 5 diǎn qǐchuáng wǒ wèishéme yào 5 diǎn qǐchuáng ne? Yīnwèi wǒ shì xué lǐjiāchéng de ér tā jiùshì rújiā sīxiǎng de zhuīsuí zhě yòng rújiā sīxiǎng qù guǎnlǐ zìjǐ, qù guǎnlǐ zìjǐ de gōngsī, suǒyǐ tā chénggōngle ér Kobe yě céng shuōguò yījù hěn jīngdiǎn dehuà nǐ zhīdào luòshānjī língchén 4 diǎn shénme yàngzi ma? Yīnwèi zhè jù huà, tā bèi chēng wèi luòshānjī língchén sì diǎn de tàiyáng yě jiùshì shuō tā cóng língchén kāishǐ xùnliàn, xíngróng tā zhège rén fēicháng zìlǜ yǒurén zhíyí zhè shì jiǎ de dàn wǒ juédé Kobe xiǎng biǎodá de zhǐshì tā zìjǐ huāle fēicháng duō shíjiān zài xùnliàn dāngshí wǒ jiùxué lǐjiāchéng hé Kobe, měitiān língchén jiù qǐlái dúshūle dàn jiānchíle hǎojǐ nián, shízài shòu bùliǎole yīnwèi měitiān dū shì hēi yǎnquān, nǎodai yě bù qīngxǐng de wǒ fāxiàn zìjǐ bìng bùshìhé zhè zhǒng fāngfǎ, nà zěnme bàn ne? Qíshí a, wǒmen bù yīdìng yào gēnsuí zìlǜ de fāngfǎ zhǐyào dádào zìlǜ de xiàoguǒ jiùxíngle qù sīkǎo zhège wèntí, wǒmen jiù yào qù liǎojiě zìlǜ de dìngyì zìlǜ jiùshì yào ràng wǒmen xīnzhōng yǒuyī bǎ chǐ nénggòu pànduàn zìjǐ zhíxíng nǎxiē xíngwéi shì zhèngquè de suǒyǐ nǐ kāi wùle ma? Zhǐyào wǒmen néng zuò dào wǒmen xīnzhōng rènwéi zhèngquè de xíngwéi wǒmen jiùshì zìlǜle! Língchén qǐlái gōngzuò hé xuéxí, jiùshì zhèngquè de shìqíng ma? Bù yīdìng wǒ rènwéi zhēnzhèng de zìlǜ jiùshì yào yǒu yīgè ràng wǒmen kěyǐ bùduàn tuījìn wǒmen chénggōng de xíguàn bàle! Yúshì wǒ cānkǎole dàojiā de sīxiǎng zhōngyú xiǎng tōngle dì èr tào guǎnlǐ zìjǐ de jīngshén dàjiā liúxīn tīng, yīnwèi tīng dǒngle, jiù dàibiǎo nǐ jìngjiè bù dī! Suǒwèi de dàojiā sīxiǎng, yīnggāi shì suíhángjiùshì méiyǒu guījǔ, dàn yòu zài guījǔ zhī zhōng shénme yìsi ne? Jiùshì xiǎng shuì jiù shuì, xiǎngqǐ jiù qǐ dàn yīqiè dōu shì wèile gōngzuò! Suǒyǐ, wǒ jiù xiǎng gōngzuò dào shénme shíhòu jiù gōngzuò dào shénme shíhòu shuì xǐngle cái qù gōngzuò, ránhòu hái qù duànliàn shēntǐ zhèyàng yī nòng, wǒ de hēi yǎnquān yě méiliǎo, wǒ de jīng shen tóu shízúle gōngzuò xiàolǜ biàn gāole, rén yě jīngshén le, shōurù gèng gāole! Suǒyǐ, dì èr tào, jiùshì gēnzhe gǎnjué lái, dàn yīqiè wèile gōngzuò jiùshì xiǎng shuì jiù shuì, shuì xǐngle jiù gōngzuò kěle jiù hē, èle jiù chī cóngxīnsuǒyù, bù yú jǔ zhè shì mǎyún, shǐyùzhù de móshì shǐyùzhù dāngnián zuò yóuxì de shēngyì, tā jiù jīngcháng tōngxiāo dádàn de wán yóuxì dàn qíshí tā shì zài gōngzuò wǒ běnrén jiùshì hé zhèyàng de móshì zuòrén, wánquán méiyǒu bìyào zuò yīgèwèi dàoshi wǒmen zhǐyào néng dádào mùbiāo, yīqiè de shǒuduàn hé biǎoxiàn xíngshì shì wúsuǒwèi de zhèlǐ wǒ sòng gěi dàjiā yì jù, nǐmen xìxīn de qù pǐn yòng zhèngquè de fāngfǎ qù zhíxíng dàn chūlái de jiéguǒ shì cuòwù de, nà yěshì cuòwù de! Xiāngfǎn, yòng cuòwù de fāngfǎ qù zhíxíng dàn chūlái de jiéguǒ shì zhèngquè de, nà yěshì zhèngquè de! Gè wèi lǎobǎn yào gēnjù zìjǐ de xīnxìng xuǎnzé yī tào móshì wán qǐlái jīngyíng qǐyè miào jiù miào zài kěyǐ biān xué biān xiǎng biān yòng miào bù kě yán, qí lè wúqióng! Zhǐyào bù wéibèi zìlǜ de yuánzé lìngwài, yào xuǎn duì yīgè chéngjiù nǐ de zàitǐ, ránhòu bǎochízhe pīnbó de jīngshén wèishéme yào zhǎodào yīgè zàitǐ ne? Hěn jiǎndān, nǐ yào gěi dà duōshù rén yīgè nǐ chénggōng de lǐyóu nǐ bùnéng shuō Kobe yīnwèi hěn qínfèn suǒyǐ chénggōng a, zhè zhǐshì yīgè yīnsù Kobe de lánqiú zhī suǒyǐ dǎ di chūsè, shì yīnwèi qínfèn zhège yīnsù dàn Kobe zhī suǒyǐ chénggōng què shì yīnwèi dǎ lánqiú chūsè de zhè jiàn shì! Suǒyǐ shǒuxiān wǒmen yào zhǎodào yīgè ràng wǒmen chénggōng de zàitǐ! Jiǎndān lái shuō jiùshì wǒmen yào xuǎndìng yīgè lǐngyù hé fāngxiàng! Dàjiā yǒu méiyǒu tīng dǒng a? Jiù hǎobǐ xīngbākè zhège qǐyè zhī suǒyǐ chénggōng shì yīnwèi tā mài kāfēi zhè jiàn shì, ér tuīdòng zhè jiā qì yè mài kāfēi chénggōng de kěnéng shì yīnwèi tā de shāngyè móshì, géjú, hái yǒu pǐnpái děng děng suǒyǐ xuǎn duì lǐngyù hé fāngxiàng, yě tóngyàng zhòngyào nà shénme yàng de zàitǐ jùyǒu qiántú ne? Rúguǒ dàjiā yǒu tóuzī gǔpiào de jīngyàn jiù huì zhīdào xiànzài gǔjià zhǎng de zuìduō de shì hùliánwǎng hángyè de gōng sī jiǎndān lái shuō jiù shì kējì gǔ yīnwèi jiānglái hěnduō shítǐ hángyè dūhuì bèi réngōng zhìnéng suǒ tìdài jièshíjiāng huì chūxiàn yī bō hángyè de dà xǐlǐ rúguǒ dàjiā xiǎng jǐnzǎo de tóurù dào hùliánwǎng hángyè wǒ jiànyì dàjiā gèngjiā yào kǎolǜ zài Youtube zhège píngtái lái chuàngyè wǒ zhīqián hěnduō yǐngpiàn dōu yǒu jiěshì dào! Nǐmen yǒu xìngqù dehuà kěyǐ qù kàn yīxià! Dàn wǒ xiǎng qiángdiào de shì YouTuber de shōurù qíshí shì hěn kěguān de dàn qiántí shì dàjiā yào zhīdào rúhé biànxiàn zhèlǐ wǒ jiù xiǎng gěi dàjiā tuījiàn wǒ cānjiāguò de xiǎochuán Youtube jīnpái yùnyíng kèchéng zhège kèchéng yě háo bù kuāzhāng de jiǎng bāng wǒ jiějuéle dà bùfèn zài Youtube shàng shíjì cāozuò de wèntí zuì zhòngyào de shì xiǎochuán zài tā de xuéyuán Facebook qún zǔ yě gěile wǒ píndào hěnduō de jiànyì! Ràng wǒ cóng duì YouTube yī wú suǒ zhī, dào xiànzài yī wú suǒ huò! Suǒyǐ wǒ bìxū bào'ēn, gěi dàjiā tuījiàn tā de kèchéng! Zhēn de tèbié hǎo! Wǒ jiànyì dàjiā diǎn jìnqù wǒ yǐngpiàn miáoshù lán shàng de liánjié lā dào zuì xiàmiàn yǒu yīgè miǎnfèi wǎngluò yántǎo huì dàjiā kěyǐ xiān tīng yīxià, shúxī yīxià xiǎochuán de jiàoyù fēnggé rúguǒ dàjiā xiànzài bàomíng cānjiā de huà, hái kěyǐ yòng dào liánjié lǐ wǒ wéi dàjiā zhēngqǔ de zuì yōuhuì jiàgé! Shì yīgè hěn dà de yōuhuì! Hǎole, xuǎn duìle zàitǐ yě bù dàibiǎo wǒmen néng chénggōng wǒmen hái xūyào zuì jīběn de pīnbó jīngshén zhǐyào dàjiā yǒu pīnbó jīngshén, hùn dé yīdìng dū bù tài chà wǒ bǎ tā xìfēn chéng nàilì, chīkǔ, guǒduàn, hái yǒu fèndòu xiān shuō dì yī gè, nàilì wǒmen hěnduō rén zuòshì yǒu bàofālì yǐjīng hěn bùcuòle yīnwèi hái néng chíxù pīnbó yī xiǎoduàn shí jiān, dànshì bùnéng chángjiǔ de pīn zhèyàng de rén zhùdìng zhǐ néng gěi biérén dǎgōng nǐ xūyào wǎng qián pǎo bù yīdìng yàoshi zhège lǐngyù lǐ pǎo dé zuì kuài de, dànshì yào pǎo dé jiǔ wǒmen kàn Kobe,37 suì cái tuìxiū érqiě tuìxiū shí hái néng yīgèrén ná xià 60 fēn dàjiā dōu zhīdào yùndòngyuán tuìxiū shì bǐjiào zǎo de yīnwèi shēntǐ chéngshòu bùliǎo yùndòngliàng, tèbié NBA zhè zhǒng gāo qiángdù de bǐsài suǒyǐ NBA de píngjūn tuìxiū niánlíng yěshì 30 suì zuǒyòu ér Kobe què zhěngzhěng wǎnle 7 nián cái tuìxiū hěnduō rén yǐwéi shì tā bǎoyǎng de hǎo, qíshí bùrán Kobe",
        chinese: `大家好，我是掃地僧
        今天很直接
        我想跟大家聊一聊一個改變我命運，讓我創業成功的人
        他就是Kobe Bryant（科比·布萊恩特）
        很多人對Kobe的印象可能是一名很出色的籃球員！
        的確，他甚至是很多NBA現役球員的偶像
        但我想問大家一個問題，當Kobe離世一週年了
        大家懷念的是Kobe的籃球技術嗎？
        不全是，其實更多的是懷念他這個人
        準確來說，是他的精神
        我告訴你，Kobe這個人如果不在籃球發展
        他也一樣會成功！為什麼？
        因為Kobe不僅僅是打籃球的
        他還是一個企業家、演講家、
        哲學家、心理學家、教育家等等
        是的，是籃球讓大家認識Kobe
        但籃球只是一個載體
        我很肯定的說，Kobe的成功是命中註定的！
        因為他的這種思維模式和精神
        就算套用在任何一個領域，也會成為那個領域的專家！
        所以，我就會問自己一個問題
        Kobe的精神能夠套用在創業和賺錢上嗎？
        很多兄弟姐妹們私下問我
        說：我不想再幫別人打工了！我要自己當老闆！
        他們問我有什麼創業的方法
        我告訴他們，創業的方法很重要
        但其實一個人真正能創業成功
        往往不是方法所決定的
        而是那些優秀的品質所決定的！
        當一個人具備了優秀的品質
        很多東西你根本不用問我
        都可以無師自通，就是所謂的覺醒
        而覺醒之前，靠的一定是模仿
        因為模仿是學習的基礎
        我們無論學游泳、學開車、
        甚至剛開始學走路，也是靠模仿
        我毫不誇張的講，只要大家把這部影片看到最後
        弄懂這些優秀的品質
        你根本不用怕賺不到錢，也不用思考賺錢這件事
        因為賺錢將會變成你的本能
        你只需要像Kobe一樣找到一個載體就行了
        但開始之前，我還是強調一下
        這個頻道是專門培養企業家、資本家、有錢人的
        如果你想免費的獲得這方面的資訊
        你可以考慮訂閱我的頻道，然後打開小鈴鐺！
        我真心的祝福為這部影片點讚的兄弟姐妹們，早日達到財富自由！
        也希望大家可以無私的把影片分享出去，讓更多的有緣人獲得祝福！
        好了，話不多說，我們直接上乾貨吧！
        首先，成大事最重要的是研究細節的精神
        去把所有讓你成功的細節都研究透徹了！
        有句話叫成大事者不拘小節
        這句話就把很多人害慘，讓大部分人都只是普通人
        當你是個菜鳥的時候
        你就要去找一個偶像，然後直接模仿他
        比如Kobe的偶像就是Michael Jordan
        他剛進NBA的時候，就直接模仿Michael Jordan的每一個動作
        Jordan的每一個走位，每一個防守，他都去研究
        研究到連Jordan帶球過人的時候會吐舌頭的小習慣
        他都全單模仿了
        到了以後就變成了自己的，這就是所謂青出於藍而勝於藍
        不止這樣，Kobe還會把所有NBA優秀選手的比賽全部看完
        並且還買錄像回家，一遍遍的去研究
        研究他們技巧、戰術、還有訓練，每一樣都研究到極致
        因為，他要成為這些人的王，他要打敗他們！
        我們創業或者做自己事業的時候
        就要去找一些我們領域的領頭人
        比如我自己會研究喬布斯，李嘉誠，馬雲，馬化騰等等
        我會去看他們的自傳，訪談，還有演講
        你看多了就會從這些成功企業家身上找到規律
        就像我們學寫字一樣，你不去看那個字，你永遠也不會寫
        我們要做到一個境界，就是把我們偶像的生平都研究到透徹
        甚至要比他們更了解自己
        你覺得很誇張嗎？還有更誇張的
        當Kobe把自己的技術搞上來以後
        就去研究在哪個角度犯規是裁判看不見的
        去研究什麼樣的動作會得到裁判的罰球
        簡單來說就是研究裁判心理學
        心理學是每個行業都要研究的
        有利於我們去談生意，去找合作
        就算你是打工的，你也要猜測老闆心裡面在想什麼，對嗎？
        你工作能力再好，如果把你老闆給得罪了
        而你的同事跟老闆的關係比你更好
        升職加薪的人也不會是你啊！
        那研究完心理學，Kobe就去研究籃球鞋
        他發現當時所有的籃球鞋都是高幫的，就是為了保護腳踝
        那他就問自己為什麼不可以做成低幫的呢？
        用低幫的話可以跑得更快、彈跳更高啊！
        於是他就找到了Nike公司，說要做一款低幫的籃球鞋！
        Nike公司的負責人就傻眼了
        說不可能！籃球鞋從來都是高幫的！
        Kobe就問為什麼一定要是高幫啊？
        我也不知道，反正就是高幫！
        於是，Kobe就跟那個負責人講了一堆運動學，人體學
        他要用科學去論證為什麼低幫更好
        我們要感謝Kobe
        因為他，世界產生了低幫的籃球鞋！
        聽到這裡，大家搞清楚
        我不是要讓大家去研究籃球鞋！
        我這裏是培養大家賺錢和創業的
        所以我是希望大家去研究
        如何創造出你們行業裡面最優秀的產品
        很多老闆問我，說他們的公司的產品好像到達了瓶頸期
        已經不能在原本的功能上再加強了！
        我就告訴他，去研究產品不方便的地方，然後給它給優化了
        或者把其他產品優秀的地方加入到自己的產品裡面
        我舉個例子，以前我們是研究如何把一部很大、很重的電話
        縮減到一部可以放在口袋裡的、方便攜帶的手機，玩的是減法
        以前我們的手機只有打電話的功能
        後來就慢慢的加上了拍照，聽音樂
        還有上網的功能，玩的是加法！
        你聽懂了嗎？我知道有的人就會說
        道理他們都懂，但就是沒有時間去研究這些啊
        而且就是不知道如何開始啊！
        這些人認為Kobe或者其他偉人
        他們之所以成功，是與運氣還有天賦有關
        但這是你個人的想法罷了！
        別把只是自己的想法當成是事實！
        你們有試過認真的去分析研究過每一個成功的企業家或偉人嗎？
        如果你有的話，你就會找到他們的一個規律和共通點
        就是他們都會覺得自己是很渺小的！
        所以他們會不斷的看書，去學習，希望能充實自己的知識
        我告訴你，讀書，是這個世界最划算的事了
        因為你只需要花點錢，就可以把這些偉人的一生精華，都學習到！
        提升自己的第一步就是謙虛，然後就是學習！
        連這些你認為比你有運氣和天賦的人都去讀書的時候
        你還有藉口偷懶嗎？
        但就算你是一個謙虛的人，還是存在一個最根本的問題
        就是時間和悟性的缺乏！
        我知道這是大家最難跨過的一道坎，尤其是時間
        當你工作完已經很累了，就沒有心情去學習了！
        我是過來人，所以我懂！
        我也想到了一個辦法去幫大家解決這個問題
        我舉辦了一個掃地僧藏經閣讀書會
        首先我會幫大家解決不會選書的問題
        我親自為大家挑選了“一百本”不同領域的好書
        這些都是曾經幫助過我成功創業和投資
        還有改變我命運和思維的書籍
        然後在這一年內，用音頻的方式跟大家進行深度拆解分析
        一段音頻20分鐘左右，每週兩更
        讓大家利用好碎片化的時間去提升自己！
        我還會為大家提供思維導圖，方便大家做歸納理解
        當中，含金量最高的就是我們的Facebook群組
        大家加入讀書會以後
        就可以免費的進入群組互相認識，進行心得交流！
        人脈就是錢脈！我會考慮定期舉辦一些抽獎活動
        或者公開一些我最新研究的賺錢方法，目的是抱團！
        我的目標是要讓群裡每一個兄弟姐妹都能成為社會的精英！
        大家都要開得起跑車！住的起豪宅！組建幸福美滿的家庭！
        大家只要在這一年內，跟著我們團隊的腳步
        做好我在群組為大家佈置的功課
        就可以透過知識的力量，從一無所有到一無所缺！
        為了回饋一直支持我的兄弟姊妹
        我為大家補貼了一點錢
        如果大家現在加入的話就可以節省百分之80的費用
        之後我們可能很快就會漲回原價了
        因為有團隊的成本在
        我也重金邀請了一些非常專業的主播朋友進行錄製
        你要知道，知識還是需要時間去堆積出來的
        讀書從來都是投資自己最好的方式！
        如果你想要開始改變自己的人生，擺脫貧窮
        但又不知道如何開始
        那麼歡迎你加入我的「掃地僧藏經閣讀書會」
        開始改變的第一步！
        大家現在可以點擊影片右上角的連結
        或者影片描述欄上的連結，加入我的讀書會吧！
        其次，是自律的精神
        我們當老闆的，經常說員工難管理
        但這個世界上最難管理的是自己
        真正牛的領導者，就是能把自己管理好的人
        這種就是所謂的自律精神，我把它分成兩種模式
        但人和人不一樣，千萬不要盲目的學別人
        第一套我認為是儒家的精神
        如果按照這種方法去做，就是給自己列一個時間表
        比如什麼時候吃飯，什麼時候睡覺，什麼時候工作
        然後完全按照時間表堅決執行
        我以前讀書考大學的時候
        都是規定自己每天早上5點起床
        我為什麼要5點起床呢？因為我是學李嘉誠的
        而他就是儒家思想的追隨者
        用儒家思想去管理自己，去管理自己的公司，所以他成功了
        而Kobe也曾說過一句很經典的話
        你知道洛杉磯凌晨4點什麼樣子嗎？
        因為這句話，他被稱為洛杉磯凌晨四點的太陽
        也就是說他從凌晨開始訓練，形容他這個人非常自律
        有人質疑這是假的
        但我覺得Kobe想表達的只是他自己花了非常多時間在訓練
        當時我就學李嘉誠和Kobe，每天凌晨就起來讀書了
        但堅持了好幾年，實在受不了了
        因為每天都是黑眼圈，腦袋也不清醒的
        我發現自己并不適合這種方法，那怎麼辦呢？
        其實啊，我們不一定要跟隨自律的方法
        只要達到自律的效果就行了
        去思考這個問題，我們就要去了解自律的定義
        自律就是要讓我們心中有一把尺
        能夠判斷自己執行哪些行為是正確的
        所以你開悟了嗎？
        只要我們能做到我們心中認為正確的行為
        我們就是自律了！
        凌晨起來工作和學習，就是正確的事情嗎？
        不一定
        我認為真正的自律
        就是要有一個讓我們可以不斷推進我們成功的習慣罷了！
        於是我參考了道家的思想
        終於想通了第二套管理自己的精神
        大家留心聽，因為聽懂了，就代表你境界不低！
        所謂的道家思想，應該是隨行就市
        沒有規矩，但又在規矩之中
        什麼意思呢？就是想睡就睡，想起就起
        但一切都是為了工作！
        所以，我就想工作到什麼時候就工作到什麼時候
        睡醒了才去工作，然後還去鍛煉身體
        這樣一弄，我的黑眼圈也沒了，我的精神頭十足了
        工作效率變高了，人也精神了，收入更高了！
        所以，第二套，就是跟著感覺來，但一切為了工作
        就是想睡就睡，睡醒了就工作
        渴了就喝，餓了就吃
        從心所欲，不踰矩
        這是馬雲、史玉柱的模式
        史玉柱當年做遊戲的生意，他就經常通宵達旦的玩遊戲
        但其實他是在工作
        我本人就適合這樣的模式
        做人，完全沒有必要做一個衛道士
        我們只要能達到目標，一切的手段和表現形式是無所謂的
        這裡我送給大家一句，你們細心的去品
        用正確的方法去執行
        但出來的結果是錯誤的，那也是錯誤的！
        相反，用錯誤的方法去執行
        但出來的結果是正確的，那也是正確的！
        各位老闆要根據自己的心性選擇一套模式玩起來
        經營企業妙就妙在可以邊學邊想邊用
        妙不可言，其樂無窮！只要不違背自律的原則
        另外，要選對一個成就你的載體，然後保持著拼搏的精神
        為什麼要找到一個載體呢？
        很簡單，你要給大多數人一個你成功的理由
        你不能說Kobe因為很勤奮所以成功啊，這只是一個因素
        Kobe的籃球之所以打的出色，是因為勤奮這個因素
        但Kobe之所以成功卻是因為打籃球出色的這件事！
        所以首先我們要找到一個讓我們成功的載體！
        簡單來說就是我們要選定一個領域和方向！
        大家有沒有聽懂啊？就好比星巴克這個企業之所以成功
        是因為他賣咖啡這件事，而推動這家企業賣咖啡成功的
        可能是因為它的商業模式，格局，還有品牌等等
        所以選對領域和方向，也同樣重要
        那什麼樣的載體具有前途呢？
        如果大家有投資股票的經驗
        就會知道現在股價漲的最多的是互聯網行業的公司
        簡單來說就是科技股
        因為將來很多實體行業都會被人工智能所替代
        屆時將會出現一波行業的大洗禮
        如果大家想儘早的投入到互聯網行業
        我建議大家更加要考慮在Youtube這個平台來創業
        我之前很多影片都有解釋到！
        你們有興趣的話可以去看一下！
        但我想強調的是
        YouTuber的收入其實是很可觀的
        但前提是大家要知道如何變現
        這裏我就想給大家推薦我參加過的小船Youtube金牌運營課程
        這個課程也毫不誇張的講
        幫我解決了大部分在Youtube上實際操作的問題
        最重要的是小船在她的學員Facebook群組
        也給了我頻道很多的建議！
        讓我從對YouTube一無所知，到現在一無所惑！
        所以我必須報恩，給大家推薦她的課程！
        真的特別好！我建議大家點進去我影片描述欄上的連結
        拉到最下面有一個免費網絡研討會
        大家可以先聽一下，熟悉一下小船的教育風格
        如果大家現在報名參加的話，還可以用到連結裡
        我為大家爭取的最優惠價格！是一個很大的優惠！
        好了，選對了載體也不代表我們能成功
        我們還需要最基本的拼搏精神
        只要大家有拼搏精神，混得一定都不太差
        我把它細分成耐力，吃苦，果斷，還有奮鬥
        先說第一個，耐力
        我們很多人做事有爆發力已經很不錯了
        因為還能持續拼搏一小段時間，但是不能長久的拼
        這樣的人注定只能給別人打工
        你需要往前跑
        不一定要是這個領域裡跑得最快的，但是要跑得久
        我們看Kobe，37歲才退休
        而且退休時還能一個人拿下60分
        大家都知道運動員退休是比較早的
        因為身體承受不了運動量，特別NBA這種高強度的比賽
        所以NBA的平均退休年齡也是30歲左右
        而Kobe卻整整晚了7年才退休
        很多人以為是他保養的好，其實不然
        Kobe因為他在場上特別的拼，所以基本上渾身都是傷
        他都是帶著傷去打每一場比賽的
        忘了告訴大家，其實Kobe還是一個人體學家
        比賽的時候手斷了，他就自己把骨頭給接了
        然後繼續比賽，因為他是有研究過的
        他知道怎麼處理是對自己最合適的
        所以，大部分人都跑不久， 他們遲早換行業
        而如果你跑得久，那麼優勢會積累下來，最終成為行業王者
        其實，跑得久不是說你在這個行業混著
        不能三天打魚（兩天曬網）
        你需要持之以恆的跑
        只要跑，早晚都會達到目標
        第二，要有吃苦精神
        做任何事情如果不付出艱辛的勞動而想做好，是不行的
        很多偉大的事情都是由單調而乏味的小事情構成的
        這個世界上，除了你的父母會無私的給予你鈔票外
        大概就只能靠自己獲取了
        說句很多人都接受不了的話
        包括你的老婆或者老公，都做不到無私的給予你鈔票
        我們要清醒的認識到這個社會現實
        所以我們要鍛煉自己的吃苦能力，因為你不吃苦不行了
        第三是果斷的精神
        果斷為什麼要提出來呢？
        因為人的一輩子都是在選擇的一輩子
        有了果斷的精神，能讓我們節約不少猶豫的時間
        我也碰到很多反复思考決定不了的事情，索性拋硬幣決定
        因為猶豫太浪費時間了
        很多事情只有在做的過程中，才能具體的了解
        在選擇上浪費很多時間，是極其劃不來的事情
        就像Kobe，很多時候都不跟教練的戰術去做
        為什麼？因為球場上的變化太多了
        當戰術不符合場上的形勢
        Kobe就要果斷的按照自己的經驗去分析每一顆球該怎麼處理
        與果斷配合起來的一個品質就是堅持
        當你選擇好了一件事情的時候，就動手去做了
        就別老是想其他的
        你必須堅持去做，只有堅持去做
        你才能在這個領域獲取更多的經驗，
        更多的資源，積累人脈，積累知識
        而如果你經常轉換，那麼是很難成長的
        深入一個行業才能挖掘到巨大的利潤
        我們選擇好了，就要準備做到別人永遠也達不到的高度
        走出別人走不出的距離
        即便是很多人說，馬上就到盡頭了，也別停下
        繼續走，走到盡頭，往往又會有新的路
        然後第四是最重要的：奮鬥
        為什麼要奮鬥？因為對於普通人來說
        只有奮鬥能改變你的生活品質，能改變命運
        人有可能靠一時間的運氣好而賺到錢
        但不可能一直運氣好
        而如果一個人有奮鬥精神
        就算在逆境中，他也會過得越來越好
        Kobe天賦不如T-Mac，身體不如LBJ
        過人也不如Iverson，扣籃不如Carter
        但他的成就卻是最高的，為什麼？
        因為奮鬥，他從進入籃球生涯就把Jordan當做他的偶像！
        並且一直朝著這個方向努力，從未間斷過！
        一步一步靠近他的偶像
        現在也成為了絕大多數NBA球星的偶像！
        我們很多創業成功的人
        實際上都把成功歸結為持續不斷的努力奮鬥
        可見這種品質是多麼的重要
        記著，30歲前獲得一個億
        跟50歲前獲得一個億，是完全兩個概念！
        希望大家有所領悟！能夠早一點培養這些優秀的品質！
        如果大家希望自己的家人孩子，伴侶，朋友等等，
        可以通過知識去改變命運，
        如果你足夠愛他們，也希望跟他們一起進步，
        就歡迎大家加入我的「掃地僧藏經閣讀書會」
        讓我們一起抱團，一起學習，一起交換心得和情報
        成為這個社會最頂尖的精英
        我的藏經閣讀書會將會是一份很好的禮物，
        讓你送給想要擺脫平凡的自己和你愛的他們
        希望我們能在讀書會的群裡相見！
        也希望大家可以成功利用YouTube這個平台來改善財富的情況
        記著！我愛大家如同愛自己！
        最後，我想借這個平台懷念一下Kobe！
        謝謝您讓我認識了籃球！謝謝您的曼巴精神改變了我的命運！
        謝謝您陪伴了我成長！也謝謝您教會了我成功！
        好了，有什麼問題可以給我留言！
        只要你們能在我今天說的內容裡面找到一兩句話是有用的
        能夠幫助自己的人生過得好一些，我就心滿意足了~
        那麼，如果你不想錯過任何關於成為富人、企業家、投資家
        達到財富自由的免費信息
        我還是呼籲你訂閱我的頻道，然後打開小鈴鐺！
        然後無私的把影片分享出去！
        我真心的祝福為這部影片點讚的兄弟姐妹們，早日達到財富自由！
        好了，我們下個禮拜再見吧，Bye~`
    }
};

export default kobyBryant;