const lucidDreaming = {
    videoId: 'u6CbubfQ3Cg',
    transcript: {
        pinyin: "hāi dàjiā hǎo wǒ shì Yuu💙 jīntiān xiǎng gēn dàjiā liáo wǒ zìshēn jīnglì qīngxǐng mèng yě jiùshì kòngzhì mèng de lìchéng fēnxiǎng zhège zhǔtí ne wǒ huì fēnchéng shàng jí gēn xià jí zài zhè yī jí zhǔyàoshi jiǎngshù yīxià wǒ liànxí qīngxǐng mèng de yīxiē fāngfǎ hái yǒu jīngyàn fēnxiǎng yǐjí wǒ xiǎng gěi duì qīngxǐng mèng yǒu xìngqù de péngyǒumen yīxiē fēicháng zhòngyào de jiànyì ér xià yī jí ne wǒ huì gēn dàjiā fēnxiǎng wǒ zuì chénggōng de qīngxǐng mèng de nèiróng ránhòu zhèxiē nèiróng wǒ shíjì shang yě yòng zài wǒ zìjǐ de yīnyuè chuàngzuò shàng wèilái zhège mèng xìliè wǒ hái huì zài zuò yīxiē bié de zhǔtí kěnéng shì yǐ fó luò yī dé (Sigmund Freud,1856-1939) de mèng de jiěxī (Die Traumdeutung) wéi zhǔ qù gēn dàjiā liáo liáo gāi zěnmó jiǎndān fēnxī zìjǐ de mèng hái yǒu yīxiē hěn diǎnxíng hěn diǎnxíng dàjiā dōu zuòguò de mèng wǒmen yīnggāi yào zěnmó qù quánshì tā suǒyǐ yào dìngyuè ō 💙 wǒ yīn wéi tiānshēng tǐzhí de guānxì suǒyǐ duì mèng yǒu yīxiē xiē de xīndé jīntiān huì cóng zìshēn de jīngyàn wéi chūfādiǎn gēn dàjiā fēnxiǎng mèng suǒyǒu rén dōu zuòguò nà shénmó jiàozuò qīngxǐng mèng ne qīngxǐng mèng (lucid dream) yòu míng qīngmíng mèng yě jiùshì shuō dāng wǒmen yìshí dào zìjǐ zhèngzài zuòmèng shí qíshí wǒmen jiù kěyǐ chāoyuè suǒyǒu wùlǐ xiànzhì suíxīn sùzào wǒmen de mèngjìng suǒyǐ nǐ kěyǐ chuānyuè qiáng kěyǐ dǎpò qiáng kěyǐ biànchéng qiáng kěyǐ... Chī diào qiáng?! Wèishémó dōu shì qiáng???? Chúle zìrán cùchéng de qīngxǐng mèng zhī wài wǎngluò shàng liúchuánzhe yīxiē fāngfǎ kěyǐ qù xùnliàn zhège qīngxǐng mèng wǒ quèshí zài liǎng sān nián qián ba lìyòng yīxiē fāngfǎ ránhòu chénggōngle dànshì xiànzài wǒ zài yě bùxiǎng yào jìnxíng zhège liànxíle wèishémó ne wǒmen lái hǎohǎo liáo liáo zhège bùfèn yǒuxiē wǒ zìjǐ qīnshēn jīnglì de bùfèn ne yǒu jǐ diǎn shì xīwàng yǒu xìngqù de péngyǒumen yě kěyǐ zhùyì dàn kěnéng wǎng lùshàng bìng bù huì gàosù nǐ zhèmó duō wǒ shì méiyǒu kàn dào la wǒ yòngle nǎxiē fāngfǎ ne wǒ xiǎng wǒ gēn dàjiā yòng de fāngfǎ yīnggāi dū dàtóngxiǎoyì yīnwèi wǒ de zīxùn láiyuán yěshì wǎngluò dàn zhè jí zhǔyào háishì fēnxiǎng wǎng lùshàng bǐjiào bù huì shuō dào de bùfèn suǒyǐ fāngfǎ wǒ jiù shāowéi tí yīxià jiù hǎo shǒuxiān nǐ xūyào zài chuáng biān zhǔnbèi bǐ hézhǐ shǒujī yě kěyǐ la zài nǐ xǐng lái hái jìdé mèng de nèiróng shí gǎnkuài gǎnkuài bǎ tā jìlù xiàlái nǐ kěyǐ yòng huà de huò shì yòng xiě de zhè kěyǐ bāngzhù nǐ jìdé gèng duō de mèng qīngxǐng mèng de qiántí jiùshì nǐ bìxūyào zhīdào shuō nǐ xiànzài zài zuòmèng suǒyǐ bāngzhù nǐ jìdé gèng duō mèng shì hěn zhòngyào de ránhòu nǐ zài mèng zhòngyào zěnmó kěyǐ qù zhījué zìjǐ zài zuòmèng ne yǒuxiē zhǐbiāo xiàng shì zài mèngzhōng de zhōngbiǎo jìngzi huòzhě shì wénzì shūjí zhèxiē dōngxī dū shì luàn de tā bù huì yǒu luójí huòzhě shì tā shì móhú de duì zhège shì wǎng lùshàng shuō de méicuò dànshì zhèxiē wǒ quánbù dōu shíyànguòle quèshí shì rúcǐ nà wǒ shì zěnmó zuò de ne shǒuxiān yào jiǎng wǒ zìjǐ zěnmó zuò zhīqián wǒ yào xiān jiǎng yīxià wǒ wèishémó huì lái liànxí zhège qīngxǐng mèng ne dāngrán yěshì yǒu yuányīn de érqiě zhè yīdiǎn fēicháng zhòngyào wǒ hòumiàn hái huì zài tí dào wǒ běnshēn shì yīgè fēicháng fēicháng duō mèng de rén zhè biān zhǐ de duō mèng qíshí shì wǒ jīhū kěyǐ zài xǐng lái zhīhòu dōu jìdé gāngcái zuò shénmó mèng yīn wéi qíshí shízhì shàng de duō mèng bìng bù cún zài wǒmen rénlèi měitiān dūhuì zuòmèng guānjiàn shì wǒmen zìjǐ xǐng lái zhīhòujì bùdé éryǐ ránhòu dāng wǒ měi cì gēn biérén shuō wǒ hěnduō mèng de shíhòu dàjiā de fǎnyìng tōngcháng dōu shì xúnwèn wǒ shì bùshì shuìmián pǐnzhí bù tài hǎo wǒ bù tài quèdìng shì bùshì zhēn de zhèyàng dànshì yīnwèi wǒ cóngxiǎo cóng wǒ yǒu jìyì yǐlái jiù zhèyàng wǒ bǐjiào qīngxiàng yú xiāngxìn zhè yīnggāi shì tiānshēng de yǒu kěnéng shì wǒ píngcháng xiǎng tài duō ránhòu dōu pǎo dào mèng lǐle wǒ dào xiànzài wǔ suì yǐqián de hěnduō mèng qíshí dōu lìlì zài mù kěnéng dàjiā yě huì yǒu zhè zhǒng jīngyàn ránhòu shènzhì yǒu hěnduō de mèng a jīhū kěyǐ shuō shì gǎibiànle wǒ zhěnggè rénshēng dāngrán wǒ de mèngzhōng bùshì zhǐyǒu hǎo de huài de yě hěnduō wǒ yě jīnglìguò jǐ cì guǐ yā chuáng tí wài huà dàjiā zhīdào yǒu bùfèn de guǐ yā chuáng qíshí shì yǒu kēxué gēnjù de ma tā qíshí jiùshì yīnwèi kěnéng yālì de yīnsù a huòzhě shì huánjìng de yīnsù a děng děng ér ràng nǐ de dànǎo yǐjīng xǐng láile dàn nǐ de shēntǐ hái méiyǒu bànfǎ xǐng lái suǒyǐ zhège duō mèng de tǐzhí yǒu shíhòu qíshí shì mán kùnrǎo de dàn jiànjiàn zhǎngdà zhīhòu wǒ yuè lái yuè kěyǐ tǐhuì dào zuòmèng de lèqù shènzhì dào hòulái dàole yīgè zǒuhuǒ rùmó dì dìbù jiùsuàn shì zuò èmèng a kěnéng dāngxià huì hàipà dànshì zuò wán èmèng zhīhòu fǎn'ér huì juédé hǎoxiàng yǒudiǎn yǒuqù wǒ kāishǐ ài shàng zuòmèng zhè jiàn shìqíng wǒ xiǎng bǎ zhège kàn sì shì quēdiǎn de bùfèn biànchéng yīgè yóuxì ma wǒ hòulái zǒule xīnlǐ dònglì xuépài zhīhòu dúle yīxiē shūjí ránhòu duì mèng chǎnshēngle gèng duō xìngqù suǒyǐ wǒ biàn kāishǐ jìnxíngle wǒ de qīngxǐng mèng duō mèng de rén xùnliàn qīngxǐng mèng shì bǐjiào róngyì de yīnwèi nǐ de kùcún bǐjiào duō yě jiù yìwèizhe bǐjiào duō de jīhuì kěyǐ ràng nǐ liànxí wǒ yěshì yī kāishǐ hěn jiǎndān de qù jìlù wǒ de mèng tā kěnéng shì hěn chǒu dehuà kěnéng shì yīduàn wén zì kěnéng shì yīxiē hái méiyǒu pīncòu wánchéng de dānzì yě kěnéng shì yǒu qǐchéngzhuǎnhé de jùqíng ránhòu zhè biān xūyào tèbié zhùyì de yīdiǎn jiùshì nǐ zuòmèng xǐng lái zhīhòu nǐ bìxūyào mǎshàng bǎ zhèxiē mèng jìlù xiàlái yīn wéi dàjiā dōu zhīdào mèng shì hěn róngyì bèi yíwàng de érqiě nǐ duì mèng de jìyì fēicháng róngyì bèi niǔqū wǒ dāngshí jiùshì yīnwèi hěn lǎn suǒyǐ méiyǒu mǎshàng jìlù xiàlái ránhòu wǒ jiù wánquán kěyǐ gǎnshòu dào zài duǎn duǎn shíjiān nèi zhège mèng de liúshī sùdù yǒu duōmó de kuài biànchéng shuō yǒu yīxiē mèng wǒ zhǐhǎo yībàn shì yòng biān de lái ràng tā wánzhěng qíshí zhèyàng yǒudiǎn kěxí yīnwèi nǐ hǎobù róngyì kěyǐ zēngjiā mèng de kùcún dànshì nǐ shuō làngfèi diàole suǒyǐ bié tōulǎn nà yī kāishǐ wǒ shì zěnmó chénggōng ne yěshì xiān cóng fāxiàn yīxiē bù hélǐ dì dìfāng ér kāishǐ jiù xiàng gānggāng tí dào de jìngzi a děng děng quánbù dōu shì rú wǎng luò suǒ shuō quándōu shì luàn de jiùshì shuō tā kěyǐ biànchéng yīgè zhǐbiāo gàosù nǐ xiànzài zhèngzài zuòmèng rúguǒ bù suàn xiānqián zìrán de qīngxǐng mèng a wǒ dì yī cì xùnliàn chénggōng a yěshì cóng fāxiàn bù zìrán de shìwù kāishǐ de wǒ shì mèng dào wǒ hǎoxiàng zài yī táichē děng yīxià wǒ kàn yīxià jìlù a wǒ de shǒujī ne??? A a zhèlǐ XD (dào nǎ qùle...) A yǒule yǒule wǒ dāngshí shì zhèyàng zi jìlù de wǒ mèng dào wǒ zài yī táichē shàng zuò zài fù jiàshǐ zuò shàng dànshì jiàshǐ zuò méiyǒu rén chēzi què hái zài pǎo yúshì wǒ biàn fāxiànle zhè shì mèng duì dàjiā kěyǐ kàn dào zhèlǐ yīnwèi wǒ fā xiàn liǎo bù hélǐ dì dìfāng wǒ jiù zhīdào shuō tā shì mèng cùchéngle qīngxǐng mèng de xíngchéng ránhòu wǒ jiù lìkè yìshí dào kěyǐ lái chángshì zuò qīngxǐng mèngle!! Yúshì ne wǒ jiù jiāng chē zǐ fēi qǐlái ránhòu wǒ chénggōngle dàn wǒ mǎshàng jiù xǐng láile wèishémó zhècì de qīngxǐng mèng huì zhèmó de duǎnzàn ne wǒ zhè biān shì zhèyàng xiě de zuò dé yuè kuāzhāng yuè xiāohào néngliàng dǎozhì wúfǎ chíjiǔ ér mǎshàng huì xǐng lái tǎnbái shuō jiùshì cāozhīguòjí nǐ yī kāishǐ zài liànxí qīngxǐng mèng de shíhòu juéduì juéduì juéduì bùkěyǐtài jí dì yī cì shíyàn chénggōng nǐ zài mèng lǐ yīdìng huì yǒudiǎn xīngfèn jiù xiàng shì wǒ yīyàng yīnwèi hěn xīngfèn suǒyǐ wǒ jiù xiǎng yào ràng chē zǐ fēi qǐlái wǒ quèshí shì chénggōngle dànshì yě yīncǐ wǒ de qíngxù dāngshí bōdòng hěn dà zhèyàng de qíngkuàng shì fēicháng róngyì xǐng lái de suǒyǐ ne wǒ yào gěi dàjiā de dì yīgè jiànyì jiùshì bié jí nǐ kěnéng huì yǒu yīzhǒng bàn qīngxǐng mèng de zhuàngtài yě jiùshì shuō nǐ zhīdào zhè shì mèngle dànshì nǐ què méiyǒu bànfǎ kòngzhì rènhé de shìwù wèishémó ne yěshì yīnwèi nǐ tài jí zhuóxiǎng yào chénggōng bù zhīdào dàjiā yǒu méiyǒu zhùyìguò nǐ zài mèng lǐ ya yuè kěwàng shénmó shìqíng tā jiù yuè huì gēn nǐ bèidào'érchí dàn nǐ yuè bùxiǎng yào shénmó dōngxī tā jiù yīdìng huì chūxiàn xiàng shì dàjiā yīnggāi dōu zài mèng lǐmiàn bèi zhuīgǎnguò zhè zhǒng qíngkuàng tōngcháng dōu shì pǎo bùdòng de nǐ yuè zhēngzhá yuè zhēngzhá bù chūlái zhè shì yīgè dìng lǜ yīnwèi nǐ kěwàng zhēngtuō suǒyǐ yù dào zhè zhǒng shìqíng qíshí bǐjiào zhòng yào de shì fàngsōng ér bùshì qù zhēngzhá huò shì táopǎo suīrán wǒ juédé hěn kùnnán la (XD) tóngyàng de nǐ yào shi tài kěwàng qīngxǐng mèng chénggōng dehuà nà jiù huì chéngwéi nǐ de zǔ'ài dì èr gè shíjī jīhū wǒ suǒyǒu chénggōng de qīngxǐng mèng dōu shì zài shénmó shíjī cùchéng de ne jiùshì wǒ yǒu jīhuì shuì wǔjiào huòzhě shì huílóng jué de shíhòu zhè tīng qǐlái yǒudiǎn qíguài dànshì huàn jù huàshuō jiùshì bǐjiào qiǎn mián de shíhòu tōngcháng wǔjiào huì bǐjiào duǎnzàn tā kěnéng bù huì jìnrù dào kuàisù dòngyǎn qī (rapid eye movement,REM) yě jiùshì REM kuàisù dòngyǎn qī jiùshì nǐ de dànǎo shì qīngxǐng de dànshì nǐ de shēntǐ zài xiūxí tōngcháng bǐjiào xǔxǔrúshēng de mèng a huòzhě jìdé bǐjiào qīngchǔ de mèng a dōu shì zài zhège shíqí chǎnshēng de dàn bìng bù dàibiǎo shuō qīngxǐng mèng jiù yīdìng dū zài zhège shíqí yīgè hǎo de shuìmián a zài yèwǎn nǐ de shēntǐ shì xū yào shù cì jìnrù zhège shíqí lái wánchéng jǐ gè shuìmián zhōuqí jíshǐ zhège shíqí mèng hěnduō dànshì yèwǎn wǒmen de shēnglǐ shì yōuxiān yú xiūxí de suǒyǐ zhège shíqí de qīngxǐng mèng bìng bù yīdìng huì róngyì hái yǒu yīgè zhuàngkuàng jiùshì rúguǒ nǐ bànyè xǐng lái ránhòu zài huíqù shuì zhège zhuàngkuàng yě mán róngyì cùchéng qīngxǐng mèng de yīnwèi nǐ xǐng lái jiùshì dǎ duàn yīgè zhōuqí yě jiùshì shuō qīngxǐng mèng qíshí bù huì zài nǐ shuì dé hěn hǎo de shíhòu fāshēng zhè jiùshì wǒ yào shuō de dì sān diǎn dì sān diǎn yěshì zhòngdiǎn jiùshì jiùshì qīngxǐng mèng de dàijià duì zhè qíshí shì zhěng bù yǐngpiàn de zhòngdiǎn wǒ xiǎng gàosù dàjiā shuō jīběn shàng nǐ xiǎng yào zuò qīngxǐng mèng tóngshí nǐ yào dédào yīgè hǎo de shuìmián shì bù tài kěnéng de qīngxǐng mèng a qíshí mán hào nǎolì de yīnwèi nǐ bìxū yào zài mèng lǐ qǔ yīgè gānggāng hǎo de pínghéng cái yǒu bànfǎ chénggōng suǒyǐ yǒuxiē qīngxǐng mèng kàn shàngqù hěn zìyóu dàn tā qízhōng shì fēicháng de xiǎoxīn jǐnshèn de xiàng shì wǒ dì yī diǎn suǒ shuō nǐ bùnéng cāozhīguòjí yào bùrán jiùshì róngyì shībài rúguǒ nǐ běnshēn shuìmián pǐnzhí bù hǎo huòzhě shì shuìmián bùgòu wǒ qíshí bìng bù jiànyì nǐ qù zuò zhège chángshì nǐ kěnéng huì yīnwèi méiyǒu shìdàng de xiūxí éryǐngxiǎng dào nǐ báitiān de gōngzuò gēn huódòng wǒmen de shēntǐ shì huì zìwǒ tiáojié de dāng nǐ yèwǎn méiyǒu dédào chōngfèn de xiūxí tā huì zài nǐ báitiān qù bǔcháng zònghé yǐshàng jǐ diǎn wǒ wèishémó qiánmiàn yào qiángdiào wǒ zuò qīngxǐng mèng de yuányīn yě jiùshì yīnwèi wǒ gānggāng tí dào wǒ běnshēn jiù duō mèngle wǒ běnlái jiù huì jìlù yī xiē duì wǒ lái shuō tèbié yǒu gǎnjué de mèng ránhòu rúguǒ tiáojiàn yǔnxǔ dehuà wǒ kě néng jiàrì yǒu shíjiān cái huì jìnxíng zhège liànxí jiā shàng wǒ yě xiǎng yòng zhège fāngshì lái tànjiù zìjǐ de mèng rúguǒ nǐ běnshēn yě duō mèng ránhòu zhēn de xiǎng qù shì shìkàn de huà wǒ jiànyì zài jiàrì de shíjiān kěyǐ shuì huílóng jué hé wǔjiào de shíhòu jiàrì ó wǒ huì qù chángshì yěshì wǒ pínggūguò zìjǐ de zhuàngkuàng dàn dāng wǒ hěn lèi de shíhòu wǒ dāngrán shì shuìmián hé xiūxí yōuxiān a zài lái wǒ kě néng yǐqián yǒuxiē chuàngzuò de xū yào zhège shì xià jí de nèiróng chángshì zuò qīngxǐng mèng shì wǒ dàxué de shíhòu ránhòu xiànzài niánjì yuè lái yuè dà wǒ de shuìmián pǐnzhí kāishǐ yuè lái yuè chà liǎo zhī hòu wǒ jiù dōu méiyǒu zài shíyànle jiùshì ràng tā zìrán fāshēng ér yǐ suíyuán yīzhí dào xiànzài wǒ háishì yǒu jìlù mèng de xíguàn yǒu shíhòu shāowéi zì cí xiūshì yīxià tā huì biànchéng yī gè fēicháng dúyīwú'èr de gùshì bìngqiě ne kě yǐ gēn wǒ dāngshí de xīnjìng zuò jiéhé nà jīntiān de nèiróng jiù dào zhè biānle fēicháng xièxiè dàjiā de guānkàn nà yǒu xìngqù de péngyǒu zài bāng wǒ àn zàn liúyán ránhòu yào jìdé dìngyuè bìng kāiqǐ xiǎo língdāng ó nà wǒmen xià zhōu wǔ zàijiàn la ? Nà wǒmen xià zhōu wǔ zàijiàn la bàibài 💙 (bié zǒu bié zǒu ~hòumiàn hái yǒu) jǐngchá!! Yǒu biàntài!!",
        chinese: `嗨
        大家好
        我是Yuu💙
        今天想跟大家聊
        我自身經歷清醒夢
        也就是控制夢的歷程分享
        這個主題呢
        我會分成上集跟下集
        在這一集
        主要是講述一下我練習清醒夢的一些方法
        還有經驗分享
        以及我想給對清醒夢有興趣的朋友們一些非常重要的建議
        而下一集呢
        我會跟大家分享我最成功的清醒夢的內容
        然後這些內容我實際上
        也用在我自己的音樂創作上
        未來這個夢系列我還會再做一些別的主題
        可能是以佛洛伊德（Sigmund Freud，1856-1939）
        的夢的解析（Die Traumdeutung）為主
        去跟大家聊聊
        該怎麽簡單分析自己的夢
        還有一些很典型很典型
        大家都做過的夢
        我們應該要怎麽去詮釋它
        所以要訂閱喔💙
        我因為天生體質的關系
        所以對夢有一些些的心得
        今天會從自身的經驗為出發點
        跟大家分享
        夢所有人都做過
        那什麽叫做清醒夢呢
        清醒夢（lucid dream）又名清明夢
        也就是說
        當我們意識到自己正在做夢時
        其實我們就可以超越所有物理限制
        隨心塑造我們的夢境
        所以你可以穿越墻
        可以打破墻
        可以變成牆
        可以...
        吃掉牆?!
        為什麽都是牆？？？？
        除了自然促成的清醒夢之外
        網絡上流傳著一些方法
        可以去訓練
        這個清醒夢
        我確實在兩三年前吧
        利用一些方法
        然後成功了
        但是現在我再也不想要進行這個練習了
        為什麽呢
        我們來好好聊聊這個部分
        有些我自己親身經歷的部分呢
        有幾點是希望有興趣的朋友們也可以注意
        但可能網路上
        並不會告訴你這麽多
        我是沒有看到啦
        我用了哪些方法呢
        我想我跟大家用的方法應該都大同小異
        因為我的資訊來源也是網絡
        但這集主要還是分享網路上比較不會說到的部分
        所以方法我就稍微提一下就好
        首先
        你需要在床邊準備筆和紙
        手機也可以啦
        在你醒來還記得夢的內容時
        趕快趕快把它記錄下來
        你可以用畫的
        或是用寫的
        這可以幫助你記得更多的夢
        清醒夢的前提就是
        你必須要知道說你現在在做夢
        所以幫助你記得更多夢是很重要的
        然後你在夢中要怎麽可以去知覺自己在做夢呢
        有些指標
        像是在夢中的鐘錶
        鏡子
        或者是文字書籍
        這些東西都是亂的
        它不會有邏輯
        或者是它是模糊的
        對這個是網路上說的沒錯
        但是這些我全部都實驗過了
        確實是如此
        那我是怎麽做的呢
        首先要講我自己怎麽做之前
        我要先講一下我為什麽會來練習這個清醒夢呢
        當然也是有原因的
        而且這一點非常重要
        我後面還會再提到
        我本身是一個非常非常多夢的人
        這邊指的多夢
        其實是我幾乎可以在醒來之後
        都記得剛才做什麽夢
        因為其實實質上的多夢並不存在
        我們人類每天都會做夢
        關鍵是我們自己醒來之後記不得而已
        然後當我每次跟別人說我很多夢的時候
        大家的反應通常都是詢問我
        是不是睡眠品質不太好
        我不太確定
        是不是真的這樣
        但是因為我從小從我有記憶以來就這樣
        我比較傾向於相信這應該是天生的
        有可能是我平常想太多
        然後都跑到夢裡了
        我到現在五歲以前的很多夢其實都歷歷在目
        可能大家也會有這種經驗
        然後甚至有很多的夢啊
        幾乎可以說是改變了我整個人生
        當然我的夢中不是只有好的
        壞的也很多
        我也經歷過幾次鬼壓床
        題外話
        大家知道有部分的鬼壓床
        其實是有科學根據的嗎
        它其實就是因為可能壓力的因素啊
        或者是環境的因素啊等等
        而讓你的大腦已經醒來了
        但你的身體還沒有辦法醒來
        所以這個多夢的體質有時候其實是蠻困擾的
        但漸漸長大之後
        我越來越可以體會到做夢的樂趣
        甚至到後來到了一個走火入魔的地步
        就算是做噩夢啊
        可能當下 會害怕
        但是做完噩夢之後
        反而會覺得好像有點有趣
        我開始愛上做夢這件事情
        我想把這個看似是缺點的部分
        變成一個遊戲嗎
        我後來走了心理動力學派之後
        讀了一些書籍
        然後對夢產生了更多興趣
        所以我便開始進行了我的清醒夢
        多夢的人訓練清醒夢
        是比較容易的
        因為你的庫存比較多
        也就意味著比較多的機會
        可以讓你練習
        我也是一開始很簡單地 去記錄我的夢
        它可能是很醜的畫
        可能是一段文字
        可能是一些還沒有拼湊完成的單字
        也可能是有起承轉合的劇情
        然後這邊需要特別注意的一點就是
        你做夢醒來之後
        你必須要馬上把這些夢記錄下來
        因為大家都知道夢是很容易被遺忘的
        而且你對夢的記憶非常容易被扭曲
        我當時就是因為很懶
        所以沒有馬上記錄下來
        然後我就完全可以感受到
        在短短時間內
        這個夢的流失速度有多麽地快
        變成說有一些夢
        我只好一半是用編的來讓它完整
        其實這樣有點可惜
        因為你好不容易可以增加夢的庫存
        但是你說浪費掉了
        所以
        別偷懶
        那一開始
        我是怎麽成功呢
        也是先從發現一些不合理的地方而開始
        就像剛剛提到的鏡子啊等等
        全部都是如網絡所說
        全都是亂的
        就是說它可以變成一個指標
        告訴你現在正在做夢
        如果不算先前自然的清醒夢啊
        我第一次訓練成功啊
        也是從發現不自然的事物開始的
        我是夢到我好像在一台車
        等一下我看一下記錄
        啊我的手機呢？？？
        啊啊這裡XD
        （到哪去了...）
        啊有了有了我當時是這樣子
        紀錄的
        我夢到 我在一台車上
        坐在副駕駛座上
        但是 駕駛座沒有人
        車子卻還在跑
        於是 我便發現了
        這是夢
        對大家可以看到這裡
        因為我發現了不合理的地方
        我就知道說它是夢
        促成了清醒夢的形成
        然後我就立刻意識到
        可以來嘗試做清醒夢了！！
        於是呢
        我就將車子飛起來
        然後我成功了
        但我馬上就醒來了
        為什麽這次的清醒夢會這麽的短暫呢
        我這邊是這樣寫的
        做得越誇張
        越消耗能量
        導致無法持久
        而馬上會醒來
        坦白說
        就是操之過急
        你一開始在練習清醒夢的時候
        絕對絕對絕對
        不可以太急
        第一次實驗成功
        你在夢裡一定會有點興奮
        就像是我一樣因為很興奮
        所以我就想要讓車子飛起來
        我確實是成功了
        但是也因此我的情緒當時波動很大
        這樣的情況是非常容易醒來的
        所以呢
        我要給大家的
        第一個建議就是
        別急
        你可能會有一種半清醒夢的狀態
        也就是說你知道這是夢了
        但是你卻沒有辦法控制任何的事物
        為什麽呢
        也是因為你太急著想要成功
        不知道大家有沒有注意過
        你在夢裡呀
        越渴望 什麽事情
        它就越會跟你 背道而馳
        但你 越不想要什麽東西
        它就一定會出現
        像是大家應該都在夢裡面被追趕過
        這種情況通常都是跑不動的
        你越掙扎
        越掙扎不出來
        這是一個定律
        因為你渴望掙脫
        所以遇到這種事情
        其實比較重要的
        是放鬆
        而不是去掙扎或是逃跑
        雖然我覺得
        很困難啦（XD）
        同樣的你要是太渴望清醒夢成功的話
        那就會成為你的阻礙
        第二個
        時機
        幾乎我所有成功的清醒夢 都是在什麽時機促成的呢
        就是我有機會睡午覺 或者是回籠覺的時候
        這聽起來有點奇怪
        但是換句話說就是比較淺眠的時候
        通常午覺會比較短暫
        它可能不會進入到快速動眼期（rapid eye movement，REM）
        也就是REM
        快速動眼期就是你的大腦是清醒的
        但是你的身體在休息
        通常比較栩栩如生的夢啊
        或者記得比較清楚的夢啊
        都是在這個時期產生的
        但並不代表說清醒夢就一定都在這個時期
        一個好的睡眠啊
        在夜晚
        你的身體是需要數次進入這個時期
        來完成幾個睡眠周期
        即使這個時期夢很多
        但是夜晚我們的生理是優先於休息的
        所以這個時期的清醒夢並不一定會容易
        還有一個狀況就是
        如果你半夜醒來
        然後再回去睡
        這個狀況也蠻容易促成清醒夢的
        因為你醒來就是打斷一個周期
        也就是說清醒夢
        其實不會在你睡得很好的時候發生
        這就是我要說的第三點
        第三點也是重點就是
        就是清醒夢的代價
        對這其實是整部影片的重點
        我想告訴大家說
        基本上 你想要做清醒夢
        同時你要得到 一個好的睡眠
        是不太可能的
        清醒夢啊
        其實蠻耗腦力的
        因為你必須要在夢裡 取一個剛剛好的平衡才有辦法成功
        所以有些清醒夢
        看上去很自由
        但它其中是非常的小心謹慎的
        像是我第一點所說
        你不能操之過急
        要不然就是容易失敗
        如果你本身睡眠品質不好
        或者是睡眠不夠
        我其實並不建議你去做這個嘗試
        你可能會因為沒有適當的休息 而影響到你白天的工作跟活動
        我們的身體是會自我調節的
        當你夜晚沒有得到充分的休息
        它會在你白天去補償
        綜合以上幾點
        我為什麽前面要強調我做清醒夢的原因
        也就是因為 我剛剛提到我本身就多夢了
        我本來就會紀錄一些 對我來說特別有感覺的夢
        然後如果條件允許的話
        我可能假日有時間才會進行這個練習
        加上我也想用這個方式來探究自己的夢
        如果你本身也多夢
        然後真的想去試試看的話
        我建議在假日的時間
        可以睡回籠覺和午覺的時候
        假日哦
        我會去嘗試
        也是我評估過自己的狀況
        但當我很累的時候
        我當然是睡眠和休息優先啊
        再來我可能以前
        有些創作的需要
        這個是下集的內容
        嘗試做清醒夢是我大學的時候
        然後現在年紀越來越大
        我的睡眠品質開始
        越來越差了之後
        我就都沒有再實驗了
        就是讓它自然發生而已
        隨緣
        一直到現在我還是有記錄夢的習慣
        有時候稍微字詞修飾一下
        它會變成一個 非常獨一無二的故事
        並且呢
        可以跟我當時的心境做結合
        那今天的內容就到這邊了
        非常謝謝大家的觀看
        那有興趣的朋友再幫我按讚留言
        然後要記得訂閱 並開啟小鈴鐺哦
        那我們下周五再見啦
        ？
        那我們下週五再見啦
        拜拜💙
        （別走別走～後面還有）
        警察！！
        有變態！！`
    }
};

export default lucidDreaming;