const magicTricks = {
    videoId: 'jN1F8MO9zsw',
    transcript: {
        pinyin: "Halo dàjiā hǎo huānyíng dàjiā lái dào mùqián xiǎngbùdào xìliè zhī móshù shī Magic āi zhè bù jiùshì rénqì míngxīng dōu zài yòng de ruǎn ké mó miē jiè wǒ yòng yīxià āi fàng wǒ chūlái fàng wǒ chūlái kuài diǎn bǎ wǒ biàn chūlái a bùyòng la wǒ zìjǐ zǒu chūlái bùrán edit yěshì hěn máfan de āi nǐmen gānggāng chāo qián běn jiémù yóu Dr.Douxi guàn míng bō chū HALO dàjiā hǎo wǒ shì móshù shī ZACH āi ZACH qíshí nǐ cóng jǐ suì kāishǐ xué shénmó shíhòu jiēchù dào jiēchù shì cóngxiǎo dàgài shì 7 suì kāishǐ jiù duì móshù yǒu xìngqù wǒ de fùqīn yěshì yīgè móshù shī tā bǎ wǒ biàn chūlái chāo lěng érqiě nǐ kàn tā jiǎnghuà yǒu móshù shī dì nà zhǒng wǒ de fùqīn yěshì tā yǒu nàgè shǒushì yǒu nàgè qìshì qíshí shì 7 suì de shíhòu nà yī nián shì wǒ fùqīn biànle yīgè xiǎo móshù gěi wǒ kàn jiùshì bǎ yīgè zhǐjīn xiāoshī diào wǒ jiù juédé hěn hàoqí zhège shìjiè zuò mó nàmó qíguài ránhòu wǒ jiù kāishǐ yánjiū guòhòu dehuà jiùshì diànshì shàng de jiémù měi cì cháng yǒu móshù jiémù huò móshù bǐsài wǒjiā rén jiù huì dì yī shíjiān tōngzhī wǒ jiào wǒ lái kàn móshù suǒyǐ jiùshì tāmen ràng wǒ zǒu shàng zhè tiáo bù guī lù wèishénmó bù hǎo zhuàn miē yīnggāi hěn hǎo zhuàn ba nǐ xiān jiǎng yīxià nǐ móshù shī dàodǐ yīgè yuè yuè shōurù duōshǎo wǒmen dǎoyǎn huì bāng wǒmen zuò zhège xiàoguǒ nǐ xiān gēn wǒ jiǎng yīxià kàn yǒu méiyǒu bǐ yǎnyuán hǎo zhuàn yǒu yǒu yǒuguò wàn ba guò wàn bǐ nǐ hǎo zhuàn ó qīn'ài de hǎohǎo zhuàn ó bǐ nǐ hǎo zhuàn ó qīn'ài de hǎohǎo zhuàn ó dānshēn dānshēn dānshēn yuè shōurù pò wàn dàjiā kěyǐ kàn yīxià zhuīzōng tā de Instagram yō dàjiā kěyǐ follow yīxià tā de Instagram OMG OMG suǒyǐ xiànzài rúguǒ wǒmen suíbiàn qǐng nǐ dehuà yīchǎng dōu yào qiān duō kuài shì bùshì sorry ó è wǔqiān wǔqiān qǐng nǐ OMG píng shénmó a yě tài guìle ba wǔqiān kuài méiyǒu la mén zài nàlǐ mén zài zhèlǐ méiyǒu la yīnwèi tā xiànzài qíshí shì tā huì chángqí yīzhí zài àomén zuò zhuānyè móshù biǎoyǎn suǒyǐ rénjiā xiànzài yǐjīng shì up levelle wǒ juédé yào xiān gěi guān zhòng liào jiè yīxià wèishénmó nǐ de jiàmǎ kěyǐ qù dào zhèyàng shì yīnwèi nǐ yǒu kǎo shénmó nǐ zhīdào kěnéng yào kǎo zhèngzhào háishì shénmó móshù dehuà méiyǒu zhèngzhào la jiùshì zhǐyào shi jiù wǒ shì yǒu cānjiā móshù gōnghuì ránhòu móshù gōnghuì jiù wǒmen yǒu yīgè dōngxī jiào shòu bàng yíshì shòu bàng yíshì jiùshì jīngguò hěnduō gè móshù shī de tóupiào ránhòu tóupiào ránhòu bù hǎoyìsi yīnwèi wǒ gēn wēi wēi duì dào yǎn shòu bàng yíshì wǒ juédé zhège zì yào xiě qīngchǔ shòu bàng yíshì OK dàjiā shòu bàng yíshì jiùshì shòu bàng yíshì lái wǒmen jiǎng jiè yīxià shénmó shì shòu bàng yíshì shòu bàng yíshì bùshì bié de “shòu” bàng yíshì shénmó shòu bàng yíshì jiùshì huì yǒu jǐ gè móshù shī huì gěi nǐ yīgè píngfēn ránhòu juédé nǐ shì yīgè hégé de móshù shī ránhòu jiù huì gěi nǐ yīgè zhèngshū yīgè zhǎngbèi jiù huì bānfā nàgè bàngzi gěi nǐ suǒyǐ nǐ jiā lǐ yǒu hěnduō gēn bàngzi méiyǒu zhǐyǒu yī gēn bàle yī gēn bàngzi jiù kěyǐ wǔqiān kuàile āi qíshí wǒ yǒu yīgè hěn hàoqí hěn hàoqí zuì hào qí de jiùshì nǐmen zěnyàng kòngzhì nàgè gēzi lēi duì wǒ juédé wǒ juédé hěn lìhài jiùshì nàgè gē zǐ kěyǐ duǒ zài màozi lǐmiàn háishì shénmó ránhòu zài bǎ tāmen fàng chūlái fēi fēi fēi fēi fēi kěshì nǐmen érqiě tā jiùshì tīng dé dǒng nǐ zài jiǎng shénmó ránhòu nǐ zài zhǐhuī tā dōu tīng dé dǒng kěshì wǒ zài xiǎng zhēn de shì zhèyàng zi ma ránhòu měi yīchǎng de gēzi dōu bù yīyàng shì bùshì dōu yīyàng dōu yīyàng dōu tóngyī zhī tóngyī zhī a fēile hái kěyǐ bǎ tā jiào huílái duì tā huì huílái huì huílái kěshì nǐ zěnyàng zhēn de huì qù xùnliàn tā ma háishì jiù rúguǒ dàjiā zàijiā lǐ yǒu yǎng chǒngwù bǐrú yǎng gǒu dehuà la jiù yīyàng nǐ bǎ fēipán fēi chūqù gǒu huì jiēle zài huílái lèisì yīyàng de dàolǐ ma suǒyǐ jiùshì yī kāishǐ dehuà kěnéng wǒmen gēn gǒu wán dehuà huì zhǔnbèi tā de sìliào ránhòu diūle jiē huílái gěi tā jiǎnglì gēn gēzi shì yīyàng de jiù kěnéng yī kāishǐ cóng wǒ de zuǒshǒu pǎo dào wǒ de yòushǒu ránhòu jiù gěi tā jiǎng lì chī yīgè sìliào ránhòu jiùshì yuè lái yuè yuǎn yuè lái yuè yuǎn tā xíguàn guòhòu jiù kěyǐ fàng tā chūqù ránhòu zài fēi yī quān huílái ó nǐ de niǎo zhēn de hěn lìhài lēi jiùshì xiǎoshíhòu wǒmen hěn chánghuì kàn dào yīxiē diànshì shàng jiù jiě kāi suǒyǒu móshù shī de mídǐ jiùshì bǎ suǒyǒu jiùshì gēn nǐ jiǎng zhège móshù shì zěnyàng biàn chūlái de zhège móshù shì zěnyàng biàn chūlái de kěshì zhèyàng zi huì bù huì zàochéng jiùshì qítā móshù shī zěnmó bàn jiùshì nǐ dōu yǐjīng bǎ suǒyǒu de nàgè jìqiǎo quánbù jiào wánliǎo zhèyàng móshù shī bùyòng zuòle gē jiù qíshí yǒu liǎng diǎn yīdiǎn qíshí jiù huì péiyǎng chū xīn de móshù shī wǒ shì nà yīdiǎn de rén lìngwài yīdiǎn jiùshì huì ràng dàjiā duì móshù bù zūnzhòng jiù hěn xiàng nǐ zài biǎoyǎn de shíhòu biérén jiù huì āi zhège wǒ kànguòle āi wǒ yěshì huì zhèyàng wǒ yěshì zhèyàng de rén kěshì yǒu yīxiē móshù bù zhǐshì kào jìqiǎo ba yǒu yīxiē xiàng shì bèi guān zài shuǐ lǐmiàn a yào jìn duōjiǔ a shénmó de zhè zhǒng yǒu shíhòu shì xùnliàn jiù réntǐ jíxiàn nǐ háishì yào tèbié xùnliàn cái kěyǐ duì duì duì duì duì yǒu yīxiē móshù hěn lìhài tā kěyǐ fēi zài bànkōng zhōng a zhè zhǒng nǐ huì ma wǒ yǒu biǎoyǎnguò nǐ yǒu biǎoyǎnguò zài jùchǎng yǒu biǎoyǎnguò yǒu biǎoyǎnguò yǒu biǎoyǎnguò suǒyǐ nǐ xiànzài kěyǐ fēi wǒmen lái edit yīxià qíshí wǒ fāxiàn dào móshù tā bùshì zhèyàng zi biàn bàle nǐ hái yào zěnyàng kěyǐ zhuā dào guān zhòng de yǎnqiú duì jiùshì nǐ yào qù gēn tāmen duìhuà yě hǎo huòzhě shì shuō nǐ zěnmó qù chéngxiàn zhège dōngxī zhītǐ dòngzuò yào hěn kuāzhāng háishì zěnmó yàng hěn xǐhuān zhèyàng a huòzhě shì zhèyàng a nǐmen yīdìng yào kàn dào zuìhòu yīnwèi tā zuìhòu huì wèi wǒmen biǎoyǎn móshù OK suǒyǐ zuìhòu lái kàn yīxià tā de zhītǐ dòngzuò ránhòu nǐ zài kàn tā biǎoyǎn de móshù zhí bù zhídé wǔqiān kuài halo dàjiā hǎo wǒ shì móshù shī Zach xiànzài ne lái dàole wǒmen de móshù shíjiān hǎo zhège móshù shì zhèyàng zi de wǒ yào nǐ zài yī dào wǔshí zhī jiān suíbiàn xiǎng yīgè hàomǎ hǎo xiǎng hǎole ma jiùshì nàgè hàomǎle bùyào biàn shénmó hàomǎ ne zuò mó yào gēn nǐ jiǎng hǎo gàosù wǒ shénmó hàomǎ xiànzài shì yào gàosù nǐ shì ma duì duì duì a hǎo shénmó hàomǎ 16 wǒ zài zhè biān ní yǒu yīgè bǐjì wǒ yào nǐ diǎn zhège bǐjì jìnqù ránhòu nǐ kàn dào guān zhòng zuì cháng xuǎn dào de pūkè pái de note ma diǎn jìnqù suǒyǐ nǐ gānggāng jiǎng de hàomǎ shì 16 qù dào dì 16 gè jì zhù nàgè pái xiànzài ne lún dào nǐ gānggāng tā xuǎnle yīgè hàomǎ 16 xiànzài ne zhè biān wǒ zhǔnbèile yīgè hézi zhège hézi lǐmiàn ne yǒu yīgè shǎizi (tiàodàn) OK lái shǎizi ránhòu lēi shǎizi hǎo jiē xiàlái wǒ yào nǐ zuò de shìqíng hěn jiǎndān wǒ yào nǐ ná zhège shǎizi suíbiàn dì fàng dào hézi lǐmiàn gài qǐlái suǒzhe jiù zhèyàng jiǎndān dànshì nàgè hàomǎ bùyào ràng wǒ kàn dào hǎo kěyǐ (yào xiān check yīxià) biǎoyǎn móshù dōu shì zhèyàng duì wǒ yào gěi guān zhòng kàn yīxià hǎo xiān bùyào ràng wǒ kàn dào nǐ zhíjiē zài jìngtóu qián ba nǐ jiù zhíjiē xuǎn ó Edmund hǎo xuǎnhǎole a nǐ de dòng hěn xiǎo dì yī cì shì zhèyàng de hǎohǎo hǎo kěyǐ nà xiànzài ne yī kāishǐ nǐmen jiù xuǎnle yīgè pái duì ba ránhòu nǐ yě xuǎnle yīgè diǎn shù nà qíshí ne wǒ bù zhīdào nǐ xuǎn de pái shì shénmó wǒ yě bù zhīdào nǐ de diǎn shù shì duōshǎo rúguǒ méiyǒu cuò ne nǐ xǐhuān bǐjiào dà de duì ma ń wǒ yào nǐ kànzhe wǒ yīxià rúguǒ méiyǒu cuò ne mán dà de nǐ mán dà de zhēn de zhēn de mán dà de tīng dàole hǒu gèwèi guān zhòng péngyǒu érqiě wǒ juédé shì 6 diǎn shì ba kàn yīxià kàn yīxià shì 6 diǎn ma 6 diǎn OMG shì 6 diǎn duì dāngrán dāngrán wǒ hái wàngjìle yī jiàn shìqíng nǐ yǒu shǒujī ma kěyǐ jiè wǒ nǐ de shǒujī ma zhè biān ní zhǔnbèile yīgè píbāo xiān bǎ wǒ de míngpiàn shùnbiàn bǎ wǒ de míngpiàn ná gěi nǐ wǒ yào nǐ bāng wǒ názhe wǒ de míngpiàn wǒ de zhège píbāo děng xià yào gàosù wǒ wǒ shì CID zhèyàng ránhòu ne wǒ yòng nǐ de shǒujī pāi yī zhāng zhàopiàn duìzhe jìngtóu xiào yīxiào 3 2 1 hǎo xíngle ránhòu wǒ yǒu yīdiǎn jǐnzhāng wǒ yào nǐmen jì zhù zhè yīmù (wǒ pà língyì shìjiàn) tōngcháng móshù shī kāishǐ biǎoyǎn móshù dūhuì ná pūkè pái chūlái wǒ jīntiān yěshì huì ná pūkè pái chūlái ń hǎoxiàng zhèyàng zi nǐ gāngcái suǒ xuǎn dì nà yī zhāng pái ne shì bùshì hēisè de jiàng jiùshì hóngsè de wǒ zhǐshì yào quèrèn nǐ yě tài chàle ba rúguǒ méiyǒu cuò ne wǒ cóng zhège píbāo lǐmiàn huì ná chū yī zhāng hóngsè de pái ér zhè zhāng hóngsè de pái ne yīnggāi jiù huì shì nǐ suǒ xuǎn de hóngxīn 7 wūshī hǎo dāngrán dāngrán OMG dāngrán zhè yīmù hěn shúxī xiànzài wǒ huì bǎ zhège hóngxīn 7 fàng zài zhège píbāo lǐmiàn jìnqù hěn shúxī ma zhè yīmù gānggāng nǐ shì bùshì xiàng zhèyàng názhe kěyǐ kàn yīxià nǐ de shǒujī yerr nǐ kuài diǎn gěi guān zhòng yǒu yīdiǎn kěpà āi OMG wǔqiān kuài gěi tā pāi pāi zhǎng jī pí gēda (hěn lìhài zhège) āi zhège hěn lìhài kěshì gānggāng shì kōng de āi érqiě nǐ zěnyàng key shàngqù ó gānggāng shì kōng de āi (móshù) suǒyǐ nàgè 6 diǎn shì nǐ suíjī xuǎn de duì ma duì duì duì ránhòu nàgè hàomǎ yěshì nǐ suíjī hǎn de duì ma wǒmen méiyǒu shìxiān zhǔnbèi méiyǒu shìxiān chuàntōng duì jiù shì yī jìng dàodǐ wǒ duì tiān fāshì wǒmen wánquán méiyǒu briefguò nèiróng rúguǒ yǒu dehuà tā jiù yuè lái yuè xiǎo duì ránhòu tā de méimáo jiù huì bèi nòng diào xǐhuān wǒmen yǐngpiàn de huà jìdé fēnxiǎng dìngyuè àn zàn hái yǒu dǎkāi nǐ de xiǎo língdāng nǐ de miànmó shì bùshì yào chāile hǎoxiàng shì āi lái bāng nǐ pēnshuǐ chāi ba Dr.Douxi ruǎn ké mó 100 kē jīdàn cái yǒu 1%de ruǎn ké mó jíbài hēisèsù gǎn zǒu àn chén huáng qì 15 fēnzhōng liàng 1 dù",
        chinese: `halo大家好
        歡迎大家來到
        目前想不到系列之
        魔術師
        Magic
        欸
        這不就是人氣明星都在用的軟殼膜咩
        借我用一下
        欸放我出來放我出來
        快點把我變出來
        啊不用啦我自己走出來
        不然edit也是很麻煩的
        欸你們剛剛超乾
        本節目由Dr.Douxi冠名播出
        HALO大家好
        我是魔術師ZACH
        欸ZACH其實你從幾歲開始學
        什麽時候接觸到
        接觸是從小大概是7歲開始
        就對魔術有興趣
        我的父親也是一個魔術師
        他把我變出來
        超冷
        而且你看他講話有魔術師的那種
        我的父親也是
        他有那個手勢
        有那個氣勢
        其實是7歲的時候
        那一年是我父親變了一個小魔術給我看
        就是把一個紙巾消失掉
        我就覺得很好奇
        這個世界做麽那麽奇怪
        然後我就開始研究
        過後的話就是
        電視上的節目每次常有魔術節目或魔術比賽
        我家人就會第一時間通知我
        叫我來看魔術
        所以就是他們讓我走上這條
        不歸路
        爲什麽不好賺咩
        應該很好賺吧
        你先講一下你魔術師到底一個月月收入多少
        我們導演會幫我們做這個效果
        你先跟我講一下
        看有沒有比演員好賺
        有有有過萬吧
        過萬 比你好賺哦親愛的
        好好賺哦 比你好賺哦親愛的
        好好賺哦
        單身
        單身
        單身
        月收入破萬
        大家可以看一下追蹤他的Instagram喲
        大家可以follow一下他的Instagram
        OMG OMG
        所以現在如果我們隨便請你的話
        一場都要千多塊是不是
        sorry哦
        呃
        五千
        五千請你
        OMG
        憑什麽啊
        也太貴了吧
        五千塊
        沒有啦
        門在那裏
        門在這裏
        沒有啦因爲他現在其實是
        他會長期一直在澳門做專業魔術表演
        所以人家現在已經是up level了
        我覺得要先給觀衆瞭解一下
        爲什麽你的價碼可以去到這樣
        是因爲你有考什麽
        你知道可能要考證照還是什麽
        魔術的話沒有證照啦
        就是只要是
        就
        我是有
        參加魔術公會
        然後魔術公會就
        我們有一個東西叫授棒儀式
        授棒儀式就是經過很多個魔術師的投票
        然後
        投票然後
        不好意思
        因爲我跟溦溦對到眼
        授棒儀式
        我覺得這個字要寫清楚
        授棒儀式OK
        大家授棒儀式就是授棒儀式
        來我們講解一下什麽是授棒儀式
        授棒儀式不是別的“受”棒儀式
        什麽授棒儀式
        就是會有幾個魔術師
        會給你一個評分
        然後覺得你是一個合格的魔術師
        然後就會給你一個證書
        一個長輩就會頒發那個
        棒子
        給你
        所以你家裏有很多根棒子
        沒有只有一根罷了
        一根棒子就可以五千塊了欸
        其實我有一個很好奇很好奇
        最好奇的就是
        你們怎樣控制那個鴿子勒
        對
        我覺得
        我覺得很厲害
        就是那個鴿子可以躲在帽子裏面還是什麽
        然後再把他們放出來
        飛飛飛飛飛
        可是你們
        而且它就是聽得懂你在講什麽
        然後你在指揮它都聽得懂
        可是我在想真的是這樣子嗎
        然後每一場的鴿子都不一樣是不是
        都一樣都一樣
        都同一隻
        同一隻啊
        飛了還可以把它叫回來
        對它會回來會回來
        可是你怎樣
        真的會去訓練它嗎
        還是
        就如果大家在家裏有養寵物
        比如養狗的話啦
        就一樣
        你把飛盤飛出去
        狗會接了再回來
        類似一樣的道理嘛
        所以就是一開始的話可能我們
        跟狗玩的話會準備它的飼料
        然後丟了接回來給他獎勵
        跟鴿子是一樣的
        就可能一開始從我的左手
        跑到我的右手
        然後就給它獎勵吃一個飼料
        然後就是越來越遠越來越遠
        它習慣過後就可以
        放它出去然後再飛一圈回來
        哦
        你的鳥真的很厲害勒
        就是小時候
        我們很常會看到一些
        電視上
        就解開所有魔術師的謎底
        就是把所有
        就是跟你講這個魔術是怎樣變出來的
        這個魔術是怎樣變出來的
        可是這樣子會不會造成就是
        其他魔術師怎麽辦
        就是你都已經把所有的
        那個技巧全部教完了
        這樣魔術師不用做了咯
        就其實有兩點
        一點其實就會培養出新的魔術師
        我是那一點的人
        另外一點就是
        會讓大家對魔術不尊重
        就很像你在表演的時候
        別人就會欸這個我看過了
        欸我也是會這樣
        我也是這樣的人
        可是有一些魔術不只是靠技巧吧
        有一些像是被關在水裏面啊
        要浸多久啊什麽的
        這種有時候是訓練
        就人體極限
        你還是要特別訓練才可以
        對對對對對
        有一些魔術很厲害
        他可以飛在半空中啊這種
        你會嗎
        我有表演過
        你有表演過
        在劇場有表演過
        有表演過
        有表演過
        所以你現在可以飛
        我們來edit一下
        其實我發現到
        魔術他不是這樣子變罷了
        你還要怎樣可以抓到觀衆的眼球
        對
        就是你要去跟他們對話也好
        或者是說
        你怎麽去呈現這個東西
        肢體動作要很誇張還是怎麽樣
        很喜歡這樣啊
        或者是這樣啊
        你們一定要看到最後
        因爲他最後會為我們表演魔術
        OK所以最後來看一下他的肢體動作
        然後你再看他表演的魔術
        值不值得五千塊
        halo大家好我是魔術師Zach
        現在呢來到了我們的魔術時間
        好這個魔術是這樣子的
        我要你在一到五十之間隨便想一個號碼
        好 想好了嗎
        就是那個號碼了
        不要變
        什麽號碼呢
        做麽要跟你講
        好 告訴我什麽號碼
        現在是要告訴你是嗎
        對對對
        啊好
        什麽號碼
        16
        我在這邊呢有一個筆記
        我要你點這個筆記進去
        然後你看到觀衆最常選到的撲克牌的note嗎
        點進去
        所以你剛剛講的號碼是
        16
        去到第16個
        記住那個牌
        現在呢
        輪到你
        剛剛她選了一個號碼16
        現在呢這邊我准備了一個盒子
        這個盒子裏面呢有
        一個骰子（跳蛋）
        OK來骰子
        然後勒
        骰子
        好接下來我要你做的事情很簡單
        我要你拿這個骰子
        隨便的放
        到盒子裏面蓋起來鎖著
        就這樣簡單
        但是那個號碼不要讓我看到
        好
        可以（要先check一下）
        表演魔術都是這樣
        對我要給觀衆看一下
        好先不要讓我看到
        你直接在鏡頭前吧
        你就直接選哦Edmund
        好
        選好了啊
        你的洞很小
        第一次是這樣的
        好好好可以
        那現在呢
        一開始你們就選了一個
        牌對吧
        然後你也選了一個點數
        那其實呢
        我不知道你選的牌是什麽
        我也不知道你的點數是多少
        如果沒有錯呢你喜歡比較大的對嗎
        嗯
        我要你看著我一下
        如果沒有錯呢
        蠻大的
        你蠻大的真的真的
        蠻大的聼到了吼各位觀衆朋友
        而且我覺得是
        6點
        是吧
        看一下
        看一下
        是6點嗎
        6點
        OMG
        是6點
        對
        當然當然
        我還忘記了一件事情
        你有手機嗎
        可以借我你的手機嗎
        這邊呢准備了一個皮包
        先把我的名片
        順便把我的名片拿給你
        我要你幫我拿著我的名片
        我的這個皮包等下要告訴我
        我是CID這樣
        然後呢我用你的手機拍一張照片
        對著鏡頭笑一笑
        3 2 1
        好行了
        然後
        我有一點緊張
        我要你們記住這一幕（我怕靈異事件）
        通常魔術師開始表演魔術都會拿撲克牌出來
        我今天也是會拿撲克牌出來
        嗯
        好 像這樣子
        你剛才所選的那一張牌呢是不是黑色的
        醬就是紅色的
        我只是要確認
        你也太差了吧
        如果沒有錯呢
        我從這個皮包裏面
        會拿出一張紅色的牌
        而這張紅色的牌呢
        應該就會是
        你所選的紅心7
        巫師
        好當然當然
        OMG
        當然這一幕很熟悉
        現在我會把這個紅心7放在這個皮包裏面進去
        很熟悉嗎這一幕
        剛剛你是不是像這樣拿著
        可以看一下你的手機
        yerr
        你快點給觀衆
        有一點可怕欸
        OMG
        五千塊給他拍拍掌
        鷄皮疙瘩（很厲害這個）
        欸這個很厲害
        可是剛剛是空的欸
        而且你怎樣key上去哦
        剛剛是空的欸（魔術）
        所以那個6點是你隨機選的對嗎
        對對對
        然後那個號碼也是你隨機喊的對嗎
        我們沒有事先準備
        沒有事先串通
        對 就是一鏡到底
        我對天發誓
        我們完全沒有brief過内容
        如果有的話他就越來越小
        對
        然後他的眉毛就會被弄掉
        喜歡我們影片的話
        記得分享訂閲按贊
        還有打開你的小鈴鐺
        你的面膜是不是要拆了
        好像是欸
        來幫你噴水
        拆吧
        Dr.Douxi軟殼膜
        100顆鷄蛋才有1%的軟殼膜
        擊敗黑色素
        趕走暗沉黃氣
        15分鐘亮1度`
    }
};

export default magicTricks;