const makePeopleLikeYou = {
    videoId: 'eyPTmnjoohQ',
    transcript: {
        pinyin: "hi dàjiā hǎo wǒ shì ā huà wǒ jīntiān xiǎng gēn nǎimen liáo jiàzhí wǒ xiāngxìn nǎimen yīdìng hěn cháng tīngdào yào tíshēng jiàzhí dànshì nǎimen xiǎng zhīdào de shì yào zěnme qù tíshēng jiàzhí ràng rén xǐhuān nǎi shǒuxiān nǎi yào liǎojiě tíshēng jiàzhí zhè jiàn shìqíng shì yī jiàn hěn quánmiàn de rúguǒ nǎi yǒu tīngdào kào yīgè tàolù jiù néng tíshēng jiàzhí ràng rén xǐhuān nǎi nà máfan bié sī cángle gǎnkuài gàosù dàjiā ba nà wǒ yě xiāngxìn nǎi yě bù huì gàosù biérén zhè zhǒng 100%de fāngshì zhè jiù yǒudiǎn xiàng shì nǎi péngyǒu gēn nǎi shuō wǒ gàosù nǎi yīgè kěyǐ 100%zhuànqián de fāngshì érqiě shì bèidòng shōurù qīngsōng qīngsōng zàijiā jiù kěyǐ tǎng zài zhuànqián nà nǎi dì yīgè kěnéng huì xiǎngdào shì shénme? Zài yīgè dēngguāng shì hóngsè de fángjiān lǐ hǎo la bù kāiwánxiào yě jiùshì nǎi yào qù lǐjiě tíshēng jiàzhí tā bìng bùshì yīgè gōngshì ér tào zhèyàng de gōngshì jiù kěyǐ ràng suǒyǒu rén dōu xǐhuān nǎi zhè yěshì wǒmen zài tíshēng zìjǐ jiàzhí guòchéng zhōng hěn cháng fàn de yīgè cuòwù jiùshì nǎi bǎ tíshēng jiàzhí ná lái dàng zuò shìgè shǒuduàn wǒ lái zuò gè bǐyù jiǎshè nǎi hěn xǐhuān dǎ lánqiú nǎi yǒu kěnéng shì zhèlǐngyù de jiǎojiǎo zhě jiéguǒ duìfāngshì xǐhuān huì yīnyuè de rén tā duìyú huì yùndòng de méi xìngqù nà rúguǒ shì zhèyàng nándào nǎi yào wèile tā qù xué yuèqì ma? Bù kěnéng ma jiùsuàn nǎi qù xuéle dédào tā de àile nǎi de rénshēng yě bù huì kuàilè érqiě fēngxiǎn hěn gāo jiù xiàng wǒ tīngguò yīxiē lìzi jiù xiàng shì yǒuxiē rén huì wèile gēn duìfāng zài yīqǐ ér xīshēng diào hěnduō zìjǐ xǐhuān de shìqíng nà zài nǎi de shìjiǎo lǐ nǎi kěnéng juédé nǎi xīshēngle shénme kěshì zài duìfāng de shìjiǎo lǐ bù huì yǒu zhè zhǒng gǎnjué nà nǎi hěn róngyì bǎ zhèyàng de gǎnshòu huàchéng shì yīzhǒng qíngxù lèsuǒ érqiě duìfāng kěnéng huì gēn nǎi shuō wǒ yòu méi yào nǎi wèi wǒ xīshēng shénme nà wǒ xiāngxìn nǎi tīngdào zhè jù huà shòushāng de shì nǎi ér nǎimen de jiéguǒ kěnéng dào zuìhòu shénme dōu méiyǒu dàn nǎi yě wúfǎ guài shuí yīnwèi zhè shì nǎi dāngchū zuò de xuǎnzé nǎi jiù bìxū qù chéngdān nǎi suǒ xuǎnzé de fēngxiǎn suǒyǐ nǎi wèile shuí qù tíshēng jiàzhí běn shì jiù yī jiàn hěn kōngxū de shìqíng érqiě zhè bù jiào tíshēng jiàzhí ér shì tíshēng biérén yǎnzhōng rèndìng de jiàzhí nà zhèyàng zuò huì fāshēng shénme shìqíng dāng nǎi yǐjīng hěn nǔlì rènwéi nǎi zài tíshēngle nǎi yě huì yīnwèi duìfāng de fǒudìng huò shì tàidù duì nǎi méiyǒu gǎibiàn ér nǎi kāishǐ fǒudìng zìjǐ nà nǎi jiù huì yuè lái yuè wúlì duì gǎnqíng yuè lái yuè mímáng ránhòu kāishǐ duì tíshēng jiàzhí zhè jiàn shìqíng gǎndào yíhuò suǒyǐ zhèyàng de nǎi cái huì juédé tíshēng jiàzhí hěn chōuxiàng dàn qíshí gēnběn méi nàme nán ér nǎi huì yǒu zhèyàng xiǎngfǎ shì nǎi méiyǒu zhèngquè de qù lǐjiě tíshēng jiàzhí zhè jiàn shì ér bùshì nǎi bù dǒng rúhé tíshēng jiàzhí nà méiguānxì wǒmen jīntiān jiù yòng gè miànxiàng qù lái tǎolùn zhè jiàn shì nà wǒmen xiān yòng lǐlùn qù lǐjiě zìwǒ jiàzhí rúguǒ yǐ lǐlùn de gàiniàn lái shuō nà wǒmen de zìwǒ jiàzhí shì tòuguò wǒmen de chéngzhǎng ér zìwǒ jiànlì de nà héxīn shì zìzūn rúguǒ yào jiǎndān yīdiǎn jiǎng jiùshì zìxìn, zìzūn, zì'ài nà zìxìn jiùshì yǎnglài zìjǐ suǒ xū de nénglì nǎi duì zìjǐ méi xìnxīn biérén jiù hěn nán duì nǎi yǒu xìnxīn nà zì'ài jiùshì rúguǒ nǎi bù ài zìjǐ biérén yě hěn nán qù ài nǎi nà zìzūn jiùshì nǎi zìjǐ bù zūnzhòng zìjǐ biérén yě hěn nán qù zūnzhòng nǎi nà wǒmen yǒule zhè yīdiǎn gàiniàn zhīhòu wǒmen jiù yòng kēxué de jiǎodù qù kàn rén yǔ rén zhī jiān xīyǐn lì nà qíshí zhège Discovery yǒu zuòle yī qí de jiémù tā jiào tòushì xìng mèilì tā shì yòng kēxué de fāngshì qù fēnxī rén yǔ rén zhī jiān de mèilì hé xīyǐn lì hé wǒmen shì zěnme qù xuǎnzé lìng yī bàn nà tāmen zhè qī jiémù lǐmiàn yǒu zuòle yīgè shíyàn tāmen zhǎole 10 gè nánshēng hé 10 gè nǚshēng yào lái jìnxíng pèiduì ránhòu tāmen suíjī zài nánnǚ de tóushàng tiē shàng 1~10 de shùzì ránhòu nǎi shì méiyǒu bànfǎ kàn dào zìjǐ de shùzì dàn nǎi kěyǐ kàn dào biérén de nà zhè yóuxì guīzé shì zhèyàng nǎi kěyǐ duì nǎi gǎnxìngqù de rén shēn chūshǒu nà rúguǒ duìfāng yě yuànyì shēn chūshǒu nà nǎimen jiù huì pèiduì chénggōng nà rúguǒ duìfāng bù yuànyì nǎi jiù jìxù qù zhǎo biérén shìyì nà zài shíyàn zhīqián ā zhǔchí rén jiù shuōle nǎimen jìnliàng qù zhǎodào zuìdà de shùzì lái pèiduì yě jiùshì zài zhēnshí de shìjiè lǐ wǒmen yī kāishǐ dūhuì bù zhīdào zìjǐ de jiàzhí yě bù zhīdào zìjǐ duō yǒu xīyǐn lì suǒyǐ yī kāishǐ dūhuì bǎ mùbiāo dìng de hěn gāo ér xiǎng yào qù dédào 10 fēn de rén nà dāng nǎi méi pèiduì dào 10 de rén wǒmen jiù huì kāishǐ jiàngdī biāozhǔn qù zhǎo yuànyì jiēshòu wǒmen de rén nà zhè lǐ jiù yǒuqù de xiànxiàng jiùshì nǎi kàn dào tóushàng shì 10 fēn de rén tā zhōuwéi jiù wéile yī duī rén ér shùzì bǐjiào dī de rén jiù bù huì jiēshōu dào rènhé yāoqǐng nà nǎi zǐxì qù xiǎng xiǎng zhèyàng de qíngkuàng shì bùshì gēn wǒmen xiànshí de shèhuì yǒu yīdiǎn diǎn xiàng yóuqí zài xuéshēng de shíqí zuì míngxiǎn yīnwèi wǒmen xuéshēng shíqí hái zài mōsuǒ yě bù liǎojiě zìjǐ duō yǒu mèilì suǒyǐ wǒmen hěn róngyì jí yóu biérén lái rèndìng zìjǐ de jiàzhí yúshì tāmen zài yīcì yào qù pèiduì de shíhòu tāmen zài qízhōng yīgè sān hào de nǚshēng shēnshang zhuāngle màikèfēng tā xiǎng yào qù liǎojiě tā shì zěnme qù zé'ǒu de yúshì dāng zhège shíyàn kāishǐ de shíhòu zhège nǚshēng jiù shuōle wǒ xiǎng dàjiā yīdìng dūhuì zǒuxiàng 10 hào de nánshēng nà guǒbùqírán tā (10 fēn) hěn kuài jiù pèiduì hǎole érqiě tā fāxiàn dào yī jiàn shì méiyǒu rén gēn tā yǒu yǎnshén de jiāohuì suǒyǐ tā kāishǐ rènwéi zìjǐ de fēnshù yīnggāi shì hěn dī dāng yǒu shùzì èr de nánshēng yào lái zhǎo tā pèiduì de shíhòu zhège nǚshēng de nèixīn jiù juédé tā kěyǐ zhǎodào gèng hǎo de tā juédé zìjǐ bù huì zhème dī fēn yúshì tā yóuyù xúnzhǎo de shíhòu dàjiā kāishǐ màn man de pèiduì chénggōng ér zuìhòu tā jiù xuǎnzé yuánběn yāoqǐng tā de 2 hào yīn wéi yǐjīng méiyǒu rén kěyǐ xuǎnzéle ér zhè jiéguǒ fāxiàn yī jiàn shìqíng jiùshì suǒyǒu rén pèiduì wán zhīhòu tāmen tóushàng de fēnshù bù huì chājù tài dà nà wǒ juédé zhège shíyàn ā tā yě zhǐshì jiǎndān kuāng chū rén yǔ rén zhī jiān zé'ǒu de fāng shì yīnwèi xiànshí de shèhuì gèng fùzá wǒ zìjǐ shì rènwéi xiànshí de shèhuì zhuàngkuàng nǎi shì wúfǎ kàn dào biérén shì pèiduì chénggōng de jiù xiàng shì duìfāng yǐjīng pèiduì chénggōng tā háishì yǒu kěnéng huì qù jiēshòu nǎi de yāoqǐng ér kěnéng jiù huì xíngchéng yīzhǒng dī fēn de rén wánquán méi rén zhǎo tā ér gāo fēn de rén yǒngyǒu fù shǔ de pèiduì duìxiàng wǒ juédé zhèyàng zi huì bǐjiào piānxiàng xiànshí miàn yīdiǎn ér wǒ huì yǒu zhèyàng de xiǎngfǎ shì yīnwèi wǒ shōu dào hěnduō sī xùn hé tóugǎo de wèntí wǒ fāxiàn yuànyì dāng bèi tāi de rén hái bù shǎo yě jiùshì nǎi jīntiān yòng lǐxìng qù fēnxī zhè jiàn shìqíng nǎi kěnéng jiǎndān juédé duìfāng yǒu duìxiàngle huò shì nǎi gēn tā jiāowǎng tā zài gēn biérén àimèi nà jiù zhíjiē fēnshǒu jiù hǎo a xiǎng zhème duō gàn ma kěshì nǎi yòng gǎn xìng de jiǎodù qù kàn zhè jiàn shì shíhòu nǎi jiù huì fāxiàn zhè shì yītiáo hěn jiānxīn de lù érqiě nǎimen xiǎng yào jiào xǐng tā jiào tā líkāi duìfāng zuìhòu de jiéguǒ shì tā huì bù lǐ bāng tā de rén wǒ rènwéi zhè cái shì xiànshí zhōng huì yù dào de shì nà zhèyàng de shíyàn ā yě xiǎnshì chū wǒmen rènwéi de jiàzhí kěnéng shì láizì biérén duì nǎi de gǎnshòu jiù xiàng shì hěnduō rén zhuī de nánshēng huò nǚshēng tāmen yīdìng bǐ yībānrén gèng yǒu zìxìn ér wánquán dōu méiyǒu rén lǐ de tāmen yǒu kěnéng jiù huì rènwéi zìjǐ bùgòu yǒu jiàzhí suǒyǐ jiù huì biànchéng nǎi xūyào biérén lái rèndìng nǎi zìjǐ de jiàzhí nà zhèyàng shì duì de ma? Zhè yǒudiǎn xiàng shì nǎi zài tǐyù bān nǎi tǐnéng hěn làn dànshì nǎi de yīnyuè nénglì hěn qiáng nà nǎi kěnéng yīnwèi huánjìng ràng nǎi chǔyú yīgè méiyǒu zìxìn de zhuàngtài yīnwèi zhōuzāo rén dōu bù dǒng yīnyuè nǎi jiù wúfǎ cóng biérén shēnshang dédào zìxìn dédào nǎi rènwéi de jiàzhí ér hěn róngyì kāishǐ zìwǒ huáiyí nà nǎi zhēn de shì méiyǒu yòng ma? Zhēn de shì méiyǒu jiàzhí ma? Wǒ xiǎng bùshì ba ér nǎi zhǐshì zài bùduì dì dìfāng éryǐ suǒyǐ kuòdà jiāoyǒu quān de mùdì shì wèile yào zhǎodào dǒng yìshù de rén lái mǎi nǎi de huà nǎi kuà bù chūqù nà bù nǎi yǒngyuǎn jué dé zìjǐ méi yǒu jiàzhí hǎo nà wǒ shuōdao gānggāng nàgè pèiduì nà xiàn shí de qíngkuàng wǒmen duìyú biāozhǔn lái shuō shì hěn zhǔguān de yě jiùshì nǎi rènwéi 9 fēn de rén tā kěnéng zài biérén yǎnzhōng zhǐyǒu 3 fēn suǒyǐ nǎi zhēn de rènwéi biérén duì nǎi rèndìng de jiàzhí zhòngyào ma? Rúguǒ nǎi yīnwèi biérén rèndìng yǐngxiǎng dào nǎi jiàzhí huì fāshēng shénme shì nǎi wúfǎ sànfà chū zìjǐ de néngliàng hé gǎnrǎn lì nǎi xiǎng xiǎng ó rúguǒ biérén duì nǎi huíkuì dōu shì bù hǎo de ér nǎi hěn róngyì kāishǐ fàngqì kāishǐ fàngqì zìjǐ de rénshēng jiù huì xiǎng shuō wǒ zài nǔlì dōu méi yòng la qù jiànshēn ràng shēncái gèng hǎo yě méi yòng yě méi rén huì kàn yǒu shèjiāo huódòng nǎi yě bùxiǎng qù fǎnzhèng méi rén huì lǐ nǎi ér zhèyàng biérén duì nǎi bù hǎo de huíkuì jiù hěn róngyì dǎozhì nǎi de nèixīn yuè lái yuè dīmí nà rúguǒ huàn yīgè jiǎodù nǎi jīntiān zài yīgè shèjiāo chǎnghé yù dào yīgè hěn xiāojí de rén nǎi huì jué dé tā huì yǒu xīyǐn lì ma? Yě jiùshì nǎi yào zuò rènhé shìqíng ràng zìjǐ gèng hǎo běnlái bu shì wèile shuí ér nǔlì yīnwèi kàoshān shān dǎo kào rén rén pǎo kào zìjǐ cáinéng yīzhí chíxù de chéngzhǎng yě bù huì yīnwèi duìfāng xiāoshī ér zhōngduàn zìjǐ tíshēng jiàzhí ér zhèyàng cái shì zhēnzhèng de tíshēng zìwǒ jiù xiàng shì nǎi rúguǒ yǒu yīzhí kàn wǒ yǐngpiàn qù liǎojiě gǎnqíng zhōng xǔduō miànxiàng huò shì qù xīshōu biérén liàn'ài de jīngyàn ér zhèyàng xīnlǐ sùzhì de qiánghuà yěshì tíshēng jiàzhí de yīzhǒng huò shì wàibiǎo de dǎbàn tǐtài de wéichí chuān dā děng děng měi yī gè xiǎo xìjié dōu shì nǎi de jiàzhí yě dū shì nǎi yǒu kěnéng xīyǐn dào duìfāng de guān jiàn nà dāng nǎi zài qiánghuà de guòchéng zhōng nǎi zhèyàng de xīntài yě huì gǎnrǎn dào duìfāng ér nǎi zhèyàng de tèzhì yěshì yīzhǒng xīyǐn lì yīnwèi nǎi jǐ rén yǒu zhǒng zhèng néngliàng de gǎnjué zhèxiē dōu shì jiàzhí nà zhège gàiniàn bùlùn shì gǎnqíng háishì gōngzuò dōu shì yīyàng nǎi zhǐyào fàngqì jìnbù jiù hěn róngyì bèi táotài hǎo la wǒmen jīntiān liáo dào zhè biān wǒ yě zhù gèwèi dōu néng zhǎodào xìngfú wǒ shì ā huà jìdé dìngyuè fēnxiǎng kāiqǐ xiǎo língdāng yǒu dìngyuè de kěyǐ àn xǐhuān yě bié wàngjì zhuīzōng wǒ de IG diǎn zàn wǒ de fěnsī tuán wǒmen xià cì jiàn bāi bāi",
        chinese: `HI大家好
        我是阿畫
        我今天想跟妳們聊價值
        我相信妳們一定很常聽到
        要提升價值
        但是妳們想知道的是
        要怎麼去提升價值
        讓人喜歡妳
        首先妳要了解
        提升價值這件事情
        是一件很全面的
        如果妳有聽到
        靠一個套路就能提升價值
        讓人喜歡妳
        那麻煩別私藏了
        趕快告訴大家吧
        那我也相信
        妳也不會告訴別人
        這種100%的方式
        這就有點像是
        妳朋友跟妳說
        我告訴妳一個
        可以100%賺錢的方式
        而且是被動收入
        輕鬆輕鬆
        在家就可以躺在賺錢
        那妳第一個可能會想到
        是甚麼?
        在一個燈光是紅色的房間裡
        好啦不開玩笑
        也就是妳要去理解
        提升價值
        它並不是一個公式
        而套這樣的公式
        就可以讓所有人都喜歡妳
        這也是我們在提升
        自己價值過程中
        很常犯的一個錯誤
        就是妳把提升價值
        拿來當作是個手段
        我來做個比喻
        假設妳很喜歡打籃球
        妳有可能是這領域的佼佼者
        結果對方是喜歡
        會音樂的人
        他對於會運動的沒興趣
        那如果是這樣
        難道妳要為了他
        去學樂器嗎?
        不可能嘛
        就算妳去學了
        得到他的愛了
        妳的人生也不會快樂
        而且風險很高
        就像我聽過一些例子
        就像是有些人
        會為了跟對方在一起
        而犧牲掉很多自己喜歡的事情
        那在妳的視角裡
        妳可能覺得妳犧牲了甚麼
        可是在對方的視角裡
        不會有這種感覺
        那妳很容易把這樣的感受
        化成是一種情緒勒索
        而且對方可能會跟妳說
        我又沒要妳為我犧牲甚麼
        那我相信妳聽到這句話
        受傷的是妳
        而妳們的結果
        可能到最後甚麼都沒有
        但妳也無法怪誰
        因為這是妳當初做的選擇
        妳就必須去承擔
        妳所選擇的風險
        所以妳為了誰去提升價值
        本是就一件很空虛的事情
        而且這不叫提升價值
        而是提升別人眼中
        認定的價值
        那這樣做會發生甚麼事情
        當妳已經很努力
        認為妳在提升了
        妳也會因為對方的否定
        或是態度對妳沒有改變
        而妳開始否定自己
        那妳就會越來越無力
        對感情越來越迷茫
        然後開始對提升價值
        這件事情
        感到疑惑
        所以這樣的妳
        才會覺得提升價值很抽象
        但其實根本沒那麼難
        而妳會有這樣想法
        是妳沒有正確的去理解
        提升價值這件事
        而不是妳
        不懂如何提升價值
        那沒關係
        我們今天就用各面向
        去來討論這件事
        那我們先用理論
        去理解自我價值
        如果以理論的概念來說
        那我們的自我價值
        是透過我們的成長
        而自我建立的
        那核心是自尊
        如果要簡單一點講
        就是自信、自尊、自愛
        那自信就是仰賴
        自己所需的能力
        妳對自己沒信心
        別人就很難對妳有信心
        那自愛就是
        如果妳不愛自己
        別人也很難去愛妳
        那自尊就是
        妳自己不尊重自己
        別人也很難去尊重妳
        那我們有了這一點概念之後
        我們就用科學的角度
        去看人與人之間
        吸引力
        那其實這個Discovery
        有做了一期的節目
        它叫透視性魅力
        它是用科學的方式
        去分析人與人之間的
        魅力和吸引力
        和我們是怎麼去選擇
        另一伴
        那它們這期節目裡面
        有做了一個實驗
        他們找了10個男生和10個女生
        要來進行配對
        然後他們隨機在男女的頭上
        貼上1~10的數字
        然後妳是沒有辦法
        看到自己的數字
        但妳可以看到別人的
        那這遊戲規則是這樣
        妳可以對妳感興趣的人伸出手
        那如果對方也願意伸出手
        那妳們就會配對成功
        那如果對方不願意
        妳就繼續去找別人示意
        那在實驗之前阿
        主持人就說了
        妳們盡量去找到
        最大的數字來配對
        也就是在真實的世界裡
        我們一開始都會不知道
        自己的價值
        也不知道自己多有吸引力
        所以一開始都會把目標
        訂的很高
        而想要去得到10分的人
        那當妳沒配對到10的人
        我們就會開始降低標準
        去找願意接受我們的人
        那這裡就有趣的現象
        就是妳看到頭上
        是10分的人
        他周圍就圍了一堆人
        而數字比較低的人
        就不會接收到任何邀請
        那妳仔細去想想
        這樣的情況是不是
        跟我們現實的社會
        有一點點像
        尤其在學生的時期最明顯
        因為我們學生時期
        還在摸索
        也不了解自己多有魅力
        所以我們很容易藉由別人
        來認定自己的價值
        於是他們再一次
        要去配對的時候
        他們在其中一個
        三號的女生身上
        裝了麥克風
        她想要去了解
        她是怎麼去擇偶的
        於是
        當這個實驗開始的時候
        這個女生就說了
        我想大家
        一定都會走向
        10號的男生
        那果不其然
        他(10分)很快就配對好了
        而且她發現到一件事
        沒有人跟她有眼神的交會
        所以她開始認為自己的分數
        應該是很低
        當有數字二的男生
        要來找她配對的時候
        這個女生的內心
        就覺得她可以找到更好的
        她覺得自己不會這麼低分
        於是她猶豫尋找的時候
        大家開始慢慢的配對成功
        而最後她就選擇
        原本邀請她的2號
        因為已經沒有人可以選擇了
        而這結果發現一件事情
        就是所有人配對完之後
        他們頭上的分數
        不會差距太大
        那我覺得這個實驗阿
        它也只是簡單框出
        人與人之間擇偶的方式
        因為現實的社會更複雜
        我自己是認為現實的社會狀況
        妳是無法看到
        別人是配對成功的
        就像是對方已經配對成功
        他還是有可能
        會去接受妳的邀請
        而可能就會形成一種
        低分的人
        完全沒人找他
        而高分的人
        擁有複數的配對對象
        我覺得這樣子
        會比較偏向現實面一點
        而我會有這樣的想法
        是因為我收到很多私訊
        和投稿的問題
        我發現願意當備胎的人
        還不少
        也就是妳今天用理性去分析
        這件事情
        妳可能簡單覺得
        對方有對象了
        或是妳跟他交往
        他在跟別人曖昧
        那就直接分手就好啊
        想這麼多幹嘛
        可是妳用感性的角度
        去看這件事時候
        妳就會發現
        這是一條很艱辛的路
        而且妳們想要叫醒她
        叫她離開對方
        最後的結果
        是她會不理幫她的人
        我認為這才是現實中
        會遇到的事
        那這樣的實驗阿
        也顯示出
        我們認為的價值
        可能是來自別人
        對妳的感受
        就像是很多人追的
        男生或女生
        他們一定比一般人更有自信
        而完全都沒有人理的
        他們有可能就會認為
        自己不夠有價值
        所以就會變成
        妳需要別人來認定
        妳自己的價值
        那這樣是對的嗎?
        這有點像是妳在體育班
        妳體能很爛
        但是妳的音樂能力很強
        那妳可能因為環境
        讓妳處於一個沒有自信的狀態
        因為周遭人都不懂音樂
        妳就無法從別人身上
        得到自信
        得到妳認為的價值
        而很容易開始自我懷疑
        那妳真的是沒有用嗎?
        真的是沒有價值嗎?
        我想不是吧
        而妳只是在不對的地方而已
        所以擴大交友圈的目的
        是為了要找到
        懂藝術的人
        來買妳的畫
        妳跨不出去那步
        妳永遠覺得自己沒有價值
        好那我說道剛剛那個配對
        那現實的情況
        我們對於標準來說
        是很主觀的
        也就是妳認為9分的人
        他可能在別人眼中
        只有3分
        所以妳真的認為
        別人對妳認定的價值
        重要嗎?
        如果妳因為別人認定
        影響到妳價值
        會發生甚麼事
        妳無法散發出自己的能量
        和感染力
        妳想想哦
        如果別人對妳回饋
        都是不好的
        而妳很容易開始放棄
        開始放棄自己的人生
        就會想說我再努力
        都沒用啦
        去健身讓身材更好
        也沒用
        也沒人會看
        有社交活動
        妳也不想去
        反正沒人會理妳
        而這樣別人對妳不好的回饋
        就很容易導致妳的內心
        越來越低迷
        那如果換一個角度
        妳今天在一個社交場合
        遇到一個很消極的人
        妳會覺得他會有吸引力嗎?
        也就是妳要做任何事情
        讓自己更好
        本來不是為了誰而努力
        因為靠山山倒
        靠人人跑
        靠自己
        才能一直持續的成長
        也不會因為對方消失
        而中斷自己提升價值
        而這樣才是真正的提升自我
        就像是妳
        如果有一直看我影片
        去了解感情中
        許多面向
        或是去吸收別人戀愛的經驗
        而這樣心理素質的強化
        也是提升價值的一種
        或是外表的打扮
        體態的維持
        穿搭等等
        每一個小細節
        都是妳的價值
        也都是妳有可能
        吸引到對方的關鍵
        那當妳在強化的過程中
        妳這樣的心態
        也會感染到對方
        而妳這樣的特質
        也是一種吸引力
        因為妳給人
        有種正能量的感覺
        這些都是價值
        那這個概念
        不論是感情還是工作
        都是一樣
        妳只要放棄進步
        就很容易被淘汰
        好啦
        我們今天聊到這邊
        我也祝各位都能找到幸福
        我是阿畫
        記得訂閱分享開啟小鈴鐺
        有訂閱的可以按喜歡
        也別忘記追蹤我的IG
        點讚我的粉絲團
        我們下次見
        掰掰`
    }
};

export default makePeopleLikeYou;