const meditation = {
    videoId: '0sNU6813Q2Q',
    transcript: {
        pinyin: "hello! Dàjiā hǎo! Wǒ shì Lindsey, jīntiān zhège shìpín, wǒmen lái liáo yīxià míngxiǎng. Míngxiǎng yǒu nǎxiē hǎochù? Zěnme míngxiǎng? Wǒ míngxiǎngle 3 gè yuè yǐhòu yǒu nǎxiē gǎnjué? Wǒ xiāngxìn dàjiā duō duō shào shào dōu tīng shuōguò míngxiǎng zhège cí yǒuxiē rén juédé tā hěn yáoyuǎn, shì yī zhǒng zōngjiào de yíshì shènzhì yǒuxiē bèi shénhuàle lìng yīxiē rén suīrán zhīdào míngxiǎng yǒu hěnduō hǎochù kě duì tāmen lái shuō, jiùsuàn shì ānjìng de dài gè jǐ fēnzhōng yě hěn kùnnán jǐ gè yuè qián de wǒ yěshì zhèyàng yīzhí yǐlái zǒng yǒu niàntou céngchūbùqióng jìngrán yě nénggòu zài yīduàn shíjiān de xùnliàn zhīhòu shēnkè de tǐhuì dàole míngxiǎng gěi wǒ cóng shēntǐ dào xīnlíng dài lái de qīngjìng yǔ tíshēng kě míngxiǎng yǒu shé me hǎochù ne? Yǐxià tí dào de yīxiē míngxiǎng de hǎochù quánbù dōu shì yǒu kēxué yánjiū zuòwéi yījù de wǒ zhǐ jiǎndān luóliè jǐ diǎn yǒuxiē hǎochù xūyào gèng cháng shíjiān de liànxí cái huì yǒu míngquè de gǎnshòu, yǒuxiē hǎochù zài zuò wán míngxiǎng dāngxià jiù néng bèi chájué míngxiǎng de hǎochù bāokuò: Zēngqiáng rén duì èliè huánjìng, nánshòu hé téngtòng de nài shòu lì tíshēng dànǎo de gè zhǒng nénglì, bāokuò jìyìlì kòngzhì sīxù, pànduàn nénglì hé gòng qíng nénglì jiǎnhuǎn yālì, jiāolǜ, yōulǜ děng fùmiàn qíngxù zēngjiā shēntǐ nèi de lì xiàn tǐ yánhuǎn shuāilǎo hé yùfáng lǎonián chīdāi zhèng zuìhòu, míngxiǎng hái kěyǐ jiāqiáng rénmen duì zìjǐ hé tārén yǒu'ài de tàidù yǐshàng, shì kēxué dé chū de jiélùn wǒ suīrán zhǐ kāishǐ míngxiǎng sān gè yuè yě méiyǒu tèbié qù cèshì zìjǐ shēntǐ hé dànǎo děng shēnglǐ shàng de biànhuà dànshì zǒngtǐ de gǎnjué jiùshì yuè lái yuè hǎo wǒ gèrén tǐyàn lǐmiàn zuìdà de gǎnshòu shì: Míngxiǎng bāngzhù wǒ “huó zài dāngxià” tíshēngle wǒ de zhuānzhù lì ràng wǒ zài bù míngxiǎng zuò qítā shìqíng de shíhòu yě biàn dé fēicháng mǐnjié gāoxiào nèixīn chángcháng gǎndào hěn píngjìng, wúlùn shēnbiān fāshēngle shénme shìqíng kàn qǐlái zài zāogāo de shìqíng, wǒ de qíngxù yě néng bǎochí dàndìng zài míngxiǎng de guòchéng zhōng, dāng wǒ bǎ zhùyì lì fàng zài zìjǐ de shēntǐ shàng shí huì bù zìjué de gǎn'ēn zìjǐ yǒngyǒu jiànkāng de shēntǐ dāng wǒ dīngzhe shūzhuō shàng de yī pén zhíwù míngxiǎng rènzhēn dì kànzhe měi yīpiàn yèzi, yèzi shàngmiàn qīngxī de màiluò tā de wénlù, yī zhǒng duì shìjiān wànwù de ài jiù huì màn man yìchūlái dāng wǒ bǎ míngxiǎng hé sànbù jiéhé zài yīqǐ jiù huì tèbié de zhuānzhù yú, zhōuwéi de huánjìng huì fāxiàn guòqù bùcéng zhùyì dào de dōngxī xiàng shì, shùcóng lǐ de yětù, hú lǐ de shuǐcǎo, shùnzhe shuǐbō yáodòng wǒ hěn zìrán dì gǎndào kuàilè, ránhòu gèng duō měimiào de shìqíng yě suí zhī fāshēng bǐrú túrán kànjiàn wǒ xǐhuān de xiǎo gǒu, lùshàng yù dào lǎo péngyǒu, huòzhě zài dà zǎoshang, ǒuyù yī chǎng làngmàn de qiúhūn zhège shíhòu nǐ kěnéng xiǎng wèn míngxiǎng yǒu huàichu ma? Dá'àn shì: Méiyǒu! Tā zhǐyào huā nǐ shí fēnzhōng zhège shíjiān kěnéng hái bùgòu shuā wán yībiàn péngyǒu quān. Míngxiǎng bùshì yīnggāi pánzhe tuǐ xiàng dǎzuò yīyàng ma? Míngxiǎng jùtǐ yīnggāi zěnme zuò ne? Qíshí bìng méiyǒu tèbié de yāoqiú, quán píng zìjǐ gāoxìng, zhǐyào zhuānzhù jiù hǎo míngxiǎng de shíjiān kě cháng kě duǎn kāishǐ de shíhòu kěnéng lián 5 fēnzhōng yě jìng bù xiàlái méiyǒu guānxì nǎpà 1 fēnzhōng yě hǎo dāng nǐ kāishǐ xíguàn bìngqiě xǐhuān shàng míngxiǎng de zhuàngtài jiù huì bù zìjué de jiā cháng shíjiān shènzhì juédé bàn gè xiǎoshí yěguò dé hěn kuài wǒ zuìchū zhǐ shè dìng 10 fēnzhōng jīběn shàng dào 7 fēnzhōng de shíhòu yǐjīng kāishǐ pínfán de kàn shǒubiǎo ér xiànzài wǒ míngxiǎng dōu shì 20–25 fēnzhōng zuǒyòu yǒushí wǒ zhēng kāi yǎnjīng, gǎnjué gòule yī kàn shǒujī, nàozhōng zhènghǎo xiǎngqǐ lái míngxiǎng zēngqiángle wǒ gǎnzhī shíjiān de nénglì zài rènhé dìfāng dōu kěyǐ míngxiǎng zài chuángshàng tǎngzhe (kě bié ràng zìjǐ shuìzhe ó) shàngbān xiūxí de jiànxì, kěyǐ zài yǐzi shàng zuòzhe míngxiǎng huòzhě zài dìshàng dǎzuò zuì kāishǐ xuǎnzé ānjìng bù bèi dǎrǎo de shìnèi yīduàn shíjiān yǐhòu, kěyǐ qù hùwài shènzhì xuānnào dì dìfāng, zǒu zài lùshàng yě kěyǐ zhǐyào xuǎnzé ānquán de huánjìng jiù hǎo bǐrú gōngyuán de bùdào, zǒngzhī, méiyǒu xiànzhì xuǎn zìjǐ xǐhuān dì dìfāng yǒurén shènzhì huì zài zìjiā hòuyuàn zuò yīgè míngxiǎng de táizi, chuàngzào yíshì gǎn míngxiǎng de pínlǜ yěshì yīn rén ér yì wǒ tōngcháng měitiān zǎoshang zuò yīcì rúguǒ wàngjìle, yě méiyǒu guānxì qiān wàn bùyào bǎ tā dàngchéng rènwù hé fùdān dāngrán, chūqí yuànyì měitiān dǎkǎ lái yǎng chéng xíguàn yě hěn hǎo xuǎnzé zài zǎoshang zuò, kěyǐ zài yītiān kāishǐ zhīqián bì kāi suǒyǒu hái wèi fāshēng de fánrǎo wèi xīn de yītiān tiáozhěng hǎo xīntài, dàngtiān yǒu jīhuì hái kěyǐ zuò jǐ cì duǎn de míngxiǎng, wéichí hǎo de zhuàngtài kāishǐ de shíhòu, zuì hǎo xuǎnzé yǔyīn yǐndǎo huì bǐjiào néng bāngzhù rén zhuānzhù ér bù zhìyú biàn chéng chèdǐ fàngkōng huò bì zhuó yǎnjīng húsīluànxiǎng yīduàn shíjiān guòhòu, bù zài xūyào yǔyīn yǐndǎo jiù kěyǐ huàn chéng shūhuǎn fàngsōng de yīnyuè huò bái zàoyīn shènzhì gāncuì bùyòng yīnyuè, lián yǎnjīng yě kěyǐ zhēng kāi. Dà duōshù qíngkuàng xià, míngxiǎng ràng rén bǎ zhùyì lì fàng zài hūxī shàng gǎnshòu kōngqì cóng bíqiāng jìnrù shēntǐ, zài chūqù yěyǒuxiē míngxiǎng ràng rén cóng tóupí màn man de yòng zhùyì lì huàguò quánshēn dào jiǎodǐ wǒ gèrén juédé zhèxiē dōu shì bāngzhù wǒmen jízhōng zhùyì lì bìngqiě gǎnshòu shēntǐ de fāngfǎ, zhēnzhèng de míngxiǎng yě méiyǒu tèdìng de yāoqiú zhǐyào bǎ zhùyì lì jízhōng zài yīgè zìjǐ gǎnjué shūfú dì dìfāng jiù hǎo zài zhège guòchéng zhōng chǎnshēng hěnduō zániàn shízài shì tài zhèngcháng bùguòle jíshǐ shì míngxiǎng dàshī, yě wúfǎ zuò dào měi yīcì míngxiǎng dōu néng jìnrù wú rén zhī jìng dànshì wǒmen yào liànxí de zhòngdiǎn jiùshì měi cì yǒule yīgè niàntou jiù fàng tā zǒu, bùyào huíxiǎng, yě bùyào zéguài zìjǐ bùgòu zhuānxīn qīng qīng de bǎ zhùyì lì zài nuó huí yuánlái dì dìfāng, qīngkōng dànǎo zhèxiē wǔhuābāmén de niàntou bāokuò jīn wǎn chī shénme shàng cì kàn dào de yīfú hǎo piàoliang xiǎng mǎi,5 tiānhòu yǒu mén kǎoshì shènzhì shì nǐ hènbudé lìkè qù zuò de shìqíng, dànshì bùyào guǎn tāmen wǒmen de shēnghuó qíshí bìng méiyǒu shé me bìxū mǎshàng zuò de shìqíng píngshí yuè jiāolǜ de rén, yuè shì jìng bù xiàlái yuè shì xǐhuān jìhuà, xiǎngzhe míngtiān zuò shénme wèilái zuò shénme de rén yuè shì wúfǎ wěn zhù zài yǎnxià de zhè yī miǎo míngxiǎng de guòchéng yěshì shěnshì zìjǐ xiǎngfǎ de guòchéng wǒmen huì fāxiàn huì fāxiàn hěnduō wúyòng de xìnxī jiù zhèyàng zài wǒmen de dànǎo lǐ dàochù liúdòng zhànjù dànǎozhe de kōngjiān, sǔnhàozhe wǒmen de jīnglì lìrú zuótiān kàn dào de xīnwén, běnlái kànguò jiù gāi wàngle kěshì míngxiǎng de shíhòu huì mòmíngqímiào de tiào chūlái bié zàiyì, ràng tā guòqù jiù hǎo, bié huíwèi zhè shíhòu, hái huì yǒu fēicháng bàng de diǎnzi mào chū lái kěnéng zuìjìn yīzhí wéi mǒu jiàn shìqíng fánnǎo, dé bù dào jiějué míngxiǎng de shíhòu línggǎn jiù shǎnxiàn chū lái guòqù de wǒ shì yīgè yǒu shé me xiǎngfǎ jiù lìkè ná chū bǐjì xiàlái de rén fǎngfú qiǎngpò zhèng yībān, hàipà cuòguò rènhé de línggǎn dànshì míngxiǎng ràng wǒ míngbái, bùyòng pà hǎo de niàntou yě xiān ràng tā zǒu, tā huì zài huílái de zài bù míngxiǎng, dànǎo hěn qīngxī de gōngzuò zhuàngtài xià ràng rén língguāng yī shǎn de diǎnzi yīdìng huì zàidù guānglín de jīngguò yīduàn shíjiān de míngxiǎng zhīhòu, wǒ kěyǐ kāishǐ zuò yújiāle yújiā shì yídòng de míngxiǎng céngjīng wǒ shì yīgè xǐhuān jùliè yǒu yǎng yùndòng de rén xiànzài cái yìshí dào, nà dàgài yěshì wǒ yòng lái duìkàng zìjǐ jiāolǜ de fāngfǎ kěshì duànliàn shēntǐ yīnggāi bǎ gè zhǒng yùndòng de jiéhé zài yīqǐ jì yǒu kuàisù de yě yǒu huǎnmàn de, cáinéng dádào zuì jiā zhuàngtài míngxiǎng shíhòu de sīxīn zániàn jiù xiàng wǒmen qiánjìn fāngxiàng zhōng yù dào de gè zhǒng gānrǎo hé zǔ'ài bǎochí zhù zìjǐ de zhùyì lì jiù néng bǎochí zhù shēnghuó de zhòngxīn hé nèixīn zhēnzhèng de xiǎng yào huǎnmàn què jiāndìng dì wǎng qián zǒu wǒ suīrán zhǐ zuòle hěn yīduàn hěn duǎn de shíjiān de míngxiǎng dànshì hěn quèdìng tā jiāng huì biàn chéng wǒ jīnhòu de shēnghuó de rìcháng xiàng chīfàn shuìjiào yīyàng, wǒ fēicháng qídài zài shíjiān de tuīyí xià wǒ kěyǐ xiūliàn dào gèng gāo de jìngjiè, jìnrù gèng gāo de wéidù jīntiān zhège shìpín jiù liáo dào zhèlǐ xièxiè dàjiā",
        chinese: `Hello! 大家好！我是Lindsey，
        今天這個視頻，我們來聊一下冥想。
        冥想有哪些好處？
        怎麼冥想？
        我冥想了3個月以後有哪些感覺？
        我相信大家多多少少都聽說過冥想這個詞
        有些人覺得它很遙遠，是一種宗教的儀式
        甚至有些被神化了
        另一些人雖然知道冥想有很多好處
        可對他們來說，就算是安靜地待個幾分鐘也很困難
        幾個月前的我也是這樣
        一直以來總有念頭層出不窮
        竟然也能夠在一段時間的訓練之後深刻地體會到了
        冥想給我從身體到心靈帶來的清淨與提升
        可冥想有什麼好處呢？
        以下提到的一些冥想的好處
        全部都是有科學研究作為依據的
        我只簡單羅列幾點
        有些好處需要更長時間的練習才會有明確的感受，
        有些好處在做完冥想當下就能被察覺
        冥想的好處包括：
        增強人對惡劣環境，難受和疼痛的耐受力
        提升大腦的各種能力，包括記憶力
        控制思緒，判斷能力和共情能力
        減緩壓力，焦慮，憂慮等負面情緒
        增加身體內的粒腺體
        延緩衰老和預防老年癡呆症
        最後，冥想還可以加強人們對自己和他人友愛的態度
        以上，是科學得出的結論
        我雖然只開始冥想三個月
        也沒有特別去測試自己身體和大腦等生理上的變化
        但是總體的感覺就是越來越好
        我個人體驗裡面最大的感受是：
        冥想幫助我“活在當下”
        提升了我的專注力
        讓我在不冥想做其他事情的時候也變得非常敏捷高效
        內心常常感到很平靜，無論身邊發生了什麼事情
        看起來再糟糕的事情，我的情緒也能保持淡定
        在冥想的過程中，當我把注意力放在自己的身體上時
        會不自覺地感恩自己擁有健康的身體
        當我盯著書桌上的一盆植物冥想
        認真地看著每一片葉子，葉子上面清晰的脈絡
        它的紋路，一種對世間萬物的愛就會慢慢溢出來
        當我把冥想和散步結合在一起
        就會特別地專注於，周圍的環境
        會發現過去不曾注意到的東西
        像是，樹叢裡的野兔，湖里的水草，順著水波搖動
        我很自然地感到快樂，然後更多美妙的事情也隨之發生
        比如突然看見我喜歡的小狗，
        路上遇到老朋友，或者在大早上，偶遇一場浪漫的求婚
        這個時候你可能想問
        冥想有壞處嗎？
        答案是： 沒有！它只要花你十分鐘
        這個時間可能還不夠刷完一遍朋友圈。
        冥想不是應該盤著腿像打坐一樣嗎?
        冥想具體應該怎麼做呢？
        其實並沒有特別的要求，全憑自己高興，只要專注就好
        冥想的時間可長可短
        開始的時候可能連5分鐘也靜不下來
        沒有關係哪怕1分鐘也好
        當你開始習慣並且喜歡上冥想的狀態
        就會不自覺地加長時間
        甚至覺得半個小時也過得很快
        我最初只設定10分鐘
        基本上到7分鐘的時候已經開始頻繁地看手錶
        而現在我冥想都是20–25分鐘左右
        有時我睜開眼睛，感覺夠了
        一看手機，鬧鍾正好響起來
        冥想增強了我感知時間的能力
        在任何地方都可以冥想
        在床上躺著（可別讓自己睡著哦）
        上班休息的間隙，可以在椅子上坐著冥想
        或者在地上打坐
        最開始選擇安靜不被打擾的室內
        一段時間以後，可以去戶外
        甚至喧鬧的地方，走在路上也可以
        只要選擇安全的環境就好
        比如公園的步道，總之，沒有限制
        選自己喜歡的地方
        有人甚至會在自家後院做一個冥想的台子，創造儀式感
        冥想的頻率也是因人而異
        我通常每天早上做一次
        如果忘記了，也沒有關係
        千萬不要把它當成任務和負擔
        當然，初期願意每天打卡來養成習慣也很好
        選擇在早上做，可以在一天開始之前避開所有還未發生的煩擾
        為新的一天調整好心態，
        當天有機會還可以做幾次短的冥想，維持好的狀態
        開始的時候，最好選擇語音引導
        會比較能幫助人專注
        而不至於變成徹底放空或閉著眼睛胡思亂想
        一段時間過後，不再需要語音引導
        就可以換成舒緩放鬆的音樂或白噪音
        甚至乾脆不用音樂，連眼睛也可以睜開。
        大多數情況下，冥想讓人把注意力放在呼吸上
        感受空氣從鼻腔進入身體，再出去
        也有些冥想讓人從頭皮慢慢地用注意力劃過全身到腳底
        我個人覺得這些都是幫助我們集中註意力
        並且感受身體的方法，真正的冥想也沒有特定的要求
        只要把注意力集中在一個自己感覺舒服的地方就好
        在這個過程中產生很多雜念實在是太正常不過了
        即使是冥想大師，也無法做到每一次冥想都能進入無人之境
        但是我們要練習的重點就是每次有了一個念頭
        就放它走，不要回想，也不要責怪自己不夠專心
        輕輕地把注意力再挪回原來的地方，清空大腦
        這些五花八門的念頭包括今晚吃什麼
        上次看到的衣服好漂亮想買，5天后有門考試
        甚至是你恨不得立刻去做的事情，但是不要管它們
        我們的生活其實並沒有什麼必須馬上做的事情
        平時越焦慮的人，越是靜不下來
        越是喜歡計劃，想著明天做什麼
        未來做什麼的人
        越是無法穩住在眼下的這一秒
        冥想的過程也是審視自己想法的過程
        我們會發現會發現很多無用的信息
        就這樣在我們的大腦裡到處流動
        佔據大腦著的空間，損耗著我們的精力
        例如昨天看到的新聞，本來看過就該忘了
        可是冥想的時候會莫名其妙地跳出來
        別在意，讓它過去就好，別回味
        這時候，還會有非常棒的點子冒出來
        可能最近一直為某件事情煩惱，得不到解決
        冥想的時候靈感就閃現出來
        過去的我是一個有什麼想法就立刻拿出筆記下來的人
        彷彿強迫症一般，害怕錯過任何的靈感
        但是冥想讓我明白，不用怕
        好的念頭也先讓它走，它會再回來的
        在不冥想，大腦很清晰的工作狀態下
        讓人靈光一閃的點子一定會再度光臨的
        經過一段時間的冥想之後，我可以開始做瑜伽了
        瑜伽是移動的冥想
        曾經我是一個喜歡劇烈有氧運動的人
        現在才意識到，那大概也是我用來對抗自己焦慮的方法
        可是鍛煉身體應該把各種運動的結合在一起
        既有快速的也有緩慢的，才能達到最佳狀態
        冥想時候的私心雜念
        就像我們前進方向中遇到的各種干擾和阻礙
        保持住自己的注意力
        就能保持住生活的重心和內心真正的想要
        緩慢卻堅定地往前走
        我雖然只做了很一段很短的時間的冥想
        但是很確定它將會變成我今後的生活的日常
        像吃飯睡覺一樣，我非常期待在時間的推移下
        我可以修煉到更高的境界，進入更高的維度
        今天這個視頻就聊到這裡
        謝謝大家`
    }
};

export default meditation;