const relievingCough = {
    videoId: '0jJf1JU52Bo',
    transcript: {
        pinyin: "chūxiàn késòu de shíhòu dì yī shíjiān xiǎngdào zhǐké nà jiù dà cuò tè cuòle wǒ lái gàosù nǐ jiùjìng wèishéme Hi péngyǒumen dàjiā hǎo wǒ shì nín de jiànkāng gùwèn jack zhōngyī shī hěn gāoxìng wǒmen yòu jiànmiànle nǐ shì bùshì zài késòu de shíhòu dì yī shíjiān xiǎngdào zhǐké yào nǐ shì bùshì zài wǎngshàng hé qítā dìfāng tīng dào yīgè zhǐké yīgè fāngfǎ kěyǐ zhǐké yòngle yǐhòu fāxiàn méiyǒuxiàoguǒ shènzhì késòu gèngjiā lìhàile késòu dàodǐ shì bùshì bìng jīntiān zhège duǎn shìpín bāngzhù nǐ jiějué yǐshàng suǒyǒu de yíhuò xìjié juédìng chéngbài qǐng nín yīdìng yào tīng dào zuìhòu bùyào lòu diào guānjiàn de nèiróng zhuǎnfā chūqù jiù kěyǐ zhēn zhēn qièqiè bāngzhù dào nǐ shēnbiān de péngyǒu hé jiārén tāmen yīyàng huì gǎnxiè nín de shànjǔ yòu dì 1 cì lái wǒ píndào de péngyǒu wǒ de jiànkāng yǎngshēng píndào hé qítā de píndào zuìdà de bùtóng shì wǒ suǒ fēnxiǎng de hěnduō jiànkāng yǎngshēng de bǎojiàn fāngfǎ yǔ zhīshì dōu shì tōngguò wǒ de línchuáng shíjiàn zìxíng tǐhuì yǒu xiào wǒ cái fèn xiǎng gěi nín rúguǒ nín qù qítā lèisì de píndào nà hěnduō zǒu ba xūyào nín zìjǐ qīngsōng chángshìle huānyíng dàjiā diǎn gè àixīn guānzhù zhèyàng wǒmen kěyǐ bǎochí liánxì hǎohuà bù duō shuō ràng wǒmen kāishǐ jīntiān de fēnxiǎng shǒuxiān hěnduō rén de guānniàn shì cuòwù de tāmen rènwéi késòu jiùshì yī zhǒng bìng suīrán hěnduō jíbìng děng huì bàn yǒu késòu bǐrú gǎnmào liúgǎn zhī qìguǎn yán fèiyán děng děng késòu běnshēn lái jiǎng tā zhǐshì yī zhǒng zhèngzhuàng quèqiè de shuō shì yī zhǒng kōngqì xùnsù cóng fèi bù páichū qīngchú hūxīdào zhōng guòliàng de fēnmì wù yètǐ fǎnshè dòngzuò yīncǐ késòu shì yī zhǒng zhòngyào de hūxī fǎnyìng jīzhì cóng zhège lǐlùn shàngqù jiǎng zhǐshì jiàn dào késòu lìjí cǎiqǔ zhǐké de fāngshì bǐrú shuō chī zhǐké yào nǐ xiǎng yī xiǎng rúguǒ lìjí zhǐké shēntǐ de fēnmì wù bǐrú dài yǒu bìngjùn de tán jiù méi fǎ jíshǐ cóng fèi bù páichū tǐwài jùhuì zài tǐnèi jiājù gǎnrǎn huòzhě shì zài huāfěn jìjié wǒmen hūxī dào bù gānjìng de kōngqì bǐrú huīchén méi yān děng děng shēntǐ huì lìkè kāiqǐ bǎohù jīzhì yòu késòu de fāngshì nǐ shuō zhège shíhòu néng zhǐké ma suǒyǐ zhǐké de shíjī hěn zhòngyào jiànyì dàjiā zài zhuānyè de yīshēng zhǐdǎo xiàlái yòngyào gěi dàjiā jǔ yīgè lìzi jiù míngbáile zài línchuáng zhōng wǒmen jiàn dào yī zhǒng bìng wèi shídào nìliú zhèng zhè zhǒng huànzhě wǎngwǎng huì róngyì fāshēng késòu de xiànxiàng jiùshì yīnwèi zài fǎn suān shí huì cìjī dào yānhóu de bùwèi zhìliáo shí gēnběn bù xūyào zhǐké zhǐyào zhìliáo wèi shídào nìliú zhèng jiù kěyǐle suǒyǐ zhì bìng qiú běn shì duōme de zhòngyào wǒ chángcháng bèi wèn dào de yīgè wèntí wèishéme tīng dào zhǐké de piānfāng hé miàozhāo yòng zài zìjǐ shēnshang méiyǒu xiàoguǒ nà shì yīnwèi nǐ méiyǒu fèn qīngchǔ shì yóu nèizài qítā jíbìng dǎozhì de késòu huò shì yóu wàigǎn yīnsù dǎozhì de késòu wèilái yīnsù yě yào fēn fēnghán huòzhě shì fēng rè zhèyàng jiù fēicháng qīngchǔ liǎo rúguǒ shì nèizài qítā jíbìng dǎozhì de késòu zhìliáo qítā de jíbìng késòu zìrán jiù xiāoshī shì fēnghán késòu dǎozhì de háishì fēng rè suǒ dǎozhì de duìzhèng zhìliáo xiàoguǒ cái hǎo zài línchuáng de guānchá zhōng lái kàn 80%dào 90 dōu shì yóu gǎnshòu fēnghán suǒ dǎozhì de késòu súhuà shuō jiùshì bèibù shòuliángle zhège shíhòu zhǐyào yòng yīxiē wēn fèi zuòyòng di yào xiàoguǒ jiù hěn hǎo bǐrú chángyòng de zhì gāncǎo gān jiāng zhī lèi de míngzì jiào gāncǎo gān jiāng tāng jiùshì yòng lái wēn fèi sàn hán tán de jiànyì dàjiā zài yīshēng de zhǐdǎo xià yòngyào duì yòngliàng de bǎwò cái gòu zhǔnquè hěnduō péngyǒu dōu tīng shuōguò chuān bèi zhēng lí néng zhǐké huà tán yòu késòu jiù yòng dànshì hūlüèle chuān bèi běnshēn shì hán xìng de běnlái késòu jiùshì yóu shòu hán yǐnqǐ de zài jiā shàng hánliàng de lí chuān bèi mǔ xiàoguǒ jiù bù hǎole zhège shíhòu yīnggāi yòng huājiāo zhēng lí huājiāo shì xīn rè de zhènghǎo yòng lái sàn hán hái yào tíxǐng dàjiā lí pí bùyào diūdiào hěnduō gōngxiào chéngfèn zài lí pí shàng yīqǐ chī xiàoguǒ cái gèngjiā nàme yǒurén kěndìng tíchū wèntí láile méiyǒu xuéguò yī de pǔtōng rén rúhé biànbié shì fēnghán háishì fēng rè késòu ne zhōngyī wàngwénwènqiè sì zhěn hé cān bùshì yījù liǎng jù kěyǐ jiǎng qīng chǔ de nàme dàjiā jiù jì zhù zuì zhòngyào de qūbié diǎn suíhòu shēn chūlái kàn kàn shétāi shì huáng háishì bái bái de shǔ hán huáng de shǔ rè zìjǐ zhào jìngzi jiù qīngchǔle fēnghán késòu wǒmen yòng huājiāo zhēng lí fēng rè késòu kěyǐ yòng chuān bèi zhēng lí lǚ shì lǚ xiào nǐ gǎnkuài fēicháng hǎo jīntiān yào gěi dàjiā fēnxiǎng liǎng gè fēicháng hǎo yòng de xuéwèi xùnsù huǎnjiě késòu de zhèngzhuàng bùguǎn shì fēnghán háishì fēng rè huòzhě shì qítā jíbìng zàochéng de bùguǎn yòng gǎnkuài shōucáng qǐlái ba bié zài yòng de shíhòu yòu zhǎo bù dào zhè liǎng gè xuéwèi dōu shì fèi jīng shàng de xuéwèi yīnwèi wǒmen zhīdào késòu hé fèizàng de guānxì zhíjiē xiāngguān dì 1 gè shì yú jì xué wǒmen shǒuzhǎng shēn kāi shí shǒuzhǎng mǔzhǐ gēnbù míngxiǎn tū qǐ de wèizhì jiùshì yú jì xué àn shàngqù huì yǒu suāntòng de gǎnjué zhè jiù duìle kěyǐ yòng mǔzhǐ huòzhě shízhǐ de dì 1 zhǐ jié jìnxíng ànyā měi cì ànyā sān fēnzhōng zuǒyòu tā kěyǐ ràng hóulóng qì guǎn dédào fàngsōng zhèyàng késòu jiù huì hǎo huǎnjiěle tóngshí tā háishì chángwèi de quánxí fǎnshè qū yòu yóuyú qì xuè kěyǐ duì wèitòng biànmì yǒu bùcuò de bāngzhù zhème hǎo de xuéwèi gǎnkuài gàosù wǒ nín de péngyǒu hé jiārén ba nàgè běijīng shàng fēicháng zhòngyào de xuéwèi shì chǐ zé xué bùguǎn shì késòu qìchuǎn hóulóng gāi yǎng yī lóu zhège xuéwèi dōu kěyǐ yòng huǎnjiě de zuòyòng lái kàn jùtǐ de wèizhì wǒmen xiān zhǎodào zhǒu héng wén zài zhǒu héng wén nà cè de zhōngyāng yǒu yīgè cū jiàn zài cū jiàn wàicè jiùshì chǐ zé xué wǒmen tóngyàng yòng mǔzhǐ jìnxíng ànyā měi cì ànyā sān fēnzhōng zuǒyòu míngtiān zhū wǒ hái fāxiàn rúguǒ wǒmen shùnzhe zhège xuéwèi wǎng xià dàyuē yīcùn de jùlí āiyā huòzhě shì yòng guāshā bǎn lái guā xiàoguǒ huì gèng hǎo yīnwèi zhè yīduàn dōu zài fèi jīng shàng tèbié shì kàn dào zhè yīduàn yǒu zhǒngzhàng de péngyǒu gèng yào duō jìnxíng ànyā huòzhě guāshā zuìhòu hái yào tíxǐng dàjiā zhōng rènwéi jíbìng zhòng zài yùfáng línchuáng zhōng chángjiàn de fēnghán gǎnmào hěnduō péngyǒu shuō zìjǐ chūmén chuān de yīfú hái tǐng duō zěnme jiù hěn róngyì gǎnshòu fēnghán ne nà shì yīnwèi zuì róngyì shòu fēng dì dìfāng nǐ méiyǒu bǎ tā bǎohù qǐlái zài rén de tóu hòu bù fà jì chù yǒu fēng chí fēng fǔ xué yǒu méiyǒu zhùyì dào jiùshì yǐ fēng zì lái mìngmíng de fēng xié jiùshì yóu zhèlǐ qīnrù réntǐ de tèbié shì duìyú tǐzhí xūruò huòzhě shì yùndòng hòu chū hàn de shíhòu gèng yào bǎohù hǎo zhèxiē bùwèi qíshí wǒmen kěyǐ chuān gāo lǐng de yīfú huòzhě yòng wéijīn bǎ tā wéi qǐlái jiù yǒu hěn hǎo de bǎohù zuòyòng nǐ jì zhùle ma hěn hǎo nǐ jiù yǒu péngyǒu kěyǐ jǔyīfǎnsānle nàme gǎnmào tóutòng de shíhòu wǒmen jiù kěyǐ tōngguò àn róu zhèxiē xuéwèi bǐrú fēng chí fēng fǔ xué lái huǎnjiě zhèngzhuàng ne tóngshí hái yǒu qū fēng sàn hán de zuòyòng péngyǒumen juédé jīntiān de fēnxiǎng shíyòng bié wàngle zài diǎn yīgè zàn huānyíng zài pínglùn qū liúyán gàosù wǒ rúguǒ nǐ píngshí késòu de shíhòu huì zěnme qù zuò wǒ shì Jack tà tàshí shí fēnxiǎng jiànkāng ràng wǒmen zài jiànkāng lùshàng bù mílù wǒmen xiàqī bùjiàn bú sàn, bàibài",
        chinese: `出現咳嗽的時候第一時間想到止咳那就
        大錯特錯了
        我來告訴你
        究竟為什麼
        Hi朋友們大家好我是您的健康顧問
        jack中醫師
        很高興我們又見面了
        你是不是在咳嗽的時候第一時間
        想到止咳藥
        你是不是在網上和其他地方聽到一個止咳一個方法可以止咳
        用了以後發現沒有效果
        甚至咳嗽
        更加厲害了
        咳嗽到底是不是病
        今天這個短視頻
        幫助你解決以上所有的疑惑
        細節決定成敗
        請您一定要聽到最後
        不要漏掉關鍵的內容
        轉發出去
        就可以真真切切幫助到你身邊的朋友
        和家人
        他們一樣
        會感謝
        您的善舉
        又第1次來我頻道的朋友
        我的健康養生頻道和其他的頻道
        最大的不同是我所分享的很多健康養生的保健方法與知識
        都是通過我的臨床實踐自行體會
        有效我才分享給您
        如果您去其他類似的頻道那很多
        走吧
        需要您自己
        輕鬆
        嘗試了
        歡迎大家點個愛心關注
        這樣我們可以保持聯繫
        好話不多說讓我們開始
        今天的分享
        首先
        很多人的
        觀念
        是錯誤的
        他們認為咳嗽就是一種病
        雖然
        很多疾病
        等會伴有咳嗽
        比如
        感冒流感
        支氣管炎
        肺炎等等
        咳嗽本身來講
        他只是一種症狀
        確切的說
        是一種
        空氣
        迅速從肺部排出
        清除
        呼吸道中過量的分泌物
        液體
        反射動作
        因此
        咳嗽
        是一種重要的
        呼吸反應機制
        從這個理論上去講
        只是見到咳嗽
        立即採取
        止咳的方式
        比如說
        吃止咳藥
        你想一想如果立即止咳身體的
        分泌物比如帶有病菌的痰
        就沒法
        即使從肺部排出體外
        聚會在
        體內加劇感染
        或者是在花粉季節
        我們呼吸到不干淨的空氣
        比如灰塵煤煙等等
        身體
        會立刻開啟保護機制
        又咳嗽的方式
        你說這個時候能止咳嗎
        所以
        止咳的時機很重要
        建議大家在專業的醫生指導下來用藥
        給大家
        舉一個例子
        就明白了
        在臨床中我們見到一種病
        胃食道逆流症
        這種患者
        往往會容易發生
        咳嗽的現象
        就是因為在
        反酸食
        會刺激到咽喉的部位
        治療時根本不需要止咳
        只要治療
        胃食道逆流症就可以了
        所以治病求本
        是多麼的重要
        我常常被問到的一個問題
        為什麼
        聽到
        止咳的偏方
        和妙招用在自己身上
        沒有效果
        那是因為你
        沒有分清楚
        是由內在
        其他疾病
        導致的咳嗽
        或是由外感因素導致的咳嗽
        未來因素也要分
        風寒或者是
        風熱
        這樣就非常清楚瞭如果是內在其他疾病導致的咳嗽
        治療其他的疾病
        咳嗽自然就消失
        是風寒咳嗽導致的
        還是風熱所導致的
        對症治療效果才好
        在臨床的觀察中來看
        80%到90都是由感受風寒
        所導致的咳嗽
        俗話說就是背部受涼了
        這個時候
        只要用一些溫肺作用的藥
        效果就很好比如
        常用的
        炙甘草
        乾薑
        之類的名字
        叫甘草乾薑湯
        就是用來
        溫肺散寒
        談的建議大家在醫生的指導下用藥
        對用量的把握才夠準確
        很多朋友都聽說過
        川貝蒸梨能止咳化痰
        又咳嗽就用
        但是忽略了
        川貝本身
        是寒性的
        本來咳嗽就是由受寒引起的
        再加上
        含量的梨
        川貝母
        效果就不好了
        這個時候應該用
        花椒蒸梨
        花椒是辛熱的
        正好用來散寒
        還要提醒大家梨皮
        不要丟掉很多功效成分
        在梨皮上
        一起吃效果
        才更加
        那麼有人肯定
        提出問題來了
        沒有學過醫的普通人
        如何辨別是風寒還是風熱咳嗽呢
        中醫望聞問切四診合參不是一句兩句可以講清楚的
        那麼大家就記住最重要的區別點
        隨後伸出來看看舌苔是黃
        還是白
        白的
        屬寒
        黃的
        屬熱
        自己照鏡子
        就清楚了
        風寒
        咳嗽我們用
        花椒蒸梨
        風熱咳嗽
        可以用川貝蒸梨
        屢試屢效
        你趕快
        非常好
        今天
        要給大家分享
        兩個非常好用的穴位
        迅速緩解咳嗽的症狀
        不管是
        風寒
        還是風熱
        或者是
        其他疾病造成的不管用
        趕快收藏起來吧
        別再用的時候又找不到
        這兩個穴位
        都是
        肺經上的穴位
        因為我們知道咳嗽
        和肺臟的關係
        直接相關
        第1個
        是魚際穴
        我們手掌伸開時
        手掌
        拇指根部
        明顯
        凸起的位置
        就是魚際穴
        按上去會有
        酸痛的感覺這就對了
        可以用拇指
        或者
        食指的
        第1指節
        進行按壓
        每次按壓
        三分鐘左右
        它可以讓喉嚨
        氣管
        得到
        放鬆
        這樣咳嗽就會好
        緩解了
        同時
        他還是
        腸胃的
        全息反射區
        又由於氣血
        可以對胃痛便秘有不錯的幫助
        這麼好的學位趕快告訴我
        您的朋友
        和家人吧
        那個北京上非常重要的穴位是
        尺澤穴
        不管是
        咳嗽氣喘
        喉嚨
        該養
        一樓這個穴位都可以用
        緩解的作用
        來看
        具體的位置
        我們先找到
        肘橫紋
        在肘橫紋
        那側的中央有一個
        粗鍵
        再粗鍵外側
        就是
        尺澤穴
        我們同樣用拇指
        進行按壓
        每次按壓
        三分鐘左右
        明天珠
        我還發現如果我們順著這個穴位往下大約一寸的距離
        哎呀
        或者是用
        刮痧板來刮
        效果會更好
        因為這一段都在
        肺經上
        特別是
        看到這一段
        有腫脹的朋友
        更要
        多進行按壓
        或者刮痧
        最後還要提醒大家終認為疾病重在預防
        臨床中
        常見的風寒感冒
        很多朋友說
        自己出門穿的衣服還挺多怎麼就很容易感受風寒呢
        那是因為最容易受風的地方你沒有把他保護起來
        在人的頭後部
        髮際處有風池風府穴
        有沒有註意到
        就是以
        風字來命名的
        風邪就是由這裡
        侵入人體的
        特別是
        對於體質虛弱
        或者是運動後
        出汗的時候更要保護好這些部位
        其實我們可以穿高領的衣服或者用圍巾
        把他圍起來就有
        很好的保護作用
        你記住了嗎
        很好你就有朋友可以
        舉一反三了
        那麼感冒頭痛的時候
        我們就可以通過按揉
        這些穴位比如
        風池風府穴
        來緩解症狀呢
        同時
        還有祛風散寒的作用
        朋友們覺得今天的分享實用別忘了在
        點一個贊
        歡迎在評論區留言告訴我
        如果你平時咳嗽的時候會怎麼去做
        我是Jack
        踏踏實實分享健康讓我們在健康路上
        不迷路
        我們下期
        不見
        不散，拜拜`
    }
};

export default relievingCough;