const spaceImages = {
    videoId: '_vDNT8fbxQ0',
    transcript: {
        pinyin: "Nǐ kě zhīdào wǒmen shēnghuó zài zhège shídài yǒu duōme xìngyùn! Nénggòu yī kuī tàiyángxì zhōng gè xíngxīng de yàngzi duìyú yǔzhòu de tànsuǒ tiānwén wàngyuǎnjìng de fǎ míngxiǎnrán shì yīgè zhòngyào de jiédiǎn zài cǐ zhīhòu wǒmen fǎngfú cái zhēng kāile yǎnjīng nǐ zhǔnbèi hǎo hé wǒ yīqǐ qù guāncè nǐ cóng wèi jiànguò de tàiyángxìle ma? Kàn dào rúcǐ chūsè de túxiàng nǐ yīdìng huì bèi zhènhàn tàiyáng yǐ tā dúyīwú'èr de wángzhě dìwèi tǒngzhìzhe zhěnggè tàiyángxì suǒyǒu tiāntǐ de yùnxíng dū bèi tā ānpái de jǐngjǐngyǒutiáo tā zhèng yǐ měi miǎo yī wàn yì kē hédàn de néngliàng ránshāo qí zhìliàng zhànjù tàiyángxì zǒng zhìliàng de 99.86% Zhè shì zhīshì diǎn yīdìng yào láojì qítā de bādà xíngxīng, ǎi xíngxīng, xiǎo xíngxīng, wèixīng, liúxīng, huìxīng, kēyībó dài de xiǎo tiāntǐ, xīngjì chén'āi…… dōu jiā zài yīqǐ yě cái zhàn dào 0.14% Tàiyáng zuì shēngdòng de yǐngxiàng zhī yī shì yóu tàiyáng dònglì xué guāncè zhàn yú 2012 nián 8 yuè 31 rì suǒ pāishè dāngshí héngxīng dàqì zhòng pánxuánzhe de wùzhí cháng sī pēnfā dào wài céng kōngjiān zhè cì zhìmìng de rìmiǎn wùzhí pāoshè yǐ měi miǎo 1500 gōnglǐ de sùdù xíngchéngle xuànlì duōcǎi de tàiyáng guāng dài zuì jiējìn tàiyáng de xíngxīng—shuǐxīng duōnián yǐlái rénmen duì shuǐxīng de yánjiū cóng wèi sōngxièguò dà dàxiǎo xiǎo de tàncè qì bùduàn xiàng shuǐxīngjìnfā shuǐxīng yě zài yīcì yòu yīcì kāntàn guòchéng zhōng dài gěi wǒmen yì xiǎngbùdào de jīngxǐ zài shuǐxīng biǎomiàn nénggòu kàn dào fùgàizhe dà dàxiǎo xiǎo xíngzhuàng gè yì de yǔnshí kēng kǎ luò lǐsī péndì shì shuǐxīng biǎomiàn zuì míng xiǎn de biāozhì zhège jùdà de yǔnshí kēng kuāndù dàyuē wèi 1300 gōnglǐ shì zài 36 yì nián yǐqián yǒuyī kē zhíjìngwèi 100 gōnglǐ zuǒyòu de xiǎo xíngxīng zhuàngjí suǒ xíngchéng wèile jìnyībù pāishè shuǐxīng biǎomiàn gāoqīngxī túxiàng jíjiāng jiéshù rènwù de xìnshǐ hào zài 2015 nián 1 yuè 21 rì zuìhòu yīcì diǎnrán qí zhù tuī qì ràng tàncè qì yǐ fēicháng jìn de jùlí gāo qiángdù gōngzuò 3 gè yuè yǐ pāishè shuǐxīng tèxiě jìngtóu 2015 nián 4 yuè 30 rì xiàwǔ 3 diǎn 26 fēn “xìnshǐ hào” yǐ zhuàngjí shuǐxīng de fāngshì jiéshù qí tàncè shǐmìng zài shuǐxīng běijí fùjìn liú xià yīgè zhíjìng dàyuē 15 mǐ de zhuàngjí kēng huòdéle chāoguò 20 duō wàn zhāng shuǐxīng biǎomiàn de qīngxī túxiàng tā zuìhòu pāishè de túxiàng chuán huí dìqiú chéngwéile zhìjīn wéizhǐ fēnbiàn lǜ zuìgāo de shuǐxīng dìbiǎo túpiàn céngjīng wǒmen yīdù rènwéi shuǐxīng shì zuì rè de xíngxīng yīnwèi tā lí tàiyáng zuìjìn rán'ér lí tàiyáng dì èr jìn de jīnxīng cái shì wǒmen tàiyángxì zhōng wēndù zuìgāo de xíngxīng bèi tàiyáng de yúrè zhì kǎo de yóurú dìyù yībān jīnxīng de dàqìcéng hòuzhòng, nóngmì ér qítè dàqì de zhǔyào chéngfèn shì èryǎnghuàtàn yuē zhàn 97%yǐshàng lìng yǒu yuē 3%de dàn dàqì mìdù shì dìqiú de 100 bèi lìng rén nányǐ zhìxìn de shì zài jīnxīng biǎomiàn shàngkōng sānsìshí gōnglǐ fànwéi nèi suǒ mìbù de nóng yún jìngrán shì yóu nóng liúsuān wù zǔchéng dàqì hěn bù píngjìng jīngcháng chūxiàn shǎndiàn hé léibào fēngsù suí gāodù de shàngshēng ér zēngjiā zài 60 duō gōnglǐ de gāokōng fēngsù kě dá 100m/s shì dìqiú shàng 12 jí táifēng sùdù de 3 bèi duō zhè céng “yún” láizì tàiyáng de rèliàng “táo” huí dào wài céng kōngjiān yěshì wèishéme jīnxīng nénggòu bùduàn xīshōu láizì tàiyáng de rèliàng bìng biàn dé yuè lái yuè rè de yuányīn shàng gè shìjì 60 niándài sūlián wèile tànsuǒ jīnxīng huāle 23 nián zhìzàole 18 gè biǎomiàn jīngguò tèshū chǔlǐ de jīnshǔ tàncè qì jìnrù dào zhège gāodá 500℃de zhìrè shìjiè cóng “jīnxīng 13 hào” kāishǐ tàncè qì bùjǐn duì jīnxīng dì dìxíng jìnxíngle sǎomiáo fēnxī érqiě hái guānchá dàole jīnxīng yǒu dìzhèn xiànxiàng zhèngmíng zhè kē xīngqiú qíshí shì “huózhe de” rán'ér tàncè qì jìnhū biàntài bān de shèjì yě jǐnjǐn zhǐ wèi “jīnxīng 13 hào” de tàntóu huàn láile 30 fēnzhōng de shòumìng zài zhè 30 fēnzhōng nèi pāishèle dàliàng de jīnxīng cǎisè túpiàn bìng zài 127 fēnzhōng nèi chíxù gōngzuò chuán huí dào dìqiú tōngguò zhèxiē cǎisè de túxiàng ràng wǒmen hěn hǎo de liǎojiě dàole jīnxīng biǎomiàn de qíngkuàng jiēzhe wǒmen lái dào jùlí tàiyáng dì 3 yuǎn de xíngxīng shì yǐ zhī wéiyī cúnzài shēngmìng dì dìfāng zhìjīn wéizhǐ wǒmen duì dìqiú de tànsuǒ yǐjīng shì fēicháng quánmiànle xiàndài de rénzào wèixīng kěyǐ zhàoshè dào dìqiú de měi yīgè jiǎoluò jiù xiàng zhè zhāng láizì měiguó guójiā hángtiān jú de túxiàng yīyàng zài dìqiú shàngkōng 35000 gōnglǐ chù pāishè kěyǐ qīngchǔ de pāishè dào dàlù bǎnkuài zuòluò zài zhè kē wèilán de xīngqiú shàng 2020 nián 12 yuè 14 rì NASA bǔhuòle yīcì rì quánshí yuèqiú de yīnyǐng lóngzhàozhe zhìlì hé āgēntíng jiāng báo báo de tǔdì dài rù duǎnzàn de wǔjiān hēi'àn zhōng nàxiē jīnglì rì quánshí de rén piējiànle zhèngzài yùndòng de tàiyángxì zài rì shí qíjiān yuèliàng chuānguò tàiyáng hé dìqiú fùgàile tàiyáng de míngliàng miàn zhè shì zài guójì kōngjiānzhàn pāishè dào dì dìqiú shàng zuì bàoliè de fēngbào jǐngguān suízhe fēngbào juǎnguò rénqún fēnbù mìjí de chéngzhèn chūxiànle kěpà de pòhuài jǐngxiàng zhè shì ràng rén jìng wèi de zìrán zhī lì zhè duàn ràng rén zhànlì de jìngtóu shì yóu 350 duō zhāng zài kōngjiānzhàn pāishè de túxiàng zǔchéng huàmiàn jiéwěi chù xiàngjī fàngdà dào fēngbào yǎn yīgè dàzhì yuán xíng de qūyù jiēshìle zhè zhǒng pòhuài xìng zìrán lìliàng wéiyī de píngjìng qūyù 2014 nián guójì kōngjiānzhàn shàng de yǔháng yuán pāishèle yī zhāng zhuàngguān de zhàopiàn sǎhālā shāmò zuòwéi dìqiú shàng zuìdà de shāmò qún tā de zhènhàn zài tàikōng wǎng xià kàn shí xiǎndé línlíjìnzhì zhè yī zhāng miányánle shù bǎi gōnglǐ de dà guīmó shāchénbào túpiàn zài wǎngshàng liúchuán jùdà gāosǒng de yúnduǒ lóngzhàozhe zhěnggè fēizhōu biǎomiàn shǐdé huǎngrán zhī zhōng zhè kē xīngqiú jìng yǔ huǒxīng xiàng shì méi cuò wǒmen jiē xiàlái zhēn de yāo fēi wǎng huǒxīng 2 yuè 5 rì zhōngguó guójiā hángtiān jú fābùle tiān wèn yī hào tàncè qì pāishè de shǒu zhāng huǒxīng zhàopiàn zài zhè zhāng jùlí huǒxīng 220 wàn gōnglǐ wài pāishè dào de zhàopiàn shàng néng yīxī kàn dào huǒxīng de jīngdiǎn dìmào dàn dàjiā yě tóngshí fāxiàn zhè zhāng zhàopiàn bìng bù qīngxī érqiě háishì hēibái de hé wǒmen chángjiàn de huǒxīng cǎisè zhàopiàn dàxiāngjìngtíng nàme nàxiē qù huǒxīng “lǚyóu” de tàncè qì dūhuì dàizhe xiàngjī tāmen pāishè dào de huǒxīng zhàopiàn wèishéme chābié huì nàme dà? Shènzhì yú wǎngyǒumen hái kāizhǎnle yī chǎng huǒxīng PS dàsài qíshí yuányīn yě hěn jiǎndān bìng bùshì jìshù gēn bù shàng tiān wèn yī hào húnshēn shang xià xiédàile yī dà piào guāngxué xiàngjī shèbèi zǒu dào nǎlǐ dōu bù huì wàngle pāizhào qízhōng bùfá jùyǒu shìjiè lǐngxiān shuǐpíng de gāo fēn xiàngjī rúguǒ tàncè qì pāishè de shì cǎisè zhàopiàn nàme wǒmen jiù zhǐ néng bǔzhuō dào kějiànguāng ér rúguǒ pāi xià hēibái zhàopiàn zé néng pāishè dào bùtóng bōcháng xià de tiāntǐ huò qítā yīxiē wèizhī shìwù lìyú fāxiàn gèng duō kěnéng xìng 2021 nián 5 yuè 19 rì guójiā hángtiān jú fābù tiān wèn yī hào rènwù tàncè qì zhuólù guòchéng liǎng qì fēnlí hé zhuólù hòu huǒxīng chē pāishè de yǐngxiàng túxiàng zhōng zhuólù píngtái hé “zhùróng hào” huǒxīng chē shǐ lí pō dào, tàiyáng yì, tiānxiàn děng bùjiàn zhǎnkāi zhèngcháng dàowèi mùqián zhùróng hào zhèngzài kāizhǎn shǐ lí zhuólù píngtái de zhǔnbèi gōngzuò hòuxù bùjǐn yào pāi xià huǒxīng de fēngjǐng hái yào yòng xiédài de 6 tái kēxué zǎihé duì huǒxīng jìnxíng shēnrù tàncè bǎ gèng duō de kēxué shùjù zhuàn huí dìqiú zhè kěshì bǐ jiǎndān pāizhào gèngjiā zhòngyào jǐn jiēzhe ràng wǒmen qiánwǎng tàiyángxì zhōng zuìdà de qìtài jùxíngxīng mùxīng měiguó de zhū nuò hào tàncè qì 2016 nián jìnrù mùxīng guǐdào xiàng rénlèi fā sòng liǎo bù shǎo mùxīng de tàncè zīliào 2017 nián 7 yuè 10 rì zhū nuò hào fēichuán pāishè dàole yī zhāng yǒushǐ yǐlái mùxīng biǎomiàn zuìdà guīmó de fēngbào túxiàng zài zhè zhāng túpiàn shàng wǒmen kěyǐ bǔzhuō dào yī dà kuài hóngbān zài cǐ zhīhòu gèng duō bùkěsīyì de túpiàn chuán huí liǎng nián hòu de 2019 nián hā bó wàngyuǎnjìng bǔzhuō dào mùxīng biǎomiàn xiǎnshì chū dà hóngbān zhèngzài suōxiǎo ér xiàmiàn zhège shì nǐ cóng dìqiú shàng hé qítā xīngqiú kàn bù dào de tiānwénxué jiā wèi cǐ dōu gǎndào shífēn jīngyà tā shì yóu bā gè fēngbào zǔchéng yīgè wěndìng de xìtǒng bèi jīngquè de bùzhì zài mùxīng běijí tú zhōng yǐn rén zhùmù dì shì guànchuān mùxīng xiácháng de wù zhuàng céng mùqián hái bù qīngchǔ zhège xiànxiàng dàodǐ shì zěnme zàochéng de rénlèi duìyú mùxīng de liǎojiě háishì tài shǎole bùguò duì pǔtōng rén lái shuō kàn dào mùxīng gāo qīng měi tú de dì yī gǎnjué jiù xiàng shì kàn dào yī fú yóuhuà yǒurén chēngzànzhe xiàng shì fàn gāo míng huà “xīngkōng” zài zhěnggè tàiyángxì zhōng tǔxīng de gètóu er juéduì shǔyú yíngyǎngwàngshèng de lèixíng tā de dàxiǎo jǐn cì yú mùxīng kěxí kōng yǒu yīgè dà ké zi zhìliàng què wúfǎ hé mùxīng xiàng tí bìng lùn píngjūn mìdù jǐnjǐn shì měi lìfāng límǐ 0.7 Kè yóuyú mìdù dī tǔxīng yǒule kěyǐ piāofú zài shuǐmiàn shàng de zīběn bǎ tǔxīng fàng zài shuǐzhōng yīdìng bù huì xià chén dàn dàodǐ yào duōdà de shuǐmiàn cáinéng róng dé xià zhège tǐjī jùdà de jiāhuo ne? Zì tàiyángxì dànshēng yǐlái tǔxīng jīng lì liǎo wúshù gè zhòuyè jiāotì zhè yīcì láizì dìqiú de shǐzhě wǒmen zhōngshí de tànxiǎn jiā—kǎ xī ní hào dì yīcì jìn jùlí mùdǔ bìng yǐ míng'àn jiāocuò héchéng de fāngshì bǔzhuō dàole yī chǎng chénhūn gēngdié 2004 nián yǐ fēixíng 7 nián de kǎ xī ní hào chénggōng pō rù tǔxīng guǐdào zài yuǎnlí tàiyáng de hánlěng shēn kōngzhōng lìng rén zhènjīng de fǎ xiàn jiēzhǒng ér zhì tǔxīng běijí jù xíng liùjiǎo fēngbào tǔ wèi liù bōguāng lín lín de jiǎwán húbó tǔ wèi èr bīng céng pēn xiàng tàikōng dì hǎishuǐ jiéjīng 2011 nián kǎ xī ní hào yòng zhǎi jiǎo xiàngjī zài yī zhèng nèi pāishè dàole tǔxīng de wǔ kē wèixīng tǔ wèi shí zhíjìng 178 gōnglǐ wèiyú zuì zuǒ cè tǔ wèi shíqī zhíjìng 84 gōnglǐ zài A huán hé xiázhǎi de F huán zhī jiān huánrào tǔxīng yùnxíng wèiyú túpiàn zhōngyāng dàizhe míngliàng fǎnguāng de tǔ wèi èr zhíjìng 500 gōnglǐ zài túpiàn de zhōng shàngfāng tǔxīng de dì èr dà wèixīng tǔ wèi wǔ zhíjìng 1528 gōnglǐ wèiyú túpiàn yòu cè zhǐ lùchū bànbiān liǎn tǔ wèi wǔ de pángbiān shì jiào xiǎo de tǔ wèi yī zhíjìng 397 gōnglǐ 2021 nián 3 yuè 18 rì NASA gē dá dé hángtiān fēixíng zhōngxīn de hā bó tuánduì fābù xīn túxiàng jiēshìle guòqù jǐ nián lǐ tǔxīng wàiguān de chāyì yǐxià dòng tú yóu hā bó tàikōng wàngyuǎnjìng fēnbié yú 2018,2019 hé 2020 nián pāishè de túxiàng héchéng jìlùle tǔxīng běibànqiú xiàjì jiéshù zhī jì de wàiguān biànhuà xiàmiàn 3 zhāng shì jìngtài túxiàng bǎn jiē xiàlái wǒmen qiánwǎng tàiyángxì zuì yuǎn de liǎng kē hánlěng ér yáoyuǎn de jù xíngxīng tiānwángxīng hé hǎiwángxīng bèi chēng wèi “bīng jùxīng” yīnwèi tāmen de nèibù jiégòu bùtóng yú mùxīng hé tǔxīng mùxīng hé tǔxīng fù hán qīng hé hài bèi chēng wèi “qìtài jù xíngxīng” cǐwài bīng jùxīng de tǐjī yě xiǎoyú qìtǐ jù xíngxīng jiè yú lèi dì xíngxīng hé qìtài jù xíngxīng zhī jiān bīng jùxīng yěshì tàiyángxì zhōng bèi tànsuǒ zuìshǎo de yī lèi xíngxīng 2004 nián yī zhāng yóu “kǎi kè wàngyuǎnjìng” pāishè de “tiānwángxīng” héchéng túxiàng pī fà biǎo zhǎnshìle bīnglěng de shìjiè hé tā de guānghuán 1986 nián 1 yuè 25 rì lǚxíng zhě 2 hào pāishè de tiānwángxīng dāngshí tā zhèng líkāi tiānwángxīng qiánwǎng hǎiwángxīng zhè shì tàiyángxì zhōng yīpiàn shénmì de kōngjiān rúguǒ dìqiú suǒ chǔ de wèizhì shì tàiyángxì wēnxīn de tíngyuàn nàme shēn chǔyú 45 yì gōnglǐ zhī wài dì hǎiwángxīng jiùshì tàiyángxì hóngwěi guódù de biānchéng tā xiàng yīgè zhōngchéng shùbiān de jiàngshì bù dòng shēngsè dì bǎohùzhe tàiyángxì de héxīn lǐngyù tā shì rúcǐ de dīdiào shènzhì zài rénlèi de shìxiàn zhōng dōu bù huì chūxiàn zài dìqiú shàng wǒmen wúfǎ tōngguò ròuyǎn zhíjiē kàn dào hǎiwángxīng shènzhì jiǎndān de wàngyuǎnjìng yě bùxíng hé tā dīdiào dì xìnggé bù xiāngfú de shì zhè kē xīngqiú de biǎomiàn bèi gāodá měi xiǎoshí 2000 duō gōnglǐ de chāo yīnsù fēng bào jiǎo dé tiānfāndìfù xiàmiàn zhè shì yī zhāng cóng dìqiú shàng pāishè dì hǎiwángxīng de xīn zhàopiàn jiǎnzhí tài shénqíle nǐ kěnéng kànguò 1989 nián pāishè de zhàopiàn dāngshí lǚxíng zhě 2 hào guǎngjiǎo xiàngjī zài jùlí hǎiwángxīng 28 wàn gōnglǐ wài yòng tòumíng lǜ guāng piàn pāishèle zhè liǎng zhāng hǎiwángxīng guānghuán de zhàopiàn zài “lǚxíng zhě 2 hào” wánchéng tā de rènwù bìng qiánwǎng xīng jì kōngjiān zhīqián yòu jìnxíngle yī cì jìn jùlí de jiējìn bìng pāi xiàle zhè zhāng zhàopiàn xiǎnshìle hǎiwángxīng dàqì zhòng míngliàng de yún wén gūlínglíng de rénlèi wèile xúnzhǎo de wài wénmíng cóng wèi tíngzhǐguò tànsuǒ de rèqíng měi dāng xiànrù mímáng wú zhù wú lù kě zǒushí bùfáng yǎng wàng xīngkōng huòxǔ jiù huì shǎo yīsī duì wèizhī de kǒngjù duō yī fēn duì wèilái de cóngróng!",
        chinese: `你可知道我們生活在這個時代有多麼幸運！
        能夠一窺太陽系中各行星的樣子
        對於宇宙的探索
        天文望遠鏡的發明顯然是一個重要的節點
        在此之後我們彷彿才睜開了眼睛
        你準備好和我一起
        去觀測你從未見過的太陽係了嗎？
        看到如此出色的圖像你一定會被震撼
        太陽以它獨一無二的王者地位
        統治著整個太陽系
        所有天體的運行都被它安排的井井有條
        它正以每秒一萬億顆核彈的能量燃燒
        其質量佔據太陽系總質量的99.86％
        這是知識點 一定要牢記
        其他的八大行星、矮行星、小行星、衛星、
        流星、彗星、柯伊伯帶的小天體、星際塵埃……
        都加在一起也才占到0.14％
        太陽最生動的影像之一是由太陽動力學觀測站
        於2012年8月31日所拍攝
        當時恆星大氣中盤旋著的物質長絲噴發到外層空間
        這次致命的日冕物質拋射以每秒1500公里的速度
        形成了絢麗多彩的太陽光帶
        最接近太陽的行星—水星
        多年以來人們對水星的研究從未鬆懈過
        大大小小的探測器不斷向水星進發
        水星也在 一次又一次勘探過程中帶給我們意想不到的驚喜
        在水星表面能夠看到覆蓋著大大小小形狀各異的隕石坑
        卡洛里斯盆地是水星表面最明顯的標誌
        這個巨大的隕石坑寬度大約為1300公里
        是在36億年以前
        有一顆直徑為100公里左右的小行星撞擊所形成
        為了進一步拍攝水星表面高清晰圖像
        即將結束任務的信使號
        在2015年1月21日最後一次點燃其助推器
        讓探測器以非常近的距離高強度工作3個月
        以拍攝水星特寫鏡頭
        2015年4月30日下午3點26分
        “信使號”以撞擊水星的方式結束其探測使命
        在水星北極附近留下一個直徑大約15米的撞擊坑
        獲得了超過20多萬張水星表面的清晰圖像
        它最後拍攝的圖像傳回地球
        成為了至今為止分辨率最高的水星地表圖片
        曾經我們一度認為水星是最熱的行星
        因為它離太陽最近
        然而離太陽第二近的金星
        才是我們太陽系中溫度最高的行星
        被太陽的餘熱炙烤的猶如地獄一般
        金星的大氣層厚重、濃密而奇特
        大氣的主要成分是二氧化碳約佔97%以上
        另有約3%的氮
        大氣密度是地球的100倍
        令人難以置信的是
        在金星表面上空三四十公里範圍內所密布的濃雲
        竟然是由濃硫酸霧組成
        大氣很不平靜經常出現閃電和雷暴
        風速隨高度的上升而增加
        在60多公里的高空風速可達100m/s
        是地球上12級颱風速度的3倍多
        這層“雲”來自太陽的熱量“逃”回到外層空間
        也是為什麼金星能夠不斷吸收來自太陽的熱量
        並變得越來越熱的原因
        上個世紀60年代蘇聯爲了探索金星
        花了23年製造了18個表面經過特殊處理的金屬探測器
        進入到這個高達500℃的炙熱世界
        從“金星13號”開始
        探測器不僅對金星的地形進行了掃描分析
        而且還觀察到了金星有地震現象
        證明這顆星球其實是“活著的”
        然而探測器近乎變態般的設計
        也僅僅只為“金星13號”的探頭換來了30分鐘的壽命
        在這30分鐘內拍攝了大量的金星彩色圖片
        並在127分鐘內持續工作傳回到地球
        通過這些彩色的圖像
        讓我們很好的了解到了金星表面的情況
        接著我們來到距離太陽第3遠的行星
        是已知唯一存在生命的地方
        至今為止我們對地球的探索已經是非常全面了
        現代的人造衛星可以照射到地球的每一個角落
        就像這張來自美國國家航天局的圖像一樣
        在地球上空35000公里處拍攝
        可以清楚的拍攝到大陸板塊坐落在這顆蔚藍的星球上
        2020年12月14日NASA捕獲了一次日全食
        月球的陰影籠罩著智利和阿根廷
        將薄薄的土地帶入短暫的午間黑暗中
        那些經曆日全食的人瞥見了正在運動的太陽系
        在日食期間
        月亮穿過太陽和地球覆蓋了太陽的明亮面
        這是在國際空間站拍攝到的地球上最爆裂的風暴景觀
        隨著風暴卷過人群分佈密集的城鎮
        出現了可怕的破壞景像這是讓人敬畏的自然之力
        這段讓人戰栗的鏡頭
        是由350多張在空間站拍攝的圖像組成
        畫面結尾處相機放大到風暴眼
        一個大致圓形的區域
        揭示了這種破壞性自然力量唯一的平靜區域
        2014年國際空間站上的宇航員拍攝了一張壯觀的照片
        撒哈拉沙漠作為地球上最大的沙漠群
        它的震撼在太空往下看時顯得淋漓盡致
        這一張綿延了數百公里的
        大規模沙塵暴圖片在網上流傳
        巨大高聳的雲朵籠罩著整個非洲表面
        使得恍然之中這顆星球竟與火星相似
        沒錯我們接下來真的要飛往火星
        2月5日中國國家航天局發布了天問一號探測器
        拍攝的首張火星照片
        在這張距離火星220萬公里外拍攝到的照片上
        能依稀看到火星的經典地貌
        但大家也同時發現這張照片並不清晰而且還是黑白的
        和我們常見的火星彩色照片大相徑庭
        那麼那些去火星“旅遊”的探測器都會帶著相機
        它們拍攝到的火星照片為什麼差別會那麼大？
        甚至於 網友們還開展了一場火星 PS 大賽
        其實原因也很簡單並不是技術跟不上
        天問一號渾身上下攜帶了一大票光學相機設備
        走到哪裡都不會忘了拍照
        其中不乏具有世界領先水平的高分相機
        如果探測器拍攝的是彩色照片
        那麼我們就只能捕捉到可見光
        而如果拍下黑白照片
        則能拍攝到不同波長下的天體或其他一些未知事物
        利於發現更多可能性
        2021年5月19日國家航天局發布天問一號任務探測器
        著陸過程兩器分離和著陸後火星車拍攝的影像
        圖像中著陸平台和“祝融號”火星車
        駛離坡道、太陽翼、天線等部件展開正常到位
        目前 祝融號正在開展駛離著陸平台的準備工作
        後續不僅要拍下火星的風景
        還要用攜帶的6台科學載荷對火星進行深入探測
        把更多的科學數據傳回地球
        這可是比簡單拍照更加重要
        緊接著讓我們前往太陽系中最大的氣態巨行星木星
        美國的朱諾號探測器2016年進入木星軌道
        向人類發送了不少木星的探測資料
        2017年7月10日朱諾號飛船拍攝到了一張
        有史以來木星表面最大規模的風暴圖像
        在這張圖片上我們可以捕捉到一大塊紅斑
        在此之後更多不可思議的圖片傳回
        兩年後的2019年哈勃望遠鏡捕捉到木星表面
        顯示出大紅斑正在縮小
        而下面這個是你從地球上和其它星球看不到的
        天文學家為此都感到十分驚訝
        它是由八個風暴組成一個穩定的系統
        被精確地佈置在木星北極
        圖中引人注目的是貫穿木星狹長的霧狀層
        目前還不清楚這個現像到底是怎麼造成的
        人類對於木星的了解還是太少了
        不過對普通人來說
        看到木星高清美圖的第一感覺就像是看到一幅油畫
        有人稱讚著像是梵高名畫《星空》
        在整個太陽系中
        土星的個頭兒絕對屬於營養旺盛的類型
        它的大小僅次於木星
        可惜空有一個大殼子
        質量卻無法和木星相提並論
        平均密度僅僅是每立方厘米0.7克
        由於密度低土星有了可以漂浮在水面上的資本
        把土星放在水中一定不會下沉
        但到底要多大的水面才能容得下
        這個體積巨大的傢伙呢？
        自太陽系誕生以來土星經歷了無數個晝夜交替
        這一次來自地球的使者
        我們忠實的探險家—卡西尼號
        第一次近距離目睹並以明暗交錯合成的方式
        捕捉到了一場晨昏更迭
        2004年已飛行7年的卡西尼號成功泊入土星軌道
        在遠離太陽的寒冷深空中令人震驚的發現接踵而至
        土星北極巨型六角風暴
        土衛六波光粼粼的甲烷湖泊
        土衛二冰層噴向太空的海水結晶
        2011年卡西尼號用窄角相機
        在一幀內拍攝到了土星的五顆衛星
        土衛十直徑178公里位於最左側
        土衛十七直徑84公里
        在A環和狹窄的F環之間環繞土星運行
        位於圖片中央
        帶著明亮反光的土衛二直徑500公里
        在圖片的中上方
        土星的第二大衛星土衛五
        直徑1528公里
        位於圖片右側只露出半邊臉
        土衛五的旁邊是較小的土衛一直徑397公里
        2021年3月18日
        NASA戈達德航天飛行中心的哈勃團隊發布新圖像
        揭示了過去幾年里土星外觀的差異
        以下動圖由哈勃太空望遠鏡
        分別於2018、2019和2020年拍攝的圖像合成
        記錄了土星北半球夏季結束之際的外觀變化
        下面3張是靜態圖像版
        接下來我們前往太陽系最遠的兩顆
        寒冷而遙遠的巨行星天王星和海王星
        被稱為“冰巨星”
        因為它們的內部結構不同於木星和土星
        木星和土星富含氫和氦被稱為“氣態巨行星”
        此外冰巨星的體積也小於氣體巨行星
        介於類地行星和氣態巨行星之間
        冰巨星也是太陽系中被探索最少的一類行星
        2004年一張由“凱克望遠鏡”
        拍攝的“天王星”合成圖像被發表
        展示了冰冷的世界和它的光環
        1986年1月25日旅行者2號拍攝的天王星
        當時它正離開天王星前往海王星
        這是太陽系中一片神秘的空間
        如果地球所處的位置是太陽系溫馨的庭院
        那麼身處於45億公里之外的海王星
        就是太陽系宏偉國度的邊城
        它像一個忠誠戍邊的將士
        不動聲色地保護著太陽系的核心領域
        它是如此的低調
        甚至在人類的視線中都不會出現
        在地球上我們無法通過肉眼直接看到海王星
        甚至簡單的望遠鏡也不行
        和它低調的性格不相符的是
        這顆星球的表面被高達
        每小時2000多公里的超音速風爆攪得天翻地覆
        下面這是一張從地球上拍攝的海王星的新照片
        簡直太神奇了
        你可能看過1989年拍攝的照片
        當時旅行者2號廣角相機在距離海王星28萬公里外
        用透明濾光片拍攝了這兩張海王星光環的照片
        在“旅行者2號”完成它的任務並前往星際空間之前
        又進行了一次近距離的接近並拍下了這張
        照片顯示了海王星大氣中明亮的雲紋
        孤零零的人類
        為了尋找地外文明
        從未停止過探索的熱情
        每當陷入迷茫無助無路可走時
        不妨仰望星空
        或許就會少一絲對未知的恐懼
        多一分對未來的從容！`
    }
};

export default spaceImages;