const joiningAStartup = {
    videoId: 'Mmet55aEpUs',
    transcript: {
        pinyin: "hello dàjiā hǎo huānyíng lái dào wǒ de píndào wǒ dàgài yǒu hěn zhǎng hěn zhǎng yīduàn shíjiān méiyǒu gēngxīnle zuìjìn yīnwèi yìqíng de yuányīn yòu gěile wǒ xiǎng yào zhìzuò shìpín de dònglì hé shíjiān chúle shíshàng chuān dā zhī wài wǒ xiǎng fēnxiǎng gèng duō guānyú zhíyè hé shēnghuó fāngmiàn de nèiróng jīntiān wǒ xiǎng hé dàjiā fēnxiǎng de nèiróng shì rúhé zhīdào zìjǐ shìfǒu shìhé chūchuàng qǐyè xiāngxìn hěnduō tóngxué dōu yǒu zhèyàng de yíwèn dà gōngsī háishì xiǎo gōngsī wǒ ne xiǎng tōngguò zìjǐ de yīxiē ge rén jīnglì hé nǐmen fēnxiǎng yīxiē wǒ de xīndé shǒuxiān ne wǒ xiān hé dàjiā fēnxiǎng xià wǒ de gèrén jīnglì 12 nián yánjiūshēng bìyè yǐhòu wǒ jiù liú zàile Pittsburgh de yījiā xiǎo gōngsī zuò shǒujī ruǎnjiàn kāifā wǒ jiārù de shíhòu hǎoxiàng shì dì yīgè nǚ chéngxù yuán ránhòu jiù kànzhe gōngsī cóng yīgè hěn xiǎo de tuánduì yīzhí dào màn man de xùnsù kuòzhāng ránhòu cáizhèng chūxiànle wéijī yīzhí dào wǒ yě yīncǐ bèi cáiyuán ránhòu wǒ jiù jiè cǐ jīhuì bān láile jiùjīnshān zài xiànzài zhè jiā gōngsī ne zuò qǐyè ruǎnjiàn wǒ dāngshí jiārù gōngsī de shíhòu ne chàbùduō hǎoxiàng yěshì 50 gèrén zuǒyòu ba ránhòu yě méiyǒu rènhé yīgè chǎnpǐn xiànzài ne bèi shōugòu qián wǒ gōngsī de yǐjīng yǒu shàng qiān duō rén ránhòu quánqiú dōu yǒu bàngōngshì suǒyǐ wǒ jiù yǒu liǎng duàn wánquán bùtóng de jīnglì dì yī duàn jiùshì hěnduō qǐ qǐfú fú suànshì yīgè shībài jīnglì ránhòu jiù kěyǐ “Learn from the worst.” Dì èr duàn jīnglìle bǐjiào wánzhěng jiùshì cóng yīgè hěn xiǎo de tuánduì yīzhí kàn tā màn man chéngzhǎng kuòzhāng érhòu yīzhí dào zuìhòu bèi shōugòu suīrán shuō méiyǒu shàngshì dànshì wǒ juédé bèi shōugòu zhège gè jiéguǒ qíshí wǒ zìjǐ hěn xǐ xǐhuān de nà jiē xiàlái wǒ jiù lái hé dàjiā fēnxiǎng yīxiē xīndé ba yīnwèi wǒ yī lù shìpín shuōhuà jiù jǐn suǒyǐ ne wǒ xūyào kàn wǒ zìjǐ de yīxiē bǐjì shǒuxiān nǐ yào sīkǎo nǐ xiǎng qù chūchuàng qǐyè de qǐdòngjī shì shénme jiù shuō nǐ yào wèn nǐ zìjǐ wèishéme wǒ wèishéme xiǎng qù bùguǎn nǐ shì gāng bìyè de xuéshēng háishì yǐjīng gōngzuò hǎoduō nián xīwàng huàn yīgè huánjìng nǐ dōu xūyào qù wèn zìjǐ wèishéme xiān xiǎng qīngchǔ zhège wèntí zài zuò juédìng nǐ de dòngjī kěyǐ shì xiǎng yào tígāo zìjǐ de jìnéng yīn wéi dà gōngsī jiùshì měi yīgè dōngxī dū yǒu hěnduō rén zài zuò kěnéng shì jǐ bǎi jǐ qiān rén zài zuò nà nǐ néng xué dào de dōngxī fēicháng shǎo ránhòu xiǎo gōngsī ba jiù kěnéng nǐ yào xué de bùjǐn shì jìshù de dōngxī nǐ kěnéng hái yào xué guānyú shìchǎng yíngxiāo de dōngxī guānyú guǎnlǐ de dōngxī jiù ràng nǐ néng hěn kuài de chéngzhǎng huòzhě nǐ xǐhuān kuài jiézòu de huánjìng wǒ juédé dà gōngsī yǒu shíhòu ràng wǒ gǎnjué yǒu zhǒng tíqián yǎnglǎo suǒyǐ wǒ nà wǒ jiù gèng xǐhuān chūchuàng qǐyè nà zhǒng kuàisù tìdài chǎnpǐn ránhòu ne jiùshì yǒuyī zhǒng gǎnjué wǒ zìjǐ hái hěn niánqīng hái hěn yǒu fènjìn huòzhě nǐ jiù xǐhuān zhège gōngsī chǎnpǐn jiù bǐrú shuō wǒ dāngnián tèbié xiǎng qù Pinterest yīnwèi zìjǐ jiù hěn xǐhuān yòng Pinterest huòzhě ne nǐ hěn yǎngmù gāi gōngsī chuàngshǐ rén jiù yǒu hěnduō Founder tā zhīqián kěnéng yǐjīng shì yǒuguò jǐ gè chénggōng de gōngsīle ránhòu tā yòu chūlái yòu zài zuò yīgè gōngsī yīgè tuánduì nǐ jiù hěn xiǎng qù jiārù tā huòzhě nǐ jiù xiǎng fācái dà duōshù xiǎng qù chūchuàng qǐyè de rén yīnggāi dōu shì bào zhuóxiǎng fācái de xīntài hái yǒu nà jiùshì bùxiǎng shuā tí wǒ jiùshì nàgè bùxiǎng shuā tí de rén jiù wǒ zài dúshū de shíhòu ba wǒ jiù wánquán méiyǒu xīn sī xiǎng qù dà gōngsī wǒ jiù yīxīn xiǎng zhǎo yīgè zìjǐ xǐhuān de chūchuàng qǐyè dì yī ne jiù xiàng wǒ shuō de bùxiǎng shuā tí yīnwèi wǒ dāngshí jìn Pittsburgh nà gōngsī wánquán jiù méiyǒu shuā tí wǒ jiù bǎ zìjǐ zài xuéxiào lǐ zuò de yīgè jǐ gè xiàngmù jiùshì jǐ gè shǒujī App ránhòu jiù fā gěi tāmen tāmen kàn yīyǎn jiù juédé āiyā kěyǐ ránhòu jiù zhíjiē jìnrù dì 2 lún miànshì dāngrán wǒ yě hěn xiǎng zài xiǎo gōngsī lǐ mó liàn zìjǐ de jìnéng yīnwèi wǒ qíshí shì cóng shāngkē zhuǎn dào jìsuànjī suǒyǐ wǒ juédé wǒ de jīchǔ yào bǐ hěnduō rén chà rúguǒ wǒ qù dà gōngsī ne wǒ kěnéng gàn gè liǎng sān nián wǒ néng jiēchù dào dōngxī háishì hěn shǎo wǒ kěnéng xuéxí de sùdù huì hěn màn jiù yào kào zìjǐ zài jiālǐ xuéxí yǒu shíhòu juédé rúguǒ nǐ néng jiēchù dào yīgè hěn hǎo de xiàngmù jiù nǐ néng hěn kuài xuéxí jiù bù xūyàole xiàbān yǐhòu hái yào huí dàojiā xuéxí yīnwèi bìjìng zài gōngzuò měitiān gōngzuò bā xiǎoshí rúguǒ nǐ néng wánquán lìyòng zhè 8 xiǎoshí bǐrú shuō zuò shǒujī ruǎnjiàn wǒ zài dì yīgè gōngsī de shíhòu wǒ cóng shèjì chǎnpǐn shèjì yīzhí dào hòulái de kāifā yīzhí dào hòulái de fǎ bù dào hòulái de hòuqí de wéihù, gēngxīn jīběn shàng dū shì wǒ yīgèrén fùzé de suǒyǐ wǒ jiù néng xué dào dōngxī fēicháng duō érqiě wǒmen zài kāifā yīgè shǒujī ruǎnjiàn de shíhòu wǒ néng xué dào de jìshù yěshì fāngfāngmiànmiàn de zhè bùjǐn zhǐshì mǒu yīgè yèmiàn mǒu yīgè gōngnéng jīběn shàng shì zhěng yī tào gōngnéng cóng yīgè liúchéng jiù néng yù dào hěnduō wèntí ránhòu cóngzhōng qù jiějué ránhòu ne jiùshì yīnwèi wǒ de dòngjī nà shì xiǎng huòdé gèng duō de jīngyàn suǒyǐ wǒ dāngshí zài Pittsburgh nà fèn gōngzuò wǒ gēnběn jiù méiyǒu kǎolǜ xīnchóu jiùshì Pittsburgh de gōngsī yě méiyǒu gěi gǔquán wǒ wánquán dōu bù zhīdào qù chūchuàng qǐyè yuánlái yǒu gǔquán zhège dōngxī ránhòu wǒ bān lái wān qū gǎnjué zìjǐ dāngshí jiùshì gè shǎzi tiāntiān jiābān shì wèile shénme jiù jiù bù xiàng zài wān qū zhè biān dàjiā xiǎng yào qù chūchuàng gōngsī dōu shì wèile xiǎng yào fācái wǒ kěnéng dāngshí zhēn de shì tài tiānzhēnle hǎo nǐ xiǎng qīngchǔ zìjǐ wèishéme yào qù chūchuàng qǐyè nà jiē xiàlái jiù yào qù sīkǎo fēngxiǎn yǒu nǎxiē bǐrú shuō chūchuàng qǐyè fúlì hěn yībān guǎnlǐ céng quēfá jīngyàn méiyǒu liúchéng méiyǒu zhíyè guīhuà jīngcháng jiābān kěnéng yě méi fǎbàn shēnfèn děng děng zhèxiē wèntí dà bùfèn chūchuàng qǐyè de xīnzī hé fúlì méi fǎ hé dà gōngsī xiāng bǐ zhè dōngxī jiùshì méi fǎ bǐ xiǎo gōngsī shì gāng kāishǐ de shíhòu tā zījīn yǒuxiàn néng shěng jiù shěng tā kěnéng huì gěi nǐ hěnduō gǔquán dànshì yǒu shíhòu gāng kāishǐ de shíhòu lián chǎnpǐn dōu méiyǒu suǒyǐ nǐ hěn nán qù héngliáng zhège gǔquán dàodǐ yǒu méiyǒu yìyì suǒyǐ nǐ háishì yào kǎolǜ qīngchǔ nǐ néng bùnéng jiēshòu zhège xīnzī ránhòu xiǎo gōngsī yě méiyǒu xiàng dà gōngsī nàxiē shénme miǎnfèi de wǔcān miǎnfèi de Gym Membership zhèxiē dōngxī dū méiyǒu dàn yǒu yīxiē fúlì nǐ háishì yào qù sīkǎo jiù shuō zhèxiē fúlì nǐ shì xūyào de bǐrú shuō nǚshēng kěnéng nǐ zhè liǎng sān nián nǐ xūyào jiéhūn shēng háizi nà xiǎo gōngsī hěnduō shíhòu tā kěnéng dōu méiyǒu shé me sān gè yuè liù gè yuè de chǎnjià nà nǐ jiù yào sīkǎo nǐ shìfǒu yīnggāi qù yīgè dà gōngsī ér bùshì xiān qù yīgè xiǎo gōngsī qícì qù chūchuàng qǐyè nǐ yào bǎ zìjǐ de qīwàng shè hǎo nǐ bùyào qù shēwàng zhè gōngsī de wénhuà kuài yǒu duō hǎo bùyào qù shēwàng nǐ huì yǒu zhíyè shàng de dǎoshī zhíyè shàng de guīhuà yīnwèi duì yīgè gānggāng kāishǐ de chūchuàng qǐyè tā hái xūyào shíjiān qù jiànlì zhèxiē dōngxī tā kěnéng qiánqí de zhòngxīn dōu shì zài chǎnpǐn kāifā shàng tā jiù bù huì qù gěi nǐ tígōng zhèxiē dōngxī suǒyǐ zhèxiē dōngxī nǐ dōu xū yào zìjǐ qù mōsuǒ zìjǐ qù jiějué hǎochù ne jiùshì nǐ kěnéng chéngwéi nàgè jiànlì guīzé de rén zhīhòu ne dāng zhè gōngsī kuòdà nǐ jiù biàn chéng yīgè tuánduì de lǐngdǎo rén nǐ kěyǐ qù péiyǎng xiàmiàn de xīnrén zhè duì nǐ yěshì yīgè chéngzhǎng yěshì yīgè hěn hǎo de jīnglì wǒ zài dì èr gè chūchuàng qǐyè de shíhòu yī kāishǐ ne wǒ jiù kāishǐ zhēngzhá wǒ shì bùshì xuǎn cuòle yīnwèi qiánqí háishì jīnglìle hěnduō gēn dì yīgè gōngsī xiāngsì de dōngxī jiùshì hěnduō dōngxī méiyǒu liúchéng ránhòu jīngcháng yīxiē dōngxī jiùshì fǎn fǎnfù fù dì zuò ránhòu jīngcháng yīgè chǎnpǐn zuò wán yǐhòu bù héshì chóngxīn zàiláiguò ránhòu nà shíhòu nà wǒ jiù kāishǐ yóuyù bù jué jiù juédé zìjǐ aya shì bùshì yīnggāi liú xiàlái ránhòu yīgè PM jiù gēn wǒ shuō wǒmen xiànzài ne hái zài yīgè kuàicān wénhuà de jiēduàn jiùshì wǒmen yào xùnsù dì kāifā chǎnpǐn bǎ tā tuī xiàng shìchǎng yīnwèi rúguǒ gōngsī méiyǒu hǎo chǎnpǐn méiyǒu shōurù nà zhè gōngsī kěnéng jiù yī liǎng nián jiù kuǎle nà nǐ yě jiù shīyèle suǒyǐ qiánqí de shíhòu ne wǒ yěyǒu huì gēnzhe gōngsīxiǎng yào rúhé qù zhuànqián ránhòu màn man de ne jiù shuō shíjiān huì ràng zhège dōngxī qù biàn chéng yī gè fine dining zhìshǎo wǒ dāngshí juédé wǒmen gōngsī de PM tāmen shì yǒu zhège xiǎngfǎ de tāmen shì zhīdào zìjǐ zài nǎ yī gè jiēduàn yīnggāi zuò shénme yàng de shìqíng ránhòu wǒ juédé jiùshì hěn OK de suǒyǐ ne wǒ jiù yě fēicháng xiāngxìn wǒmen gōngsī de tuánduì suǒyǐ cái huì yī dài dàile liù nián dāng nǐ sīkǎole qù chūchuàng gōngsī de yīxiē fēngxiǎn yīnsù shì shénme nǐ jiù kěyǐ sīkǎo nǐ zuìdà de dǐxiàn shì shénme bǐrú shuō wǒ dì yī gè gōngsī méi rì méi yè de jiābān dì èr gè gōngsī nà wǒ jiù bùxiǎng zài yǒu zhèyàng de shēnghuó suǒyǐ wǒ dāngshí miànshì de shíhòu wǒ yěyǒu wèn guānyú yī gè jiābān wénhuà ránhòu dāngshí tāmen yě gēn wǒ shuō dì 1 nián de shíhòu nà kěndìng shì yào jiābān de kěndìng shì yào dàjiā nǔlì yīdiǎn duō zuò yīdiǎn dànshì zhīhòu ne gōngsī màn man kuòdà měi gèrén de kěndìng shì huì jiùshì huì bǎ shēnghuó hái gěi nǐ suǒyǐ wǒ dāngshí jiù juédé hǎo wǒ kěyǐ jiārù zhège tuánduì suǒyǐ nǐ jiù yào qù sīkǎo jiù shuō nǐ de dǐxiànzài nǎlǐ jiù yǒuxiē shìqíng nǐ juédé nǐ shì méi fǎ jiēshòu de nà nǐ jiù háishì bùyào qù zhège chūchuàng qǐyè huòzhě nǐ jiù yàgēn bùnéng qù chūchuàng qǐyè xiān cóng dà gōngsī zuò qǐ jiùshì rúguǒ nǐ de dòng jī shì néng kèfú zhèxiē fēngxiǎn de nà nǐ kěyǐ sīkǎo nǐ yào zěnme qù kèfú zhège wèntí jiù shì nǐ kěyǐ qù xiǎngxiàng dāng zhège wèntí fāshēng yǐhòu nǐ huì qù zěnme kèfú bǐrú shuō xiǎo gōngsī méiyǒu zhǐyǒu guīhuà nǐ jiù shuō OK de yīnwèi xiànzài wǎngshàng yǒu hěnduō xìnxī nǐ kěnéng jiù zài wǎngshàng fā gè tiē tí gè wèn biérén jiù huì gěi nǐ hěnduō yìjiàn suǒyǐ nǐ jiù kěyǐ qù sīkǎo rúguǒ nǐ zài zhège gōngsī huì fāxiàn zhège wèntí nǐ yào qù zěnme jiějué yīdàn nǐ zuò hǎo zìjǐ de xīnlǐ jiànshè nǐ zài jiārù yī gè chūchuàng qǐyè nǐ jiù bù huì yǒu nàme duō de luòchā shuō dào zhèlǐ bù zhīdào huán yǒu duōshǎo tóngxué juédé zìjǐ shì shìhé chūchuàng qǐyè de rúguǒ nǐ juédé zìjǐ shìhé nà nǐ kěyǐ qídài yīxià wǒ xià qí de nèiróng wǒ xiàqī ne huì hé dàjiā fēnxiǎng rúhé xuǎnzé chūchuàng qǐyè wǒ zìjǐ gèrén shì fēicháng tuījiàn qù chūchuàng qǐyè pīn yī pīn tǐyàn xià shēnghuó shì hǎo shì huài zhè dōu shì nǐ rénshēng de yīxiē hěn zhēnguì de jīnglì wǒ juédé zìjǐ shì hěn xìngyùn de yīnwèi xiàn zài zhège chūchuàng qǐyè bèi dà gōngsī shōugòu yǐhòu wǒ yòu bùyòng shuā tí de jìnrùle zìjǐ xiǎng qù de dà gōngsī kěnéng zhīhòu hái kěyǐ gēn dàjiā fēnxiǎng zài xiǎo gōngsī hé dà gōngsī wǒ gèng xǐhuān nǎ yī nǎ yī zhǒng wénhuà ba hǎo la jīntiān jiù liáo dào zhèlǐle rúguǒ nǐ yǒu xiǎng kàn de nèiróng jìdé zài pínglùn qū liúyán rúguǒ nǐ yǒu yīxiē chuàngyè qǐyè de jīnglì nǐ kěyǐ zài pínglùn qū hé dàjiā fēnxiǎng yěxǔ duì yīxiē rén lái shuō tā kěyǐ shòudào yīxiē qǐfā rúguǒ nǐ xǐhuān zhè qī nèiróng jiù jìdé diǎn zàn yě huānyíng dìngyuè wǒ yīdìng huì nǔlì gēngxīn de nà xià cì zàijiànle xièxiè dàjiā zhīchí",
        chinese: `Hello大家好歡迎來到我的頻道
        我大概有很長很長一段時間沒有更新了
        最近因為疫情的原因又給了我
        想要製作視頻的
        動力和時間
        除了時尚穿搭之外
        我想分享更多關於職業和生活方面的內容
        今天我想和大家分享的內容是
        如何知道自己是否適合初創企業
        相信很多同學都有這樣的疑問
        大公司還是小公司
        我呢想通過自己的一些個人經歷
        和你們分享一些我的心得
        首先呢我先和大家分享下我的個人經歷
        12年研究生畢業以後
        我就留在了Pittsburgh的一家小公司
        做手機軟件開發
        我加入的時候好像是
        第一個女程序員
        然後就看著公司從一個很小的團隊
        一直到
        慢慢地迅速擴張
        然後
        財政出現了危機
        一直到我也因此被裁員
        然後我就藉此機會
        搬來了舊金山
        在現在這家公司呢做企業軟件
        我當時加入公司的時候呢
        差不多好像也是50個人左右吧
        然後也沒有任何一個產品
        現在呢
        被收購前我公司的已經有上千多人
        然後全球都有
        辦公室
        所以我就有兩段完全不同的經歷
        第一段就是很多起起伏伏
        算是一個失敗經歷
        然後就可以“Learn from the worst.”
        第二段經歷了比較完整
        就是從一個
        很小的團隊一直看他慢慢成長
        擴張而後一直到最後被收購
        雖然說沒有上市
        但是
        我覺得被收購這個個結果其實我自己很喜
        喜歡的
        那接下來我就來
        和大家分享一些心得吧
        因為
        我一錄視頻說話就緊
        所以呢
        我需要看我自己的
        一些
        筆記
        首先你要思考你想去
        初創企業的起動機是什麼
        就說你要問你自己
        為什麼
        我為什麼想去
        不管你是剛畢業的學生
        還是已經工作好多年
        希望換一個環境
        你都需要去問自己為什麼
        先想清楚這個問題
        再做決定
        你的動機可以是想要提高自己的技能
        因為大公司
        就是每一個東西都有很多人在做
        可能是幾百幾千人在做
        那你能學到的東西非常少
        然後小公司吧
        就可能你要學的不僅是技術的東西
        你可能還要學
        關於市場營銷的東西
        關於管理的東西
        就讓你能
        很快的成長
        或者你喜歡快節奏的環境
        我覺得大公司有時候讓我感覺
        有種提前
        養老
        所以我那我就更喜歡初創企業那種
        快速替代產品
        然後呢就是
        有一種感覺我自己還很年輕還很有奮進
        或者你就喜歡這個公司產品
        就比如說我當年特別想去Pinterest
        因為自己就很喜歡用Pinterest
        或者呢你很仰慕該公司創始人
        就有很多Founder他之前可能已經是
        有過幾個成功的公司了
        然後他又出來又
        再做一個公司一個團隊
        你就很想去加入他
        或者你就想發財
        大多數
        想去初創企業的人
        應該都是抱著想發財的心態
        還有那就是
        不想刷題
        我就是那個
        不想刷題的人
        就我在讀書的時候吧
        我就完全沒有心思
        想去大公司
        我就一心想找一個自己喜歡的初創企業
        第一呢就像我說的不想刷題
        因為我當時進Pittsburgh那公司
        完全就沒有刷題
        我就把自己
        在學校裡做的一個
        幾個項目
        就是幾個手機
        App
        然後就發給他們
        他們看一眼
        就覺得哎呀可以
        然後就直接進入第2
        輪面試
        當然我也很想在小公司裡
        磨練自己的技能
        因為我
        其實是從商科轉到計算機
        所以我覺得我的基礎要比很多人差
        如果我去大公司呢
        我可能干個兩三年
        我能接觸到東西還是很少
        我可能學習的速度會很慢
        就要靠自己在家裡學習
        有時候覺得如果你能
        接觸到一個很好的項目
        就你能
        很快學習
        就不需要了
        下班以後還要回到家學習
        因為畢竟在工作
        每天工作八小時
        如果你能完全利用這8小時
        比如說做手機軟件
        我在
        第一個公司的時候
        我從設計
        產品設計
        一直到後來的開發
        一直到後來的發布
        到後來的後期的維護、更新
        基本上都是我一個人負責的
        所以我就能學到東西非常多
        而且我們在開發一個手機軟件的時候
        我能學到的技術
        也是方方面面的
        這不僅只是
        某一個頁面
        某一個功能
        基本上是整一套功能
        從一個流程
        就能遇到很多問題
        然後從中去解決
        然後呢就是因為我的動機那是想獲得更多的經驗
        所以我當時在Pittsburgh那份工作
        我根本就沒有考慮薪酬
        就是
        Pittsburgh的公司也沒有給股權
        我完全都不知道去初創企業
        原來有股權這個東西
        然後我搬來灣區
        感覺自己當時就是個傻子
        天天加班
        是為了什麼
        就
        就不像在灣區這邊大家想要去初創公司
        都是為了想要發財
        我可能當時真的是太天真了
        好 你想清楚自己為什麼要去初創企業
        那接下來就要去思考
        風險有哪些
        比如說初創企業福利很一般
        管理層缺乏經驗
        沒有流程
        沒有職業規劃
        經常加班
        可能也沒法辦身份
        等等這些
        問題
        大部分初創企業的薪資和福利沒法和大公司相比
        這東西就是沒法比
        小公司是剛開始的時候
        他資金有限
        能省就省
        他可能會給你很多股權
        但是
        有時候剛開始的時候連產品都沒有
        所以你很難去衡量這個股權到底有沒有意義
        所以你還是要
        考慮清楚你能不能接受這個薪資
        然後
        小公司也沒有像大公司那些什麼
        免費的
        午餐
        免費的
        Gym Membership
        這些東西都沒有
        但有一些福利你還是要去思考
        就說這些福利
        你是需要的
        比如說女生
        可能你這兩三年你需要
        結婚生孩子
        那小公司很多時候他可能都沒有什麼
        三個月六個月的產假
        那你就要思考
        你是否應該去一個大公司
        而不是
        先去一個小公司
        其次去初創企業你要把自己的期望設好
        你不要去奢望這公司的文化會有多好
        不要去奢望你會有職業上的導師
        職業上的規劃
        因為對一個剛剛開始的初創企業
        他還需要時間去建立這些東西
        他可能前期的重心都是在產品開發上
        他就不會
        去給你提供這些東西
        所以這些東西你都需要
        自己去摸索
        自己去解決
        好處呢就是
        你可能成為那個建立規則的人
        之後呢當這公司擴大
        你就變成一個團隊的領導人
        你可以去培養下面的新人
        這對你也是
        一個
        成長
        也是一個很好的經歷
        我在第二個初創企業的時候
        一開始呢
        我就開始掙扎
        我是不是選錯了
        因為前期還是經歷了很多
        跟第一個公司相似的東西
        就是很多東西沒有流程
        然後經常一些東西就是反反复复地做
        然後經常一個產品做完以後
        不合適重新再來過
        然後
        那時候那我就開始猶豫不決
        就覺得自己
        啊呀
        是不是應該留下來
        然後一個PM就跟我說
        我們現在呢
        還在一個快餐文化的階段
        就是我們要迅速地開發產品
        把它推向市場
        因為如果公司沒有好產品
        沒有收入
        那這公司
        可能就一兩年就垮了
        那你也就失業了
        所以前期的時候呢我也有
        會跟著公司想要如何去賺錢
        然後慢慢地呢
        就說時間會讓這個東西
        去變成一個fine dining
        至少我當時覺得我們公司的PM
        他們是有這個想法的
        他們是知道自己
        在哪一個階段應該做什麼樣的事情
        然後我覺得就是很OK的
        所以呢我就
        也非常相信我們公司的團隊所以才會
        一待待了六年
        當你思考了去初創公司的一些
        風險因素是什麼
        你就可以
        思考你最大的底線是什麼
        比如說我第一個公司
        沒日沒夜的加班
        第二個公司那我就不想
        再有這樣的生活
        所以我當時面試的時候
        我也有問關於一個加班文化
        然後當時
        他們也跟我說第1年的時候那肯定是要加班的
        肯定是要大家努力一點多做一點
        但是之後呢
        公司慢慢擴大
        每個人的肯定是
        會
        就是會把生活還給你
        所以我當時就覺得好
        我可以加入這個團隊
        所以你就要去思考
        就說你的底線在哪裡
        就有些事情你覺得你是沒法接受的
        那你就
        還是不要去這個初創企業
        或者你就壓根不能
        去初創企業
        先從大公司做起
        就是如果你的動機是能克服這些風險的
        那你可以思考你要怎麼去克服這個問題
        就是你可以去想像當這個問題發生以後
        你會去怎麼克服
        比如說小公司沒有隻有
        規劃你就說OK的
        因為現在網上有很多信息
        你可能就在網上發個帖提個問
        別人就會給你很多意見
        所以你就可以去思考
        如果你在這個公司會發現這個問題
        你要去怎麼解決
        一旦你
        做好自己的心理建設
        你再加入一個初創企業
        你就不會有那麼多的落差
        說到這裡
        不知道還有多少同學
        覺得自己是適合初創企業的
        如果你覺得自己適合
        那你可以期待一下我下期的內容
        我下期呢會和大家分享如何選擇初創企業
        我自己個人是非常推薦
        去初創企業
        拼一拼
        體驗下生活
        是好是壞
        這都是你人生的
        一些很珍貴的經歷
        我覺得自己是
        很幸運的
        因為現在這個
        初創企業被大公司收購以後
        我又不用刷題的
        進入了自己想去的大公司
        可能之後還可以跟大家分享
        在小公司和大公司我更喜歡哪一
        哪一種文化吧
        好啦今天就聊到這裡了
        如果你有想看的內容記得在評論區留言
        如果你有一些
        創業企業的經歷
        你可以在評論區和大家分享
        也許對一些人來說他可以受到一些啟發
        如果你喜歡這期內容
        就記得點贊
        也歡迎訂閱
        我一定會努力更新的
        那下次再見了
        謝謝大家支持`
    }
};

export default joiningAStartup;