const ukraineWar = {
    videoId: '2KC-0gsqs98',
    transcript: {
        pinyin: "wéigōng wūkèlán, chūbīng hāsàkè, wèishéme zhè jǐ nián èluósī duì línjūmen de jūnshìjièrù, sìhū biànchéng jiāchángbiànfàn? Zài pǔ dīng de lǐngdǎo zhī xià, jiětǐ sānshí nián de `sūlián'nándào jiù yào fùhuóle ma? Jīntiān, jiù ràng wǒmen yīqǐlái liáo liáo `pǔ dīng de sūlián mèng'ba! Hiho~dàjiā hǎo, wǒ shì zhì qí! Cóng qùnián niándǐ kāishǐ, èluósī yǐ yǎnxí wèi míngyì zài wūkèlán biānjìng jùjíle chāoguò shí wàn rén de dàjūn měiguó de qíngbào dānwèi zhǐchū éguó hěn kěnéng huì zài jīnnián chūntiān, xiàng wūkèlán kāizhàn! Suīrán éguó fǒurèn yǒu rùqīn wūkèlán de yìtú dàn tāmen yě jǐnggào rúguǒ wūkèlán jiārù běi dàxīyáng gōngyuē zǔzhī (běiyuē) èluósī yě huì cǎiqǔ `bìyào de bàofù shǒuduàn' suízhe zhuàngkuàng yuè lái yuè jǐnzhāng, gèguó kāishǐ jiāng rényuán chèlí wūkèlán běiyuē yě zēng pài jūnduì dào dōng'ōu dàimìng shuāngfāng jiàn bá nú zhāng, jīhū bīnlín zhànzhēng biānyuán wūkèlán de wéijī, ràng quánqiú xiànrù kǒnghuāng bùguò, rúguǒ wǒmen bǎ shìjiǎo lā gāo, huì fāxiàn zhè yīchǎng chōngtú kěnéng zhǐshì qípán shàng de yī xiǎo bù éryǐ zài pǔ dīng de xīnzhōng, sìhū hái yǒu gèng dà de yěxīn yào wánchéng jiùjìng, pínpín duì línjū chūzhēng de èluósī, bèihòu yǒu shé me mùdì ne? Yīzhào guànlì, wǒmen yào xiān lái yī xiǎoduàn gōngshāng shíjiān zuìjìn zhì qí qīqī tuánduì zhèngzài zhāomù lìhài de xīn huǒbàn la! Wǒmen xiǎng yào zhǐqiú `quánzhí de yǐngpiàn nèiróng qǐhuà' gēn wǒmen yīqǐ zhuī shíshì, liáo yìtí xiě jiǎoběn, fā xiǎng jiémù qǐhuà yíngjiē gèzhǒng jīngyíng píndào huì yù dào de tiǎozhàn! Bùguǎn nǐ yǒu shé me yàng de zhīshì lǐngyù zhuāncháng zhǐyào nǐ shàncháng xiězuò, hěn huì sōují zīliào luójí qīngxī, jùbèi dúdào de guāndiǎn érqiě lèyú gōutōng, néng bǎ fùzá de dōngxī jiǎndān shuō qīngchǔ nà nǐ jiùshì wǒmen xīwàng néng yāoqǐng dào de réncái! Dāngrán, rúguǒ nǐ yǐjīng yǒu `wénzì yǐngyīn chuàngzuò' huò `jiémù píndào jīngyíng'de xiāngguān jīngyàn, nà jiù gèng bàng la! Rúguǒ nǐ rèntóngzhì qí qīqī píndào de lǐniàn yě xiǎng yào jiārù wǒmen de hángliè nà jiù gǎnkuài shàng wǒmen de guānwǎng qù kàn kàn zhí quē nèiróng ba! [Dòngdàng de ōu yà dàlù] chúle gānggāng tí dào de wūkèlán wéijī wài, guòqù èrshí nián nèi èluósī zài ōu yà dàlù shàng, kěyǐ shuō shì dòngzuò bùduàn 2008 nián, èluósī yǔ qiáozhìyà bàofā zhànzhēng, bìng zài zhànshèng zhīhòu shízhì zhànlǐngle qiáozhìyà de bùfèn lǐngtǔ 2014 nián, èluósī zé túxí wūkèlán tūnbìngle wūkèlán nánbù de kè lǐ mǐ yà bàndǎo bìng shāndòng wūkèlán dōngbù pànbiàn, chénglì qīn é de zìzhì zhèngfǔ chú cǐ zhī wài, èluósī yě jījí dì jièrù gèguó de nèizhèng wèntí xiàng shì jīnnián yī yuè, hāsàkè bàofā shìwēi, mínzhòng shàng jiē yāoqiú zhèngzhì gǎigé dàn zài hāsàkè zǒngtǒng de qǐngqiú xià èluósī huǒsù pàichū wéihé bùduì, xùnsù yāzhìle kàngyì mínzhòng zhè jǐ niánlái, zài dōng'ōu, zhōng yà, hé gāojiāsuǒ dìqū yuè lái yuè chángjiàn dào é jūn de yǐngzi, èluósī zhèngzài yǐ lǎo dàgē de zītài chóngxīn jiànlì ōu yà dàlù de zhìxù ér zhèxiē dòngzuò, ràng bù shǎo rén dānxīn xiāoshī sānshí nián de sūlián, sìhū jíjiāng zàicì huíguī! [Sūlián shì shénme?] Yǒu de rén kěnéng duì `sūlián'bù tài shúxī, wǒmen zhèlǐ jiǎndān jièshào yīxià sūlián de quán míng shì `sūwéi'āi shèhuì zhǔyì gònghéguó liánméng' tā chénglì yú 1922 nián, shì yóu sū é, bái luósī wūkèlán děng guó chuànglì de yīgè liánbāng zhì gòngchǎn guójiā yóu wèiyú mòsīkē de sūlián gòngchǎndǎng zhízhèng, lǐngdǎo zhěnggèguójiā de yùnzuò èrzhàn jiéshù hòu, sūlián kòngzhìle dōng'ōu dìqū huòqǔle dàliàng tǔdì, rénkǒu hé zīyuán bù zhǐshì dāngshí shìjiè lǐngtǔ zuìdà de guójiā yěshì jīngjì hé jūnshì shàng de chāojí qiángquán wèile zhēngduó èrzhàn hòu de huàyǔ quán, sūlián dàilǐng de `gòngchǎn zhǔyì zhènyíng' yǔ měiguó dàilǐng de `zīběn zhǔyì zhènyíng' zhǎnkāi jīngjì, jūnshì hé tàikōng kējì de quánmiàn duìkàng shuāngfāng yě zài gèdì jìnxíng dàilǐ rén zhànzhēng, zhēngduó shì jiè bàzhǔ dì dìwèi! Rán'ér, dàole 1980 niándài, sūlián de jīngjì fāzhǎn yù shàng kùnjìng zài jiā shàng nèibù de zhèngzhì máodùn, dǎozhì sūlián kāishǐ fēnbēnglíxī 1991 nián, mòsīkē dāngjú zhōngyú fàngshǒu xuānbù sūlián jiětǐ, yīdài qiángquán yě jiùcǐ huà xià jùdiǎn sūlián jiětǐ zhīhòu, fēnliè chéng èluósī, wūkèlán qiáozhìyà, hāsàkè děng shí duō gè dúlì guójiā ér zhèxiē guójiā, yě màn man jìnxíng gǎigé kāifàng, gèzì mài xiàng mínzhǔ huà zhǐ bùguò, zhè jǐ nián, èluósī yòu kāishǐ gānshè zhèxiē dìfāng sìhū xiǎng hé dāngnián de sūlián yīyàng, zàidù chéngwéi ōu yà dàlù de qiángquán ér zhè yīcì, tāmen bù zài shì wèile xuānyáng gòngchǎn zhǔyì ér shì wèile duóqǔ gèng shízhì de lìyì! [Èluósī xiǎngdédào shénme: Néngyuán kòngzhì] xǔduō zhuānjiā rènwéi, èluósī zhè jǐ nián zhème jījí dì xiǎng kuòzhāng zhǔyào chūzì yú néngyuán, jūnshì hé zhèngzhì sān gè miànxiàng de kǎoliáng zài néngyuán fāngmiàn, zài èluósī de tǔdì shàng bùmǎnle xǔduō guǎnxiàn, jiāng tiānránqì, shíyóu shū wǎng ōuzhōu dàlù zhèxiē néngyuán duì èluósī lái shuō, chúle shì zhòngyào de shōurù láiyuán yěshì fēicháng hǎo yòng de tánpàn chóumǎ tāmen suíshí kěyǐ qiē duàn guǎnxiàn, tíngzhǐ tèdìng dìqū de néngyuán gōngyìng shǐdé ōuzhōu guójiā chǎnshēng wúxíng de zhèngzhì yālì xiàng shì zài déguó, yǒu chāoguò yībàn de tiānránqì, dōu shì cóng èluósī jìnkǒu de ér zhèxiē tiānránqì shì fādiàn, qǔnuǎn de zhòngyào láiyuán suǒyǐ, zài zhècì de wūkèlán wéijī zhōng déguó zhī suǒyǐ bù tài yuànyì qiǎnzé èluósī, hěn dà yībùfèn yuányīn yěshì yīn wéi hàipà tiānránqì bèi qiē duàn, cái bù gǎn dézuì pǔ dīng ér èluósī yě qīngchǔ,`néngyuán'shì tāmen xiàn jiēduàn gēn xīfāng lièqiáng kànghéng de zuìdà chóumǎ suǒyǐ tāmen fēicháng nǔlì de xiǎng yào kuòzhāng shìlì fànwéi, duóqǔ gèng duō de tiānrán zīyuán xiàng shì hāsàkè suǒ chǔ de zhōng yà dìqū, jiù yùnhánle dàliàng de shíyóu hé tiānránqì zhǐyào zhǎngkòng zhè kuài dì, jiù yǒu jīhuì kāicǎi gèng duō néngyuán huò shì gèng yǒu xiàoyì dì pūshè guǎnxiàn, jìnyībù zēngjiā éguó zài dāngdì de yǐngxiǎng lì ràng tāmen zhàn wěn néngyuán bàzhǔ dìwèi! [Èluósī xiǎngdédào shénme: Jūnshì kànghéng] zài jūnshì fāngmiàn, èluósī zé xīwàng kuòzhāng jūnshì bǎntú, gēn běiyuē hùxiāng kànghéng zài sūlián jiětǐ zhīhòu, dōng'ōu de qián sūlián guójiā xiàng shìlìtáowǎn, bōlán, jiékè, yīgè jiēzhe yīgè tiàocáo dào běiyuē gēn měiguó zhàn zài tóngyī zhènxiàn ér zài 2014 nián, èluósī tūnbìng kè lǐ mǐ yà hòu běiyuē yě kāishǐ zài dōng'ōu jiànshè jūnshì jīdì, jiùjìn jiānkòng èluósī suí zhuó běiyuē shìlì bǎntú yuè lái yuè dà, ràng èluósī zhèngfǔ yuè lái yuè bùmǎn tāmen xīwàng zhèxiē qián sūlián guójiā, chóngxīn huí dào èluósī de zhǎngkòng chéngwéi èluósī zhōuwéi de `huǎnchōng qū', bìmiǎn běiyuē de jūnduì zhíjiē pǎo dào èluósī de jiā ménkǒu, duì shǒudū mòsīkē zàochéng wēixié jiǎndān lái shuō, pǔ dīng xīwàng kěyǐ chóngxīn huà shè lěngzhàn zhīhòu de ōuzhōubiānjiè jiànlì yīgè yóu èluósī zhǔdǎo de jūnshì qūyù, lái duìkàng xīfāngshìlì zuìhòu, èluósī zhī suǒyǐ dòngzuò zhème duō hái yǒu gè hěn zhòngyào de yuányīn, nà jiùshì pǔ dīng gèrén de zhèngzhì yěxīn! [Pǔ dīng xiǎng yào shénme: Fùxīng sūlián] pǔ dīng chūshēng yú sūlián shídài, yě dānrènguò sūlián de tèwù rényuán duì tā lái shuō, sūlián jiùshì yǎngyù tā zhǎngdà de mǔqīn yěshì `fánróng, qiángshèng, wěidà'de dàimíngcí suǒyǐ, dāng pǔ dīng kàn dào sūlián kuǎtái hòu èluósī jīngjì shuāituì de múyàng, tā de nèixīn fēicháng nánshòu pǔ dīng céngjīng biǎoshì, sūlián jiětǐ jiùshì `20 shìjì zuìdà de zāinàn zhī yī' hěnduō zhuānjiā yě tuīcè, zài pǔ dīng xīnzhōng yīnggāi yīzhí bào yǒu `fùxīng sūlián'de yuǎndà lǐxiǎng wèile ràng qián sūlián guójiā zàicì tuánjié, pǔ dīng chángcháng zhōubiān guójiā jìnxíng xīn zhàn hǎnhuà xiàng shì duì wūkèlán shuō `wǒmen dōu shì tóngwén tóngzhǒng',`é wū yījiā qīn'děng děng zhè tīng qǐlái ~ yǒudiǎn ěrshú de xuānchuán huàyǔ shènzhì, pǔ dīng hái céngjīng gōngkāi shuōguò `èluósī de biānjiè wú zhǐ jǐn!' Suīrán tā mǎshàng chéngqīng `zhǐshì kāi gè wánxiào'dàn duōshǎo yě tòulù chū tā xiǎng yào shōufù shī tǔ de yěxīn ér duì pǔ dīng lái shuō,`fùxīng sūlián'bù zhǐyǒu qínggǎn shàng de yìyì shízhì shàng, yě duì tā de zhèngzhì shēngyá yǒu hěn dà de bāngzhù! [Pǔ dīng xiǎng yào shénme: Dǎzhàng jiù mín diào?] Pǔ dīng fāxiàn, duìwài de jūnshì huódòng kěyǐ zhuǎnyí mínzhòng duì guónèi wèntí de bù mǎn yě kěyǐ jīfā mínzhòng de àiguó xīn, gǒnggù zìjǐ de zhèngquán 2012 nián zuǒyòu, pǔ dīng shēn xiàn xuǎnjǔ wǔbì de fēngbō jiētóu chūxiàn dà guīmó de fǎn zhèngfǔ yóuxíng, pǔ dīng mín diào yīdù diéluò gǔdǐ dànshì dào 2014 nián, dāng pǔ dīng juédìng chūbīng wūkèlán zhànlǐng kè lǐ mǐ yà de shíhòu, mín diào mǎshàng zhǐ diē biāoshēng ràng tā zàidù chéngwéi shòu rénmín àidài de qiáng rén zǒngtǒng! Cháng dào tiántou de pǔ dīng, cóngcǐ fāxiàn `dǎzhàng jiù mín diào'de liúliàng mìmǎ shícháng tòuguò duìwài de jūnshì xíngdòng, lái wéichí zìjǐ de zhīchí lǜ zhídào jīntiān, réng yǒu yībàn de éguó mínzhòng zhīchí pǔ dīng 2024 nián hòu jìxù dāng zǒngtǒng, rènwéi zhǐyǒu pǔ dīng cái yǒu bànfǎ `ràng èluósī zàicì wěidà' ér pǔ dīng xiǎng yào zhuàngdà èluósī de jì huà, bùshì zhǐyǒu zuǐ shàng shuō shuō éryǐ wèile chóng huí sūlián shíqí de guānghuī suìyuè, èluósī qíshí zǎo jiù kāishǐ dòngzuòle! [Duì nèizhèngcè: Èluósī bǎowèi zhàn!] Gēnjù wài méi bàodǎo, pǔ dīng zhǎngquán xià de èluósī yǐjīng jiànlìle mínzhòng de `zhànzhēng yìshí' guòqù bā nián, èluósī tòuguò xuéxiào, méitǐ, jiàohuì bùduàn xuānchuán `zǔguó bèi dírén bāowéi'de xiǎngfǎ cóng èluósī guānfāng de xuānchuán lái kàn, shì xīfāng shì lì zài éguó zhōu biān zēngjiā jūnduì bìngqiě yòng jīngjì zhìcái de shǒuduàn dǎyā éguó, cái huì ràng tāmen de chǔjìng rúcǐ jiānxīn bù shǎo èluósī rén yě rènwéi, éguó bìng bùshì xié'è de qīnlüè zhě ér shì xīfāng bà líng xià de shòuhài zhě wèile bǎohù zìjǐ de zhǔquán, shìdàng de xiàng wài kuòzhāng, chéngwéile tāmen wéiyī de chūlù suīrán shuō, háishì yǒu hěnduō èluósī rén duì zhànzhēng méi xìngqù dàn zài chángqí xuānchuán zhī xià, dàjiā yě duì fādòng zhànzhēng zhè jiàn shì gǎndào yuè lái yuè mámù. Rúguǒ nǎ tiān pǔ dīng zhēn de duì qítā guójiā dòngwǔ guónèi kěnéng yě bù huì yǒu tài duō de fǎntán shēnglàng! [Duìwài zhèngcè: Shùn wǒ zhě shēng, nì wǒ zhě wáng] duìwài zhèngcè shàng, pǔ dīng zé kāishǐ yāoqiú qián sūlián guójiā de lǐngdǎo rén yào zài `qīn é'hé `qīn ōu'zhī jiān zuò chū xuǎnzé! Rúguǒ nǐ xuǎnzé `qīn é', gēn pǔ dīng zhàn zài tóng yībiān, nà gōngxǐ nǐ! Mǎshàng jiù kěyǐ huòdé èluósī lǎo dàgē de zhàogù rúguǒ nǐ de guójiā fāshēng kàngyì yóuxíng, èluósī huì chūbīng bāng nǐ bǎipíng yàoshi nǐ de jīngjì yù dào kùnnán, èluósī yě huì huā qián bāng nǐ dùguò nánguān dàn rúguǒ nǐ xuǎnzé `qīn ōu', pǎo qù tóukào xīfāng guójiā nà tōngcháng jiù bù huì yǒu tài hǎo de xiàchǎng èluósī kěnéng huì chángcháng pǎo dào nǐ de fùjìn jìnxíng jūn yǎn, shè shè fēidàn, xiù xiù wǔlì ràng nǐ zhīdào lǎo dàgē de lìhài; yě kěnéng huì àndìlǐ fúchí qīn é de wǔzhuāng fēnzǐ ràng nǐ de guójiā xiànrù fēnliè wéijī zǒngzhī, tòuguò zhè zhǒng `shùn wǒ zhě shēng, nì wǒ zhě wáng'de fāng shì pǔ dīng yībù yībù de, chóngxīn jiàngòu èluósī zài ōu yà dàlù de yǐngxiǎng lì! [Pǔ dīng de xià yībù?] Xǔduō zhuānjiā rènwéi, zhècì wū é zhī jiān de chōngtú hěn kěnéng zhǐshì pǔ dīng zài `shì shuǐ wēn'éryǐ yī fāngmiàn, pǔ dīng xiǎng cèshì měiguó, kàn kàn bài dēng zhèngfǔ zài qùnián (2021) lángbèi de āfùhàn chèjūn hòu hái yǒu duōshǎo yìyuàn chāshǒu bié guó de shìwù lìng yī fāngmiàn, zé shì cèshì běiyuē dàodǐ tuán bù tuánjié, yǐjí qítā guójiā de fǎntán lìdào zhècì de jiéguǒ, kěyǐ ràng pǔ dīng nǎniē rúguǒ èluósī wèilái hái yào zàidù kuòzhāng, huì yù shàng shénme chéngdù de zǔ'ài nàme, zài wūkèlán zhīhòu, xià yīgè chōngtú diǎn huì zài nǎlǐ ne? Suīrán mùqián hái méiyǒu míngquè de xiànsuǒ bùguò, pǔ dīng céngjīng shuōguò, tā huì bǎohù suǒyǒu jìngwài de é yì rénkǒu hànwèi èyǔ dìqū de ānquán ér zài hāsàkè, lìtáowǎn, àishāníyǎ hé qítā qián sūlián guójiā zhōng dōu yǒu bù xiǎo bǐlì de rénkǒu shì èluósī rén yě jiùshì shuō, rúguǒ zhèxiē guójiā fāshēng zhèngzhì dòngdàng pǔ dīng jiù kěnéng yòng `bǎohù èluósī rén'de míngyì, chūbīng zhànlǐng zhèxiē dìqū rán'ér, zhèxiē dōu zhǐshì tuīcè, bìjìng, pǔ dīng zuì chángyòng de cèlüè jiùshì bù àn pái lǐ chū pái huòxǔ, zhīdào èluósī xià yībù de, zhǐyǒu pǔ dīng zìjǐ éryǐ ba! [Wǒmen de guāndiǎn] zài jìnrù guāndiǎn yǐqián, wǒmen yào xiān xièxiè dàjiā bǎ yǐngpiàn kàn dào zhè biān wǒ yě yào tèbié gǎnxiè zhì qí qīqī suǒyǒu de huìyuán yīnwèi yǒule dàjiā de zhīchí hé zànzhù, wǒmen cáinéng chíxù yùnzuò zhège píndào zhìzuò gèng duō guójì yìtí de yǐngpiàn rúguǒ nǐ yuànyì zhīchí wǒmen zǒu dé gèng yuǎn, huānyíng diǎnjī zīxùn lán de zhège liánjié jiārù wǒmen de huìyuán, huòzhě yě kěyǐ yòng `chāojí gǎnxiè', xiǎo'é zhīchí wǒmen huí dào jīntiān de yìtí, wǒmen zhī suǒyǐ xiǎng zuò zhè jí bùshì wèile qiángdiào pǔ dīng hǎo huài huài, huòzhě èluósī yǒu duōme bàdào bìjìng, jūnshì kuòzhāng, gānshè nèi zhèng zhè zhǒng shì měiguó, zhōngguó yě dūhuì zuò, bìng méiyǒu shé me tèbié de zhǐ bùguò, èluósī zhè jǐ nián, jūnshì huódòng zhēn de bǐjiào pínfán zài jiā shàng, pǔ dīng zhèngzài xúnqiú yánxù zhèngzhì shēngyá yīncǐ, tā huì bù huì lìyòng duìwài zhànzhēng, lái gǒnggù zìjǐ de quánlì cái shì dàjiā tèbié dānxīn dì dìfāng! Ér huà yòu shuō huílái, suīrán pǔ dīng sìhū yǒu fùxīng sūlián de lǐxiǎng dàn wǒmen juédé, sūlián hé èluósī, háishì yǒu běnzhí shàng de qūbié guòqù, sūlián nèibù de chéngyuán guó, zhī suǒyǐ huì tīngmìng èluósī chúle jūnshì hé jīngjì shàng de yīlài, gèng shì yīnwèi duì `gòngchǎn zhǔyì'yǒu rèn tóng gǎn cái ràng dàjiā tuánjié zài yī qǐ dàn sūlián jiětǐ hòu, gèguó yǐjīng méiyǒu gòngchǎn zhǔyì zuòwéi niánhé jìle zhèxiē guójiā, rúguǒ ná bù dào shízhì de hǎochù sìhū méi shénme lǐyóu yào dāng èluósī de xiǎodì zài jiā shàng, hěnduō qián sūlián guójiā yǐjīng mínzhǔ huà xǔduō rén xíguànle zìyóu de shēnghuó, duì xiāngduì zhuānzhì de èluósī gǎndào fǎngǎn yóuqí niánqīng shìdài, gēnběn méiyǒu jīnglìguò sūlián shíqí de guānghuī suìyuè duìyú pǔ dīng tíchū de yuànjǐng, hěn kěnéng yīdiǎn gòngmíng yě méiyǒu mùqián kàn qǐlái, bù shǎo qián sūlián de guójiā, mímànzhe qiángliè de fǎn é qíngxù rúguǒ pǔ dīng zhēn de xīwàng, èluósī néng zàidù chéngwéi ōu yà dàlù de lǎo dàgē nàme, yào rúhé yíng huí dàjiā de xìnrèn gēn gè guó jiànlì yǒushàn de huǒbàn guānxì, huòxǔ shì cái shì pǔ dīng de zuìdà tiǎozhàn ba! Hǎo de, jīntiān zhè jí jiù liáo dào zhè biān zuìhòu, rúguǒ nǐ xǐhuān jīntiān de yǐngpiàn, huānyíng fēnxiǎng chūqù ràng gèng duō rén zhīdào pǔ dīng wèishéme yīzhí xiǎng duìwài kuòzhāng! Cǐwài yě kěyǐ diǎn zhè biān, kàn kàn `pǔ dīng píng shénme yīzhí dāng zǒngtǒng' yǐjí `bái luósī de rénzào nànmín cháo' nàme, jīntiān de zhì qí qīqī jiù dào zhè biān gào yīduànluò wǒmen míng wǎn zàijiàn luō!",
        chinese: `圍攻烏克蘭、出兵哈薩克，為什麼這幾年
        俄羅斯對鄰居們的軍事介入，似乎變成家常便飯？
        在普丁的領導之下，解體三十年的「蘇聯」難道就要復活了嗎？
        今天，就讓我們一起來聊聊「普丁的蘇聯夢」吧！
        hiho～大家好，我是志祺！
        從去年年底開始，俄羅斯以演習為名義
        在烏克蘭邊境聚集了超過十萬人的大軍
        美國的情報單位指出
        俄國很可能會在今年春天，向烏克蘭開戰！
        雖然俄國否認有入侵烏克蘭的意圖
        但他們也警告
        如果烏克蘭加入北大西洋公約組織（北約）
        俄羅斯也會採取「必要的報復手段」
        隨著狀況越來越緊張，各國開始將人員撤離烏克蘭
        北約也增派軍隊到東歐待命
        雙方劍拔奴張，幾乎瀕臨戰爭邊緣
        烏克蘭的危機，讓全球陷入恐慌
        不過，如果我們把視角拉高，會發現這一場衝突
        可能只是棋盤上的一小步而已
        在普丁的心中，似乎還有更大的野心要完成
        究竟，頻頻對鄰居出征的俄羅斯，背後有什麼目的呢？
        依照慣例，我們要先來一小段工商時間
        最近志祺七七團隊
        正在招募厲害的新夥伴啦！
        我們想要徵求「全職的影片內容企劃」
        跟我們一起追時事、聊議題
        寫腳本、發想節目企劃
        迎接各種經營頻道會遇到的挑戰！
        不管你有什麼樣的知識領域專長
        只要你擅長寫作、很會蒐集資料
        邏輯清晰、具備獨到的觀點
        而且樂於溝通、能把複雜的東西簡單說清楚
        那你就是我們希望能邀請到的人才！
        當然，如果你已經有
        「文字影音創作」
        或「節目頻道經營」的相關經驗，那就更棒啦！
        如果你認同志祺七七頻道的理念
        也想要加入我們的行列
        那就趕快上我們的官網去看看職缺內容吧！
        【動盪的歐亞大陸】
        除了剛剛提到的烏克蘭危機外，過去二十年內
        俄羅斯在歐亞大陸上，可以說是動作不斷
        2008年，俄羅斯與喬治亞爆發戰爭，並在戰勝之後
        實質佔領了喬治亞的部分領土
        2014年，俄羅斯則突襲烏克蘭
        吞併了烏克蘭南部的克里米亞半島
        並煽動烏克蘭東部叛變，成立親俄的自治政府
        除此之外，俄羅斯也積極地介入各國的內政問題
        像是今年一月，哈薩克爆發示威，民眾上街要求政治改革
        但在哈薩克總統的請求下
        俄羅斯火速派出維和部隊，迅速壓制了抗議民眾
        這幾年來，在東歐、中亞、和高加索地區
        越來越常見到俄軍的影子，俄羅斯正在以老大哥的姿態
        重新建立歐亞大陸的秩序
        而這些動作，讓不少人擔心
        消失三十年的蘇聯，似乎即將再次回歸！
        【蘇聯是什麼？】
        有的人可能對「蘇聯」不太熟悉，我們這裡簡單介紹一下
        蘇聯的全名是「蘇維埃社會主義共和國聯盟」
        它成立於1922年，是由蘇俄、白羅斯
        烏克蘭等國創立的一個聯邦制共產國家
        由位於莫斯科的蘇聯共產黨執政，領導整個國家的運作
        二戰結束後，蘇聯控制了東歐地區
        獲取了大量土地、人口和資源
        不只是當時世界領土最大的國家
        也是經濟和軍事上的超級強權
        為了爭奪二戰後的話語權，蘇聯帶領的「共產主義陣營」
        與美國帶領的「資本主義陣營」
        展開經濟、軍事和太空科技的全面對抗
        雙方也在各地進行代理人戰爭，爭奪世界霸主的地位！
        然而，到了1980年代，蘇聯的經濟發展遇上困境
        再加上內部的政治矛盾，導致蘇聯開始分崩離析
        1991年，莫斯科當局終於放手
        宣布蘇聯解體，一代強權也就此畫下句點
        蘇聯解體之後，分裂成俄羅斯、烏克蘭
        喬治亞、哈薩克等十多個獨立國家
        而這些國家，也慢慢進行改革開放，各自邁向民主化
        只不過，這幾年，俄羅斯又開始干涉這些地方
        似乎想和當年的蘇聯一樣，再度成為歐亞大陸的強權
        而這一次，他們不再是為了宣揚共產主義
        而是為了奪取更實質的利益！
        【俄羅斯想得到什麼：能源控制】
        許多專家認為，俄羅斯這幾年這麼積極地想擴張
        主要出自於能源、軍事和政治三個面向的考量
        在能源方面，在俄羅斯的土地上
        布滿了許多管線，將天然氣、石油輸往歐洲大陸
        這些能源對俄羅斯來說，除了是重要的收入來源
        也是非常好用的談判籌碼
        他們隨時可以切斷管線，停止特定地區的能源供應
        使得歐洲國家產生無形的政治壓力
        像是在德國，有超過一半的天然氣，都是從俄羅斯進口的
        而這些天然氣是發電、取暖的重要來源
        所以，在這次的烏克蘭危機中
        德國之所以不太願意譴責俄羅斯，很大一部分原因
        也是因為害怕天然氣被切斷，才不敢得罪普丁
        而俄羅斯也清楚，「能源」是他們現階段
        跟西方列強抗衡的最大籌碼
        所以他們非常努力地
        想要擴張勢力範圍，奪取更多的天然資源
        像是哈薩克所處的中亞地區，就蘊含了大量的石油和天然氣
        只要掌控這塊地，就有機會開採更多能源
        或是更有效益地鋪設管線，進一步增加俄國在當地的影響力
        讓他們站穩能源霸主地位！
        【俄羅斯想得到什麼：軍事抗衡】
        在軍事方面，俄羅斯則希望擴張軍事版圖，跟北約互相抗衡
        在蘇聯解體之後，東歐的前蘇聯國家
        像是立陶宛、波蘭、捷克，一個接著一個跳槽到北約
        跟美國站在同一陣線
        而在2014年，俄羅斯吞併克里米亞後
        北約也開始在東歐建設軍事基地，就近監控俄羅斯
        隨著北約勢力版圖越來越大，讓俄羅斯政府越來越不滿
        他們希望這些前蘇聯國家，重新回到俄羅斯的掌控
        成為俄羅斯週圍的「緩衝區」，避免北約的軍隊
        直接跑到俄羅斯的家門口，對首都莫斯科造成威脅
        簡單來說，普丁希望可以重新畫設冷戰之後的歐洲邊界
        建立一個由俄羅斯主導的軍事區域，來對抗西方勢力
        最後，俄羅斯之所以動作這麼多
        還有個很重要的原因，那就是普丁個人的政治野心！
        【普丁想要什麼：復興蘇聯】
        普丁出生於蘇聯時代，也擔任過蘇聯的特務人員
        對他來說，蘇聯就是養育他長大的母親
        也是「繁榮、強盛、偉大」的代名詞
        所以，當普丁看到蘇聯垮台後
        俄羅斯經濟衰退的模樣，他的內心非常難受
        普丁曾經表示，蘇聯解體就是「20世紀最大的災難之一」
        很多專家也推測，在普丁心中
        應該一直抱有「復興蘇聯」的遠大理想
        為了讓前蘇聯國家再次團結，普丁常常周邊國家進行心戰喊話
        像是對烏克蘭說「我們都是同文同種」、「俄烏一家親」等等
        這聽起來～
        有點耳熟的宣傳話語
        甚至，普丁還曾經公開說過「俄羅斯的邊界無止盡！」
        雖然他馬上澄清「只是開個玩笑」但多少也透露出
        他想要收復失土的野心
        而對普丁來說，「復興蘇聯」不只有情感上的意義
        實質上，也對他的政治生涯有很大的幫助！
        【普丁想要什麼：打仗救民調？】
        普丁發現，對外的軍事活動
        可以轉移民眾對國內問題的不滿
        也可以激發民眾的愛國心，鞏固自己的政權
        2012年左右，普丁深陷選舉舞弊的風波
        街頭出現大規模的反政府遊行，普丁民調一度跌落谷底
        但是到2014年，當普丁決定出兵烏克蘭
        佔領克里米亞的時候，民調馬上止跌飆升
        讓他再度成為受人民愛戴的強人總統！
        嘗到甜頭的普丁，從此發現「打仗救民調」的流量密碼
        時常透過對外的軍事行動，來維持自己的支持率
        直到今天，仍有一半的俄國民眾
        支持普丁2024年後繼續當總統，認為只有普丁
        才有辦法「讓俄羅斯再次偉大」
        而普丁想要壯大俄羅斯的計畫，不是只有嘴上說說而已
        為了重回蘇聯時期的光輝歲月，俄羅斯其實早就開始動作了！
        【對內政策：俄羅斯保衛戰！】
        根據外媒報導，普丁掌權下的俄羅斯
        已經建立了民眾的「戰爭意識」
        過去八年，俄羅斯透過學校、媒體、教會
        不斷宣傳「祖國被敵人包圍」的想法
        從俄羅斯官方的宣傳來看，是西方勢力在俄國周邊增加軍隊
        並且用經濟制裁的手段打壓俄國，才會讓他們的處境如此艱辛
        不少俄羅斯人也認為，俄國並不是邪惡的侵略者
        而是西方霸凌下的受害者
        為了保護自己的主權，適當的向外擴張，成為了他們唯一的出路
        雖然說，還是有很多俄羅斯人對戰爭沒興趣
        但在長期宣傳之下，大家也對發動戰爭這件事
        感到越來越麻木。如果哪天普丁真的對其他國家動武
        國內可能也不會有太多的反彈聲浪！
        【對外政策：順我者生，逆我者亡】
        對外政策上，普丁則開始要求前蘇聯國家的領導人
        要在「親俄」和「親歐」之間做出選擇！
        如果你選擇「親俄」，跟普丁站在同一邊，那恭喜你！
        馬上就可以獲得俄羅斯老大哥的照顧
        如果你的國家發生抗議遊行，俄羅斯會出兵幫你擺平
        要是你的經濟遇到困難，俄羅斯也會花錢幫你度過難關
        但如果你選擇「親歐」，跑去投靠西方國家
        那通常就不會有太好的下場
        俄羅斯可能會常常跑到你的附近進行軍演，射射飛彈、秀秀武力
        讓你知道老大哥的厲害；也可能會暗地裡扶持親俄的武裝分子
        讓你的國家陷入分裂危機
        總之，透過這種「順我者生、逆我者亡」的方式
        普丁一步一步地，重新建構俄羅斯在歐亞大陸的影響力！
        【普丁的下一步？】
        許多專家認為，這次烏俄之間的衝突
        很可能只是普丁在「試水溫」而已
        一方面，普丁想測試美國，看看拜登政府
        在去年（2021）狼狽的阿富汗撤軍後
        還有多少意願插手別國的事務
        另一方面，則是測試北約到底團不團結，以及其他國家的反彈力道
        這次的結果，可以讓普丁拿捏
        如果俄羅斯未來還要再度擴張，會遇上什麼程度的阻礙
        那麼，在烏克蘭之後，下一個衝突點會在哪裡呢？
        雖然目前還沒有明確的線索
        不過，普丁曾經說過，他會保護所有境外的俄裔人口
        捍衛俄語地區的安全
        而在哈薩克、立陶宛、愛沙尼亞和其他前蘇聯國家中
        都有不小比例的人口是俄羅斯人
        也就是說，如果這些國家發生政治動盪
        普丁就可能用「保護俄羅斯人」的名義，出兵佔領這些地區
        然而，這些都只是推測，畢竟，普丁最常用的策略
        就是不按牌理出牌
        或許，知道俄羅斯下一步的，只有普丁自己而已吧！
        【我們的觀點】
        在進入觀點以前，我們要先謝謝大家把影片看到這邊
        我也要特別感謝志祺七七所有的會員
        因為有了大家的支持和贊助，我們才能持續運作這個頻道
        製作更多國際議題的影片
        如果你願意支持我們走得更遠，歡迎點擊資訊欄的這個連結
        加入我們的會員，或者也可以用「超級感謝」，小額支持我們
        回到今天的議題，我們之所以想做這集
        不是為了強調普丁好壞壞、或者俄羅斯有多麼霸道
        畢竟，軍事擴張、干涉內政這種事
        美國、中國也都會做，並沒有什麼特別的
        只不過，俄羅斯這幾年，軍事活動真的比較頻繁
        再加上，普丁正在尋求延續政治生涯
        因此，他會不會利用對外戰爭，來鞏固自己的權力
        才是大家特別擔心的地方！
        而話又說回來，雖然普丁似乎有復興蘇聯的理想
        但我們覺得，蘇聯和俄羅斯，還是有本質上的區別
        過去，蘇聯內部的成員國，之所以會聽命俄羅斯
        除了軍事和經濟上的依賴，更是因為對「共產主義」有認同感
        才讓大家團結在一起
        但蘇聯解體後，各國已經沒有共產主義作為黏合劑了
        這些國家，如果拿不到實質的好處
        似乎沒什麼理由要當俄羅斯的小弟
        再加上，很多前蘇聯國家已經民主化
        許多人習慣了自由的生活，對相對專制的俄羅斯感到反感
        尤其年輕世代，根本沒有經歷過蘇聯時期的光輝歲月
        對於普丁提出的願景，很可能一點共鳴也沒有
        目前看起來，不少前蘇聯的國家，瀰漫著強烈的反俄情緒
        如果普丁真的希望，俄羅斯能再度成為歐亞大陸的老大哥
        那麼，要如何贏回大家的信任
        跟各國建立友善的夥伴關係，或許是才是普丁的最大挑戰吧！
        好的，今天這集就聊到這邊
        最後，如果你喜歡今天的影片，歡迎分享出去
        讓更多人知道普丁為什麼一直想對外擴張！
        此外也可以點這邊，看看「普丁憑什麼一直當總統」
        以及「白羅斯的人造難民潮」
        那麼，今天的志祺七七就到這邊告一段落
        我們明晚再見囉！`
    }
};

export default ukraineWar;